{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backItemEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationBarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNavigationBarView","text":"GTNavigationBarView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuiviewcontroller\/backitemevent(barview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController\/backItemEvent(barView:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GTNavigationBarViewDelegate.backItemEvent(barView:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"backItemEvent(barView:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backItemEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTNavigationBarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNavigationBarView"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:7GTUIKit18GTUIViewControllerC13backItemEvent7barViewyAA015GTNavigationBarH0C_tF","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController\/GTNavigationBarViewDelegate-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIViewController/GTNavigationBarViewDelegate-Implementations":{"role":"collectionGroup","title":"GTNavigationBarViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController\/GTNavigationBarViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtuiviewcontroller\/gtnavigationbarviewdelegate-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIViewController":{"role":"symbol","title":"GTUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIViewController"}],"url":"\/documentation\/gtuikit\/gtuiviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNavigationBarView":{"role":"symbol","title":"GTNavigationBarView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNavigationBarView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationBarView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNavigationBarView"}],"url":"\/documentation\/gtuikit\/gtnavigationbarview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIViewController/backItemEvent(barView:)":{"role":"symbol","title":"backItemEvent(barView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backItemEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTNavigationBarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNavigationBarView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController\/backItemEvent(barView:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuiviewcontroller\/backitemevent(barview:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIViewController\/title","value":"GTUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIViewController\/fragments","value":[{"kind":"identifier","text":"GTUIViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNavigationBarView\/title","value":"GTNavigationBarView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNavigationBarView\/fragments","value":[{"kind":"identifier","text":"GTNavigationBarView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}