{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationBarView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationBarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNavigationBarView","text":"GTNavigationBarView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuiviewcontroller\/navigationbarview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController\/navigationBarView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"自定义导航栏"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationBarView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTNavigationBarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNavigationBarView"}],"title":"navigationBarView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit18GTUIViewControllerC17navigationBarViewAA012GTNavigationeF0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIViewController/navigationBarView":{"role":"symbol","title":"navigationBarView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationBarView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTNavigationBarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNavigationBarView"}],"abstract":[{"type":"text","text":"自定义导航栏"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController\/navigationBarView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuiviewcontroller\/navigationbarview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNavigationBarView":{"role":"symbol","title":"GTNavigationBarView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNavigationBarView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationBarView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNavigationBarView"}],"url":"\/documentation\/gtuikit\/gtnavigationbarview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIViewController":{"role":"symbol","title":"GTUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIViewController"}],"url":"\/documentation\/gtuikit\/gtuiviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNavigationBarView\/title","value":"GTNavigationBarView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNavigationBarView\/fragments","value":[{"kind":"identifier","text":"GTNavigationBarView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIViewController\/title","value":"GTUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIViewController\/fragments","value":[{"kind":"identifier","text":"GTUIViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}