{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNumberPercentView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtnumberpercentview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtnumberpercentview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView\/intrinsicContentSize"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView\/layoutSubviews()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNumberPercentView"}],"title":"GTNumberPercentView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTNumberPercentView","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTNumberPercentView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNumberPercentView/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/gtuikit\/gtnumberpercentview\/init()"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/9PinLayout14SizeCalculableP":{"type":"unresolvable","title":"PinLayout.SizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"},"doc://org.cocoapods.GTUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNumberPercentView/intrinsicContentSize":{"role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView\/intrinsicContentSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/gtuikit\/gtnumberpercentview\/intrinsiccontentsize"},"doc://org.cocoapods.GTUIKit/12SkeletonView0aB8ExtendedP":{"type":"unresolvable","title":"SkeletonView.SkeletonViewExtended","identifier":"doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyType":{"role":"symbol","title":"GTEmptyType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyType"}],"url":"\/documentation\/gtuikit\/gtemptytype"},"doc://org.cocoapods.GTUIKit/9PinLayout10LayoutableP":{"type":"unresolvable","title":"PinLayout.Layoutable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNumberPercentView/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/gtuikit\/gtnumberpercentview\/layoutsubviews()"},"doc://org.cocoapods.GTUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.GTUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNumberPercentView":{"role":"symbol","title":"GTNumberPercentView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNumberPercentView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNumberPercentView"}],"url":"\/documentation\/gtuikit\/gtnumberpercentview"},"doc://org.cocoapods.GTUIKit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.GTUIKit/9PinLayout18AutoSizeCalculableP":{"type":"unresolvable","title":"PinLayout.AutoSizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.GTUIKit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTNumberPercentView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTNumberPercentView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTNumberPercentView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView\/intrinsicContentSize"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView\/init()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPercentView\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNumberPercentView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNumberPercentView~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNumberPercentView~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNumberPercentView~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNumberPercentView~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNumberPercentView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNumberPercentView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNumberPercentView\/title","value":"GTNumberPercentView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNumberPercentView\/fragments","value":[{"kind":"identifier","text":"GTNumberPercentView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}