{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtpopoverprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverGuideView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverView"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/arrowSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/dismissOnBackgroundTap","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/onDismissBlock","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/popoverColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/popoverMaxWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/popoverMinWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/position","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/sideEdge"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/dismiss()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverProtocol"}],"title":"GTPopoverProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit17GTPopoverProtocolP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTPopoverProtocol"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol/popoverColor":{"role":"symbol","title":"popoverColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"popoverColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/popoverColor","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtpopoverprotocol\/popovercolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView":{"role":"symbol","title":"GTPopoverMenuView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverMenuView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopoverMenuView"}],"url":"\/documentation\/gtuikit\/gtpopovermenuview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol/popoverMinWidth":{"role":"symbol","title":"popoverMinWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"popoverMinWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/popoverMinWidth","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtpopoverprotocol\/popoverminwidth"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol/onDismissBlock":{"role":"symbol","title":"onDismissBlock","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"os_block_t","preciseIdentifier":"c:@T@os_block_t"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/onDismissBlock","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtpopoverprotocol\/ondismissblock"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol/sideEdge":{"role":"symbol","title":"sideEdge","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sideEdge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/sideEdge","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtpopoverprotocol\/sideedge"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol/popoverMaxWidth":{"role":"symbol","title":"popoverMaxWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"popoverMaxWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/popoverMaxWidth","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtpopoverprotocol\/popovermaxwidth"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol/dismiss()":{"role":"symbol","title":"dismiss()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/dismiss()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtpopoverprotocol\/dismiss()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol/dismissOnBackgroundTap":{"role":"symbol","title":"dismissOnBackgroundTap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissOnBackgroundTap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/dismissOnBackgroundTap","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtpopoverprotocol\/dismissonbackgroundtap"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverGuideView":{"role":"symbol","title":"GTPopoverGuideView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverGuideView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverGuideView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopoverGuideView"}],"url":"\/documentation\/gtuikit\/gtpopoverguideview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol/arrowSize":{"role":"symbol","title":"arrowSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"arrowSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/arrowSize","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtpopoverprotocol\/arrowsize"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol":{"role":"symbol","title":"GTPopoverProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopoverProtocol"}],"url":"\/documentation\/gtuikit\/gtpopoverprotocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverView":{"role":"symbol","title":"GTPopoverView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopoverView"}],"url":"\/documentation\/gtuikit\/gtpopoverview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol/position":{"role":"symbol","title":"position","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopoverPosition","preciseIdentifier":"s:7GTUIKit17GTPopoverPositionO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol\/position","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtpopoverprotocol\/position"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverMenuView\/title","value":"GTPopoverMenuView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverMenuView\/fragments","value":[{"kind":"identifier","text":"GTPopoverMenuView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverGuideView\/title","value":"GTPopoverGuideView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverGuideView\/fragments","value":[{"kind":"identifier","text":"GTPopoverGuideView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverView\/title","value":"GTPopoverView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverView\/fragments","value":[{"kind":"identifier","text":"GTPopoverView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}