{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItemProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionItem"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/backgroundItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/footerItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/headerItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/insetForSection","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/minimumInteritemSpacing","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/minimumLineSpacing","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/sectionIdentifier","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/sectionItems"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItemProtocol"}],"title":"GTUICollectionViewSectionItemProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit37GTUICollectionViewSectionItemProtocolP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewSectionItemProtocol"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol/insetForSection":{"role":"symbol","title":"insetForSection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"insetForSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/insetForSection","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol\/insetforsection"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionItem":{"role":"symbol","title":"GTUIFallLayoutSectionItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutSectionItem"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutsectionitem"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol/minimumLineSpacing":{"role":"symbol","title":"minimumLineSpacing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumLineSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/minimumLineSpacing","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol\/minimumlinespacing"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol/minimumInteritemSpacing":{"role":"symbol","title":"minimumInteritemSpacing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumInteritemSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/minimumInteritemSpacing","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol\/minimuminteritemspacing"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol/sectionItems":{"role":"symbol","title":"sectionItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sectionItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTUICollectionReusableViewItemProtocol","preciseIdentifier":"s:7GTUIKit38GTUICollectionReusableViewItemProtocolP"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/sectionItems","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol\/sectionitems"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol/headerItem":{"role":"symbol","title":"headerItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUICollectionReusableViewItemProtocol","preciseIdentifier":"s:7GTUIKit38GTUICollectionReusableViewItemProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/headerItem","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol\/headeritem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem":{"role":"symbol","title":"GTUICollectionViewSectionItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewSectionItem"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol/backgroundItem":{"role":"symbol","title":"backgroundItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUICollectionReusableViewItemProtocol","preciseIdentifier":"s:7GTUIKit38GTUICollectionReusableViewItemProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/backgroundItem","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol\/backgrounditem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem":{"role":"symbol","title":"GTUIFallLayoutSectionBaseItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol":{"role":"symbol","title":"GTUICollectionViewSectionItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItemProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewSectionItemProtocol"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol/footerItem":{"role":"symbol","title":"footerItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUICollectionReusableViewItemProtocol","preciseIdentifier":"s:7GTUIKit38GTUICollectionReusableViewItemProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/footerItem","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol\/footeritem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol/sectionIdentifier":{"role":"symbol","title":"sectionIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sectionIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol\/sectionIdentifier","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol\/sectionidentifier"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionItem\/title","value":"GTUIFallLayoutSectionItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionItem\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewSectionItem\/title","value":"GTUICollectionViewSectionItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewSectionItem\/fragments","value":[{"kind":"identifier","text":"GTUICollectionViewSectionItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/title","value":"GTUIFallLayoutSectionBaseItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}