{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYPageViewDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/lypageviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/lypageviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate\/pageDidClickTitle(at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate\/pageDidSelected(at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate\/pageWillDragging(at:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYPageViewDelegate"}],"title":"LYPageViewDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@GTUIKit@objc(pl)LYPageViewDelegate","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"LYPageViewDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYPageViewDelegate/pageDidSelected(at:)":{"role":"symbol","title":"pageDidSelected(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageDidSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate\/pageDidSelected(at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageDidSelectedAt:"}],"url":"\/documentation\/gtuikit\/lypageviewdelegate\/pagedidselected(at:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYPageViewDelegate":{"role":"symbol","title":"LYPageViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYPageViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LYPageViewDelegate"}],"url":"\/documentation\/gtuikit\/lypageviewdelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYPageViewDelegate/pageWillDragging(at:)":{"role":"symbol","title":"pageWillDragging(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageWillDragging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate\/pageWillDragging(at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageWillDraggingAt:"}],"url":"\/documentation\/gtuikit\/lypageviewdelegate\/pagewilldragging(at:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYPageViewDelegate/pageDidClickTitle(at:)":{"role":"symbol","title":"pageDidClickTitle(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageDidClickTitle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate\/pageDidClickTitle(at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageDidClickTitleAt:"}],"url":"\/documentation\/gtuikit\/lypageviewdelegate\/pagedidclicktitle(at:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"LYPageViewDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LYPageViewDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LYPageViewDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate\/pageDidClickTitle(at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate\/pageDidSelected(at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageViewDelegate\/pageWillDragging(at:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYPageViewDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageViewDelegate~1pageDidSelected(at:)\/title","value":"pageDidSelectedAt:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageViewDelegate~1pageDidSelected(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageDidSelectedAt:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageViewDelegate\/title","value":"LYPageViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageViewDelegate\/fragments","value":[{"kind":"identifier","text":"LYPageViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageViewDelegate~1pageWillDragging(at:)\/title","value":"pageWillDraggingAt:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageViewDelegate~1pageWillDragging(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageWillDraggingAt:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageViewDelegate~1pageDidClickTitle(at:)\/title","value":"pageDidClickTitleAt:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageViewDelegate~1pageDidClickTitle(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageDidClickTitleAt:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}