{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBDesignable"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarqueeLabel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/marqueelabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/marqueelabel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UILabel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CAAnimationDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIContentSizeCategoryAdjusting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/init(frame:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/init(frame:duration:fadeLength:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/init(frame:rate:fadeLength:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationCurve","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationDelay","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationDuration","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationPosition","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/attributedText","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/awayFromHome","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/backgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/baselineAdjustment","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/contentMode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/fadeLength","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/font","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/forLastBaselineLayout","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/forceScrolling","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/highlightedTextColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/holdScrolling","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/intrinsicContentSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isAccessibilityElement","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isEnabled","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isHighlighted","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isPaused","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/leadingBuffer","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/numberOfLines","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/scrollDuration","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/scrollRate","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/scrollSequence","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/shadowColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/shadowOffset","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/speed","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/tapToScroll","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/text","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/textColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/tintColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/trailingBuffer","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animateForController(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationDidStop(_:finished:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/awakeFromNib()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/didMoveToWindow()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/draw(_:in:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/forBaselineLayout()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelReturnedToHome(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelShouldScroll()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelWasTapped(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelWillBeginScroll()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelizeForController(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/layoutSubviews()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/pauseLabel()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/prepareForInterfaceBuilder()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/resetLabel()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/restartForViewController(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/restartLabel()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/shutdownLabel()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/sizeThatFits(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/sizeThatFits(_:withBuffers:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/textCoordinateForFramePoint(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/textLayoutSize()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/tintColorDidChange()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/triggerScrollStart()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/unpauseLabel()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/willMove(toWindow:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/layerClass"]},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/controllerLabelsAnimate(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/controllerLabelsLabelize(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/controllerViewDidAppear(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/controllerViewWillAppear(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/restartLabelsOfController(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/MarqueeType","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/SpeedLimit"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarqueeLabel"}],"title":"MarqueeLabel","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)MarqueeLabel","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MarqueeLabel"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UIContentSizeCategoryAdjusting":{"type":"unresolvable","title":"UIKit.UIContentSizeCategoryAdjusting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIContentSizeCategoryAdjusting"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/init(coder:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/restartLabel()":{"role":"symbol","title":"restartLabel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restartLabel"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Immediately resets the label to the home position, cancelling any in-flight scroll animation, and restarts the scroll animation if the appropriate conditions are met."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/restartLabel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restartLabel"}],"url":"\/documentation\/gtuikit\/marqueelabel\/restartlabel()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/animationDuration":{"role":"symbol","title":"animationDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The read-only\/computed duration of the scroll animation (not including delay)."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationDuration","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/animationduration"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/resetLabel()":{"role":"symbol","title":"resetLabel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetLabel"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Resets the label text, recalculating the scroll animation."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/resetLabel()","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/gtuikit\/marqueelabel\/resetlabel()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/tintColorDidChange()":{"role":"symbol","title":"tintColorDidChange()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tintColorDidChange"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/tintColorDidChange()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tintColorDidChange"}],"url":"\/documentation\/gtuikit\/marqueelabel\/tintcolordidchange()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/forBaselineLayout()":{"role":"symbol","title":"forBaselineLayout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"forBaselineLayout"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/forBaselineLayout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewForBaselineLayout"}],"url":"\/documentation\/gtuikit\/marqueelabel\/forbaselinelayout()"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyType":{"role":"symbol","title":"GTEmptyType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyType"}],"url":"\/documentation\/gtuikit\/gtemptytype"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/shadowColor":{"role":"symbol","title":"shadowColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/shadowColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shadowColor"}],"url":"\/documentation\/gtuikit\/marqueelabel\/shadowcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/awayFromHome":{"role":"symbol","title":"awayFromHome","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"awayFromHome"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A boolean property that indicates if the label is currently away from the home location."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/awayFromHome","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/awayfromhome"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/labelShouldScroll()":{"role":"symbol","title":"labelShouldScroll()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelShouldScroll"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelShouldScroll()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/labelshouldscroll()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/trailingBuffer":{"role":"symbol","title":"trailingBuffer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trailingBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"A buffer (offset) between the trailing edge of the label text and the label frame."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/trailingBuffer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trailingBuffer"}],"url":"\/documentation\/gtuikit\/marqueelabel\/trailingbuffer"},"doc://org.cocoapods.GTUIKit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/init(frame:rate:fadeLength:)":{"role":"symbol","title":"init(frame:rate:fadeLength:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fadeLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a newly initialized "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" instance with the specified scroll rate and edge transparency fade length."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/init(frame:rate:fadeLength:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/init(frame:rate:fadelength:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/numberOfLines":{"role":"symbol","title":"numberOfLines","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfLines"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/numberOfLines","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfLines"}],"url":"\/documentation\/gtuikit\/marqueelabel\/numberoflines"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/isPaused":{"role":"symbol","title":"isPaused","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPaused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A read-only boolean property that indicates if the label’s scroll animation has been paused."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isPaused","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/ispaused"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/labelReturnedToHome(_:)":{"role":"symbol","title":"labelReturnedToHome(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelReturnedToHome"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the label animation has finished, and the label is at the home position."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelReturnedToHome(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/labelreturnedtohome(_:)"},"doc://org.cocoapods.GTUIKit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/labelWasTapped(_:)":{"role":"symbol","title":"labelWasTapped(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelWasTapped"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelWasTapped(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"labelWasTapped:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/labelwastapped(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/restartLabelsOfController(_:)":{"role":"symbol","title":"restartLabelsOfController(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restartLabelsOfController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Convenience method to restart all "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" instances that have the specified view controller in their next responder chain."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/restartLabelsOfController(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/restartlabelsofcontroller(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/intrinsicContentSize":{"role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/intrinsicContentSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/gtuikit\/marqueelabel\/intrinsiccontentsize"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/MarqueeType":{"role":"symbol","title":"MarqueeLabel.MarqueeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarqueeType"}],"abstract":[{"type":"text","text":"An enum that defines the types of "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" scrolling"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/MarqueeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarqueeType"}],"url":"\/documentation\/gtuikit\/marqueelabel\/marqueetype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel":{"role":"symbol","title":"MarqueeLabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarqueeLabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarqueeLabel"}],"url":"\/documentation\/gtuikit\/marqueelabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/backgroundColor":{"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/backgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"url":"\/documentation\/gtuikit\/marqueelabel\/backgroundcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/sizeThatFits(_:withBuffers:)":{"role":"symbol","title":"sizeThatFits(_:withBuffers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withBuffers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/sizeThatFits(_:withBuffers:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/sizethatfits(_:withbuffers:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"},"doc://org.cocoapods.GTUIKit/9PinLayout14SizeCalculableP":{"type":"unresolvable","title":"PinLayout.SizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/leadingBuffer":{"role":"symbol","title":"leadingBuffer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leadingBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"A buffer (offset) between the leading edge of the label text and the label frame."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/leadingBuffer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leadingBuffer"}],"url":"\/documentation\/gtuikit\/marqueelabel\/leadingbuffer"},"doc://org.cocoapods.GTUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)CAAnimationDelegate":{"type":"unresolvable","title":"CAAnimationDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CAAnimationDelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/holdScrolling":{"role":"symbol","title":"holdScrolling","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"holdScrolling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A boolean property that sets whether the "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" should hold (prevent) automatic label scrolling."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/holdScrolling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"holdScrolling"}],"url":"\/documentation\/gtuikit\/marqueelabel\/holdscrolling"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/triggerScrollStart()":{"role":"symbol","title":"triggerScrollStart()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"triggerScrollStart"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Overrides any non-size condition which is preventing the receiver from automatically scrolling, and begins a scroll animation."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/triggerScrollStart()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/triggerscrollstart()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/textColor":{"role":"symbol","title":"textColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/textColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textColor"}],"url":"\/documentation\/gtuikit\/marqueelabel\/textcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/isAccessibilityElement":{"role":"symbol","title":"isAccessibilityElement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAccessibilityElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isAccessibilityElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAccessibilityElement"}],"url":"\/documentation\/gtuikit\/marqueelabel\/isaccessibilityelement"},"doc://org.cocoapods.GTUIKit/12SkeletonView0aB8ExtendedP":{"type":"unresolvable","title":"SkeletonView.SkeletonViewExtended","identifier":"doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/labelizeForController(_:)":{"role":"symbol","title":"labelizeForController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelizeForController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelizeForController(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"labelizeForController:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/labelizeforcontroller(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/controllerViewWillAppear(_:)":{"role":"symbol","title":"controllerViewWillAppear(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerViewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Convenience method to restart all "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" instances that have the specified view controller in their next responder chain."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/controllerViewWillAppear(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/controllerviewwillappear(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/init(frame:duration:fadeLength:)":{"role":"symbol","title":"init(frame:duration:fadeLength:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fadeLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a newly initialized "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" instance with the specified scroll rate and edge transparency fade length."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/init(frame:duration:fadeLength:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/init(frame:duration:fadelength:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MarqueeType","preciseIdentifier":"s:7GTUIKit12MarqueeLabelC0B4TypeO"}],"abstract":[{"type":"text","text":"Defines the direction and method in which the "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" instance scrolls."},{"type":"text","text":" "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" supports six default types of scrolling: "},{"type":"codeVoice","code":"Left"},{"type":"text","text":", "},{"type":"codeVoice","code":"LeftRight"},{"type":"text","text":", "},{"type":"codeVoice","code":"Right"},{"type":"text","text":", "},{"type":"codeVoice","code":"RightLeft"},{"type":"text","text":", "},{"type":"codeVoice","code":"Continuous"},{"type":"text","text":", and "},{"type":"codeVoice","code":"ContinuousReverse"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/type","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/type"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a newly initialized "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/init(frame:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/scrollSequence":{"role":"symbol","title":"scrollSequence","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollSequence"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MarqueeStep","preciseIdentifier":"s:7GTUIKit11MarqueeStepP"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"An optional custom scroll “sequence”, defined by an array of "},{"type":"codeVoice","code":"ScrollStep"},{"type":"text","text":" or "},{"type":"codeVoice","code":"FadeStep"},{"type":"text","text":" instances. A sequence"},{"type":"text","text":" "},{"type":"text","text":"defines a single scroll\/animation loop, which will continue to be automatically repeated like the default types."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/scrollSequence","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/scrollsequence"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/labelize":{"role":"symbol","title":"labelize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A boolean property that sets whether the "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" should behave like a normal "},{"type":"codeVoice","code":"UILabel"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"labelize"}],"url":"\/documentation\/gtuikit\/marqueelabel\/labelize"},"doc://org.cocoapods.GTUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/prepareForInterfaceBuilder()":{"role":"symbol","title":"prepareForInterfaceBuilder()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForInterfaceBuilder"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/prepareForInterfaceBuilder()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareForInterfaceBuilder"}],"url":"\/documentation\/gtuikit\/marqueelabel\/prepareforinterfacebuilder()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/text":{"role":"symbol","title":"text","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/text","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"text"}],"url":"\/documentation\/gtuikit\/marqueelabel\/text"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/isHighlighted":{"role":"symbol","title":"isHighlighted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHighlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isHighlighted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlighted"}],"url":"\/documentation\/gtuikit\/marqueelabel\/ishighlighted"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/animationDelay":{"role":"symbol","title":"animationDelay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The length of delay in seconds that the label pauses at the completion of a scroll."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationDelay"}],"url":"\/documentation\/gtuikit\/marqueelabel\/animationdelay"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/controllerLabelsAnimate(_:)":{"role":"symbol","title":"controllerLabelsAnimate(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerLabelsAnimate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"De-labelizes all "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" instances that have the specified view controller in their next responder chain."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/controllerLabelsAnimate(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/controllerlabelsanimate(_:)"},"doc://org.cocoapods.GTUIKit/9PinLayout10LayoutableP":{"type":"unresolvable","title":"PinLayout.Layoutable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/9PinLayout18AutoSizeCalculableP":{"type":"unresolvable","title":"PinLayout.AutoSizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/forceScrolling":{"role":"symbol","title":"forceScrolling","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceScrolling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A boolean property that sets whether the "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" should scroll, even if the specificed test string"},{"type":"text","text":" "},{"type":"text","text":"can be fully contained within the label frame."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/forceScrolling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"forceScrolling"}],"url":"\/documentation\/gtuikit\/marqueelabel\/forcescrolling"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/attributedText":{"role":"symbol","title":"attributedText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributedText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/attributedText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"attributedText"}],"url":"\/documentation\/gtuikit\/marqueelabel\/attributedtext"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/SpeedLimit":{"role":"symbol","title":"MarqueeLabel.SpeedLimit","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpeedLimit"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" scrolling speed may be defined by one of two ways:"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/SpeedLimit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SpeedLimit"}],"url":"\/documentation\/gtuikit\/marqueelabel\/speedlimit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/willMove(toWindow:)":{"role":"symbol","title":"willMove(toWindow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/willMove(toWindow:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/willmove(towindow:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/controllerLabelsLabelize(_:)":{"role":"symbol","title":"controllerLabelsLabelize(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerLabelsLabelize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Labelizes all "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" instances that have the specified view controller in their next responder chain."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/controllerLabelsLabelize(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/controllerlabelslabelize(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/animationCurve":{"role":"symbol","title":"animationCurve","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationCurve"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AnimationCurve","preciseIdentifier":"c:@E@UIViewAnimationCurve"}],"abstract":[{"type":"text","text":"Specifies the animation curve used in the scrolling motion of the labels."},{"type":"text","text":" "},{"type":"text","text":"Allowable options:"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationCurve","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/animationcurve"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/shutdownLabel()":{"role":"symbol","title":"shutdownLabel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutdownLabel"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Immediately resets the label to the home position, cancelling any in-flight scroll animation."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/shutdownLabel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shutdownLabel"}],"url":"\/documentation\/gtuikit\/marqueelabel\/shutdownlabel()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/tapToScroll":{"role":"symbol","title":"tapToScroll","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tapToScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A boolean property that sets whether the "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" should only begin a scroll when tapped."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/tapToScroll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tapToScroll"}],"url":"\/documentation\/gtuikit\/marqueelabel\/taptoscroll"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/highlightedTextColor":{"role":"symbol","title":"highlightedTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/highlightedTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlightedTextColor"}],"url":"\/documentation\/gtuikit\/marqueelabel\/highlightedtextcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/unpauseLabel()":{"role":"symbol","title":"unpauseLabel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unpauseLabel"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Un-pauses a previously paused text scrolling animation. This method has no effect if the label was not previously paused using "},{"type":"codeVoice","code":"pauseLabel"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/unpauseLabel()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/unpauselabel()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/scrollRate":{"deprecated":true,"role":"symbol","title":"scrollRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/scrollRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollRate"}],"url":"\/documentation\/gtuikit\/marqueelabel\/scrollrate"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/scrollDuration":{"deprecated":true,"role":"symbol","title":"scrollDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/scrollDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollDuration"}],"url":"\/documentation\/gtuikit\/marqueelabel\/scrollduration"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/didMoveToWindow()":{"role":"symbol","title":"didMoveToWindow()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToWindow"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/didMoveToWindow()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didMoveToWindow"}],"url":"\/documentation\/gtuikit\/marqueelabel\/didmovetowindow()"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/gtuikit\/marqueelabel\/layoutsubviews()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/textCoordinateForFramePoint(_:)":{"role":"symbol","title":"textCoordinateForFramePoint(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textCoordinateForFramePoint"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Function to convert a point from the label view frame coordinates to “text” coordinates, i.e. the equivalent"},{"type":"text","text":" "},{"type":"text","text":"position in the (possibly) scrolling label. For example, it can be used to convert the coordinates"},{"type":"text","text":" "},{"type":"text","text":"of a tap point on the MarqueeLabel view into that of the scrolling label, in order to determine the"},{"type":"text","text":" "},{"type":"text","text":"word or character under the tap point."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/textCoordinateForFramePoint(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/textcoordinateforframepoint(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/baselineAdjustment":{"role":"symbol","title":"baselineAdjustment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"baselineAdjustment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBaselineAdjustment","preciseIdentifier":"c:@E@UIBaselineAdjustment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/baselineAdjustment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baselineAdjustment"}],"url":"\/documentation\/gtuikit\/marqueelabel\/baselineadjustment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/shadowOffset":{"role":"symbol","title":"shadowOffset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/shadowOffset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shadowOffset"}],"url":"\/documentation\/gtuikit\/marqueelabel\/shadowoffset"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/layerClass":{"role":"symbol","title":"layerClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/layerClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layerClass"}],"url":"\/documentation\/gtuikit\/marqueelabel\/layerclass"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/speed":{"role":"symbol","title":"speed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SpeedLimit","preciseIdentifier":"s:7GTUIKit12MarqueeLabelC10SpeedLimitO"}],"abstract":[{"type":"text","text":"Defines the speed of the "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" scrolling animation."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/speed","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/speed"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/draw(_:in:)":{"role":"symbol","title":"draw(_:in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CALayer","preciseIdentifier":"c:objc(cs)CALayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/draw(_:in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawLayer:inContext:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/draw(_:in:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/animateForController(_:)":{"role":"symbol","title":"animateForController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animateForController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animateForController(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animateForController:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/animateforcontroller(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/controllerViewDidAppear(_:)":{"role":"symbol","title":"controllerViewDidAppear(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerViewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Convenience method to restart all "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" instances that have the specified view controller in their next responder chain."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/controllerViewDidAppear(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/controllerviewdidappear(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/forLastBaselineLayout":{"role":"symbol","title":"forLastBaselineLayout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forLastBaselineLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/forLastBaselineLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewForLastBaselineLayout"}],"url":"\/documentation\/gtuikit\/marqueelabel\/forlastbaselinelayout"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/labelWillBeginScroll()":{"role":"symbol","title":"labelWillBeginScroll()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelWillBeginScroll"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the label animation is about to begin."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelWillBeginScroll()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/labelwillbeginscroll()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/restartForViewController(_:)":{"role":"symbol","title":"restartForViewController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restartForViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/restartForViewController(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restartForViewController:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/restartforviewcontroller(_:)"},"doc://org.cocoapods.GTUIKit/objc(cs)UILabel":{"type":"unresolvable","title":"UILabel","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UILabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/font":{"role":"symbol","title":"font","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/font","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"font"}],"url":"\/documentation\/gtuikit\/marqueelabel\/font"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/pauseLabel()":{"role":"symbol","title":"pauseLabel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseLabel"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Pauses the text scrolling animation, at any point during an in-progress animation."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/pauseLabel()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/pauselabel()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/gtuikit\/marqueelabel\/awakefromnib()"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/contentMode":{"role":"symbol","title":"contentMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"c:@E@UIViewContentMode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/contentMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentMode"}],"url":"\/documentation\/gtuikit\/marqueelabel\/contentmode"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/animationDidStop(_:finished:)":{"role":"symbol","title":"animationDidStop(_:finished:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDidStop"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CAAnimation","preciseIdentifier":"c:objc(cs)CAAnimation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationDidStop(_:finished:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationDidStop:finished:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/animationdidstop(_:finished:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/fadeLength":{"role":"symbol","title":"fadeLength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fadeLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The length of transparency fade at the left and right edges of the frame."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/fadeLength","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fadeLength"}],"url":"\/documentation\/gtuikit\/marqueelabel\/fadelength"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/tintColor":{"role":"symbol","title":"tintColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/tintColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tintColor"}],"url":"\/documentation\/gtuikit\/marqueelabel\/tintcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/sizeThatFits(_:)":{"role":"symbol","title":"sizeThatFits(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/sizeThatFits(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sizeThatFits:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/sizethatfits(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/animationPosition":{"role":"symbol","title":"animationPosition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"An optional CGFloat computed value that provides the current scroll animation position, as a value between"},{"type":"text","text":" "},{"type":"text","text":"0.0 and 1.0. A value of 0.0 indicates the label is “at home” ("},{"type":"codeVoice","code":"awayFromHome"},{"type":"text","text":" will be false). A value"},{"type":"text","text":" "},{"type":"text","text":"of 1.0 indicates the label is at the “away” position (and "},{"type":"codeVoice","code":"awayFromHome"},{"type":"text","text":" will be true)."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationPosition","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/animationposition"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/textLayoutSize()":{"role":"symbol","title":"textLayoutSize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textLayoutSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"Returns the unconstrained size of the specified label text (for a single line)."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/textLayoutSize()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/marqueelabel\/textlayoutsize()"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/isEnabled":{"role":"symbol","title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enabled"}],"url":"\/documentation\/gtuikit\/marqueelabel\/isenabled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MarqueeLabel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MarqueeLabel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MarqueeLabel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationDelay","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/attributedText","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/backgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/baselineAdjustment","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/contentMode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/fadeLength","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/font","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/forLastBaselineLayout","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/forceScrolling","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/highlightedTextColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/holdScrolling","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/intrinsicContentSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isAccessibilityElement","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isEnabled","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/isHighlighted","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/leadingBuffer","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/numberOfLines","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/scrollDuration","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/scrollRate","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/shadowColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/shadowOffset","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/tapToScroll","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/text","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/textColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/tintColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/trailingBuffer"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animateForController(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/animationDidStop(_:finished:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/awakeFromNib()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/didMoveToWindow()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/draw(_:in:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/forBaselineLayout()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/init(frame:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelWasTapped(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelizeForController(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/layoutSubviews()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/prepareForInterfaceBuilder()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/restartForViewController(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/restartLabel()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/shutdownLabel()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/sizeThatFits(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/tintColorDidChange()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/willMove(toWindow:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/layerClass"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UILabel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CAAnimationDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarqueeLabel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1restartLabel()\/title","value":"restartLabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1restartLabel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"restartLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1tintColorDidChange()\/title","value":"tintColorDidChange"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1tintColorDidChange()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tintColorDidChange"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1forBaselineLayout()\/title","value":"viewForBaselineLayout"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1forBaselineLayout()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewForBaselineLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1shadowColor\/title","value":"shadowColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1shadowColor\/fragments","value":[{"kind":"identifier","text":"shadowColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1trailingBuffer\/title","value":"trailingBuffer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1trailingBuffer\/fragments","value":[{"kind":"identifier","text":"trailingBuffer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1numberOfLines\/title","value":"numberOfLines"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1numberOfLines\/fragments","value":[{"kind":"identifier","text":"numberOfLines"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1labelWasTapped(_:)\/title","value":"labelWasTapped:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1labelWasTapped(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"labelWasTapped:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel\/title","value":"MarqueeLabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel\/fragments","value":[{"kind":"identifier","text":"MarqueeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1backgroundColor\/title","value":"backgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1backgroundColor\/fragments","value":[{"kind":"identifier","text":"backgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1leadingBuffer\/title","value":"leadingBuffer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1leadingBuffer\/fragments","value":[{"kind":"identifier","text":"leadingBuffer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1holdScrolling\/title","value":"holdScrolling"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1holdScrolling\/fragments","value":[{"kind":"identifier","text":"holdScrolling"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1textColor\/title","value":"textColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1textColor\/fragments","value":[{"kind":"identifier","text":"textColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1isAccessibilityElement\/title","value":"isAccessibilityElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1isAccessibilityElement\/fragments","value":[{"kind":"identifier","text":"isAccessibilityElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1labelizeForController(_:)\/title","value":"labelizeForController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1labelizeForController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"labelizeForController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1labelize\/title","value":"labelize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1labelize\/fragments","value":[{"kind":"identifier","text":"labelize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1prepareForInterfaceBuilder()\/title","value":"prepareForInterfaceBuilder"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1prepareForInterfaceBuilder()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForInterfaceBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1text\/title","value":"text"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1text\/fragments","value":[{"kind":"identifier","text":"text"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1isHighlighted\/title","value":"highlighted"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1isHighlighted\/fragments","value":[{"kind":"identifier","text":"highlighted"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1animationDelay\/title","value":"animationDelay"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1animationDelay\/fragments","value":[{"kind":"identifier","text":"animationDelay"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1forceScrolling\/title","value":"forceScrolling"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1forceScrolling\/fragments","value":[{"kind":"identifier","text":"forceScrolling"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1attributedText\/title","value":"attributedText"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1attributedText\/fragments","value":[{"kind":"identifier","text":"attributedText"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1willMove(toWindow:)\/title","value":"willMoveToWindow:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1willMove(toWindow:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToWindow:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1shutdownLabel()\/title","value":"shutdownLabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1shutdownLabel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shutdownLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1tapToScroll\/title","value":"tapToScroll"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1tapToScroll\/fragments","value":[{"kind":"identifier","text":"tapToScroll"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1highlightedTextColor\/title","value":"highlightedTextColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1highlightedTextColor\/fragments","value":[{"kind":"identifier","text":"highlightedTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1scrollRate\/title","value":"scrollRate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1scrollRate\/fragments","value":[{"kind":"identifier","text":"scrollRate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1scrollDuration\/title","value":"scrollDuration"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1scrollDuration\/fragments","value":[{"kind":"identifier","text":"scrollDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1didMoveToWindow()\/title","value":"didMoveToWindow"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1didMoveToWindow()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1baselineAdjustment\/title","value":"baselineAdjustment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1baselineAdjustment\/fragments","value":[{"kind":"identifier","text":"baselineAdjustment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1shadowOffset\/title","value":"shadowOffset"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1shadowOffset\/fragments","value":[{"kind":"identifier","text":"shadowOffset"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1layerClass\/title","value":"layerClass"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1layerClass\/fragments","value":[{"kind":"identifier","text":"layerClass"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1draw(_:in:)\/title","value":"drawLayer:inContext:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1draw(_:in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawLayer:inContext:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1animateForController(_:)\/title","value":"animateForController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1animateForController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animateForController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1forLastBaselineLayout\/title","value":"viewForLastBaselineLayout"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1forLastBaselineLayout\/fragments","value":[{"kind":"identifier","text":"viewForLastBaselineLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1restartForViewController(_:)\/title","value":"restartForViewController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1restartForViewController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"restartForViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1font\/title","value":"font"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1font\/fragments","value":[{"kind":"identifier","text":"font"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1contentMode\/title","value":"contentMode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1contentMode\/fragments","value":[{"kind":"identifier","text":"contentMode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1animationDidStop(_:finished:)\/title","value":"animationDidStop:finished:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1animationDidStop(_:finished:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationDidStop:finished:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1fadeLength\/title","value":"fadeLength"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1fadeLength\/fragments","value":[{"kind":"identifier","text":"fadeLength"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1tintColor\/title","value":"tintColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1tintColor\/fragments","value":[{"kind":"identifier","text":"tintColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1sizeThatFits(_:)\/title","value":"sizeThatFits:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1sizeThatFits(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeThatFits:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1isEnabled\/title","value":"enabled"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1isEnabled\/fragments","value":[{"kind":"identifier","text":"enabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}