{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRecognizeSimultaneouslyWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"otherGestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuicollectionview\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuicollectionview\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionView\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}],"role":"symbol","title":"gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRecognizeSimultaneouslyWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTUICollectionView(im)gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionView":{"role":"symbol","title":"GTUICollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionView"}],"url":"\/documentation\/gtuikit\/gtuicollectionview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionView/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)":{"role":"symbol","title":"gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRecognizeSimultaneouslyWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionView\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}],"url":"\/documentation\/gtuikit\/gtuicollectionview\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"gestureRecognizer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRecognizeSimultaneouslyWithGestureRecognizer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"otherGestureRecognizer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionView\/title","value":"GTUICollectionView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionView\/fragments","value":[{"kind":"identifier","text":"GTUICollectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionView~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)\/title","value":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionView~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}