{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSpecThatFits"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"constrainedSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASSizeRange","preciseIdentifier":"c:@SA@ASSizeRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASLayoutSpec","preciseIdentifier":"c:objc(cs)ASLayoutSpec"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtalertoptionitemnode\/layoutspecthatfits(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtalertoptionitemnode\/layoutspecthatfits(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertOptionItemNode\/layoutSpecThatFits(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSpecThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASSizeRange","preciseIdentifier":"c:@SA@ASSizeRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASLayoutSpec","preciseIdentifier":"c:objc(cs)ASLayoutSpec"}],"title":"layoutSpecThatFits(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)GTAlertOptionItemNode(im)layoutSpecThatFits:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"layoutSpecThatFits:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertOptionItemNode"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertOptionItemNode":{"role":"symbol","title":"GTAlertOptionItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertOptionItemNode"}],"abstract":[{"type":"text","text":"Option Item Alert"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertOptionItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertOptionItemNode"}],"url":"\/documentation\/gtuikit\/gtalertoptionitemnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertOptionItemNode/layoutSpecThatFits(_:)":{"role":"symbol","title":"layoutSpecThatFits(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSpecThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASSizeRange","preciseIdentifier":"c:@SA@ASSizeRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASLayoutSpec","preciseIdentifier":"c:objc(cs)ASLayoutSpec"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertOptionItemNode\/layoutSpecThatFits(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSpecThatFits:"}],"url":"\/documentation\/gtuikit\/gtalertoptionitemnode\/layoutspecthatfits(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"layoutSpecThatFits:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSpecThatFits:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"ASLayoutSpec","preciseIdentifier":"c:objc(cs)ASLayoutSpec"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"layoutSpecThatFits:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASSizeRange","preciseIdentifier":"c:@SA@ASSizeRange"},{"kind":"text","text":") "},{"kind":"internalParam","text":"constrainedSize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertOptionItemNode\/title","value":"GTAlertOptionItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertOptionItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertOptionItemNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertOptionItemNode~1layoutSpecThatFits(_:)\/title","value":"layoutSpecThatFits:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertOptionItemNode~1layoutSpecThatFits(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSpecThatFits:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}