{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentTransitionAdaptor","text":"GTUISegmentTransitionAdaptor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"translate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fromIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"toIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"percent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmentadaptor\/segmenttransition(adaptor:translate:toindex:percent:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/segmentTransition(adaptor:translate:toIndex:percent:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"转场中"}],"kind":"symbol","metadata":{"role":"symbol","title":"segmentTransition(adaptor:translate:toIndex:percent:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentTransitionAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentTransitionAdaptor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"translate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"toIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"percent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:7GTUIKit18GTUISegmentAdaptorC17segmentTransition7adaptor9translate7toIndex7percentyAA0beC0C_SiSgSi14CoreFoundation7CGFloatVtF","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/GTUISegmentTransitionAdaptorDelegate-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptor/segmentTransition(adaptor:translate:toIndex:percent:)":{"role":"symbol","title":"segmentTransition(adaptor:translate:toIndex:percent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentTransitionAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentTransitionAdaptor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"translate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"toIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"percent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"转场中"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/segmentTransition(adaptor:translate:toIndex:percent:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentadaptor\/segmenttransition(adaptor:translate:toindex:percent:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptor/GTUISegmentTransitionAdaptorDelegate-Implementations":{"role":"collectionGroup","title":"GTUISegmentTransitionAdaptorDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/GTUISegmentTransitionAdaptorDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentadaptor\/gtuisegmenttransitionadaptordelegate-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionAdaptor":{"role":"symbol","title":"GTUISegmentTransitionAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentTransitionAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentTransitionAdaptor"}],"url":"\/documentation\/gtuikit\/gtuisegmenttransitionadaptor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptor":{"role":"symbol","title":"GTUISegmentAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentAdaptor"}],"url":"\/documentation\/gtuikit\/gtuisegmentadaptor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionAdaptor\/title","value":"GTUISegmentTransitionAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUISegmentTransitionAdaptor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor\/title","value":"GTUISegmentAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUISegmentAdaptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}