{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segmentControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentControl","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentControl","text":"GTUISegmentControl"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isRepeat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmentadaptor\/segment(segmentcontrol:didselectat:isrepeat:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/segment(segmentControl:didSelectAt:isRepeat:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"选中某个Item"}],"kind":"symbol","metadata":{"role":"symbol","title":"segment(segmentControl:didSelectAt:isRepeat:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segmentControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentControl","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentControl"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isRepeat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:7GTUIKit18GTUISegmentAdaptorC7segment0D7Control11didSelectAt8isRepeatyAA0bE0C_SiSbtF","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/GTUISegmentControlDelegate-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptor/GTUISegmentControlDelegate-Implementations":{"role":"collectionGroup","title":"GTUISegmentControlDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/GTUISegmentControlDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentadaptor\/gtuisegmentcontroldelegate-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentControl":{"role":"symbol","title":"GTUISegmentControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentControl"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentControl"}],"url":"\/documentation\/gtuikit\/gtuisegmentcontrol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptor/segment(segmentControl:didSelectAt:isRepeat:)":{"role":"symbol","title":"segment(segmentControl:didSelectAt:isRepeat:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segmentControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentControl","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentControl"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isRepeat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"选中某个Item"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/segment(segmentControl:didSelectAt:isRepeat:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentadaptor\/segment(segmentcontrol:didselectat:isrepeat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptor":{"role":"symbol","title":"GTUISegmentAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentAdaptor"}],"url":"\/documentation\/gtuikit\/gtuisegmentadaptor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentControl\/title","value":"GTUISegmentControl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentControl\/fragments","value":[{"kind":"identifier","text":"GTUISegmentControl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor\/title","value":"GTUISegmentAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUISegmentAdaptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}