{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeToNextState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsView","text":"GTStepsView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView","text":"GTStepsItemView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView","text":"GTStepsItemView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView\/State-swift.enum","preciseIdentifier":"s:7GTUIKit15GTStepsItemViewC5StateO","text":"State"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView","text":"GTStepsItemView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView\/State-swift.enum","preciseIdentifier":"s:7GTUIKit15GTStepsItemViewC5StateO","text":"State"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"view","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"GTStepsView"}]}]},{"name":"item","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"当前正在流转的"},{"type":"codeVoice","code":"GTStepsItemView"}]}]},{"name":"state","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"流转的当前状态"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"流转的下一个状态"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtstepsviewdelegate\/changetonextstate(view:item:state:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsViewDelegate\/changeToNextState(view:item:state:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"流转状态"}],"kind":"symbol","metadata":{"role":"symbol","title":"changeToNextState(view:item:state:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeToNextState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTStepsView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:7GTUIKit15GTStepsItemViewC5StateO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:7GTUIKit15GTStepsItemViewC5StateO"}],"symbolKind":"method","externalID":"s:7GTUIKit19GTStepsViewDelegateP17changeToNextState4view4item5stateAA0b4ItemC0C0H0OAA0bC0C_AiKtF","required":true,"modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsViewDelegate"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsItemView":{"role":"symbol","title":"GTStepsItemView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepsItemView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepsItemView"}],"url":"\/documentation\/gtuikit\/gtstepsitemview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsItemView/State-swift.enum":{"role":"symbol","title":"GTStepsItemView.State","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"abstract":[{"type":"text","text":"ready: 准备"},{"type":"text","text":" "},{"type":"text","text":"inprogress：进行中,"},{"type":"text","text":" "},{"type":"text","text":"done：完成"},{"type":"text","text":" "},{"type":"text","text":"error：错误"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView\/State-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"State"}],"url":"\/documentation\/gtuikit\/gtstepsitemview\/state-swift.enum"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsView":{"role":"symbol","title":"GTStepsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepsView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepsView"}],"url":"\/documentation\/gtuikit\/gtstepsview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsViewDelegate/changeToNextState(view:item:state:)":{"role":"symbol","title":"changeToNextState(view:item:state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeToNextState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTStepsView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:7GTUIKit15GTStepsItemViewC5StateO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:7GTUIKit15GTStepsItemViewC5StateO"}],"abstract":[{"type":"text","text":"流转状态"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsViewDelegate\/changeToNextState(view:item:state:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtstepsviewdelegate\/changetonextstate(view:item:state:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsViewDelegate":{"role":"symbol","title":"GTStepsViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepsViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepsViewDelegate"}],"url":"\/documentation\/gtuikit\/gtstepsviewdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsItemView\/title","value":"GTStepsItemView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsItemView\/fragments","value":[{"kind":"identifier","text":"GTStepsItemView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsView\/title","value":"GTStepsView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsView\/fragments","value":[{"kind":"identifier","text":"GTStepsView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}