{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemContentView","text":"ESTabBarItemContentView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/estabbaritem\/contentview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/contentView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Customize content view"}],"kind":"symbol","metadata":{"role":"symbol","title":"contentView","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ESTabBarItemContentView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemContentView"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:7GTUIKit12ESTabBarItemC11contentViewAA0bcd7ContentF0CSgvp","modules":[{"name":"GTUIKit"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"8.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView":{"role":"symbol","title":"ESTabBarItemContentView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItemContentView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarItemContentView"}],"url":"\/documentation\/gtuikit\/estabbaritemcontentview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem":{"role":"symbol","title":"ESTabBarItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarItem"}],"url":"\/documentation\/gtuikit\/estabbaritem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/contentView":{"role":"symbol","title":"contentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ESTabBarItemContentView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemContentView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Customize content view"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/contentView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritem\/contentview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView\/title","value":"ESTabBarItemContentView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView\/fragments","value":[{"kind":"identifier","text":"ESTabBarItemContentView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem\/title","value":"ESTabBarItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem\/fragments","value":[{"kind":"identifier","text":"ESTabBarItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}