{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkageManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageManager","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILinkageManager","text":"GTUILinkageManager"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuilinkageviewcontroller\/linkagemanager"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/linkageManager","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkageManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILinkageManager","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILinkageManager"}],"title":"linkageManager","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit25GTUILinkageViewControllerC14linkageManagerAA0bF0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController/linkageManager":{"role":"symbol","title":"linkageManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkageManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILinkageManager","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILinkageManager"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/linkageManager","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller\/linkagemanager"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController":{"role":"symbol","title":"GTUILinkageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILinkageViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILinkageViewController"}],"url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageManager":{"role":"symbol","title":"GTUILinkageManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILinkageManager"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILinkageManager"}],"url":"\/documentation\/gtuikit\/gtuilinkagemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/title","value":"GTUILinkageViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/fragments","value":[{"kind":"identifier","text":"GTUILinkageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageManager\/title","value":"GTUILinkageManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageManager\/fragments","value":[{"kind":"identifier","text":"GTUILinkageManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}