{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentAdaptor","text":"GTUISegmentAdaptor"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemType","preciseIdentifier":"s:7GTUIKit19GTUISegmentItemTypeP","text":"GTUISegmentItemType"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"adaptor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"GTUISegmentAdaptor"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"[GTUISegmentItemType]"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuilinkageviewcontroller\/segment(adaptor:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/segment(adaptor:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"返回的items数量"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentAdaptor"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"GTUISegmentItemType","preciseIdentifier":"s:7GTUIKit19GTUISegmentItemTypeP"},{"kind":"text","text":"]"}],"title":"segment(adaptor:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7GTUIKit25GTUILinkageViewControllerC7segment7adaptorSayAA19GTUISegmentItemType_pGAA0G7AdaptorC_tF","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController":{"role":"symbol","title":"GTUILinkageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILinkageViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILinkageViewController"}],"url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentItemType":{"role":"symbol","title":"GTUISegmentItemType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentItemType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentItemType"}],"url":"\/documentation\/gtuikit\/gtuisegmentitemtype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptor":{"role":"symbol","title":"GTUISegmentAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentAdaptor"}],"url":"\/documentation\/gtuikit\/gtuisegmentadaptor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController/segment(adaptor:)":{"role":"symbol","title":"segment(adaptor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentAdaptor"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"GTUISegmentItemType","preciseIdentifier":"s:7GTUIKit19GTUISegmentItemTypeP"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"返回的items数量"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/segment(adaptor:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller\/segment(adaptor:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/title","value":"GTUILinkageViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/fragments","value":[{"kind":"identifier","text":"GTUILinkageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor\/title","value":"GTUISegmentAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUISegmentAdaptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}