{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISubLinkageViewController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISubLinkageViewController","text":"GTUISubLinkageViewController"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuilinkageviewcontroller\/subviewcontroller(vc:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/subViewController(vc:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GTUISubLinkageViewControllerDelegate.subViewController(vc:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"subViewController(vc:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISubLinkageViewController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISubLinkageViewController"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"s:7GTUIKit25GTUILinkageViewControllerC03subcD02vcyAA014GTUISubLinkagecD0CSg_tF","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/GTUISubLinkageViewControllerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController/subViewController(vc:)":{"role":"symbol","title":"subViewController(vc:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISubLinkageViewController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISubLinkageViewController"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/subViewController(vc:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller\/subviewcontroller(vc:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISubLinkageViewController":{"role":"symbol","title":"GTUISubLinkageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISubLinkageViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISubLinkageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISubLinkageViewController"}],"url":"\/documentation\/gtuikit\/gtuisublinkageviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController":{"role":"symbol","title":"GTUILinkageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILinkageViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILinkageViewController"}],"url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController/GTUISubLinkageViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"GTUISubLinkageViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/GTUISubLinkageViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller\/gtuisublinkageviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISubLinkageViewController\/title","value":"GTUISubLinkageViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISubLinkageViewController\/fragments","value":[{"kind":"identifier","text":"GTUISubLinkageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/title","value":"GTUILinkageViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/fragments","value":[{"kind":"identifier","text":"GTUILinkageViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}