{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/marqueelabel\/willmove(towindow:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/marqueelabel\/willmove(towindow:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/willMove(toWindow:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?)"}],"title":"willMove(toWindow:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)MarqueeLabel(im)willMoveToWindow:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel":{"role":"symbol","title":"MarqueeLabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarqueeLabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarqueeLabel"}],"url":"\/documentation\/gtuikit\/marqueelabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/willMove(toWindow:)":{"role":"symbol","title":"willMove(toWindow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/willMove(toWindow:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}],"url":"\/documentation\/gtuikit\/marqueelabel\/willmove(towindow:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"willMoveToWindow:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToWindow:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"willMoveToWindow:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"newWindow"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel\/title","value":"MarqueeLabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel\/fragments","value":[{"kind":"identifier","text":"MarqueeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1willMove(toWindow:)\/title","value":"willMoveToWindow:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1willMove(toWindow:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToWindow:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}