{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pagerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtpagecontrolview\/pagerview(_:didselectitemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtpagecontrolview\/pagerview(_:didselectitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerView(_:didSelectItemAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"FSPagerViewDelegate.pagerView(_:didSelectItemAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"pagerView:didSelectItemAtIndex:"}],"role":"symbol","title":"pagerView(_:didSelectItemAt:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTPageControlView(im)pagerView:didSelectItemAtIndex:","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/FSPagerViewDelegate-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControlView/pagerView(_:didSelectItemAt:)":{"role":"symbol","title":"pagerView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerView(_:didSelectItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pagerView:didSelectItemAtIndex:"}],"url":"\/documentation\/gtuikit\/gtpagecontrolview\/pagerview(_:didselectitemat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControlView/FSPagerViewDelegate-Implementations":{"role":"collectionGroup","title":"FSPagerViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/FSPagerViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtpagecontrolview\/fspagerviewdelegate-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControlView":{"role":"symbol","title":"GTPageControlView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPageControlView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPageControlView"}],"url":"\/documentation\/gtuikit\/gtpagecontrolview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pagerView:didSelectItemAtIndex:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pagerView:didSelectItemAtIndex:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"pagerView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pagerView"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectItemAtIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView~1pagerView(_:didSelectItemAt:)\/title","value":"pagerView:didSelectItemAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView~1pagerView(_:didSelectItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pagerView:didSelectItemAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView\/title","value":"GTPageControlView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView\/fragments","value":[{"kind":"identifier","text":"GTPageControlView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}