{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableViewAdaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUITableViewAdaptor","text":"GTUITableViewAdaptor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuitableviewcontroller\/tableviewadaptor"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewController\/tableViewAdaptor","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableViewAdaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUITableViewAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUITableViewAdaptor"}],"title":"tableViewAdaptor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit23GTUITableViewControllerC05tableC7AdaptorAA0bcF0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewController"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewController":{"role":"symbol","title":"GTUITableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewController"}],"url":"\/documentation\/gtuikit\/gtuitableviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor":{"role":"symbol","title":"GTUITableViewAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewAdaptor"}],"url":"\/documentation\/gtuikit\/gtuitableviewadaptor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewController/tableViewAdaptor":{"role":"symbol","title":"tableViewAdaptor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableViewAdaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUITableViewAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUITableViewAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewController\/tableViewAdaptor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewcontroller\/tableviewadaptor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewController\/title","value":"GTUITableViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewController\/fragments","value":[{"kind":"identifier","text":"GTUITableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor\/title","value":"GTUITableViewAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUITableViewAdaptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}