{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNavigationItem","text":"GTNavigationItem"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtnavigationbarview\/backitem"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationBarView\/backItem","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTNavigationItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNavigationItem"}],"title":"backItem","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit19GTNavigationBarViewC8backItemAA0bF0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationBarView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNavigationBarView/backItem":{"role":"symbol","title":"backItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTNavigationItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNavigationItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationBarView\/backItem","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtnavigationbarview\/backitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNavigationItem":{"role":"symbol","title":"GTNavigationItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNavigationItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNavigationItem"}],"url":"\/documentation\/gtuikit\/gtnavigationitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNavigationBarView":{"role":"symbol","title":"GTNavigationBarView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNavigationBarView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationBarView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNavigationBarView"}],"url":"\/documentation\/gtuikit\/gtnavigationbarview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNavigationItem\/title","value":"GTNavigationItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNavigationItem\/fragments","value":[{"kind":"identifier","text":"GTNavigationItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNavigationBarView\/title","value":"GTNavigationBarView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNavigationBarView\/fragments","value":[{"kind":"identifier","text":"GTNavigationBarView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}