{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFirstItemImage"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/setfirstitemimage()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/setfirstitemimage()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/setFirstItemImage()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFirstItemImage"},{"kind":"text","text":"()"}],"title":"setFirstItemImage()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)GTAlertTitleMessageItemNode(im)setFirstItemImage","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"setFirstItemImage"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode":{"role":"symbol","title":"GTAlertTitleMessageItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}],"url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/setFirstItemImage()":{"role":"symbol","title":"setFirstItemImage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFirstItemImage"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/setFirstItemImage()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFirstItemImage"}],"url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/setfirstitemimage()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setFirstItemImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFirstItemImage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setFirstItemImage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode\/title","value":"GTAlertTitleMessageItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1setFirstItemImage()\/title","value":"setFirstItemImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1setFirstItemImage()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFirstItemImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}