{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutRender","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutRender","text":"GTUIFallLayoutRender"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutsectionitem\/render"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionItem\/render","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutRender","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutRender"}],"title":"render","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit25GTUIFallLayoutSectionItemC6renderAA0bC6RenderCvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionItem"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutRender":{"role":"symbol","title":"GTUIFallLayoutRender","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutRender"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutRender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutRender"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutrender"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionItem":{"role":"symbol","title":"GTUIFallLayoutSectionItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutSectionItem"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutsectionitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionItem/render":{"role":"symbol","title":"render","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutRender","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutRender"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionItem\/render","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionitem\/render"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutRender\/title","value":"GTUIFallLayoutRender"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutRender\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutRender"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionItem\/title","value":"GTUIFallLayoutSectionItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionItem\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}