{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForRowAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuitableviewadaptor\/tableview(_:heightforrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuitableviewadaptor\/tableview(_:heightforrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/tableView(_:heightForRowAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDelegate.tableView(_:heightForRowAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"tableView(_:heightForRowAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTUITableViewAdaptor(im)tableView:heightForRowAtIndexPath:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/UITableViewDelegate-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor/tableView(_:heightForRowAt:)":{"role":"symbol","title":"tableView(_:heightForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/tableView(_:heightForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}],"url":"\/documentation\/gtuikit\/gtuitableviewadaptor\/tableview(_:heightforrowat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor":{"role":"symbol","title":"GTUITableViewAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewAdaptor"}],"url":"\/documentation\/gtuikit\/gtuitableviewadaptor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewadaptor\/uitableviewdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tableView:heightForRowAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightForRowAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1tableView(_:heightForRowAt:)\/title","value":"tableView:heightForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1tableView(_:heightForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor\/title","value":"GTUITableViewAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUITableViewAdaptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}