{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pagerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtnoticebar\/numberofitems(in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtnoticebar\/numberofitems(in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/numberOfItems(in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"FSPagerViewDataSource.numberOfItems(in:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"numberOfItemsInPagerView:"}],"role":"symbol","title":"numberOfItems(in:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTNoticeBar(im)numberOfItemsInPagerView:","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/FSPagerViewDataSource-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar":{"role":"symbol","title":"GTNoticeBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNoticeBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNoticeBar"}],"url":"\/documentation\/gtuikit\/gtnoticebar"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar/numberOfItems(in:)":{"role":"symbol","title":"numberOfItems(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/numberOfItems(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfItemsInPagerView:"}],"url":"\/documentation\/gtuikit\/gtnoticebar\/numberofitems(in:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar/FSPagerViewDataSource-Implementations":{"role":"collectionGroup","title":"FSPagerViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/FSPagerViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtnoticebar\/fspagerviewdatasource-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"numberOfItemsInPagerView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfItemsInPagerView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"numberOfItemsInPagerView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pagerView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar\/title","value":"GTNoticeBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar\/fragments","value":[{"kind":"identifier","text":"GTNoticeBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar~1numberOfItems(in:)\/title","value":"numberOfItemsInPagerView:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar~1numberOfItems(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfItemsInPagerView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}