{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alertNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertNode","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAlertNode","text":"GTAlertNode"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtalertcontentnode\/alertnode"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertContentNode\/alertNode","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alertNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAlertNode","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAlertNode"},{"kind":"text","text":"?"}],"title":"alertNode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit18GTAlertContentNodeC05alertD0AA0bD0CSgvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertContentNode"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertContentNode/alertNode":{"role":"symbol","title":"alertNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alertNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAlertNode","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAlertNode"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertContentNode\/alertNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalertcontentnode\/alertnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertNode":{"role":"symbol","title":"GTAlertNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertNode"}],"url":"\/documentation\/gtuikit\/gtalertnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertContentNode":{"role":"symbol","title":"GTAlertContentNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertContentNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertContentNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertContentNode"}],"url":"\/documentation\/gtuikit\/gtalertcontentnode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertNode\/title","value":"GTAlertNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertNode\/fragments","value":[{"kind":"identifier","text":"GTAlertNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertContentNode\/title","value":"GTAlertContentNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertContentNode\/fragments","value":[{"kind":"identifier","text":"GTAlertContentNode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}