{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel","text":"GTUILabel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtbasepopview\/titlelable"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/titleLable","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel"}],"title":"titleLable","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit13GTBasePopViewC10titleLableAA9GTUILabelCvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILabel":{"role":"symbol","title":"GTUILabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILabel"}],"url":"\/documentation\/gtuikit\/gtuilabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView":{"role":"symbol","title":"GTBasePopView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBasePopView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTBasePopView"}],"url":"\/documentation\/gtuikit\/gtbasepopview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/titleLable":{"role":"symbol","title":"titleLable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/titleLable","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/titlelable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILabel\/title","value":"GTUILabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILabel\/fragments","value":[{"kind":"identifier","text":"GTUILabel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBasePopView\/title","value":"GTBasePopView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBasePopView\/fragments","value":[{"kind":"identifier","text":"GTBasePopView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}