{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectNumberPad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPadKeyboardView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNumberPadKeyboardView","text":"GTNumberPadKeyboardView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTKeyboardItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTKeyboardItem","text":"GTKeyboardItem"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTKeyboardItem\/ItemType","preciseIdentifier":"s:7GTUIKit14GTKeyboardItemC0C4TypeO","text":"ItemType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtnumberpadkeyboardviewdelegate\/didselectnumberpad(view:value:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPadKeyboardViewDelegate\/didSelectNumberPad(view:value:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"didSelectNumberPad(view:value:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectNumberPad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTNumberPadKeyboardView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNumberPadKeyboardView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTKeyboardItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTKeyboardItem"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ItemType","preciseIdentifier":"s:7GTUIKit14GTKeyboardItemC0C4TypeO"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:7GTUIKit31GTNumberPadKeyboardViewDelegateP015didSelectNumberC04view5valueyAA0bcdE0CSg_AA14GTKeyboardItemC0M4TypeOtF","required":true,"modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPadKeyboardViewDelegate"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTKeyboardItem/ItemType":{"role":"symbol","title":"GTKeyboardItem.ItemType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ItemType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTKeyboardItem\/ItemType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ItemType"}],"url":"\/documentation\/gtuikit\/gtkeyboarditem\/itemtype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNumberPadKeyboardViewDelegate/didSelectNumberPad(view:value:)":{"role":"symbol","title":"didSelectNumberPad(view:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectNumberPad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTNumberPadKeyboardView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTNumberPadKeyboardView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTKeyboardItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTKeyboardItem"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ItemType","preciseIdentifier":"s:7GTUIKit14GTKeyboardItemC0C4TypeO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPadKeyboardViewDelegate\/didSelectNumberPad(view:value:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtnumberpadkeyboardviewdelegate\/didselectnumberpad(view:value:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTKeyboardItem":{"role":"symbol","title":"GTKeyboardItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTKeyboardItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTKeyboardItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTKeyboardItem"}],"url":"\/documentation\/gtuikit\/gtkeyboarditem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNumberPadKeyboardView":{"role":"symbol","title":"GTNumberPadKeyboardView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNumberPadKeyboardView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPadKeyboardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNumberPadKeyboardView"}],"url":"\/documentation\/gtuikit\/gtnumberpadkeyboardview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNumberPadKeyboardViewDelegate":{"role":"symbol","title":"GTNumberPadKeyboardViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNumberPadKeyboardViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNumberPadKeyboardViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNumberPadKeyboardViewDelegate"}],"url":"\/documentation\/gtuikit\/gtnumberpadkeyboardviewdelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTKeyboardItem\/title","value":"GTKeyboardItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTKeyboardItem\/fragments","value":[{"kind":"identifier","text":"GTKeyboardItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNumberPadKeyboardView\/title","value":"GTNumberPadKeyboardView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNumberPadKeyboardView\/fragments","value":[{"kind":"identifier","text":"GTNumberPadKeyboardView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}