{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutLinkageObject","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutLinkageObject","text":"GTUIFallLayoutLinkageObject"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutconfiguration\/linkage"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutConfiguration\/linkage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"是否需要保留联动视图"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutLinkageObject","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutLinkageObject"},{"kind":"text","text":"?"}],"title":"linkage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit27GTUIFallLayoutConfigurationC7linkageAA0bC13LinkageObjectCSgvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutConfiguration"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutLinkageObject":{"role":"symbol","title":"GTUIFallLayoutLinkageObject","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutLinkageObject","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutlinkageobject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutConfiguration/linkage":{"role":"symbol","title":"linkage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutLinkageObject","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutLinkageObject"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"是否需要保留联动视图"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutConfiguration\/linkage","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutconfiguration\/linkage"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutConfiguration":{"role":"symbol","title":"GTUIFallLayoutConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutConfiguration"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutConfiguration"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutLinkageObject\/title","value":"GTUIFallLayoutLinkageObject"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutLinkageObject\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutConfiguration\/title","value":"GTUIFallLayoutConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutConfiguration\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}