{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentAdaptor","text":"GTUISegmentAdaptor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishTranslateTo"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isCancel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmentadaptordelegate\/segment(adaptor:didfinishtranslateto:iscancel:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuisegmentadaptordelegate\/segment(adaptor:didfinishtranslateto:iscancel:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptorDelegate\/segment(adaptor:didFinishTranslateTo:isCancel:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"segmentWithAdaptor:didFinishTranslateTo:isCancel:"}],"role":"symbol","title":"segment(adaptor:didFinishTranslateTo:isCancel:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentAdaptor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishTranslateTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isCancel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@GTUIKit@objc(pl)GTUISegmentAdaptorDelegate(im)segmentWithAdaptor:didFinishTranslateTo:isCancel:","required":true,"modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptorDelegate"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptorDelegate/segment(adaptor:didFinishTranslateTo:isCancel:)":{"navigatorTitle":[{"kind":"identifier","text":"segmentWithAdaptor:didFinishTranslateTo:isCancel:"}],"role":"symbol","title":"segment(adaptor:didFinishTranslateTo:isCancel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"segment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adaptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentAdaptor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishTranslateTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isCancel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptorDelegate\/segment(adaptor:didFinishTranslateTo:isCancel:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentadaptordelegate\/segment(adaptor:didfinishtranslateto:iscancel:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptorDelegate":{"role":"symbol","title":"GTUISegmentAdaptorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentAdaptorDelegate"}],"abstract":[{"type":"text","text":"Delegate"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptorDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentAdaptorDelegate"}],"url":"\/documentation\/gtuikit\/gtuisegmentadaptordelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptor":{"role":"symbol","title":"GTUISegmentAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentAdaptor"}],"url":"\/documentation\/gtuikit\/gtuisegmentadaptor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"segmentWithAdaptor:didFinishTranslateTo:isCancel:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"segmentWithAdaptor:didFinishTranslateTo:isCancel:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"segmentWithAdaptor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentAdaptor","text":"GTUISegmentAdaptor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"adaptor"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishTranslateTo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"index"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCancel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isCancel"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptorDelegate~1segment(adaptor:didFinishTranslateTo:isCancel:)\/title","value":"segmentWithAdaptor:didFinishTranslateTo:isCancel:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptorDelegate~1segment(adaptor:didFinishTranslateTo:isCancel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"segmentWithAdaptor:didFinishTranslateTo:isCancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptorDelegate\/title","value":"GTUISegmentAdaptorDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptorDelegate\/fragments","value":[{"kind":"identifier","text":"GTUISegmentAdaptorDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor\/title","value":"GTUISegmentAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUISegmentAdaptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}