{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextView","text":"GTTextView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttexthelperview\/textview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextHelperView\/textView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextView"}],"title":"textView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit16GTTextHelperViewC04textD0AA0bD0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextHelperView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextHelperView/textView":{"role":"symbol","title":"textView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextHelperView\/textView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gttexthelperview\/textview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextView":{"role":"symbol","title":"GTTextView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextView"}],"url":"\/documentation\/gtuikit\/gttextview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextHelperView":{"role":"symbol","title":"GTTextHelperView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextHelperView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextHelperView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextHelperView"}],"url":"\/documentation\/gtuikit\/gttexthelperview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextView\/title","value":"GTTextView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextView\/fragments","value":[{"kind":"identifier","text":"GTTextView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextHelperView\/title","value":"GTTextHelperView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextHelperView\/fragments","value":[{"kind":"identifier","text":"GTTextHelperView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}