{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nibName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nibBundleOrNil"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuilinkageviewcontroller\/init(nibname:bundle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuilinkageviewcontroller\/init(nibname:bundle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/init(nibName:bundle:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nibName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?)"}],"title":"init(nibName:bundle:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@GTUIKit@objc(cs)GTUILinkageViewController(im)initWithNibName:bundle:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController":{"role":"symbol","title":"GTUILinkageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILinkageViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILinkageViewController"}],"url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController/init(nibName:bundle:)":{"role":"symbol","title":"init(nibName:bundle:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nibName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/init(nibName:bundle:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller\/init(nibname:bundle:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithNibName:bundle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNibName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSBundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibBundleOrNil"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/title","value":"GTUILinkageViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/fragments","value":[{"kind":"identifier","text":"GTUILinkageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController~1init(nibName:bundle:)\/title","value":"initWithNibName:bundle:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController~1init(nibName:bundle:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}