{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkageManagerRequestResetSubScrollViewOffset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"linkageManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageManager","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILinkageManager","text":"GTUILinkageManager"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuilinkageviewcontroller\/linkagemanagerrequestresetsubscrollviewoffset(linkagemanager:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/linkageManagerRequestResetSubScrollViewOffset(linkageManager:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GTUILinkageManagerDelegate.linkageManagerRequestResetSubScrollViewOffset(linkageManager:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkageManagerRequestResetSubScrollViewOffset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"linkageManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILinkageManager","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILinkageManager"},{"kind":"text","text":")"}],"title":"linkageManagerRequestResetSubScrollViewOffset(linkageManager:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7GTUIKit25GTUILinkageViewControllerC035linkageManagerRequestResetSubScrollC6Offset0eF0yAA0bF0C_tF","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController/linkageManagerRequestResetSubScrollViewOffset(linkageManager:)":{"role":"symbol","title":"linkageManagerRequestResetSubScrollViewOffset(linkageManager:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkageManagerRequestResetSubScrollViewOffset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"linkageManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILinkageManager","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILinkageManager"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController\/linkageManagerRequestResetSubScrollViewOffset(linkageManager:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller\/linkagemanagerrequestresetsubscrollviewoffset(linkagemanager:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageManager":{"role":"symbol","title":"GTUILinkageManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILinkageManager"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILinkageManager"}],"url":"\/documentation\/gtuikit\/gtuilinkagemanager"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController":{"role":"symbol","title":"GTUILinkageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILinkageViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILinkageViewController"}],"url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageManager\/title","value":"GTUILinkageManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageManager\/fragments","value":[{"kind":"identifier","text":"GTUILinkageManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/title","value":"GTUILinkageViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/fragments","value":[{"kind":"identifier","text":"GTUILinkageViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}