{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick","text":"GTUIFallLayoutStick"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutheader\/stick"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/stick","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"固定"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick"},{"kind":"text","text":"?"}],"title":"stick","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit20GTUIFallLayoutHeaderC5stickAA0bC5StickCSgvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutHeader":{"role":"symbol","title":"GTUIFallLayoutHeader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutHeader"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutHeader"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutheader"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutHeader/stick":{"role":"symbol","title":"stick","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"固定"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/stick","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutheader\/stick"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutStick":{"role":"symbol","title":"GTUIFallLayoutStick","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutStick"}],"abstract":[{"type":"text","text":"需要固定的位置"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutStick","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutStick"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutstick"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutHeader\/title","value":"GTUIFallLayoutHeader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutHeader\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutHeader"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutStick\/title","value":"GTUIFallLayoutStick"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutStick\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutStick"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}