{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTab"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)LYPageView","text":"LYPageView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/lypageviewdatasource\/numberoftab(view:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/lypageviewdatasource\/numberoftab(view:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/numberOfTab(view:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"顶部tab页签个数"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"numberOfTabWithView:"}],"role":"symbol","title":"numberOfTab(view:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTab"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LYPageView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)LYPageView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"symbolKind":"method","externalID":"c:@M@GTUIKit@objc(pl)LYpageViewDataSource(im)numberOfTabWithView:","required":true,"modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYpageViewDataSource":{"role":"symbol","title":"LYpageViewDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYpageViewDataSource"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LYpageViewDataSource"}],"url":"\/documentation\/gtuikit\/lypageviewdatasource"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYpageViewDataSource/numberOfTab(view:)":{"navigatorTitle":[{"kind":"identifier","text":"numberOfTabWithView:"}],"role":"symbol","title":"numberOfTab(view:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTab"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LYPageView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)LYPageView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"顶部tab页签个数"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/numberOfTab(view:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/lypageviewdatasource\/numberoftab(view:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYPageView":{"role":"symbol","title":"LYPageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYPageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LYPageView"}],"url":"\/documentation\/gtuikit\/lypageview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"numberOfTabWithView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfTabWithView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"numberOfTabWithView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)LYPageView","text":"LYPageView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"view"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource\/title","value":"LYpageViewDataSource"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource\/fragments","value":[{"kind":"identifier","text":"LYpageViewDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource~1numberOfTab(view:)\/title","value":"numberOfTabWithView:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource~1numberOfTab(view:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfTabWithView:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageView\/title","value":"LYPageView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageView\/fragments","value":[{"kind":"identifier","text":"LYPageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}