{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutBackground","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutBackground","text":"GTUIFallLayoutBackground"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/background"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/background","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutBackground","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutBackground"},{"kind":"text","text":"?"}],"title":"background","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit29GTUIFallLayoutSectionBaseItemC10backgroundAA0bC10BackgroundCSgvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/background":{"role":"symbol","title":"background","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutBackground","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutBackground"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/background","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/background"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutBackground":{"role":"symbol","title":"GTUIFallLayoutBackground","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutBackground"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutBackground","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutBackground"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutbackground"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem":{"role":"symbol","title":"GTUIFallLayoutSectionBaseItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutBackground\/title","value":"GTUIFallLayoutBackground"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutBackground\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutBackground"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/title","value":"GTUIFallLayoutSectionBaseItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}