{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutFooter","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutFooter","text":"GTUIFallLayoutFooter"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/footer"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/footer","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutFooter","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutFooter"},{"kind":"text","text":"?"}],"title":"footer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit29GTUIFallLayoutSectionBaseItemC6footerAA0bC6FooterCSgvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/footer":{"role":"symbol","title":"footer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutFooter","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutFooter"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/footer","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/footer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutFooter":{"role":"symbol","title":"GTUIFallLayoutFooter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutFooter"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutFooter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutFooter"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutfooter"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem":{"role":"symbol","title":"GTUIFallLayoutSectionBaseItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutFooter\/title","value":"GTUIFallLayoutFooter"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutFooter\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutFooter"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/title","value":"GTUIFallLayoutSectionBaseItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}