{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick","text":"GTUIFallLayoutStick"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/stick"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/stick","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick"},{"kind":"text","text":"?"}],"title":"stick","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit29GTUIFallLayoutSectionBaseItemC5stickAA0bC5StickCSgvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/stick":{"role":"symbol","title":"stick","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/stick","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/stick"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem":{"role":"symbol","title":"GTUIFallLayoutSectionBaseItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutStick":{"role":"symbol","title":"GTUIFallLayoutStick","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutStick"}],"abstract":[{"type":"text","text":"需要固定的位置"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutStick","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutStick"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutstick"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/title","value":"GTUIFallLayoutSectionBaseItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutStick\/title","value":"GTUIFallLayoutStick"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutStick\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutStick"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}