{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finishInteractiveTransition"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/finishinteractivetransition()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/finishinteractivetransition()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/finishInteractiveTransition()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIViewControllerContextTransitioning.finishInteractiveTransition()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"finishInteractiveTransition"}],"role":"symbol","title":"finishInteractiveTransition()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finishInteractiveTransition"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTUISegmentTransitionContext(im)finishInteractiveTransition","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/UIViewControllerContextTransitioning-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/finishInteractiveTransition()":{"role":"symbol","title":"finishInteractiveTransition()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finishInteractiveTransition"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/finishInteractiveTransition()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finishInteractiveTransition"}],"url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/finishinteractivetransition()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext":{"role":"symbol","title":"GTUISegmentTransitionContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentTransitionContext"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}],"url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/UIViewControllerContextTransitioning-Implementations":{"role":"collectionGroup","title":"UIViewControllerContextTransitioning Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/UIViewControllerContextTransitioning-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/uiviewcontrollercontexttransitioning-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"finishInteractiveTransition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finishInteractiveTransition"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"finishInteractiveTransition"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionContext~1finishInteractiveTransition()\/title","value":"finishInteractiveTransition"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionContext~1finishInteractiveTransition()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finishInteractiveTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionContext\/title","value":"GTUISegmentTransitionContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionContext\/fragments","value":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}