{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentSlideAnimationController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentSlideAnimationController","text":"GTUISegmentSlideAnimationController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/start(_:)-mnk6"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/start(_:)-mnk6","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"start(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTUISegmentSlideAnimationController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentSlideAnimationController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:7GTUIKit28GTUISegmentTransitionContextC5startyyAA0B24SlideAnimationControllerCF","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/start(_:)-mnk6":{"role":"symbol","title":"start(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTUISegmentSlideAnimationController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentSlideAnimationController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/start(_:)-mnk6","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/start(_:)-mnk6"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext":{"role":"symbol","title":"GTUISegmentTransitionContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentTransitionContext"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}],"url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentSlideAnimationController":{"role":"symbol","title":"GTUISegmentSlideAnimationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentSlideAnimationController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentSlideAnimationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentSlideAnimationController"}],"url":"\/documentation\/gtuikit\/gtuisegmentslideanimationcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionContext\/title","value":"GTUISegmentTransitionContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionContext\/fragments","value":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentSlideAnimationController\/title","value":"GTUISegmentSlideAnimationController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentSlideAnimationController\/fragments","value":[{"kind":"identifier","text":"GTUISegmentSlideAnimationController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}