{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefixTitleDescView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleValueLabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTitleValueLabel","text":"GTTitleValueLabel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttableviewcellv3\/prefixtitledescview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3\/prefixTitleDescView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefixTitleDescView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTitleValueLabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTitleValueLabel"}],"title":"prefixTitleDescView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit17GTTableViewCellV3C015prefixTitleDescC0AA17GTTitleValueLabelCvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewCellV3":{"role":"symbol","title":"GTTableViewCellV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTableViewCellV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTableViewCellV3"}],"url":"\/documentation\/gtuikit\/gttableviewcellv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleValueLabel":{"role":"symbol","title":"GTTitleValueLabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTitleValueLabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleValueLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTitleValueLabel"}],"url":"\/documentation\/gtuikit\/gttitlevaluelabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewCellV3/prefixTitleDescView":{"role":"symbol","title":"prefixTitleDescView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefixTitleDescView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTitleValueLabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTitleValueLabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3\/prefixTitleDescView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gttableviewcellv3\/prefixtitledescview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/title","value":"GTTableViewCellV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/fragments","value":[{"kind":"identifier","text":"GTTableViewCellV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleValueLabel\/title","value":"GTTitleValueLabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleValueLabel\/fragments","value":[{"kind":"identifier","text":"GTTitleValueLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}