{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suffixCheckBoxItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTCheckBoxV3","text":"GTCheckBoxV3"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttableviewcellv3\/suffixcheckboxitem"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3\/suffixCheckBoxItem","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suffixCheckBoxItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTCheckBoxV3","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTCheckBoxV3"}],"title":"suffixCheckBoxItem","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit17GTTableViewCellV3C18suffixCheckBoxItemAA07GTCheckhE0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewCellV3":{"role":"symbol","title":"GTTableViewCellV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTableViewCellV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTableViewCellV3"}],"url":"\/documentation\/gtuikit\/gttableviewcellv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewCellV3/suffixCheckBoxItem":{"role":"symbol","title":"suffixCheckBoxItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suffixCheckBoxItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTCheckBoxV3","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTCheckBoxV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3\/suffixCheckBoxItem","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gttableviewcellv3\/suffixcheckboxitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxV3":{"role":"symbol","title":"GTCheckBoxV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBoxV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBoxV3"}],"url":"\/documentation\/gtuikit\/gtcheckboxv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/title","value":"GTTableViewCellV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/fragments","value":[{"kind":"identifier","text":"GTTableViewCellV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/title","value":"GTCheckBoxV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/fragments","value":[{"kind":"identifier","text":"GTCheckBoxV3"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}