{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dimension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick","text":"GTUIFallLayoutStick"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"zIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutZIndex","preciseIdentifier":"s:7GTUIKit20GTUIFallLayoutZIndexO","text":"GTUIFallLayoutZIndex"},{"kind":"text","text":" = .topOfItem)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutheader\/init(dimension:stick:zindex:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/init(dimension:stick:zIndex:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dimension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"zIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutZIndex","preciseIdentifier":"s:7GTUIKit20GTUIFallLayoutZIndexO"},{"kind":"text","text":")"}],"title":"init(dimension:stick:zIndex:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:7GTUIKit20GTUIFallLayoutHeaderC9dimension5stick6zIndexAC14CoreFoundation7CGFloatV_AA0bC5StickCSgAA0bC6ZIndexOtcfc","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutHeader/init(dimension:stick:zIndex:)":{"role":"symbol","title":"init(dimension:stick:zIndex:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dimension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"zIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutZIndex","preciseIdentifier":"s:7GTUIKit20GTUIFallLayoutZIndexO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/init(dimension:stick:zIndex:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutheader\/init(dimension:stick:zindex:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutStick":{"role":"symbol","title":"GTUIFallLayoutStick","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutStick"}],"abstract":[{"type":"text","text":"需要固定的位置"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutStick","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutStick"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutstick"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutHeader":{"role":"symbol","title":"GTUIFallLayoutHeader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutHeader"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutHeader"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutheader"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutZIndex":{"role":"symbol","title":"GTUIFallLayoutZIndex","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutZIndex"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutZIndex","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutZIndex"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutzindex"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutStick\/title","value":"GTUIFallLayoutStick"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutStick\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutStick"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutHeader\/title","value":"GTUIFallLayoutHeader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutHeader\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutHeader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}