{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configMoreNumber"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarGroupView","text":"GTAvatarGroupView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel","text":"GTUILabel"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtavatargroupviewdelegate\/configmorenumber(groupview:view:)-1ruay"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupViewDelegate\/configMoreNumber(groupView:view:)-1ruay","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"configMoreNumber(groupView:view:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configMoreNumber"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAvatarGroupView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarGroupView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:7GTUIKit25GTAvatarGroupViewDelegatePAAE16configMoreNumber05groupD04viewyAA0bcD0C_AA9GTUILabelCtF","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupViewDelegate","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupViewDelegate\/configMoreNumber(groupView:view:)-8r4be"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILabel":{"role":"symbol","title":"GTUILabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILabel"}],"url":"\/documentation\/gtuikit\/gtuilabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarGroupViewDelegate":{"role":"symbol","title":"GTAvatarGroupViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAvatarGroupViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAvatarGroupViewDelegate"}],"url":"\/documentation\/gtuikit\/gtavatargroupviewdelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarGroupViewDelegate/configMoreNumber(groupView:view:)-1ruay":{"role":"symbol","title":"configMoreNumber(groupView:view:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configMoreNumber"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAvatarGroupView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarGroupView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupViewDelegate\/configMoreNumber(groupView:view:)-1ruay","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtavatargroupviewdelegate\/configmorenumber(groupview:view:)-1ruay"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarGroupViewDelegate/configMoreNumber(groupView:view:)-8r4be":{"defaultImplementations":1,"role":"symbol","title":"configMoreNumber(groupView:view:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configMoreNumber"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAvatarGroupView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarGroupView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupViewDelegate\/configMoreNumber(groupView:view:)-8r4be","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtavatargroupviewdelegate\/configmorenumber(groupview:view:)-8r4be"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarGroupView":{"role":"symbol","title":"GTAvatarGroupView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAvatarGroupView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAvatarGroupView"}],"url":"\/documentation\/gtuikit\/gtavatargroupview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILabel\/title","value":"GTUILabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILabel\/fragments","value":[{"kind":"identifier","text":"GTUILabel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarGroupView\/title","value":"GTAvatarGroupView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarGroupView\/fragments","value":[{"kind":"identifier","text":"GTAvatarGroupView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}