{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreContentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemContentView","text":"ESTabBarItemContentView"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/estabbar\/morecontentview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBar\/moreContentView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"自定义’More’按钮样式，继承自ESTabBarItemContentView"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreContentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ESTabBarItemContentView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemContentView"},{"kind":"text","text":"?"}],"title":"moreContentView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit8ESTabBarC15moreContentViewAA0bc4ItemeF0CSgvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBar"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBar":{"role":"symbol","title":"ESTabBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBar"}],"abstract":[{"type":"text","text":"ESTabBar是高度自定义的UITabBar子类，通过添加UIControl的方式实现自定义tabBarItem的效果。目前支持tabBar的大部分属性的设置，例如delegate,items,selectedImge,itemPositioning,itemWidth,itemSpacing等，以后会更加细致的优化tabBar原有属性的设置效果。"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBar"}],"url":"\/documentation\/gtuikit\/estabbar"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBar/moreContentView":{"role":"symbol","title":"moreContentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreContentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ESTabBarItemContentView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemContentView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"自定义’More’按钮样式，继承自ESTabBarItemContentView"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBar\/moreContentView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbar\/morecontentview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView":{"role":"symbol","title":"ESTabBarItemContentView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItemContentView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarItemContentView"}],"url":"\/documentation\/gtuikit\/estabbaritemcontentview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBar\/title","value":"ESTabBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBar\/fragments","value":[{"kind":"identifier","text":"ESTabBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView\/title","value":"ESTabBarItemContentView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView\/fragments","value":[{"kind":"identifier","text":"ESTabBarItemContentView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}