{"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmentadaptor\/uigesturerecognizerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuisegmentadaptor\/uigesturerecognizerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/UIGestureRecognizerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/gestureRecognizerShouldBegin(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptor/gestureRecognizerShouldBegin(_:)":{"role":"symbol","title":"gestureRecognizerShouldBegin(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/gestureRecognizerShouldBegin(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"url":"\/documentation\/gtuikit\/gtuisegmentadaptor\/gesturerecognizershouldbegin(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptor":{"role":"symbol","title":"GTUISegmentAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentAdaptor"}],"url":"\/documentation\/gtuikit\/gtuisegmentadaptor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptor\/gestureRecognizerShouldBegin(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor~1gestureRecognizerShouldBegin(_:)\/title","value":"gestureRecognizerShouldBegin:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor~1gestureRecognizerShouldBegin(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor\/title","value":"GTUISegmentAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUISegmentAdaptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}