{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttableviewheaderfooterview\/init(reuseidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gttableviewheaderfooterview\/init(reuseidentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewHeaderFooterView\/init(reuseIdentifier:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(reuseIdentifier:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@GTUIKit@objc(cs)GTTableViewHeaderFooterView(im)initWithReuseIdentifier:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithReuseIdentifier:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewHeaderFooterView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewHeaderFooterView/init(reuseIdentifier:)":{"role":"symbol","title":"init(reuseIdentifier:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewHeaderFooterView\/init(reuseIdentifier:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithReuseIdentifier:"}],"url":"\/documentation\/gtuikit\/gttableviewheaderfooterview\/init(reuseidentifier:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewHeaderFooterView":{"role":"symbol","title":"GTTableViewHeaderFooterView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTableViewHeaderFooterView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewHeaderFooterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTableViewHeaderFooterView"}],"url":"\/documentation\/gtuikit\/gttableviewheaderfooterview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithReuseIdentifier:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithReuseIdentifier:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithReuseIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reuseIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewHeaderFooterView~1init(reuseIdentifier:)\/title","value":"initWithReuseIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewHeaderFooterView~1init(reuseIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithReuseIdentifier:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewHeaderFooterView\/title","value":"GTTableViewHeaderFooterView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewHeaderFooterView\/fragments","value":[{"kind":"identifier","text":"GTTableViewHeaderFooterView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}