{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setBackgroundImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThemeImagePicker","preciseIdentifier":"s:7GTUIKit18GTThemeImagePickera","text":"GTThemeImagePicker"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuibuttonv3\/gt_setbackgroundimage(_:forstate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuibuttonv3\/gt_setbackgroundimage(_:forstate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setBackgroundImage(_:forState:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"gt_setBackgroundImage:forState:"}],"role":"symbol","title":"gt_setBackgroundImage(_:forState:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setBackgroundImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeImagePicker","preciseIdentifier":"s:7GTUIKit18GTThemeImagePickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTUIButtonV3(im)gt_setBackgroundImage:forState:","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3":{"role":"symbol","title":"GTUIButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIButtonV3"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setBackgroundImage(_:forState:)":{"role":"symbol","title":"gt_setBackgroundImage(_:forState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setBackgroundImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeImagePicker","preciseIdentifier":"s:7GTUIKit18GTThemeImagePickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setBackgroundImage(_:forState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setBackgroundImage:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_setbackgroundimage(_:forstate:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTThemeImagePicker":{"role":"symbol","title":"GTThemeImagePicker","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTThemeImagePicker"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThemeImagePicker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTThemeImagePicker"}],"url":"\/documentation\/gtuikit\/gtthemeimagepicker"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"gt_setBackgroundImage:forState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setBackgroundImage:forState:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"gt_setBackgroundImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ThemeImagePicker","preciseIdentifier":"c:objc(cs)ThemeImagePicker"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":" "},{"kind":"identifier","text":"forState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIControlState","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/title","value":"GTUIButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/fragments","value":[{"kind":"identifier","text":"GTUIButtonV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setBackgroundImage(_:forState:)\/title","value":"gt_setBackgroundImage:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setBackgroundImage(_:forState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setBackgroundImage:forState:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}