{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSuffixAttributedIcon"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuibuttonv3\/setsuffixattributedicon(_:for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuibuttonv3\/setsuffixattributedicon(_:for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixAttributedIcon(_:for:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSuffixAttributedIcon"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"title":"setSuffixAttributedIcon(_:for:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTUIButtonV3(im)setSuffixAttributedIcon:for:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"setSuffixAttributedIcon:for:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setSuffixAttributedIcon(_:for:)":{"role":"symbol","title":"setSuffixAttributedIcon(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSuffixAttributedIcon"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixAttributedIcon(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSuffixAttributedIcon:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setsuffixattributedicon(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3":{"role":"symbol","title":"GTUIButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIButtonV3"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setSuffixAttributedIcon:for:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSuffixAttributedIcon:for:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setSuffixAttributedIcon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"icon"},{"kind":"text","text":" "},{"kind":"identifier","text":"for:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIControlState","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setSuffixAttributedIcon(_:for:)\/title","value":"setSuffixAttributedIcon:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setSuffixAttributedIcon(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSuffixAttributedIcon:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/title","value":"GTUIButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/fragments","value":[{"kind":"identifier","text":"GTUIButtonV3"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}