{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" the "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" will behave and look like a normal "},{"type":"codeVoice","code":"UILabel"},{"type":"text","text":", and  will not begin any scrolling animations."},{"type":"text","text":" "},{"type":"text","text":"Changes to this property take effect immediately, removing any in-flight animation as well as any edge fade. Note that "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" "},{"type":"text","text":"will respect the current values of the "},{"type":"codeVoice","code":"lineBreakMode"},{"type":"text","text":" and "},{"type":"codeVoice","code":"textAlignment"},{"type":"text","text":"properties while labelized."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To simply prevent automatic scrolling, use the "},{"type":"codeVoice","code":"holdScrolling"},{"type":"text","text":" property."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The label will not automatically scroll when this property is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}],"type":"aside","name":"Note"},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The UILabel default setting for the "},{"type":"codeVoice","code":"lineBreakMode"},{"type":"text","text":" property is "},{"type":"codeVoice","code":"NSLineBreakByTruncatingTail"},{"type":"text","text":", which truncates"},{"type":"text","text":" "},{"type":"text","text":"the text adds an ellipsis glyph (…). Set the "},{"type":"codeVoice","code":"lineBreakMode"},{"type":"text","text":" property to "},{"type":"codeVoice","code":"NSLineBreakByClipping"},{"type":"text","text":" in order to avoid the"},{"type":"text","text":" "},{"type":"text","text":"ellipsis, especially if using an edge transparency fade."}]}],"type":"aside","name":"Warning"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/marqueelabel\/labelize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/marqueelabel\/labelize"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelize","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A boolean property that sets whether the "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" should behave like a normal "},{"type":"codeVoice","code":"UILabel"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"labelize","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@GTUIKit@objc(cs)MarqueeLabel(py)labelize","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"labelize"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/labelize":{"role":"symbol","title":"labelize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A boolean property that sets whether the "},{"type":"codeVoice","code":"MarqueeLabel"},{"type":"text","text":" should behave like a normal "},{"type":"codeVoice","code":"UILabel"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/labelize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"labelize"}],"url":"\/documentation\/gtuikit\/marqueelabel\/labelize"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel":{"role":"symbol","title":"MarqueeLabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarqueeLabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarqueeLabel"}],"url":"\/documentation\/gtuikit\/marqueelabel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"labelize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"labelize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelize"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1labelize\/title","value":"labelize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1labelize\/fragments","value":[{"kind":"identifier","text":"labelize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel\/title","value":"MarqueeLabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel\/fragments","value":[{"kind":"identifier","text":"MarqueeLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}