{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leadingBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property adds additional space between the leading edge of the label text and the label frame. The"},{"type":"text","text":" "},{"type":"text","text":"leading edge is the edge of the label text facing the direction of scroll (i.e. the edge that animates"},{"type":"text","text":" "},{"type":"text","text":"offscreen first during scrolling)."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"0"},{"type":"text","text":"."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The value set to this property affects label positioning at all times (including when "},{"type":"codeVoice","code":"labelize"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"),"},{"type":"text","text":" "},{"type":"text","text":"including when the text string length is short enough that the label does not need to scroll."}]}],"type":"aside","name":"Note"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For Continuous-type labels, the smallest value of "},{"type":"codeVoice","code":"leadingBuffer"},{"type":"text","text":", "},{"type":"codeVoice","code":"trailingBuffer"},{"type":"text","text":", and "},{"type":"codeVoice","code":"fadeLength"},{"type":"text","text":" "},{"type":"text","text":"is used as spacing between the two label instances. Zero is an allowable value for all three properties."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/marqueelabel\/leadingbuffer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/marqueelabel\/leadingbuffer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/leadingBuffer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A buffer (offset) between the leading edge of the label text and the label frame."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leadingBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"leadingBuffer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@GTUIKit@objc(cs)MarqueeLabel(py)leadingBuffer","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"leadingBuffer"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel/leadingBuffer":{"role":"symbol","title":"leadingBuffer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leadingBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"A buffer (offset) between the leading edge of the label text and the label frame."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel\/leadingBuffer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leadingBuffer"}],"url":"\/documentation\/gtuikit\/marqueelabel\/leadingbuffer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/MarqueeLabel":{"role":"symbol","title":"MarqueeLabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarqueeLabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/MarqueeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MarqueeLabel"}],"url":"\/documentation\/gtuikit\/marqueelabel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"leadingBuffer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"leadingBuffer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"leadingBuffer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1leadingBuffer\/title","value":"leadingBuffer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel~1leadingBuffer\/fragments","value":[{"kind":"identifier","text":"leadingBuffer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel\/title","value":"MarqueeLabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1MarqueeLabel\/fragments","value":[{"kind":"identifier","text":"MarqueeLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}