{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"helper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextField","text":"GTTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField\/InputState-swift.enum","preciseIdentifier":"s:7GTUIKit11GTTextFieldC10InputStateO","text":"InputState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttextfieldalertview\/update(helper:state:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldAlertView\/update(helper:state:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"helper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextField","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"InputState","preciseIdentifier":"s:7GTUIKit11GTTextFieldC10InputStateO"},{"kind":"text","text":")"}],"title":"update(helper:state:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7GTUIKit20GTTextFieldAlertViewC6update6helper5stateySSSg_AA0bC0C10InputStateOtF","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldAlertView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextField":{"role":"symbol","title":"GTTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextField"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextField"}],"url":"\/documentation\/gtuikit\/gttextfield"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextField/InputState-swift.enum":{"role":"symbol","title":"GTTextField.InputState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputState"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField\/InputState-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputState"}],"url":"\/documentation\/gtuikit\/gttextfield\/inputstate-swift.enum"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldAlertView/update(helper:state:)":{"role":"symbol","title":"update(helper:state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"helper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextField","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"InputState","preciseIdentifier":"s:7GTUIKit11GTTextFieldC10InputStateO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldAlertView\/update(helper:state:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gttextfieldalertview\/update(helper:state:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldAlertView":{"role":"symbol","title":"GTTextFieldAlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextFieldAlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldAlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextFieldAlertView"}],"url":"\/documentation\/gtuikit\/gttextfieldalertview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextField\/title","value":"GTTextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextField\/fragments","value":[{"kind":"identifier","text":"GTTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldAlertView\/title","value":"GTTextFieldAlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldAlertView\/fragments","value":[{"kind":"identifier","text":"GTTextFieldAlertView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}