{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertTag"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTagView","text":"GTTagView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttaglistview\/inserttag(_:at:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTagListView\/insertTag(_:at:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertTag"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTTagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTagView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"insertTag(_:at:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:7GTUIKit13GTTagListViewC9insertTag_2atyAA0bD0C_SitF","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTagListView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTagView":{"role":"symbol","title":"GTTagView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTagView"}],"abstract":[{"type":"text","text":"Tag标签：用于信息的选择、筛选、分类。用户通过标签进行信息反馈和交互操作。"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTagView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTagView"}],"url":"\/documentation\/gtuikit\/gttagview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTagListView":{"role":"symbol","title":"GTTagListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTagListView"}],"abstract":[{"type":"text","text":"Tag标签列表"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTagListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTagListView"}],"url":"\/documentation\/gtuikit\/gttaglistview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTagListView/insertTag(_:at:)":{"role":"symbol","title":"insertTag(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertTag"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTTagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTagView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTagListView\/insertTag(_:at:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gttaglistview\/inserttag(_:at:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTagView\/title","value":"GTTagView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTagView\/fragments","value":[{"kind":"identifier","text":"GTTagView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTagListView\/title","value":"GTTagListView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTagListView\/fragments","value":[{"kind":"identifier","text":"GTTagListView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}