{"variants":[{"paths":["\/documentation\/gtuikit\/gtnoticebar\/fspagerviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtnoticebar\/fspagerviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/FSPagerViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/pagerView(_:didSelectItemAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"FSPagerViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar":{"role":"symbol","title":"GTNoticeBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNoticeBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNoticeBar"}],"url":"\/documentation\/gtuikit\/gtnoticebar"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar/pagerView(_:didSelectItemAt:)":{"role":"symbol","title":"pagerView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/pagerView(_:didSelectItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pagerView:didSelectItemAtIndex:"}],"url":"\/documentation\/gtuikit\/gtnoticebar\/pagerview(_:didselectitemat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/pagerView(_:didSelectItemAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar\/title","value":"GTNoticeBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar\/fragments","value":[{"kind":"identifier","text":"GTNoticeBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar~1pagerView(_:didSelectItemAt:)\/title","value":"pagerView:didSelectItemAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar~1pagerView(_:didSelectItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pagerView:didSelectItemAtIndex:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}