{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pagerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FSPagerViewCell","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerViewCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtnoticebar\/pagerview(_:cellforitemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtnoticebar\/pagerview(_:cellforitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/pagerView(_:cellForItemAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"FSPagerViewDataSource.pagerView(_:cellForItemAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"pagerView:cellForItemAtIndex:"}],"role":"symbol","title":"pagerView(_:cellForItemAt:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FSPagerViewCell","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerViewCell"}],"symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTNoticeBar(im)pagerView:cellForItemAtIndex:","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/FSPagerViewDataSource-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar":{"role":"symbol","title":"GTNoticeBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNoticeBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNoticeBar"}],"url":"\/documentation\/gtuikit\/gtnoticebar"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar/FSPagerViewDataSource-Implementations":{"role":"collectionGroup","title":"FSPagerViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/FSPagerViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtnoticebar\/fspagerviewdatasource-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar/pagerView(_:cellForItemAt:)":{"role":"symbol","title":"pagerView(_:cellForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FSPagerViewCell","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerViewCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/pagerView(_:cellForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pagerView:cellForItemAtIndex:"}],"url":"\/documentation\/gtuikit\/gtnoticebar\/pagerview(_:cellforitemat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pagerView:cellForItemAtIndex:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pagerView:cellForItemAtIndex:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"FSPagerViewCell","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerViewCell"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"pagerView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pagerView"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellForItemAtIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar\/title","value":"GTNoticeBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar\/fragments","value":[{"kind":"identifier","text":"GTNoticeBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar~1pagerView(_:cellForItemAt:)\/title","value":"pagerView:cellForItemAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar~1pagerView(_:cellForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pagerView:cellForItemAtIndex:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}