{"variants":[{"paths":["\/documentation\/gtuikit\/gtsearchbarview\/uitextfielddelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtsearchbarview\/uitextfielddelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/UITextFieldDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textField(_:shouldChangeCharactersIn:replacementString:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldDidBeginEditing(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldDidEndEditing(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldBeginEditing(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldClear(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldEndEditing(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldReturn(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"UITextFieldDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView/textFieldShouldEndEditing(_:)":{"role":"symbol","title":"textFieldShouldEndEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldEndEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldEndEditing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldShouldEndEditing:"}],"url":"\/documentation\/gtuikit\/gtsearchbarview\/textfieldshouldendediting(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView/textFieldShouldReturn(_:)":{"role":"symbol","title":"textFieldShouldReturn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldReturn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldReturn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldShouldReturn:"}],"url":"\/documentation\/gtuikit\/gtsearchbarview\/textfieldshouldreturn(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView/textFieldDidEndEditing(_:)":{"role":"symbol","title":"textFieldDidEndEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDidEndEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldDidEndEditing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldDidEndEditing:"}],"url":"\/documentation\/gtuikit\/gtsearchbarview\/textfielddidendediting(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView/textFieldShouldClear(_:)":{"role":"symbol","title":"textFieldShouldClear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldClear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldClear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldShouldClear:"}],"url":"\/documentation\/gtuikit\/gtsearchbarview\/textfieldshouldclear(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView/textField(_:shouldChangeCharactersIn:replacementString:)":{"role":"symbol","title":"textField(_:shouldChangeCharactersIn:replacementString:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textField(_:shouldChangeCharactersIn:replacementString:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}],"url":"\/documentation\/gtuikit\/gtsearchbarview\/textfield(_:shouldchangecharactersin:replacementstring:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView/textFieldDidBeginEditing(_:)":{"role":"symbol","title":"textFieldDidBeginEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDidBeginEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldDidBeginEditing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldDidBeginEditing:"}],"url":"\/documentation\/gtuikit\/gtsearchbarview\/textfielddidbeginediting(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView/textFieldShouldBeginEditing(_:)":{"role":"symbol","title":"textFieldShouldBeginEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldBeginEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldBeginEditing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldShouldBeginEditing:"}],"url":"\/documentation\/gtuikit\/gtsearchbarview\/textfieldshouldbeginediting(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView":{"role":"symbol","title":"GTSearchBarView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSearchBarView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSearchBarView"}],"url":"\/documentation\/gtuikit\/gtsearchbarview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textField(_:shouldChangeCharactersIn:replacementString:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldDidBeginEditing(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldDidEndEditing(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldBeginEditing(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldClear(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldEndEditing(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textFieldShouldReturn(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldShouldEndEditing(_:)\/title","value":"textFieldShouldEndEditing:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldShouldEndEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldShouldEndEditing:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldShouldReturn(_:)\/title","value":"textFieldShouldReturn:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldShouldReturn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldShouldReturn:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldDidEndEditing(_:)\/title","value":"textFieldDidEndEditing:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldDidEndEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldDidEndEditing:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldShouldClear(_:)\/title","value":"textFieldShouldClear:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldShouldClear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldShouldClear:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textField(_:shouldChangeCharactersIn:replacementString:)\/title","value":"textField:shouldChangeCharactersInRange:replacementString:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textField(_:shouldChangeCharactersIn:replacementString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldDidBeginEditing(_:)\/title","value":"textFieldDidBeginEditing:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldDidBeginEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldDidBeginEditing:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldShouldBeginEditing(_:)\/title","value":"textFieldShouldBeginEditing:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textFieldShouldBeginEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldShouldBeginEditing:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView\/title","value":"GTSearchBarView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView\/fragments","value":[{"kind":"identifier","text":"GTSearchBarView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}