{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"moveItemAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sourceIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"destinationIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:moveitemat:to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:moveitemat:to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:moveItemAt:to:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDataSource.collectionView(_:moveItemAt:to:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"moveItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"title":"collectionView(_:moveItemAt:to:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTUICollectionViewBaseAdaptor(im)collectionView:moveItemAtIndexPath:toIndexPath:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:moveItemAtIndexPath:toIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/UICollectionViewDataSource-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/UICollectionViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/uicollectionviewdatasource-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor":{"role":"symbol","title":"GTUICollectionViewBaseAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/collectionView(_:moveItemAt:to:)":{"role":"symbol","title":"collectionView(_:moveItemAt:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"moveItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:moveItemAt:to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:moveItemAtIndexPath:toIndexPath:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:moveitemat:to:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"collectionView:moveItemAtIndexPath:toIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:moveItemAtIndexPath:toIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveItemAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sourceIndexPath"},{"kind":"text","text":" "},{"kind":"identifier","text":"toIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"destinationIndexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor\/title","value":"GTUICollectionViewBaseAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:moveItemAt:to:)\/title","value":"collectionView:moveItemAtIndexPath:toIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:moveItemAt:to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:moveItemAtIndexPath:toIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}