{"variants":[{"paths":["\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/UICollectionViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:didEndDisplaying:forItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:didEndDisplayingSupplementaryView:forElementOfKind:at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:didSelectItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:willDisplay:forItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:willDisplaySupplementaryView:forElementKind:at:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"UICollectionViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor":{"role":"symbol","title":"GTUICollectionViewBaseAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/collectionView(_:willDisplay:forItemAt:)":{"role":"symbol","title":"collectionView(_:willDisplay:forItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:willDisplay:forItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:willDisplayCell:forItemAtIndexPath:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:willdisplay:foritemat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/collectionView(_:willDisplaySupplementaryView:forElementKind:at:)":{"role":"symbol","title":"collectionView(_:willDisplaySupplementaryView:forElementKind:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplaySupplementaryView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionReusableView","preciseIdentifier":"c:objc(cs)UICollectionReusableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forElementKind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:willDisplaySupplementaryView:forElementKind:at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:willDisplaySupplementaryView:forElementKind:atIndexPath:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:willdisplaysupplementaryview:forelementkind:at:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/collectionView(_:didEndDisplayingSupplementaryView:forElementOfKind:at:)":{"role":"symbol","title":"collectionView(_:didEndDisplayingSupplementaryView:forElementOfKind:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndDisplayingSupplementaryView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionReusableView","preciseIdentifier":"c:objc(cs)UICollectionReusableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forElementOfKind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:didEndDisplayingSupplementaryView:forElementOfKind:at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:didEndDisplayingSupplementaryView:forElementOfKind:atIndexPath:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:didenddisplayingsupplementaryview:forelementofkind:at:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/collectionView(_:didSelectItemAt:)":{"role":"symbol","title":"collectionView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:didSelectItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:didselectitemat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/collectionView(_:didEndDisplaying:forItemAt:)":{"role":"symbol","title":"collectionView(_:didEndDisplaying:forItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndDisplaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:didEndDisplaying:forItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:didenddisplaying:foritemat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:didEndDisplaying:forItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:didEndDisplayingSupplementaryView:forElementOfKind:at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:didSelectItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:willDisplay:forItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:willDisplaySupplementaryView:forElementKind:at:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor\/title","value":"GTUICollectionViewBaseAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:willDisplay:forItemAt:)\/title","value":"collectionView:willDisplayCell:forItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:willDisplay:forItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:willDisplayCell:forItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:willDisplaySupplementaryView:forElementKind:at:)\/title","value":"collectionView:willDisplaySupplementaryView:forElementKind:atIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:willDisplaySupplementaryView:forElementKind:at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:willDisplaySupplementaryView:forElementKind:atIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:didEndDisplayingSupplementaryView:forElementOfKind:at:)\/title","value":"collectionView:didEndDisplayingSupplementaryView:forElementOfKind:atIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:didEndDisplayingSupplementaryView:forElementOfKind:at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didEndDisplayingSupplementaryView:forElementOfKind:atIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:didSelectItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:didEndDisplaying:forItemAt:)\/title","value":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:didEndDisplaying:forItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}