{"variants":[{"paths":["\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/UIScrollViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndDragging(_:willDecelerate:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndScrollingAnimation(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndZooming(_:with:atScale:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidScroll(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidZoom(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewShouldScrollToTop(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillBeginDecelerating(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillBeginDragging(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillBeginZooming(_:with:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/viewForZooming(in:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"UIScrollViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewDidZoom(_:)":{"role":"symbol","title":"scrollViewDidZoom(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidZoom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidZoom(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidZoom:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewdidzoom(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/viewForZooming(in:)":{"role":"symbol","title":"viewForZooming(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForZooming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/viewForZooming(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewForZoomingInScrollView:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/viewforzooming(in:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewWillBeginZooming(_:with:)":{"role":"symbol","title":"scrollViewWillBeginZooming(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginZooming"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillBeginZooming(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginZooming:withView:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewwillbeginzooming(_:with:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewWillBeginDecelerating(_:)":{"role":"symbol","title":"scrollViewWillBeginDecelerating(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDecelerating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillBeginDecelerating(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDecelerating:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewwillbegindecelerating(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewDidEndZooming(_:with:atScale:)":{"role":"symbol","title":"scrollViewDidEndZooming(_:with:atScale:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndZooming"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"atScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndZooming(_:with:atScale:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndZooming:withView:atScale:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewdidendzooming(_:with:atscale:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewDidEndScrollingAnimation(_:)":{"role":"symbol","title":"scrollViewDidEndScrollingAnimation(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndScrollingAnimation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndScrollingAnimation(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndScrollingAnimation:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewdidendscrollinganimation(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewDidEndDragging(_:willDecelerate:)":{"role":"symbol","title":"scrollViewDidEndDragging(_:willDecelerate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDecelerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndDragging(_:willDecelerate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewdidenddragging(_:willdecelerate:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewWillBeginDragging(_:)":{"role":"symbol","title":"scrollViewWillBeginDragging(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillBeginDragging(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDragging:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewwillbegindragging(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewDidEndDecelerating(_:)":{"role":"symbol","title":"scrollViewDidEndDecelerating(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDecelerating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndDecelerating(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewdidenddecelerating(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewShouldScrollToTop(_:)":{"role":"symbol","title":"scrollViewShouldScrollToTop(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewShouldScrollToTop"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewShouldScrollToTop(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewShouldScrollToTop:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewshouldscrolltotop(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor":{"role":"symbol","title":"GTUICollectionViewBaseAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)":{"role":"symbol","title":"scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillEndDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withVelocity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetContentOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewwillenddragging(_:withvelocity:targetcontentoffset:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/scrollViewDidScroll(_:)":{"role":"symbol","title":"scrollViewDidScroll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidScroll(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/scrollviewdidscroll(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndDragging(_:willDecelerate:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndScrollingAnimation(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidEndZooming(_:with:atScale:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidScroll(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewDidZoom(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewShouldScrollToTop(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillBeginDecelerating(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillBeginDragging(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillBeginZooming(_:with:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/viewForZooming(in:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidZoom(_:)\/title","value":"scrollViewDidZoom:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidZoom(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidZoom:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1viewForZooming(in:)\/title","value":"viewForZoomingInScrollView:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1viewForZooming(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewForZoomingInScrollView:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewWillBeginZooming(_:with:)\/title","value":"scrollViewWillBeginZooming:withView:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewWillBeginZooming(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginZooming:withView:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewWillBeginDecelerating(_:)\/title","value":"scrollViewWillBeginDecelerating:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewWillBeginDecelerating(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDecelerating:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidEndZooming(_:with:atScale:)\/title","value":"scrollViewDidEndZooming:withView:atScale:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidEndZooming(_:with:atScale:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndZooming:withView:atScale:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidEndScrollingAnimation(_:)\/title","value":"scrollViewDidEndScrollingAnimation:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidEndScrollingAnimation(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndScrollingAnimation:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidEndDragging(_:willDecelerate:)\/title","value":"scrollViewDidEndDragging:willDecelerate:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidEndDragging(_:willDecelerate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewWillBeginDragging(_:)\/title","value":"scrollViewWillBeginDragging:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewWillBeginDragging(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidEndDecelerating(_:)\/title","value":"scrollViewDidEndDecelerating:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidEndDecelerating(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewShouldScrollToTop(_:)\/title","value":"scrollViewShouldScrollToTop:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewShouldScrollToTop(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewShouldScrollToTop:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor\/title","value":"GTUICollectionViewBaseAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)\/title","value":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidScroll(_:)\/title","value":"scrollViewDidScroll:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1scrollViewDidScroll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}