{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customLayoutAtTarget"},{"kind":"text","text":"("},{"kind":"externalParam","text":"popView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPopView","text":"GTPopView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtdropdownmenuview\/customlayoutattarget(popview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtdropdownmenuview\/customlayoutattarget(popview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView\/customLayoutAtTarget(popView:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GTPopViewProtocol.customLayoutAtTarget(popView:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customLayoutAtTarget"},{"kind":"text","text":"("},{"kind":"externalParam","text":"popView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPopView"},{"kind":"text","text":")"}],"title":"customLayoutAtTarget(popView:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)GTDropdownMenuView(im)customLayoutAtTargetWithPopView:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"customLayoutAtTargetWithPopView:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopView":{"role":"symbol","title":"GTPopView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopView"}],"url":"\/documentation\/gtuikit\/gtpopview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownMenuView/customLayoutAtTarget(popView:)":{"role":"symbol","title":"customLayoutAtTarget(popView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customLayoutAtTarget"},{"kind":"text","text":"("},{"kind":"externalParam","text":"popView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPopView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView\/customLayoutAtTarget(popView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customLayoutAtTargetWithPopView:"}],"url":"\/documentation\/gtuikit\/gtdropdownmenuview\/customlayoutattarget(popview:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownMenuView":{"role":"symbol","title":"GTDropdownMenuView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDropdownMenuView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTDropdownMenuView"}],"url":"\/documentation\/gtuikit\/gtdropdownmenuview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"customLayoutAtTargetWithPopView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customLayoutAtTargetWithPopView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"customLayoutAtTargetWithPopView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPopView","text":"GTPopView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"popView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopView\/title","value":"GTPopView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopView\/fragments","value":[{"kind":"identifier","text":"GTPopView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownMenuView~1customLayoutAtTarget(popView:)\/title","value":"customLayoutAtTargetWithPopView:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownMenuView~1customLayoutAtTarget(popView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customLayoutAtTargetWithPopView:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownMenuView\/title","value":"GTDropdownMenuView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownMenuView\/fragments","value":[{"kind":"identifier","text":"GTDropdownMenuView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}