{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTDropdownView","text":"GTDropdownView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/Style-swift.enum","preciseIdentifier":"s:7GTUIKit14GTDropdownViewC5StyleO","text":"Style"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownItem","preciseIdentifier":"s:7GTUIKit14GTDropdownItemV","text":"GTDropdownItem"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtdropdownmenuview\/init(style:items:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView\/init(style:items:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTDropdownView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTDropdownView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:7GTUIKit14GTDropdownViewC5StyleO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTDropdownItem","preciseIdentifier":"s:7GTUIKit14GTDropdownItemV"},{"kind":"text","text":"])"}],"title":"init(style:items:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:7GTUIKit18GTDropdownMenuViewC5style5itemsAcA0bD0C5StyleO_SayAA0B4ItemVGtcfc","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownMenuView/init(style:items:)":{"role":"symbol","title":"init(style:items:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTDropdownView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTDropdownView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:7GTUIKit14GTDropdownViewC5StyleO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTDropdownItem","preciseIdentifier":"s:7GTUIKit14GTDropdownItemV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView\/init(style:items:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtdropdownmenuview\/init(style:items:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView":{"role":"symbol","title":"GTDropdownView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDropdownView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTDropdownView"}],"url":"\/documentation\/gtuikit\/gtdropdownview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView/Style-swift.enum":{"role":"symbol","title":"GTDropdownView.Style","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/Style-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/gtuikit\/gtdropdownview\/style-swift.enum"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownMenuView":{"role":"symbol","title":"GTDropdownMenuView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDropdownMenuView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTDropdownMenuView"}],"url":"\/documentation\/gtuikit\/gtdropdownmenuview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownItem":{"role":"symbol","title":"GTDropdownItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDropdownItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTDropdownItem"}],"url":"\/documentation\/gtuikit\/gtdropdownitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownView\/title","value":"GTDropdownView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownView\/fragments","value":[{"kind":"identifier","text":"GTDropdownView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownMenuView\/title","value":"GTDropdownMenuView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownMenuView\/fragments","value":[{"kind":"identifier","text":"GTDropdownMenuView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}