{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTDropdownView","text":"GTDropdownView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/Style-swift.enum","preciseIdentifier":"s:7GTUIKit14GTDropdownViewC5StyleO","text":"Style"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtdropdownmenuview\/style"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView\/style","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTDropdownView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTDropdownView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:7GTUIKit14GTDropdownViewC5StyleO"}],"title":"style","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit18GTDropdownMenuViewC5styleAA0bD0C5StyleOvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownMenuView/style":{"role":"symbol","title":"style","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTDropdownView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTDropdownView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:7GTUIKit14GTDropdownViewC5StyleO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView\/style","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtdropdownmenuview\/style"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView":{"role":"symbol","title":"GTDropdownView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDropdownView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTDropdownView"}],"url":"\/documentation\/gtuikit\/gtdropdownview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView/Style-swift.enum":{"role":"symbol","title":"GTDropdownView.Style","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/Style-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/gtuikit\/gtdropdownview\/style-swift.enum"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownMenuView":{"role":"symbol","title":"GTDropdownMenuView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDropdownMenuView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownMenuView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTDropdownMenuView"}],"url":"\/documentation\/gtuikit\/gtdropdownmenuview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownView\/title","value":"GTDropdownView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownView\/fragments","value":[{"kind":"identifier","text":"GTDropdownView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownMenuView\/title","value":"GTDropdownMenuView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownMenuView\/fragments","value":[{"kind":"identifier","text":"GTDropdownMenuView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}