{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutAttributesForElements"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayout\/layoutattributesforelements(in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuifalllayout\/layoutattributesforelements(in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayout\/layoutAttributesForElements(in:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutAttributesForElements"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"]?"}],"title":"layoutAttributesForElements(in:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)GTUIFallLayout(im)layoutAttributesForElementsInRect:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"layoutAttributesForElementsInRect:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayout"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayout":{"role":"symbol","title":"GTUIFallLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayout"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayout"}],"url":"\/documentation\/gtuikit\/gtuifalllayout"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayout/layoutAttributesForElements(in:)":{"role":"symbol","title":"layoutAttributesForElements(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutAttributesForElements"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayout\/layoutAttributesForElements(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutAttributesForElementsInRect:"}],"url":"\/documentation\/gtuikit\/gtuifalllayout\/layoutattributesforelements(in:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"layoutAttributesForElementsInRect:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutAttributesForElementsInRect:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<UICollectionViewLayoutAttributes *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"layoutAttributesForElementsInRect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayout\/title","value":"GTUIFallLayout"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayout\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayout~1layoutAttributesForElements(in:)\/title","value":"layoutAttributesForElementsInRect:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayout~1layoutAttributesForElements(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutAttributesForElementsInRect:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}