{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/Alignment-swift.enum","preciseIdentifier":"s:7GTUIKit11TagListViewC9AlignmentO","text":"Alignment"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/taglistview\/alignment-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/taglistview\/alignment-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/alignment-swift.property","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Alignment","preciseIdentifier":"s:7GTUIKit11TagListViewC9AlignmentO"}],"title":"alignment","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@GTUIKit@objc(cs)TagListView(py)alignment","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"alignment"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView":{"role":"symbol","title":"TagListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListView"}],"url":"\/documentation\/gtuikit\/taglistview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/Alignment-swift.enum":{"role":"symbol","title":"TagListView.Alignment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Alignment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/Alignment-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Alignment"}],"url":"\/documentation\/gtuikit\/taglistview\/alignment-swift.enum"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/alignment-swift.property":{"role":"symbol","title":"alignment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Alignment","preciseIdentifier":"s:7GTUIKit11TagListViewC9AlignmentO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/alignment-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"alignment"}],"url":"\/documentation\/gtuikit\/taglistview\/alignment-swift.property"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/Alignment":{"role":"symbol","title":"Alignment","fragments":[{"kind":"identifier","text":"Alignment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/Alignment","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/alignment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"alignment"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"alignment"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/Alignment","preciseIdentifier":"c:@M@GTUIKit@E@Alignment","text":"Alignment"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView\/title","value":"TagListView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView\/fragments","value":[{"kind":"identifier","text":"TagListView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1alignment-swift.property\/title","value":"alignment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1alignment-swift.property\/fragments","value":[{"kind":"identifier","text":"alignment"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}