{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextView","text":"GTTextView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextView\/InputState-swift.enum","preciseIdentifier":"s:7GTUIKit10GTTextViewC10InputStateO","text":"InputState"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttexthelperview\/inputstate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextHelperView\/inputState","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"InputState","preciseIdentifier":"s:7GTUIKit10GTTextViewC10InputStateO"}],"title":"inputState","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit16GTTextHelperViewC10inputStateAA0bD0C05InputF0Ovp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextHelperView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextHelperView":{"role":"symbol","title":"GTTextHelperView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextHelperView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextHelperView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextHelperView"}],"url":"\/documentation\/gtuikit\/gttexthelperview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextHelperView/inputState":{"role":"symbol","title":"inputState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"InputState","preciseIdentifier":"s:7GTUIKit10GTTextViewC10InputStateO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextHelperView\/inputState","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gttexthelperview\/inputstate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextView":{"role":"symbol","title":"GTTextView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextView"}],"url":"\/documentation\/gtuikit\/gttextview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextView/InputState-swift.enum":{"role":"symbol","title":"GTTextView.InputState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputState"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextView\/InputState-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputState"}],"url":"\/documentation\/gtuikit\/gttextview\/inputstate-swift.enum"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextHelperView\/title","value":"GTTextHelperView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextHelperView\/fragments","value":[{"kind":"identifier","text":"GTTextHelperView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextView\/title","value":"GTTextView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextView\/fragments","value":[{"kind":"identifier","text":"GTTextView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}