{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel","text":"GTUILabel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttipsview\/iconlabel"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTipsView\/iconLabel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel"}],"title":"iconLabel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit10GTTipsViewC9iconLabelAA9GTUILabelCvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTipsView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILabel":{"role":"symbol","title":"GTUILabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILabel"}],"url":"\/documentation\/gtuikit\/gtuilabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTipsView":{"role":"symbol","title":"GTTipsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTipsView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTipsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTipsView"}],"url":"\/documentation\/gtuikit\/gttipsview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTipsView/iconLabel":{"role":"symbol","title":"iconLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTipsView\/iconLabel","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gttipsview\/iconlabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILabel\/title","value":"GTUILabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILabel\/fragments","value":[{"kind":"identifier","text":"GTUILabel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTipsView\/title","value":"GTTipsView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTipsView\/fragments","value":[{"kind":"identifier","text":"GTTipsView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}