{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASButtonNode","preciseIdentifier":"c:objc(cs)ASButtonNode"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtalertinputitem\/itemevent(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtalertinputitem\/itemevent(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertInputItem\/itemEvent(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASButtonNode","preciseIdentifier":"c:objc(cs)ASButtonNode"},{"kind":"text","text":")"}],"title":"itemEvent(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)GTAlertInputItem(im)itemEvent:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"itemEvent:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertInputItem"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertInputItem/itemEvent(_:)":{"role":"symbol","title":"itemEvent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASButtonNode","preciseIdentifier":"c:objc(cs)ASButtonNode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertInputItem\/itemEvent(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"itemEvent:"}],"url":"\/documentation\/gtuikit\/gtalertinputitem\/itemevent(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertInputItem":{"role":"symbol","title":"GTAlertInputItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertInputItem"}],"abstract":[{"type":"text","text":"Input Item Alert"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertInputItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertInputItem"}],"url":"\/documentation\/gtuikit\/gtalertinputitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"itemEvent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"itemEvent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"itemEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASButtonNode","preciseIdentifier":"c:objc(cs)ASButtonNode"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertInputItem~1itemEvent(_:)\/title","value":"itemEvent:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertInputItem~1itemEvent(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"itemEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertInputItem\/title","value":"GTAlertInputItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertInputItem\/fragments","value":[{"kind":"identifier","text":"GTAlertInputItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}