{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_placeholderTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThemeColorPicker","preciseIdentifier":"s:7GTUIKit18GTThemeColorPickera","text":"GTThemeColorPicker"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuitextview\/gt_placeholdertextcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuitextview\/gt_placeholdertextcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView\/gt_placeholderTextColor","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"gt_placeholderTextColor"}],"role":"symbol","title":"gt_placeholderTextColor","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_placeholderTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTThemeColorPicker","preciseIdentifier":"s:7GTUIKit18GTThemeColorPickera"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@CM@GTUIKit@objc(cs)GTUITextView(py)gt_placeholderTextColor","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITextView/gt_placeholderTextColor":{"role":"symbol","title":"gt_placeholderTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_placeholderTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTThemeColorPicker","preciseIdentifier":"s:7GTUIKit18GTThemeColorPickera"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView\/gt_placeholderTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_placeholderTextColor"}],"url":"\/documentation\/gtuikit\/gtuitextview\/gt_placeholdertextcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTThemeColorPicker":{"role":"symbol","title":"GTThemeColorPicker","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTThemeColorPicker"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThemeColorPicker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTThemeColorPicker"}],"url":"\/documentation\/gtuikit\/gtthemecolorpicker"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITextView":{"role":"symbol","title":"GTUITextView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITextView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITextView"}],"url":"\/documentation\/gtuikit\/gtuitextview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"gt_placeholderTextColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"gt_placeholderTextColor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ThemeColorPicker","preciseIdentifier":"c:objc(cs)ThemeColorPicker"},{"kind":"text","text":" * "},{"kind":"identifier","text":"gt_placeholderTextColor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView~1gt_placeholderTextColor\/title","value":"gt_placeholderTextColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView~1gt_placeholderTextColor\/fragments","value":[{"kind":"identifier","text":"gt_placeholderTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView\/title","value":"GTUITextView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView\/fragments","value":[{"kind":"identifier","text":"GTUITextView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}