{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitch","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTSwitch","text":"GTSwitch"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttitleswitchcell\/switchbutton"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSwitchCell\/switchButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTSwitch","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTSwitch"}],"title":"switchButton","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit17GTTitleSwitchCellC12switchButtonAA8GTSwitchCvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSwitchCell"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleSwitchCell":{"role":"symbol","title":"GTTitleSwitchCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTitleSwitchCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSwitchCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTitleSwitchCell"}],"url":"\/documentation\/gtuikit\/gttitleswitchcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleSwitchCell/switchButton":{"role":"symbol","title":"switchButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTSwitch","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTSwitch"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSwitchCell\/switchButton","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gttitleswitchcell\/switchbutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSwitch":{"role":"symbol","title":"GTSwitch","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSwitch"}],"abstract":[{"type":"text","text":"自定义Switch 通过枚举设置size，不需要外部再设置大小，"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSwitch"}],"url":"\/documentation\/gtuikit\/gtswitch"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleSwitchCell\/title","value":"GTTitleSwitchCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleSwitchCell\/fragments","value":[{"kind":"identifier","text":"GTTitleSwitchCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitch\/title","value":"GTSwitch"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitch\/fragments","value":[{"kind":"identifier","text":"GTSwitch"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}