{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalLayoutAttributesForDisappearingSupplementaryElement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofKind"},{"kind":"text","text":" "},{"kind":"internalParam","text":"elementKind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"kind":"internalParam","text":"elementIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayout\/finallayoutattributesfordisappearingsupplementaryelement(ofkind:at:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuifalllayout\/finallayoutattributesfordisappearingsupplementaryelement(ofkind:at:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayout\/finalLayoutAttributesForDisappearingSupplementaryElement(ofKind:at:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalLayoutAttributesForDisappearingSupplementaryElement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofKind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"?"}],"title":"finalLayoutAttributesForDisappearingSupplementaryElement(ofKind:at:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)GTUIFallLayout(im)finalLayoutAttributesForDisappearingSupplementaryElementOfKind:atIndexPath:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"finalLayoutAttributesForDisappearingSupplementaryElementOfKind:atIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayout"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayout/finalLayoutAttributesForDisappearingSupplementaryElement(ofKind:at:)":{"role":"symbol","title":"finalLayoutAttributesForDisappearingSupplementaryElement(ofKind:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalLayoutAttributesForDisappearingSupplementaryElement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofKind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayout\/finalLayoutAttributesForDisappearingSupplementaryElement(ofKind:at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finalLayoutAttributesForDisappearingSupplementaryElementOfKind:atIndexPath:"}],"url":"\/documentation\/gtuikit\/gtuifalllayout\/finallayoutattributesfordisappearingsupplementaryelement(ofkind:at:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayout":{"role":"symbol","title":"GTUIFallLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayout"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayout"}],"url":"\/documentation\/gtuikit\/gtuifalllayout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"finalLayoutAttributesForDisappearingSupplementaryElementOfKind:atIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finalLayoutAttributesForDisappearingSupplementaryElementOfKind:atIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"finalLayoutAttributesForDisappearingSupplementaryElementOfKind:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"elementKind"},{"kind":"text","text":" "},{"kind":"identifier","text":"atIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"elementIndexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayout~1finalLayoutAttributesForDisappearingSupplementaryElement(ofKind:at:)\/title","value":"finalLayoutAttributesForDisappearingSupplementaryElementOfKind:atIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayout~1finalLayoutAttributesForDisappearingSupplementaryElement(ofKind:at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finalLayoutAttributesForDisappearingSupplementaryElementOfKind:atIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayout\/title","value":"GTUIFallLayout"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayout\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}