{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"interactiveTransition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentInteractiveTransition","text":"GTUISegmentInteractiveTransition"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/start(_:)-4fzh4"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/start(_:)-4fzh4","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"start(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTUISegmentInteractiveTransition","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentInteractiveTransition"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:7GTUIKit28GTUISegmentTransitionContextC5startyyAA0b11InteractiveC0CF","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/start(_:)-4fzh4":{"role":"symbol","title":"start(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTUISegmentInteractiveTransition","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentInteractiveTransition"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/start(_:)-4fzh4","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/start(_:)-4fzh4"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext":{"role":"symbol","title":"GTUISegmentTransitionContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentTransitionContext"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}],"url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentInteractiveTransition":{"role":"symbol","title":"GTUISegmentInteractiveTransition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}],"url":"\/documentation\/gtuikit\/gtuisegmentinteractivetransition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionContext\/title","value":"GTUISegmentTransitionContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionContext\/fragments","value":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition\/title","value":"GTUISegmentInteractiveTransition"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition\/fragments","value":[{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}