{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"render"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutRender","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutRender","text":"GTUIFallLayoutRender"},{"kind":"text","text":", "},{"kind":"externalParam","text":"columnCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"columnSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutcompositor\/init(render:columncount:columnspacing:itemspacing:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutCompositor\/init(render:columnCount:columnSpacing:itemSpacing:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"render"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutRender","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutRender"},{"kind":"text","text":", "},{"kind":"externalParam","text":"columnCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"columnSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"title":"init(render:columnCount:columnSpacing:itemSpacing:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:7GTUIKit24GTUIFallLayoutCompositorC6render11columnCount0F7Spacing04itemH0AcA0bC6RenderC_Si14CoreFoundation7CGFloatVALtcfc","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutCompositor"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutRender":{"role":"symbol","title":"GTUIFallLayoutRender","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutRender"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutRender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutRender"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutrender"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutCompositor/init(render:columnCount:columnSpacing:itemSpacing:)":{"role":"symbol","title":"init(render:columnCount:columnSpacing:itemSpacing:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"render"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutRender","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutRender"},{"kind":"text","text":", "},{"kind":"externalParam","text":"columnCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"columnSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutCompositor\/init(render:columnCount:columnSpacing:itemSpacing:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutcompositor\/init(render:columncount:columnspacing:itemspacing:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutCompositor":{"role":"symbol","title":"GTUIFallLayoutCompositor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutCompositor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutCompositor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutCompositor"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutcompositor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutRender\/title","value":"GTUIFallLayoutRender"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutRender\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutRender"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutCompositor\/title","value":"GTUIFallLayoutCompositor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutCompositor\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutCompositor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}