{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endRefreshing"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtrefreshgamefiheader\/endrefreshing()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtrefreshgamefiheader\/endrefreshing()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTRefreshGamefiHeader\/endRefreshing()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endRefreshing"},{"kind":"text","text":"()"}],"title":"endRefreshing()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)GTRefreshGamefiHeader(im)endRefreshing","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"endRefreshing"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTRefreshGamefiHeader"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTRefreshGamefiHeader":{"role":"symbol","title":"GTRefreshGamefiHeader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTRefreshGamefiHeader"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTRefreshGamefiHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTRefreshGamefiHeader"}],"url":"\/documentation\/gtuikit\/gtrefreshgamefiheader"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTRefreshGamefiHeader/endRefreshing()":{"role":"symbol","title":"endRefreshing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endRefreshing"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTRefreshGamefiHeader\/endRefreshing()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endRefreshing"}],"url":"\/documentation\/gtuikit\/gtrefreshgamefiheader\/endrefreshing()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"endRefreshing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endRefreshing"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"endRefreshing"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTRefreshGamefiHeader\/title","value":"GTRefreshGamefiHeader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTRefreshGamefiHeader\/fragments","value":[{"kind":"identifier","text":"GTRefreshGamefiHeader"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTRefreshGamefiHeader~1endRefreshing()\/title","value":"endRefreshing"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTRefreshGamefiHeader~1endRefreshing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endRefreshing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}