{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkageManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageManager","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILinkageManager","text":"GTUILinkageManager"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisublinkageviewcontroller\/linkagemanager"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISubLinkageViewController\/linkageManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GTUILinkageObject.linkageManager"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkageManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILinkageManager","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILinkageManager"},{"kind":"text","text":"?"}],"title":"linkageManager","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit28GTUISubLinkageViewControllerC14linkageManagerAA011GTUILinkageG0CSgvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISubLinkageViewController"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageManager":{"role":"symbol","title":"GTUILinkageManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILinkageManager"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILinkageManager"}],"url":"\/documentation\/gtuikit\/gtuilinkagemanager"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISubLinkageViewController/linkageManager":{"role":"symbol","title":"linkageManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkageManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILinkageManager","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILinkageManager"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISubLinkageViewController\/linkageManager","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisublinkageviewcontroller\/linkagemanager"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISubLinkageViewController":{"role":"symbol","title":"GTUISubLinkageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISubLinkageViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISubLinkageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISubLinkageViewController"}],"url":"\/documentation\/gtuikit\/gtuisublinkageviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageManager\/title","value":"GTUILinkageManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageManager\/fragments","value":[{"kind":"identifier","text":"GTUILinkageManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISubLinkageViewController\/title","value":"GTUISubLinkageViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISubLinkageViewController\/fragments","value":[{"kind":"identifier","text":"GTUISubLinkageViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}