{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableNode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASTableNode","preciseIdentifier":"c:objc(cs)ASTableNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":" "},{"kind":"internalParam","text":"section"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtalertrowitemnode\/tablenode(_:numberofrowsinsection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtalertrowitemnode\/tablenode(_:numberofrowsinsection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:numberOfRowsInSection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ASTableDataSource.tableNode(_:numberOfRowsInSection:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableNode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASTableNode","preciseIdentifier":"c:objc(cs)ASTableNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"tableNode(_:numberOfRowsInSection:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTAlertRowItemNode(im)tableNode:numberOfRowsInSection:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"tableNode:numberOfRowsInSection:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/ASTableDataSource-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/ASTableDataSource-Implementations":{"role":"collectionGroup","title":"ASTableDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/ASTableDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtalertrowitemnode\/astabledatasource-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/tableNode(_:numberOfRowsInSection:)":{"role":"symbol","title":"tableNode(_:numberOfRowsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableNode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASTableNode","preciseIdentifier":"c:objc(cs)ASTableNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:numberOfRowsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableNode:numberOfRowsInSection:"}],"url":"\/documentation\/gtuikit\/gtalertrowitemnode\/tablenode(_:numberofrowsinsection:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode":{"role":"symbol","title":"GTAlertRowItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertRowItemNode"}],"abstract":[{"type":"text","text":"Cancel Item Alert"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertRowItemNode"}],"url":"\/documentation\/gtuikit\/gtalertrowitemnode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tableNode:numberOfRowsInSection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableNode:numberOfRowsInSection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"tableNode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASTableNode","preciseIdentifier":"c:objc(cs)ASTableNode"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tableNode"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfRowsInSection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"section"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode~1tableNode(_:numberOfRowsInSection:)\/title","value":"tableNode:numberOfRowsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode~1tableNode(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableNode:numberOfRowsInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/title","value":"GTAlertRowItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertRowItemNode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}