{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tabBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITabBar","preciseIdentifier":"c:objc(cs)UITabBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndCustomizing"},{"kind":"text","text":" "},{"kind":"internalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UITabBarItem","preciseIdentifier":"c:objc(cs)UITabBarItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"changed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/estabbarcontroller\/tabbar(_:didendcustomizing:changed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/estabbarcontroller\/tabbar(_:didendcustomizing:changed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarController\/tabBar(_:didEndCustomizing:changed:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBar","preciseIdentifier":"c:objc(cs)UITabBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndCustomizing"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UITabBarItem","preciseIdentifier":"c:objc(cs)UITabBarItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"changed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"tabBar(_:didEndCustomizing:changed:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)ESTabBarController(im)tabBar:didEndCustomizingItems:changed:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"tabBar:didEndCustomizingItems:changed:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarController"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarController":{"role":"symbol","title":"ESTabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarController"}],"url":"\/documentation\/gtuikit\/estabbarcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarController/tabBar(_:didEndCustomizing:changed:)":{"role":"symbol","title":"tabBar(_:didEndCustomizing:changed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBar","preciseIdentifier":"c:objc(cs)UITabBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndCustomizing"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UITabBarItem","preciseIdentifier":"c:objc(cs)UITabBarItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"changed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarController\/tabBar(_:didEndCustomizing:changed:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tabBar:didEndCustomizingItems:changed:"}],"url":"\/documentation\/gtuikit\/estabbarcontroller\/tabbar(_:didendcustomizing:changed:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tabBar:didEndCustomizingItems:changed:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tabBar:didEndCustomizingItems:changed:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"tabBar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBar","preciseIdentifier":"c:objc(cs)UITabBar"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tabBar"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEndCustomizingItems:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<UITabBarItem *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"items"},{"kind":"text","text":" "},{"kind":"identifier","text":"changed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"changed"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarController\/title","value":"ESTabBarController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarController\/fragments","value":[{"kind":"identifier","text":"ESTabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarController~1tabBar(_:didEndCustomizing:changed:)\/title","value":"tabBar:didEndCustomizingItems:changed:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarController~1tabBar(_:didEndCustomizing:changed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tabBar:didEndCustomizingItems:changed:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}