{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"canMoveItemAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:canmoveitemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:canmoveitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:canMoveItemAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDataSource.collectionView(_:canMoveItemAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"canMoveItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"collectionView(_:canMoveItemAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTUICollectionViewBaseAdaptor(im)collectionView:canMoveItemAtIndexPath:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:canMoveItemAtIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/UICollectionViewDataSource-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor":{"role":"symbol","title":"GTUICollectionViewBaseAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/collectionView(_:canMoveItemAt:)":{"role":"symbol","title":"collectionView(_:canMoveItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"canMoveItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/collectionView(_:canMoveItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:canMoveItemAtIndexPath:"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/collectionview(_:canmoveitemat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewBaseAdaptor/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewBaseAdaptor\/UICollectionViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewbaseadaptor\/uicollectionviewdatasource-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"collectionView:canMoveItemAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:canMoveItemAtIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"canMoveItemAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor\/title","value":"GTUICollectionViewBaseAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUICollectionViewBaseAdaptor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:canMoveItemAt:)\/title","value":"collectionView:canMoveItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewBaseAdaptor~1collectionView(_:canMoveItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:canMoveItemAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}