{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateIntrinsicContentSize"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtcollapseview\/invalidateintrinsiccontentsize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtcollapseview\/invalidateintrinsiccontentsize()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCollapseView\/invalidateIntrinsicContentSize()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateIntrinsicContentSize"},{"kind":"text","text":"()"}],"title":"invalidateIntrinsicContentSize()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)GTCollapseView(im)invalidateIntrinsicContentSize","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"invalidateIntrinsicContentSize"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCollapseView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCollapseView/invalidateIntrinsicContentSize()":{"role":"symbol","title":"invalidateIntrinsicContentSize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateIntrinsicContentSize"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCollapseView\/invalidateIntrinsicContentSize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"invalidateIntrinsicContentSize"}],"url":"\/documentation\/gtuikit\/gtcollapseview\/invalidateintrinsiccontentsize()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCollapseView":{"role":"symbol","title":"GTCollapseView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCollapseView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCollapseView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCollapseView"}],"url":"\/documentation\/gtuikit\/gtcollapseview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"invalidateIntrinsicContentSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateIntrinsicContentSize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"invalidateIntrinsicContentSize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCollapseView~1invalidateIntrinsicContentSize()\/title","value":"invalidateIntrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCollapseView~1invalidateIntrinsicContentSize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateIntrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCollapseView\/title","value":"GTCollapseView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCollapseView\/fragments","value":[{"kind":"identifier","text":"GTCollapseView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}