{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"itemTitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTActionItem","text":"GTActionItem"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionItem\/ItemType","preciseIdentifier":"s:7GTUIKit12GTActionItemC0C4TypeO","text":"ItemType"},{"kind":"text","text":" = .normal)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtactionsheetreuseview\/init(message:itemtitles:type:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetReuseView\/init(message:itemTitles:type:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"itemTitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTActionItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTActionItem"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ItemType","preciseIdentifier":"s:7GTUIKit12GTActionItemC0C4TypeO"},{"kind":"text","text":")"}],"title":"init(message:itemTitles:type:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:7GTUIKit22GTActionSheetReuseViewC7message10itemTitles4typeACSSSg_SaySSGAA0B4ItemC0J4TypeOtcfc","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetReuseView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionSheetReuseView":{"role":"symbol","title":"GTActionSheetReuseView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTActionSheetReuseView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetReuseView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTActionSheetReuseView"}],"url":"\/documentation\/gtuikit\/gtactionsheetreuseview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionItem/ItemType":{"role":"symbol","title":"GTActionItem.ItemType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ItemType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionItem\/ItemType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ItemType"}],"url":"\/documentation\/gtuikit\/gtactionitem\/itemtype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionSheetReuseView/init(message:itemTitles:type:)":{"role":"symbol","title":"init(message:itemTitles:type:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"itemTitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTActionItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTActionItem"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ItemType","preciseIdentifier":"s:7GTUIKit12GTActionItemC0C4TypeO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetReuseView\/init(message:itemTitles:type:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtactionsheetreuseview\/init(message:itemtitles:type:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionItem":{"role":"symbol","title":"GTActionItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTActionItem"}],"abstract":[{"type":"text","text":"GTActionSheetView 按钮"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTActionItem"}],"url":"\/documentation\/gtuikit\/gtactionitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionSheetReuseView\/title","value":"GTActionSheetReuseView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionSheetReuseView\/fragments","value":[{"kind":"identifier","text":"GTActionSheetReuseView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionItem\/title","value":"GTActionItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionItem\/fragments","value":[{"kind":"identifier","text":"GTActionItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}