{"variants":[{"paths":["\/documentation\/gtuikit\/gtuitableviewadaptor\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuitableviewadaptor\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/UIScrollViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndDragging(_:willDecelerate:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndScrollingAnimation(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndZooming(_:with:atScale:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidScroll(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewWillBeginDragging(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"UIScrollViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor/scrollViewDidEndZooming(_:with:atScale:)":{"role":"symbol","title":"scrollViewDidEndZooming(_:with:atScale:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndZooming"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"atScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndZooming(_:with:atScale:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndZooming:withView:atScale:"}],"url":"\/documentation\/gtuikit\/gtuitableviewadaptor\/scrollviewdidendzooming(_:with:atscale:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor/scrollViewWillBeginDragging(_:)":{"role":"symbol","title":"scrollViewWillBeginDragging(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewWillBeginDragging(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDragging:"}],"url":"\/documentation\/gtuikit\/gtuitableviewadaptor\/scrollviewwillbegindragging(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor":{"role":"symbol","title":"GTUITableViewAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewAdaptor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewAdaptor"}],"url":"\/documentation\/gtuikit\/gtuitableviewadaptor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor/scrollViewDidEndDragging(_:willDecelerate:)":{"role":"symbol","title":"scrollViewDidEndDragging(_:willDecelerate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDecelerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndDragging(_:willDecelerate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}],"url":"\/documentation\/gtuikit\/gtuitableviewadaptor\/scrollviewdidenddragging(_:willdecelerate:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor/scrollViewDidEndDecelerating(_:)":{"role":"symbol","title":"scrollViewDidEndDecelerating(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDecelerating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndDecelerating(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"url":"\/documentation\/gtuikit\/gtuitableviewadaptor\/scrollviewdidenddecelerating(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor/scrollViewDidEndScrollingAnimation(_:)":{"role":"symbol","title":"scrollViewDidEndScrollingAnimation(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndScrollingAnimation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndScrollingAnimation(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndScrollingAnimation:"}],"url":"\/documentation\/gtuikit\/gtuitableviewadaptor\/scrollviewdidendscrollinganimation(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewAdaptor/scrollViewDidScroll(_:)":{"role":"symbol","title":"scrollViewDidScroll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidScroll(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}],"url":"\/documentation\/gtuikit\/gtuitableviewadaptor\/scrollviewdidscroll(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndDragging(_:willDecelerate:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndScrollingAnimation(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidEndZooming(_:with:atScale:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewDidScroll(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewAdaptor\/scrollViewWillBeginDragging(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewDidEndZooming(_:with:atScale:)\/title","value":"scrollViewDidEndZooming:withView:atScale:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewDidEndZooming(_:with:atScale:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndZooming:withView:atScale:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewWillBeginDragging(_:)\/title","value":"scrollViewWillBeginDragging:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewWillBeginDragging(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor\/title","value":"GTUITableViewAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor\/fragments","value":[{"kind":"identifier","text":"GTUITableViewAdaptor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewDidEndDragging(_:willDecelerate:)\/title","value":"scrollViewDidEndDragging:willDecelerate:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewDidEndDragging(_:willDecelerate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewDidEndDecelerating(_:)\/title","value":"scrollViewDidEndDecelerating:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewDidEndDecelerating(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewDidEndScrollingAnimation(_:)\/title","value":"scrollViewDidEndScrollingAnimation:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewDidEndScrollingAnimation(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndScrollingAnimation:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewDidScroll(_:)\/title","value":"scrollViewDidScroll:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewAdaptor~1scrollViewDidScroll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}