{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configAvatarView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarGroupView","text":"GTAvatarGroupView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarView","text":"GTAvatarView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtavatargroupviewdelegate\/configavatarview(groupview:view:index:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupViewDelegate\/configAvatarView(groupView:view:index:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"configAvatarView(groupView:view:index:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configAvatarView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAvatarGroupView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarGroupView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAvatarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:7GTUIKit25GTAvatarGroupViewDelegateP012configAvatarD005groupD04view5indexyAA0bcD0C_AA0bD0CSitF","required":true,"modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupViewDelegate"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarGroupViewDelegate/configAvatarView(groupView:view:index:)":{"role":"symbol","title":"configAvatarView(groupView:view:index:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configAvatarView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAvatarGroupView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarGroupView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAvatarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupViewDelegate\/configAvatarView(groupView:view:index:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtavatargroupviewdelegate\/configavatarview(groupview:view:index:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarGroupViewDelegate":{"role":"symbol","title":"GTAvatarGroupViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAvatarGroupViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAvatarGroupViewDelegate"}],"url":"\/documentation\/gtuikit\/gtavatargroupviewdelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarGroupView":{"role":"symbol","title":"GTAvatarGroupView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAvatarGroupView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarGroupView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAvatarGroupView"}],"url":"\/documentation\/gtuikit\/gtavatargroupview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarView":{"role":"symbol","title":"GTAvatarView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAvatarView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAvatarView"}],"url":"\/documentation\/gtuikit\/gtavatarview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarGroupView\/title","value":"GTAvatarGroupView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarGroupView\/fragments","value":[{"kind":"identifier","text":"GTAvatarGroupView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarView\/title","value":"GTAvatarView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarView\/fragments","value":[{"kind":"identifier","text":"GTAvatarView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}