{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/estabbar\/layoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/estabbar\/layoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBar\/layoutSubviews()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"title":"layoutSubviews()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)ESTabBar(im)layoutSubviews","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBar"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBar/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBar\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/gtuikit\/estabbar\/layoutsubviews()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBar":{"role":"symbol","title":"ESTabBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBar"}],"abstract":[{"type":"text","text":"ESTabBar是高度自定义的UITabBar子类，通过添加UIControl的方式实现自定义tabBarItem的效果。目前支持tabBar的大部分属性的设置，例如delegate,items,selectedImge,itemPositioning,itemWidth,itemSpacing等，以后会更加细致的优化tabBar原有属性的设置效果。"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBar"}],"url":"\/documentation\/gtuikit\/estabbar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"layoutSubviews"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBar~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBar~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBar\/title","value":"ESTabBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBar\/fragments","value":[{"kind":"identifier","text":"ESTabBar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}