{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/estabbaritem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/estabbaritem"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UITabBarItem"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTabBarLottieItem"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UISpringLoadedInteractionSupporting"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/init(_:title:image:selectedImage:tag:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/badgeColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/badgeValue","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/contentView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/image","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/selectedImage","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/tag","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/title"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/setTitle(_:image:selectedImage:tag:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"ESTabBarItem"}],"role":"symbol","title":"ESTabBarItem","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItem"}],"symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)ESTabBarItem","modules":[{"name":"GTUIKit"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"8.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/badgeValue":{"role":"symbol","title":"badgeValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/badgeValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"badgeValue"}],"url":"\/documentation\/gtuikit\/estabbaritem\/badgevalue"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/badgeColor":{"role":"symbol","title":"badgeColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Override UITabBarItem.badgeColor, make it available for iOS8.0 and later."},{"type":"text","text":" "},{"type":"text","text":"If this item displays a badge, this color will be used for the badge’s background. If set to nil, the default background color will be used instead."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/badgeColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"badgeColor"}],"url":"\/documentation\/gtuikit\/estabbaritem\/badgecolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/init(_:title:image:selectedImage:tag:)":{"role":"symbol","title":"init(_:title:image:selectedImage:tag:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ESTabBarItemContentView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemContentView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"selectedImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/init(_:title:image:selectedImage:tag:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritem\/init(_:title:image:selectedimage:tag:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem":{"role":"symbol","title":"ESTabBarItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarItem"}],"url":"\/documentation\/gtuikit\/estabbaritem"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/gtuikit\/estabbaritem\/init(coder:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/image":{"role":"symbol","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"image"}],"url":"\/documentation\/gtuikit\/estabbaritem\/image"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/tag":{"role":"symbol","title":"tag","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/tag","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tag"}],"url":"\/documentation\/gtuikit\/estabbaritem\/tag"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/title","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"title"}],"url":"\/documentation\/gtuikit\/estabbaritem\/title"},"doc://org.cocoapods.GTUIKit/objc(cs)UITabBarItem":{"type":"unresolvable","title":"UITabBarItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UITabBarItem"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/contentView":{"role":"symbol","title":"contentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ESTabBarItemContentView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemContentView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Customize content view"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/contentView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritem\/contentview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/setTitle(_:image:selectedImage:tag:)":{"role":"symbol","title":"setTitle(_:image:selectedImage:tag:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"selectedImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/setTitle(_:image:selectedImage:tag:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritem\/settitle(_:image:selectedimage:tag:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTabBarLottieItem":{"role":"symbol","title":"GTTabBarLottieItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTabBarLottieItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTabBarLottieItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTabBarLottieItem"}],"url":"\/documentation\/gtuikit\/gttabbarlottieitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItem/selectedImage":{"role":"symbol","title":"selectedImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/selectedImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedImage"}],"url":"\/documentation\/gtuikit\/estabbaritem\/selectedimage"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ESTabBarItem"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ESTabBarItem"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ESTabBarItem"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/badgeColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/badgeValue","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/image","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/selectedImage","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/tag","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/title"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItem\/init(coder:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UITabBarItem"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTabBarLottieItem"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItem"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITabBarItem","preciseIdentifier":"c:objc(cs)UITabBarItem"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1badgeValue\/title","value":"badgeValue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1badgeValue\/fragments","value":[{"kind":"identifier","text":"badgeValue"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1badgeColor\/title","value":"badgeColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1badgeColor\/fragments","value":[{"kind":"identifier","text":"badgeColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem\/title","value":"ESTabBarItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem\/fragments","value":[{"kind":"identifier","text":"ESTabBarItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1image\/title","value":"image"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1image\/fragments","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1tag\/title","value":"tag"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1tag\/fragments","value":[{"kind":"identifier","text":"tag"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1title\/title","value":"title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1title\/fragments","value":[{"kind":"identifier","text":"title"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTabBarLottieItem\/title","value":"GTTabBarLottieItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTabBarLottieItem\/fragments","value":[{"kind":"identifier","text":"GTTabBarLottieItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1selectedImage\/title","value":"selectedImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItem~1selectedImage\/fragments","value":[{"kind":"identifier","text":"selectedImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}