{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertSwitchItemNode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtalertswitchitemnode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtalertswitchitemnode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASCommonTableDataSource","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASCommonTableViewDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTableDataSource","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTableDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIScrollViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertSwitchItemNode","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertSwitchItemNode\/tableNode(_:nodeBlockForRowAt:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertSwitchItemNode"}],"title":"GTAlertSwitchItemNode","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTAlertSwitchItemNode","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTAlertSwitchItemNode"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIScrollViewDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementStylability":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementStylability","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability"},"doc://org.cocoapods.GTUIKit/objc(pl)ASInterfaceStateDelegate":{"type":"unresolvable","title":"AsyncDisplayKit.ASInterfaceStateDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode":{"role":"symbol","title":"GTAlertRowItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertRowItemNode"}],"abstract":[{"type":"text","text":"Cancel Item Alert"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertRowItemNode"}],"url":"\/documentation\/gtuikit\/gtalertrowitemnode"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementExtensibility":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementExtensibility","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertSwitchItemNode":{"role":"symbol","title":"GTAlertSwitchItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertSwitchItemNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertSwitchItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertSwitchItemNode"}],"url":"\/documentation\/gtuikit\/gtalertswitchitemnode"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElement":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElement","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement"},"doc://org.cocoapods.GTUIKit/objc(pl)ASCommonTableDataSource":{"type":"unresolvable","title":"AsyncDisplayKit.ASCommonTableDataSource","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASCommonTableDataSource"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTableDelegate":{"type":"unresolvable","title":"AsyncDisplayKit.ASTableDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTableDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)NSLocking":{"type":"unresolvable","title":"Foundation.NSLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking"},"doc://org.cocoapods.GTUIKit/objc(pl)ASCommonTableViewDelegate":{"type":"unresolvable","title":"AsyncDisplayKit.ASCommonTableViewDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASCommonTableViewDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)ASDebugNameProvider":{"type":"unresolvable","title":"AsyncDisplayKit.ASDebugNameProvider","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLocking":{"type":"unresolvable","title":"AsyncDisplayKit.ASLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTableDataSource":{"type":"unresolvable","title":"AsyncDisplayKit.ASTableDataSource","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTableDataSource"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTraitEnvironment":{"type":"unresolvable","title":"AsyncDisplayKit.ASTraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementAsciiArtProtocol":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementAsciiArtProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertSwitchItemNode/tableNode(_:nodeBlockForRowAt:)":{"role":"symbol","title":"tableNode(_:nodeBlockForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableNode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASTableNode","preciseIdentifier":"c:objc(cs)ASTableNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nodeBlockForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASCellNodeBlock","preciseIdentifier":"c:ASBlockTypes.h@T@ASCellNodeBlock"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertSwitchItemNode\/tableNode(_:nodeBlockForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableNode:nodeBlockForRowAtIndexPath:"}],"url":"\/documentation\/gtuikit\/gtalertswitchitemnode\/tablenode(_:nodeblockforrowat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTAlertSwitchItemNode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTAlertSwitchItemNode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTAlertSwitchItemNode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertSwitchItemNode\/tableNode(_:nodeBlockForRowAt:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertSwitchItemNode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAlertRowItemNode","text":"GTAlertRowItemNode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/title","value":"GTAlertRowItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertRowItemNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertSwitchItemNode\/title","value":"GTAlertSwitchItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertSwitchItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertSwitchItemNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertSwitchItemNode~1tableNode(_:nodeBlockForRowAt:)\/title","value":"tableNode:nodeBlockForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertSwitchItemNode~1tableNode(_:nodeBlockForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableNode:nodeBlockForRowAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}