{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertRowItemNode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtalertrowitemnode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtalertrowitemnode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertSwitchItemNode"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASCommonTableDataSource","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASCommonTableViewDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTableDataSource","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTableDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIScrollViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Cancel Item Alert"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertRowItemNode"}],"title":"GTAlertRowItemNode","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTAlertRowItemNode","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTAlertRowItemNode"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/init(config:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/customNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableHeight","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/ASTableDataSource-Implementations","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/ASTableDelegate-Implementations","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/UIScrollViewDelegate-Implementations"],"generated":true}],"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/customNode":{"role":"symbol","title":"customNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASLayoutElement","preciseIdentifier":"c:objc(pl)ASLayoutElement"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/customNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalertrowitemnode\/customnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode":{"role":"symbol","title":"GTAlertTitleMessageItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}],"url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode"},"doc://org.cocoapods.GTUIKit/objc(pl)ASDebugNameProvider":{"type":"unresolvable","title":"AsyncDisplayKit.ASDebugNameProvider","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementExtensibility":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementExtensibility","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertSwitchItemNode":{"role":"symbol","title":"GTAlertSwitchItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertSwitchItemNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertSwitchItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertSwitchItemNode"}],"url":"\/documentation\/gtuikit\/gtalertswitchitemnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/init(config:)":{"role":"symbol","title":"init(config:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAlertRowItemConfig","preciseIdentifier":"s:7GTUIKit20GTAlertRowItemConfigC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/init(config:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalertrowitemnode\/init(config:)"},"doc://org.cocoapods.GTUIKit/objc(pl)ASCommonTableViewDelegate":{"type":"unresolvable","title":"AsyncDisplayKit.ASCommonTableViewDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASCommonTableViewDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIScrollViewDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/ASTableDelegate-Implementations":{"role":"collectionGroup","title":"ASTableDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/ASTableDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtalertrowitemnode\/astabledelegate-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/ASTableDataSource-Implementations":{"role":"collectionGroup","title":"ASTableDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/ASTableDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtalertrowitemnode\/astabledatasource-implementations"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTraitEnvironment":{"type":"unresolvable","title":"AsyncDisplayKit.ASTraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/tableNode":{"role":"symbol","title":"tableNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASTableNode","preciseIdentifier":"c:objc(cs)ASTableNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalertrowitemnode\/tablenode"},"doc://org.cocoapods.GTUIKit/objc(pl)ASCommonTableDataSource":{"type":"unresolvable","title":"AsyncDisplayKit.ASCommonTableDataSource","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASCommonTableDataSource"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementStylability":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementStylability","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTableDelegate":{"type":"unresolvable","title":"ASTableDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTableDelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/tableHeight":{"role":"symbol","title":"tableHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableHeight","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalertrowitemnode\/tableheight"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTableDataSource":{"type":"unresolvable","title":"ASTableDataSource","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTableDataSource"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLocking":{"type":"unresolvable","title":"AsyncDisplayKit.ASLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/UIScrollViewDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/UIScrollViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtalertrowitemnode\/uiscrollviewdelegate-implementations"},"doc://org.cocoapods.GTUIKit/objc(pl)NSLocking":{"type":"unresolvable","title":"Foundation.NSLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode":{"role":"symbol","title":"GTAlertRowItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertRowItemNode"}],"abstract":[{"type":"text","text":"Cancel Item Alert"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertRowItemNode"}],"url":"\/documentation\/gtuikit\/gtalertrowitemnode"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElement":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElement","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementAsciiArtProtocol":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementAsciiArtProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol"},"doc://org.cocoapods.GTUIKit/objc(pl)ASInterfaceStateDelegate":{"type":"unresolvable","title":"AsyncDisplayKit.ASInterfaceStateDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTAlertRowItemNode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTAlertRowItemNode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTAlertRowItemNode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/ASTableDataSource-Implementations","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/ASTableDelegate-Implementations","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/UIScrollViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertSwitchItemNode"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTableDataSource","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTableDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertRowItemNode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAlertTitleMessageItemNode","text":"GTAlertTitleMessageItemNode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode\/title","value":"GTAlertTitleMessageItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertSwitchItemNode\/title","value":"GTAlertSwitchItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertSwitchItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertSwitchItemNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/title","value":"GTAlertRowItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertRowItemNode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}