{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtalerttitlemessageitemnode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtalerttitlemessageitemnode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertContentNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertCheckBoxItemNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertImageNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertOptionItemNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/init(config:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/buttonItems","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/closeNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/config","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/customNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/itemHorizon","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/itemHorizonWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/messageContentNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/messageNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/messageScroll","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/selectClosure","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/titleNode"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/calculateMessage()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/closeEvent()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/isConfirm(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/itemEvent(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/itemFactory(title:tag:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/layoutSpecThatFits(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/setFirstItemImage()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/show(contentPositin:view:selectClosure:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/showInit()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}],"title":"GTAlertTitleMessageItemNode","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTAlertTitleMessageItemNode","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/titleNode":{"role":"symbol","title":"titleNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASTextNode2","preciseIdentifier":"c:objc(cs)ASTextNode2"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/titleNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/titlenode"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLocking":{"type":"unresolvable","title":"AsyncDisplayKit.ASLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/closeNode":{"role":"symbol","title":"closeNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASImageNode","preciseIdentifier":"c:objc(cs)ASImageNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/closeNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/closenode"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)NSLocking":{"type":"unresolvable","title":"Foundation.NSLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/isConfirm(_:)":{"role":"symbol","title":"isConfirm(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConfirm"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASButtonNode","preciseIdentifier":"c:objc(cs)ASButtonNode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/isConfirm(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/isconfirm(_:)"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementStylability":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementStylability","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability"},"doc://org.cocoapods.GTUIKit/objc(pl)ASInterfaceStateDelegate":{"type":"unresolvable","title":"AsyncDisplayKit.ASInterfaceStateDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/setFirstItemImage()":{"role":"symbol","title":"setFirstItemImage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFirstItemImage"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/setFirstItemImage()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFirstItemImage"}],"url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/setfirstitemimage()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/messageContentNode":{"role":"symbol","title":"messageContentNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageContentNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASDisplayNode","preciseIdentifier":"c:objc(cs)ASDisplayNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/messageContentNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/messagecontentnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/layoutSpecThatFits(_:)":{"role":"symbol","title":"layoutSpecThatFits(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSpecThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASSizeRange","preciseIdentifier":"c:@SA@ASSizeRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASLayoutSpec","preciseIdentifier":"c:objc(cs)ASLayoutSpec"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/layoutSpecThatFits(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSpecThatFits:"}],"url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/layoutspecthatfits(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/selectClosure":{"role":"symbol","title":"selectClosure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectClosure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAlertEventType","preciseIdentifier":"s:7GTUIKit16GTAlertEventTypea"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/selectClosure","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/selectclosure"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/customNode":{"role":"symbol","title":"customNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASLayoutElement","preciseIdentifier":"c:objc(pl)ASLayoutElement"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/customNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/customnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/calculateMessage()":{"role":"symbol","title":"calculateMessage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateMessage"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/calculateMessage()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/calculatemessage()"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElement":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElement","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement"},"doc://org.cocoapods.GTUIKit/objc(pl)ASDebugNameProvider":{"type":"unresolvable","title":"AsyncDisplayKit.ASDebugNameProvider","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/init(config:)":{"role":"symbol","title":"init(config:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAlertItemConfig","preciseIdentifier":"s:7GTUIKit17GTAlertItemConfigC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/init(config:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/init(config:)"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementExtensibility":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementExtensibility","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementAsciiArtProtocol":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementAsciiArtProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/buttonItems":{"role":"symbol","title":"buttonItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ASButtonNode","preciseIdentifier":"c:objc(cs)ASButtonNode"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/buttonItems","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/buttonitems"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/closeEvent()":{"role":"symbol","title":"closeEvent()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeEvent"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/closeEvent()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"closeEvent"}],"url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/closeevent()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/showInit()":{"role":"symbol","title":"showInit()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showInit"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/showInit()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/showinit()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/messageNode":{"role":"symbol","title":"messageNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASTextNode2","preciseIdentifier":"c:objc(cs)ASTextNode2"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/messageNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/messagenode"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertImageNode":{"role":"symbol","title":"GTAlertImageNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertImageNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertImageNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertImageNode"}],"url":"\/documentation\/gtuikit\/gtalertimagenode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/messageScroll":{"role":"symbol","title":"messageScroll","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageScroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/messageScroll","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/messagescroll"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertCheckBoxItemNode":{"role":"symbol","title":"GTAlertCheckBoxItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertCheckBoxItemNode"}],"abstract":[{"type":"text","text":"Option Item Alert"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertCheckBoxItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertCheckBoxItemNode"}],"url":"\/documentation\/gtuikit\/gtalertcheckboxitemnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/show(contentPositin:view:selectClosure:)":{"role":"symbol","title":"show(contentPositin:view:selectClosure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"contentPositin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAlertPosition","preciseIdentifier":"s:7GTUIKit15GTAlertPositionO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"selectClosure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAlertEventType","preciseIdentifier":"s:7GTUIKit16GTAlertEventTypea"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"show & hidden"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/show(contentPositin:view:selectClosure:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/show(contentpositin:view:selectclosure:)"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTraitEnvironment":{"type":"unresolvable","title":"AsyncDisplayKit.ASTraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/config":{"role":"symbol","title":"config","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAlertItemConfig","preciseIdentifier":"s:7GTUIKit17GTAlertItemConfigC"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/config","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/config"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode":{"role":"symbol","title":"GTAlertTitleMessageItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}],"url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode":{"role":"symbol","title":"GTAlertRowItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertRowItemNode"}],"abstract":[{"type":"text","text":"Cancel Item Alert"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertRowItemNode"}],"url":"\/documentation\/gtuikit\/gtalertrowitemnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/itemHorizonWidth":{"role":"symbol","title":"itemHorizonWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemHorizonWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/itemHorizonWidth","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/itemhorizonwidth"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertContentNode":{"role":"symbol","title":"GTAlertContentNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertContentNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertContentNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertContentNode"}],"url":"\/documentation\/gtuikit\/gtalertcontentnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/itemEvent(_:)":{"role":"symbol","title":"itemEvent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASButtonNode","preciseIdentifier":"c:objc(cs)ASButtonNode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/itemEvent(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"itemEvent:"}],"url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/itemevent(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/itemFactory(title:tag:)":{"role":"symbol","title":"itemFactory(title:tag:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemFactory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASButtonNode","preciseIdentifier":"c:objc(cs)ASButtonNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/itemFactory(title:tag:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"itemFactoryWithTitle:tag:"}],"url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/itemfactory(title:tag:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertOptionItemNode":{"role":"symbol","title":"GTAlertOptionItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertOptionItemNode"}],"abstract":[{"type":"text","text":"Option Item Alert"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertOptionItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertOptionItemNode"}],"url":"\/documentation\/gtuikit\/gtalertoptionitemnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertTitleMessageItemNode/itemHorizon":{"role":"symbol","title":"itemHorizon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemHorizon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/itemHorizon","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtalerttitlemessageitemnode\/itemhorizon"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTAlertTitleMessageItemNode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/closeEvent()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/itemEvent(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/itemFactory(title:tag:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/layoutSpecThatFits(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertTitleMessageItemNode\/setFirstItemImage()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertContentNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertCheckBoxItemNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertImageNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertOptionItemNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertTitleMessageItemNode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertContentNode","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAlertContentNode","text":"GTAlertContentNode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1setFirstItemImage()\/title","value":"setFirstItemImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1setFirstItemImage()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFirstItemImage"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1layoutSpecThatFits(_:)\/title","value":"layoutSpecThatFits:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1layoutSpecThatFits(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSpecThatFits:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1closeEvent()\/title","value":"closeEvent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1closeEvent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closeEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertImageNode\/title","value":"GTAlertImageNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertImageNode\/fragments","value":[{"kind":"identifier","text":"GTAlertImageNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertCheckBoxItemNode\/title","value":"GTAlertCheckBoxItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertCheckBoxItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertCheckBoxItemNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode\/title","value":"GTAlertTitleMessageItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertTitleMessageItemNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/title","value":"GTAlertRowItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertRowItemNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertContentNode\/title","value":"GTAlertContentNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertContentNode\/fragments","value":[{"kind":"identifier","text":"GTAlertContentNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1itemEvent(_:)\/title","value":"itemEvent:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1itemEvent(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"itemEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1itemFactory(title:tag:)\/title","value":"itemFactoryWithTitle:tag:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertTitleMessageItemNode~1itemFactory(title:tag:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"itemFactoryWithTitle:tag:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertOptionItemNode\/title","value":"GTAlertOptionItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertOptionItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertOptionItemNode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}