{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBasePopCustomViewType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtbasepopcustomviewtype"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetReuseView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckAlertView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDatePickerView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTFundsPasswordView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTMessagePopItemView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTMessageResultPopItemView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStarRateInputTextView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStarRateMessageView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldAlertView"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopCustomViewType","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopCustomViewType\/target-5ri6z"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopCustomViewType\/calculateSize(containerSize:)-4b9y1"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBasePopCustomViewType"}],"title":"GTBasePopCustomViewType","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit23GTBasePopCustomViewTypeP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTBasePopCustomViewType"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDatePickerView":{"role":"symbol","title":"GTDatePickerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDatePickerView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDatePickerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTDatePickerView"}],"url":"\/documentation\/gtuikit\/gtdatepickerview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopCustomViewType":{"role":"symbol","title":"GTBasePopCustomViewType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBasePopCustomViewType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopCustomViewType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTBasePopCustomViewType"}],"url":"\/documentation\/gtuikit\/gtbasepopcustomviewtype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTFundsPasswordView":{"role":"symbol","title":"GTFundsPasswordView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTFundsPasswordView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTFundsPasswordView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTFundsPasswordView"}],"url":"\/documentation\/gtuikit\/gtfundspasswordview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsView":{"role":"symbol","title":"GTStepsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepsView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepsView"}],"url":"\/documentation\/gtuikit\/gtstepsview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStarRateMessageView":{"role":"symbol","title":"GTStarRateMessageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStarRateMessageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStarRateMessageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStarRateMessageView"}],"url":"\/documentation\/gtuikit\/gtstarratemessageview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTMessageResultPopItemView":{"role":"symbol","title":"GTMessageResultPopItemView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMessageResultPopItemView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTMessageResultPopItemView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMessageResultPopItemView"}],"url":"\/documentation\/gtuikit\/gtmessageresultpopitemview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionSheetView":{"role":"symbol","title":"GTActionSheetView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTActionSheetView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTActionSheetView"}],"url":"\/documentation\/gtuikit\/gtactionsheetview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckAlertView":{"role":"symbol","title":"GTCheckAlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckAlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckAlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckAlertView"}],"url":"\/documentation\/gtuikit\/gtcheckalertview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionSheetReuseView":{"role":"symbol","title":"GTActionSheetReuseView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTActionSheetReuseView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetReuseView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTActionSheetReuseView"}],"url":"\/documentation\/gtuikit\/gtactionsheetreuseview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopCustomViewType/calculateSize(containerSize:)-4b9y1":{"defaultImplementations":1,"role":"symbol","title":"calculateSize(containerSize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"containerSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopCustomViewType\/calculateSize(containerSize:)-4b9y1","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtbasepopcustomviewtype\/calculatesize(containersize:)-4b9y1"},"doc://org.cocoapods.GTUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIKit.UIView","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTMessagePopItemView":{"role":"symbol","title":"GTMessagePopItemView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMessagePopItemView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTMessagePopItemView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMessagePopItemView"}],"url":"\/documentation\/gtuikit\/gtmessagepopitemview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStarRateInputTextView":{"role":"symbol","title":"GTStarRateInputTextView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStarRateInputTextView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStarRateInputTextView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStarRateInputTextView"}],"url":"\/documentation\/gtuikit\/gtstarrateinputtextview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldAlertView":{"role":"symbol","title":"GTTextFieldAlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextFieldAlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldAlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextFieldAlertView"}],"url":"\/documentation\/gtuikit\/gttextfieldalertview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopCustomViewType/target-5ri6z":{"defaultImplementations":1,"role":"symbol","title":"target","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopTargetType","preciseIdentifier":"s:7GTUIKit15GTPopTargetTypeP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"需要声明成weak 否则会导致不释放"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopCustomViewType\/target-5ri6z","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtbasepopcustomviewtype\/target-5ri6z"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDatePickerView\/title","value":"GTDatePickerView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDatePickerView\/fragments","value":[{"kind":"identifier","text":"GTDatePickerView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTFundsPasswordView\/title","value":"GTFundsPasswordView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTFundsPasswordView\/fragments","value":[{"kind":"identifier","text":"GTFundsPasswordView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsView\/title","value":"GTStepsView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsView\/fragments","value":[{"kind":"identifier","text":"GTStepsView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStarRateMessageView\/title","value":"GTStarRateMessageView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStarRateMessageView\/fragments","value":[{"kind":"identifier","text":"GTStarRateMessageView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTMessageResultPopItemView\/title","value":"GTMessageResultPopItemView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTMessageResultPopItemView\/fragments","value":[{"kind":"identifier","text":"GTMessageResultPopItemView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionSheetView\/title","value":"GTActionSheetView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionSheetView\/fragments","value":[{"kind":"identifier","text":"GTActionSheetView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckAlertView\/title","value":"GTCheckAlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckAlertView\/fragments","value":[{"kind":"identifier","text":"GTCheckAlertView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionSheetReuseView\/title","value":"GTActionSheetReuseView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionSheetReuseView\/fragments","value":[{"kind":"identifier","text":"GTActionSheetReuseView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTMessagePopItemView\/title","value":"GTMessagePopItemView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTMessagePopItemView\/fragments","value":[{"kind":"identifier","text":"GTMessagePopItemView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStarRateInputTextView\/title","value":"GTStarRateInputTextView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStarRateInputTextView\/fragments","value":[{"kind":"identifier","text":"GTStarRateInputTextView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldAlertView\/title","value":"GTTextFieldAlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldAlertView\/fragments","value":[{"kind":"identifier","text":"GTTextFieldAlertView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}