{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBasePopView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtbasepopview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtbasepopview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopTargetType","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/init(config:customView:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/cancelButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/checkBoxButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/closeButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/customContainerView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/eventCallback","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/isSelected","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/mainButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/statementLable","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/titleLable"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/hiddenEvent()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/hiddenWhenPush()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/layout()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/layoutSubviews()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/popViewDismiss()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/show(in:popStyle:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/showWhenPop()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/updatePopViewBackground(style:)"]},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/show(_:customView:inView:eventHandle:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/showAttributedMessage(_:attributedMessagePicker:inView:eventHandle:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/showMessage(_:message:inView:eventHandle:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/showResult(_:message:sence:inView:eventHandle:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBasePopView"}],"title":"GTBasePopView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTBasePopView","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTBasePopView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"seeAlsoSections":[{"title":"弹窗","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView"],"generated":true}],"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/showAttributedMessage(_:attributedMessagePicker:inView:eventHandle:)":{"role":"symbol","title":"showAttributedMessage(_:attributedMessagePicker:inView:eventHandle:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAttributedMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTBasePopConfig","preciseIdentifier":"s:7GTUIKit15GTBasePopConfigC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributedMessagePicker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThemeAttributedStringPicker","preciseIdentifier":"c:@M@SwiftTheme@objc(cs)ThemeAttributedStringPicker"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eventHandle"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"GTBasePopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTBasePopView"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"GTBasePopEvent","preciseIdentifier":"s:7GTUIKit14GTBasePopEventO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"GTBasePopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTBasePopView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"显示富文本弹窗"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/showAttributedMessage(_:attributedMessagePicker:inView:eventHandle:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/showattributedmessage(_:attributedmessagepicker:inview:eventhandle:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/statementLable":{"role":"symbol","title":"statementLable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statementLable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"YYLabel","preciseIdentifier":"c:objc(cs)YYLabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/statementLable","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/statementlable"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/customContainerView":{"role":"symbol","title":"customContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/customContainerView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/customcontainerview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/showMessage(_:message:inView:eventHandle:)":{"role":"symbol","title":"showMessage(_:message:inView:eventHandle:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTBasePopConfig","preciseIdentifier":"s:7GTUIKit15GTBasePopConfigC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eventHandle"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"GTBasePopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTBasePopView"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"GTBasePopEvent","preciseIdentifier":"s:7GTUIKit14GTBasePopEventO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"GTBasePopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTBasePopView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"显示文本弹窗"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/showMessage(_:message:inView:eventHandle:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/showmessage(_:message:inview:eventhandle:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/show(_:customView:inView:eventHandle:)":{"role":"symbol","title":"show(_:customView:inView:eventHandle:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTBasePopConfig","preciseIdentifier":"s:7GTUIKit15GTBasePopConfigC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTBasePopCustomViewType","preciseIdentifier":"s:7GTUIKit23GTBasePopCustomViewTypeP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eventHandle"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"GTBasePopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTBasePopView"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"GTBasePopEvent","preciseIdentifier":"s:7GTUIKit14GTBasePopEventO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"GTBasePopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTBasePopView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"显示自定义弹窗"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/show(_:customView:inView:eventHandle:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/show(_:customview:inview:eventhandle:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/updatePopViewBackground(style:)":{"role":"symbol","title":"updatePopViewBackground(style:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePopViewBackground"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopViewBackgroundStyle","preciseIdentifier":"s:7GTUIKit24GTPopViewBackgroundStyleO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/updatePopViewBackground(style:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/updatepopviewbackground(style:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/show(in:popStyle:)":{"role":"symbol","title":"show(in:popStyle:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"popStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopViewPopStyle","preciseIdentifier":"s:7GTUIKit17GTPopViewPopStyleO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"显示popView"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/show(in:popStyle:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/show(in:popstyle:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBaseAlertView":{"role":"symbol","title":"GTBaseAlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBaseAlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTBaseAlertView"}],"url":"\/documentation\/gtuikit\/gtbasealertview"},"doc://org.cocoapods.GTUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView":{"role":"symbol","title":"GTBasePopView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBasePopView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTBasePopView"}],"url":"\/documentation\/gtuikit\/gtbasepopview"},"doc://org.cocoapods.GTUIKit/9PinLayout14SizeCalculableP":{"type":"unresolvable","title":"PinLayout.SizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/popViewDismiss()":{"role":"symbol","title":"popViewDismiss()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"popViewDismiss"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/popViewDismiss()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/popviewdismiss()"},"doc://org.cocoapods.GTUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.GTUIKit/12SkeletonView0aB8ExtendedP":{"type":"unresolvable","title":"SkeletonView.SkeletonViewExtended","identifier":"doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"},"doc://org.cocoapods.GTUIKit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/closeButton":{"role":"symbol","title":"closeButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/closeButton","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/closebutton"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/9PinLayout10LayoutableP":{"type":"unresolvable","title":"PinLayout.Layoutable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/layout()":{"role":"symbol","title":"layout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/layout()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/layout()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/init(config:customView:)":{"role":"symbol","title":"init(config:customView:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTBasePopConfig","preciseIdentifier":"s:7GTUIKit15GTBasePopConfigC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTBasePopCustomViewType","preciseIdentifier":"s:7GTUIKit23GTBasePopCustomViewTypeP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/init(config:customView:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/init(config:customview:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/showResult(_:message:sence:inView:eventHandle:)":{"role":"symbol","title":"showResult(_:message:sence:inView:eventHandle:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showResult"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTBasePopConfig","preciseIdentifier":"s:7GTUIKit15GTBasePopConfigC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTResultSence","preciseIdentifier":"s:7GTUIKit13GTResultSenceO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eventHandle"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"GTBasePopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTBasePopView"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"GTBasePopEvent","preciseIdentifier":"s:7GTUIKit14GTBasePopEventO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"GTBasePopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTBasePopView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"显示结果弹窗"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/showResult(_:message:sence:inView:eventHandle:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/showresult(_:message:sence:inview:eventhandle:)"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/cancelButton":{"role":"symbol","title":"cancelButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/cancelButton","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/cancelbutton"},"doc://org.cocoapods.GTUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/hiddenWhenPush()":{"role":"symbol","title":"hiddenWhenPush()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenWhenPush"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/hiddenWhenPush()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/hiddenwhenpush()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyType":{"role":"symbol","title":"GTEmptyType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyType"}],"url":"\/documentation\/gtuikit\/gtemptytype"},"doc://org.cocoapods.GTUIKit/9PinLayout18AutoSizeCalculableP":{"type":"unresolvable","title":"PinLayout.AutoSizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopTargetType":{"role":"symbol","title":"GTPopTargetType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopTargetType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopTargetType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopTargetType"}],"url":"\/documentation\/gtuikit\/gtpoptargettype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/eventCallback":{"role":"symbol","title":"eventCallback","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventCallback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"GTBasePopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTBasePopView"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"GTBasePopEvent","preciseIdentifier":"s:7GTUIKit14GTBasePopEventO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/eventCallback","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/eventcallback"},"doc://org.cocoapods.GTUIKit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/checkBoxButton":{"role":"symbol","title":"checkBoxButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkBoxButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/checkBoxButton","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/checkboxbutton"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/mainButton":{"role":"symbol","title":"mainButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/mainButton","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/mainbutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/titleLable":{"role":"symbol","title":"titleLable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/titleLable","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/titlelable"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/showWhenPop()":{"role":"symbol","title":"showWhenPop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showWhenPop"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/showWhenPop()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/showwhenpop()"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/gtuikit\/gtbasepopview\/init(coder:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/isSelected":{"role":"symbol","title":"isSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/isSelected","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasepopview\/isselected"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/gtuikit\/gtbasepopview\/layoutsubviews()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBasePopView/hiddenEvent()":{"role":"symbol","title":"hiddenEvent()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenEvent"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"隐藏弹窗"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/hiddenEvent()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hiddenEvent"}],"url":"\/documentation\/gtuikit\/gtbasepopview\/hiddenevent()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTBasePopView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTBasePopView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTBasePopView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/hiddenEvent()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBasePopView\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"弹窗","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBasePopView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBaseAlertView\/title","value":"GTBaseAlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBaseAlertView\/fragments","value":[{"kind":"identifier","text":"GTBaseAlertView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBasePopView\/title","value":"GTBasePopView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBasePopView\/fragments","value":[{"kind":"identifier","text":"GTBasePopView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBasePopView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBasePopView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBasePopView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBasePopView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBasePopView~1hiddenEvent()\/title","value":"hiddenEvent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBasePopView~1hiddenEvent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hiddenEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}