{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTConfigTextListNode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtconfigtextlistnode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtconfigtextlistnode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/init()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/datas","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/iconActionClsore","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/iconFontName","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/iconfontColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/iconfontSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/leftActionClsore","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/leftColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/leftFont","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/leftMaxNumber","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/rightActionClsore","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/rightColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/rightFont","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/rightMaxNumber","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/space"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/changeLeftTextColor(color:at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/changeRightTextColor(color:at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/layoutSpecThatFits(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTConfigTextListNode"}],"title":"GTConfigTextListNode","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTConfigTextListNode","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTConfigTextListNode"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/space":{"role":"symbol","title":"space","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"space"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"上下间距"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/space","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/space"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/iconfontSize":{"role":"symbol","title":"iconfontSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconfontSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/iconfontSize","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/iconfontsize"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/leftActionClsore":{"role":"symbol","title":"leftActionClsore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftActionClsore"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ())?"}],"abstract":[{"type":"text","text":"事件回调"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/leftActionClsore","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/leftactionclsore"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/iconfontColor":{"role":"symbol","title":"iconfontColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconfontColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/iconfontColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/iconfontcolor"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/iconActionClsore":{"role":"symbol","title":"iconActionClsore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconActionClsore"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ())?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/iconActionClsore","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/iconactionclsore"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementAsciiArtProtocol":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementAsciiArtProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol"},"doc://org.cocoapods.GTUIKit/objc(cs)ASDisplayNode":{"type":"unresolvable","title":"ASDisplayNode","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/leftMaxNumber":{"role":"symbol","title":"leftMaxNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftMaxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/leftMaxNumber","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/leftmaxnumber"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/layoutSpecThatFits(_:)":{"role":"symbol","title":"layoutSpecThatFits(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSpecThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASSizeRange","preciseIdentifier":"c:@SA@ASSizeRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASLayoutSpec","preciseIdentifier":"c:objc(cs)ASLayoutSpec"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/layoutSpecThatFits(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSpecThatFits:"}],"url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/layoutspecthatfits(_:)"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/iconFontName":{"role":"symbol","title":"iconFontName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconFontName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/iconFontName","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/iconfontname"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTraitEnvironment":{"type":"unresolvable","title":"AsyncDisplayKit.ASTraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/init(coder:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/init(coder:)"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/rightActionClsore":{"role":"symbol","title":"rightActionClsore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightActionClsore"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ())?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/rightActionClsore","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/rightactionclsore"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/rightFont":{"role":"symbol","title":"rightFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/rightFont","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/rightfont"},"doc://org.cocoapods.GTUIKit/objc(pl)ASDebugNameProvider":{"type":"unresolvable","title":"AsyncDisplayKit.ASDebugNameProvider","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/rightColor":{"role":"symbol","title":"rightColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/rightColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/rightcolor"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementExtensibility":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementExtensibility","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/leftFont":{"role":"symbol","title":"leftFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/leftFont","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/leftfont"},"doc://org.cocoapods.GTUIKit/objc(pl)NSLocking":{"type":"unresolvable","title":"Foundation.NSLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/rightMaxNumber":{"role":"symbol","title":"rightMaxNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightMaxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/rightMaxNumber","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/rightmaxnumber"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLocking":{"type":"unresolvable","title":"AsyncDisplayKit.ASLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/changeLeftTextColor(color:at:)":{"role":"symbol","title":"changeLeftTextColor(color:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeLeftTextColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"修改左侧文本颜色"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/changeLeftTextColor(color:at:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/changelefttextcolor(color:at:)"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElement":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElement","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/changeRightTextColor(color:at:)":{"role":"symbol","title":"changeRightTextColor(color:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeRightTextColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"修改右侧文本颜色"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/changeRightTextColor(color:at:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/changerighttextcolor(color:at:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/init()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/datas":{"role":"symbol","title":"datas","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"datas"},{"kind":"text","text":": [("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"GTIconTextPosition","preciseIdentifier":"s:7GTUIKit18GTIconTextPositionO"},{"kind":"text","text":")]"}],"abstract":[{"type":"text","text":"最后赋值(左侧文字, 右侧文字, 图标位置)"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/datas","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/datas"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementStylability":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementStylability","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode":{"role":"symbol","title":"GTConfigTextListNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTConfigTextListNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTConfigTextListNode"}],"url":"\/documentation\/gtuikit\/gtconfigtextlistnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTConfigTextListNode/leftColor":{"role":"symbol","title":"leftColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/leftColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtconfigtextlistnode\/leftcolor"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)ASInterfaceStateDelegate":{"type":"unresolvable","title":"AsyncDisplayKit.ASInterfaceStateDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTConfigTextListNode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTConfigTextListNode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTConfigTextListNode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/init()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTConfigTextListNode\/layoutSpecThatFits(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTConfigTextListNode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ASDisplayNode","preciseIdentifier":"c:objc(cs)ASDisplayNode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTConfigTextListNode~1layoutSpecThatFits(_:)\/title","value":"layoutSpecThatFits:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTConfigTextListNode~1layoutSpecThatFits(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSpecThatFits:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTConfigTextListNode~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTConfigTextListNode~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTConfigTextListNode\/title","value":"GTConfigTextListNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTConfigTextListNode\/fragments","value":[{"kind":"identifier","text":"GTConfigTextListNode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}