{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDropdownView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtdropdownview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtdropdownview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/init(style:title:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/intrinsicContentSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/isShowDropMenuPopView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/onTapBlock","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/style-swift.property","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/title"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/Style-swift.enum"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDropdownView"}],"title":"GTDropdownView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTDropdownView","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTDropdownView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView/style-swift.property":{"role":"symbol","title":"style","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTDropdownView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTDropdownView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:7GTUIKit14GTDropdownViewC5StyleO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/style-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtdropdownview\/style-swift.property"},"doc://org.cocoapods.GTUIKit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/9PinLayout14SizeCalculableP":{"type":"unresolvable","title":"PinLayout.SizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyType":{"role":"symbol","title":"GTEmptyType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyType"}],"url":"\/documentation\/gtuikit\/gtemptytype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView/isShowDropMenuPopView":{"role":"symbol","title":"isShowDropMenuPopView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShowDropMenuPopView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/isShowDropMenuPopView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtdropdownview\/isshowdropmenupopview"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView/intrinsicContentSize":{"role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/intrinsicContentSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/gtuikit\/gtdropdownview\/intrinsiccontentsize"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/9PinLayout18AutoSizeCalculableP":{"type":"unresolvable","title":"PinLayout.AutoSizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/12SkeletonView0aB8ExtendedP":{"type":"unresolvable","title":"SkeletonView.SkeletonViewExtended","identifier":"doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView/onTapBlock":{"role":"symbol","title":"onTapBlock","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTapBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"GTDropdownView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTDropdownView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/onTapBlock","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtdropdownview\/ontapblock"},"doc://org.cocoapods.GTUIKit/9PinLayout10LayoutableP":{"type":"unresolvable","title":"PinLayout.Layoutable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.GTUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView/Style-swift.enum":{"role":"symbol","title":"GTDropdownView.Style","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/Style-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/gtuikit\/gtdropdownview\/style-swift.enum"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/title","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtdropdownview\/title"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView":{"role":"symbol","title":"GTDropdownView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDropdownView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTDropdownView"}],"url":"\/documentation\/gtuikit\/gtdropdownview"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDropdownView/init(style:title:)":{"role":"symbol","title":"init(style:title:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTDropdownView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTDropdownView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:7GTUIKit14GTDropdownViewC5StyleO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/init(style:title:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtdropdownview\/init(style:title:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTDropdownView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTDropdownView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTDropdownView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDropdownView\/intrinsicContentSize"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDropdownView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownView~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownView~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownView\/title","value":"GTDropdownView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDropdownView\/fragments","value":[{"kind":"identifier","text":"GTDropdownView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}