{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmpty"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtempty"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyV3"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty\/init(view:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty\/hidden()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty\/show(_:bottomButtonTap:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty\/showNoData(sence:title:message:btnTitle:topOffset:centerOffset:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty\/normalConfig"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmpty"}],"title":"GTEmpty","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:7GTUIKit7GTEmptyC","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTEmpty"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"seeAlsoSections":[{"title":"基础组件","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonTheme","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBadgeView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSlider","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitch","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitchV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPaginationViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3"],"generated":true}],"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover":{"role":"symbol","title":"GTPopover","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopover"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopover"}],"url":"\/documentation\/gtuikit\/gtpopover"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmpty/normalConfig":{"role":"symbol","title":"normalConfig","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTEmptyConfig","preciseIdentifier":"s:7GTUIKit13GTEmptyConfigV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty\/normalConfig","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtempty\/normalconfig"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmpty/init(view:)":{"role":"symbol","title":"init(view:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty\/init(view:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtempty\/init(view:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBadgeView":{"role":"symbol","title":"GTBadgeView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBadgeView"}],"abstract":[{"type":"text","text":"徽标提供及时、重要的信息提示。"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBadgeView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTBadgeView"}],"url":"\/documentation\/gtuikit\/gtbadgeview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTButtonV3":{"role":"symbol","title":"GTButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTButtonV3"}],"url":"\/documentation\/gtuikit\/gtbuttonv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBox":{"role":"symbol","title":"GTCheckBox","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBox"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBox"}],"url":"\/documentation\/gtuikit\/gtcheckbox"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmpty/show(_:bottomButtonTap:)":{"role":"symbol","title":"show(_:bottomButtonTap:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTEmptyConfig","preciseIdentifier":"s:7GTUIKit13GTEmptyConfigV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomButtonTap"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"显示空白页"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty\/show(_:bottomButtonTap:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtempty\/show(_:bottombuttontap:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmpty/hidden()":{"role":"symbol","title":"hidden()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty\/hidden()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtempty\/hidden()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepViewV3":{"role":"symbol","title":"GTStepViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepViewV3"}],"url":"\/documentation\/gtuikit\/gtstepviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSwitch":{"role":"symbol","title":"GTSwitch","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSwitch"}],"abstract":[{"type":"text","text":"自定义Switch 通过枚举设置size，不需要外部再设置大小，"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSwitch"}],"url":"\/documentation\/gtuikit\/gtswitch"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarViewV3":{"role":"symbol","title":"GTSearchBarViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSearchBarViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSearchBarViewV3"}],"url":"\/documentation\/gtuikit\/gtsearchbarviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTButtonTheme":{"role":"symbol","title":"GTButtonTheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTButtonTheme"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTButtonTheme"}],"url":"\/documentation\/gtuikit\/gtbuttontheme"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarViewV3":{"role":"symbol","title":"GTAvatarViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAvatarViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAvatarViewV3"}],"url":"\/documentation\/gtuikit\/gtavatarviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmpty/showNoData(sence:title:message:btnTitle:topOffset:centerOffset:)":{"role":"symbol","title":"showNoData(sence:title:message:btnTitle:topOffset:centerOffset:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNoData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTEmptySence","preciseIdentifier":"s:7GTUIKit12GTEmptySenceO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"btnTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"topOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"centerOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"带NoDatas文案"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty\/showNoData(sence:title:message:btnTitle:topOffset:centerOffset:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtempty\/shownodata(sence:title:message:btntitle:topoffset:centeroffset:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading":{"role":"symbol","title":"GTLoading","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTLoading"}],"abstract":[{"type":"text","text":"Loding动画"},{"type":"text","text":" "},{"type":"text","text":"显示: "},{"type":"codeVoice","code":"view.loading.show()"},{"type":"text","text":" "},{"type":"text","text":"隐藏:"},{"type":"codeVoice","code":" view.loading.hidden()"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTLoading"}],"url":"\/documentation\/gtuikit\/gtloading"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewCellV3":{"role":"symbol","title":"GTTableViewCellV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTableViewCellV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTableViewCellV3"}],"url":"\/documentation\/gtuikit\/gttableviewcellv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopView":{"role":"symbol","title":"GTPopView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopView"}],"url":"\/documentation\/gtuikit\/gtpopview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSwitchV3":{"role":"symbol","title":"GTSwitchV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSwitchV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitchV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSwitchV3"}],"url":"\/documentation\/gtuikit\/gtswitchv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSlider":{"role":"symbol","title":"GTSlider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSlider"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSlider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSlider"}],"url":"\/documentation\/gtuikit\/gtslider"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPaginationViewV3":{"role":"symbol","title":"GTPaginationViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPaginationViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPaginationViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPaginationViewV3"}],"url":"\/documentation\/gtuikit\/gtpaginationviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmpty":{"role":"symbol","title":"GTEmpty","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmpty"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmpty"}],"url":"\/documentation\/gtuikit\/gtempty"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyV3":{"role":"symbol","title":"GTEmptyV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyV3"}],"url":"\/documentation\/gtuikit\/gtemptyv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxV3":{"role":"symbol","title":"GTCheckBoxV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBoxV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBoxV3"}],"url":"\/documentation\/gtuikit\/gtcheckboxv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldV3":{"role":"symbol","title":"GTTextFieldV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextFieldV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextFieldV3"}],"url":"\/documentation\/gtuikit\/gttextfieldv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover\/title","value":"GTPopover"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover\/fragments","value":[{"kind":"identifier","text":"GTPopover"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBadgeView\/title","value":"GTBadgeView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBadgeView\/fragments","value":[{"kind":"identifier","text":"GTBadgeView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTButtonV3\/title","value":"GTButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTButtonV3\/fragments","value":[{"kind":"identifier","text":"GTButtonV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBox\/title","value":"GTCheckBox"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBox\/fragments","value":[{"kind":"identifier","text":"GTCheckBox"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepViewV3\/title","value":"GTStepViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepViewV3\/fragments","value":[{"kind":"identifier","text":"GTStepViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitch\/title","value":"GTSwitch"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitch\/fragments","value":[{"kind":"identifier","text":"GTSwitch"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarViewV3\/title","value":"GTSearchBarViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarViewV3\/fragments","value":[{"kind":"identifier","text":"GTSearchBarViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarViewV3\/title","value":"GTAvatarViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarViewV3\/fragments","value":[{"kind":"identifier","text":"GTAvatarViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/title","value":"GTTableViewCellV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/fragments","value":[{"kind":"identifier","text":"GTTableViewCellV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopView\/title","value":"GTPopView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopView\/fragments","value":[{"kind":"identifier","text":"GTPopView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitchV3\/title","value":"GTSwitchV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitchV3\/fragments","value":[{"kind":"identifier","text":"GTSwitchV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSlider\/title","value":"GTSlider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSlider\/fragments","value":[{"kind":"identifier","text":"GTSlider"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPaginationViewV3\/title","value":"GTPaginationViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPaginationViewV3\/fragments","value":[{"kind":"identifier","text":"GTPaginationViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/title","value":"GTCheckBoxV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/fragments","value":[{"kind":"identifier","text":"GTCheckBoxV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldV3\/title","value":"GTTextFieldV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldV3\/fragments","value":[{"kind":"identifier","text":"GTTextFieldV3"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}