{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTInputFieldNode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtinputfieldnode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtinputfieldnode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode\/init(placeHolder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode\/text","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode\/textEdit"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode\/didLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTInputFieldNode"}],"title":"GTInputFieldNode","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTInputFieldNode","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTInputFieldNode"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTraitEnvironment":{"type":"unresolvable","title":"AsyncDisplayKit.ASTraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementStylability":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementStylability","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability"},"doc://org.cocoapods.GTUIKit/objc(pl)ASInterfaceStateDelegate":{"type":"unresolvable","title":"AsyncDisplayKit.ASInterfaceStateDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTInputFieldNode/init(placeHolder:)":{"role":"symbol","title":"init(placeHolder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"placeHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode\/init(placeHolder:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtinputfieldnode\/init(placeholder:)"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTInputFieldNode/textEdit":{"role":"symbol","title":"textEdit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textEdit"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode\/textEdit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtinputfieldnode\/textedit"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementAsciiArtProtocol":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementAsciiArtProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTInputFieldNode/didLoad()":{"role":"symbol","title":"didLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode\/didLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didLoad"}],"url":"\/documentation\/gtuikit\/gtinputfieldnode\/didload()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTInputFieldNode":{"role":"symbol","title":"GTInputFieldNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTInputFieldNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTInputFieldNode"}],"url":"\/documentation\/gtuikit\/gtinputfieldnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTInputFieldNode/text":{"role":"symbol","title":"text","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode\/text","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtinputfieldnode\/text"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLocking":{"type":"unresolvable","title":"AsyncDisplayKit.ASLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElement":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElement","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementExtensibility":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementExtensibility","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/objc(pl)NSLocking":{"type":"unresolvable","title":"Foundation.NSLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/objc(pl)ASDebugNameProvider":{"type":"unresolvable","title":"AsyncDisplayKit.ASDebugNameProvider","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider"},"doc://org.cocoapods.GTUIKit/objc(cs)ASDisplayNode":{"type":"unresolvable","title":"ASDisplayNode","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTInputFieldNode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTInputFieldNode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTInputFieldNode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTInputFieldNode\/didLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTInputFieldNode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ASDisplayNode","preciseIdentifier":"c:objc(cs)ASDisplayNode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTInputFieldNode~1didLoad()\/title","value":"didLoad"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTInputFieldNode~1didLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTInputFieldNode\/title","value":"GTInputFieldNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTInputFieldNode\/fragments","value":[{"kind":"identifier","text":"GTInputFieldNode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}