{"seeAlsoSections":[{"title":"基础组件","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonTheme","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBadgeView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSlider","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitch","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitchV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPaginationViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTLoading"}],"title":"GTLoading","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:7GTUIKit9GTLoadingC","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTLoading"}]},"abstract":[{"type":"text","text":"Loding动画"},{"type":"text","text":" "},{"type":"text","text":"显示: "},{"type":"codeVoice","code":"view.loading.show()"},{"type":"text","text":" "},{"type":"text","text":"隐藏:"},{"type":"codeVoice","code":" view.loading.hidden()"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoadingAnimationType"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/init(view:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/hiddenDuration","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/isLoading","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/isUserInteractionEnabled","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/loadingBackgroundView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/offset"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/hidden()-swift.method","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/hiddenWhitOutDelay()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/show(isInteractionEnabled:duration:hiddenWhenOtherShow:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/notificationNameHidden","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/notificationNameHiddenAll","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/notificationNameShow"]},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/hidden()-swift.type.method","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/hiddenAll()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/show(isInteractionEnabled:duration:)-swift.type.method"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/GTLoadingAnimationType-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/gtuikit\/gtloading"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTLoading"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewCellV3":{"role":"symbol","title":"GTTableViewCellV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTableViewCellV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTableViewCellV3"}],"url":"\/documentation\/gtuikit\/gttableviewcellv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/show(isInteractionEnabled:duration:)-swift.type.method":{"role":"symbol","title":"show(isInteractionEnabled:duration:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isInteractionEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/show(isInteractionEnabled:duration:)-swift.type.method","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/show(isinteractionenabled:duration:)-swift.type.method"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/notificationNameHiddenAll":{"role":"symbol","title":"notificationNameHiddenAll","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationNameHiddenAll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/notificationNameHiddenAll","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/notificationnamehiddenall"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPaginationViewV3":{"role":"symbol","title":"GTPaginationViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPaginationViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPaginationViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPaginationViewV3"}],"url":"\/documentation\/gtuikit\/gtpaginationviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepViewV3":{"role":"symbol","title":"GTStepViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepViewV3"}],"url":"\/documentation\/gtuikit\/gtstepviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoadingAnimationType":{"role":"symbol","title":"GTLoadingAnimationType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTLoadingAnimationType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoadingAnimationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTLoadingAnimationType"}],"url":"\/documentation\/gtuikit\/gtloadinganimationtype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldV3":{"role":"symbol","title":"GTTextFieldV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextFieldV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextFieldV3"}],"url":"\/documentation\/gtuikit\/gttextfieldv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover":{"role":"symbol","title":"GTPopover","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopover"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopover"}],"url":"\/documentation\/gtuikit\/gtpopover"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSwitch":{"role":"symbol","title":"GTSwitch","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSwitch"}],"abstract":[{"type":"text","text":"自定义Switch 通过枚举设置size，不需要外部再设置大小，"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSwitch"}],"url":"\/documentation\/gtuikit\/gtswitch"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/hidden()-swift.method":{"role":"symbol","title":"hidden()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/hidden()-swift.method","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/hidden()-swift.method"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/notificationNameShow":{"role":"symbol","title":"notificationNameShow","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationNameShow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/notificationNameShow","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/notificationnameshow"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBox":{"role":"symbol","title":"GTCheckBox","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBox"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBox"}],"url":"\/documentation\/gtuikit\/gtcheckbox"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSlider":{"role":"symbol","title":"GTSlider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSlider"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSlider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSlider"}],"url":"\/documentation\/gtuikit\/gtslider"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/loadingBackgroundView":{"role":"symbol","title":"loadingBackgroundView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadingBackgroundView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/loadingBackgroundView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/loadingbackgroundview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/hidden()-swift.type.method":{"role":"symbol","title":"hidden()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/hidden()-swift.type.method","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/hidden()-swift.type.method"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/init(view:)":{"role":"symbol","title":"init(view:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/init(view:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/init(view:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSwitchV3":{"role":"symbol","title":"GTSwitchV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSwitchV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitchV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSwitchV3"}],"url":"\/documentation\/gtuikit\/gtswitchv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/isLoading":{"role":"symbol","title":"isLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/isLoading","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/isloading"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxV3":{"role":"symbol","title":"GTCheckBoxV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBoxV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBoxV3"}],"url":"\/documentation\/gtuikit\/gtcheckboxv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/offset":{"role":"symbol","title":"offset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/offset","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/offset"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/show(isInteractionEnabled:duration:hiddenWhenOtherShow:)":{"role":"symbol","title":"show(isInteractionEnabled:duration:hiddenWhenOtherShow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isInteractionEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hiddenWhenOtherShow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"显示loading"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/show(isInteractionEnabled:duration:hiddenWhenOtherShow:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/show(isinteractionenabled:duration:hiddenwhenothershow:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBadgeView":{"role":"symbol","title":"GTBadgeView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBadgeView"}],"abstract":[{"type":"text","text":"徽标提供及时、重要的信息提示。"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBadgeView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTBadgeView"}],"url":"\/documentation\/gtuikit\/gtbadgeview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/hiddenDuration":{"role":"symbol","title":"hiddenDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/hiddenDuration","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/hiddenduration"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarViewV3":{"role":"symbol","title":"GTSearchBarViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSearchBarViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSearchBarViewV3"}],"url":"\/documentation\/gtuikit\/gtsearchbarviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/hiddenWhitOutDelay()":{"role":"symbol","title":"hiddenWhitOutDelay()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenWhitOutDelay"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/hiddenWhitOutDelay()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/hiddenwhitoutdelay()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarViewV3":{"role":"symbol","title":"GTAvatarViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAvatarViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAvatarViewV3"}],"url":"\/documentation\/gtuikit\/gtavatarviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmpty":{"role":"symbol","title":"GTEmpty","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmpty"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmpty"}],"url":"\/documentation\/gtuikit\/gtempty"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTButtonV3":{"role":"symbol","title":"GTButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTButtonV3"}],"url":"\/documentation\/gtuikit\/gtbuttonv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopView":{"role":"symbol","title":"GTPopView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopView"}],"url":"\/documentation\/gtuikit\/gtpopview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyV3":{"role":"symbol","title":"GTEmptyV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyV3"}],"url":"\/documentation\/gtuikit\/gtemptyv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/GTLoadingAnimationType-Implementations":{"role":"collectionGroup","title":"GTLoadingAnimationType Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/GTLoadingAnimationType-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/gtloadinganimationtype-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading":{"role":"symbol","title":"GTLoading","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTLoading"}],"abstract":[{"type":"text","text":"Loding动画"},{"type":"text","text":" "},{"type":"text","text":"显示: "},{"type":"codeVoice","code":"view.loading.show()"},{"type":"text","text":" "},{"type":"text","text":"隐藏:"},{"type":"codeVoice","code":" view.loading.hidden()"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTLoading"}],"url":"\/documentation\/gtuikit\/gtloading"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/hiddenAll()":{"role":"symbol","title":"hiddenAll()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenAll"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/hiddenAll()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/hiddenall()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/notificationNameHidden":{"role":"symbol","title":"notificationNameHidden","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationNameHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/notificationNameHidden","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/notificationnamehidden"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading/isUserInteractionEnabled":{"role":"symbol","title":"isUserInteractionEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserInteractionEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading\/isUserInteractionEnabled","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtloading\/isuserinteractionenabled"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTButtonTheme":{"role":"symbol","title":"GTButtonTheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTButtonTheme"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTButtonTheme"}],"url":"\/documentation\/gtuikit\/gtbuttontheme"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/title","value":"GTTableViewCellV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/fragments","value":[{"kind":"identifier","text":"GTTableViewCellV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPaginationViewV3\/title","value":"GTPaginationViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPaginationViewV3\/fragments","value":[{"kind":"identifier","text":"GTPaginationViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepViewV3\/title","value":"GTStepViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepViewV3\/fragments","value":[{"kind":"identifier","text":"GTStepViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldV3\/title","value":"GTTextFieldV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldV3\/fragments","value":[{"kind":"identifier","text":"GTTextFieldV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover\/title","value":"GTPopover"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover\/fragments","value":[{"kind":"identifier","text":"GTPopover"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitch\/title","value":"GTSwitch"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitch\/fragments","value":[{"kind":"identifier","text":"GTSwitch"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBox\/title","value":"GTCheckBox"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBox\/fragments","value":[{"kind":"identifier","text":"GTCheckBox"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSlider\/title","value":"GTSlider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSlider\/fragments","value":[{"kind":"identifier","text":"GTSlider"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitchV3\/title","value":"GTSwitchV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitchV3\/fragments","value":[{"kind":"identifier","text":"GTSwitchV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/title","value":"GTCheckBoxV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/fragments","value":[{"kind":"identifier","text":"GTCheckBoxV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBadgeView\/title","value":"GTBadgeView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBadgeView\/fragments","value":[{"kind":"identifier","text":"GTBadgeView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarViewV3\/title","value":"GTSearchBarViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarViewV3\/fragments","value":[{"kind":"identifier","text":"GTSearchBarViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarViewV3\/title","value":"GTAvatarViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarViewV3\/fragments","value":[{"kind":"identifier","text":"GTAvatarViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTButtonV3\/title","value":"GTButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTButtonV3\/fragments","value":[{"kind":"identifier","text":"GTButtonV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopView\/title","value":"GTPopView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopView\/fragments","value":[{"kind":"identifier","text":"GTPopView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}