{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopover"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtpopover"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtpopover"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/init()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/init(options:showHandler:dismissHandler:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/init(showHandler:dismissHandler:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/animationIn","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/animationOut","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/arrowSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/blackOverlay","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/blackOverlayColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/borderColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/cornerRadius","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/didDismissHandler","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/didShowHandler","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/dismissOnBlackOverlayTap","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/highlightCornerRadius","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/highlightFromView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/initialSpringVelocity","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/overlayBlur","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/popoverColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/popoverType","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/showBlackOverlay","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/sideEdge","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/sideOffset","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/springDamping","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/willDismissHandler","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/willShowHandler"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/accessibilityPerformEscape()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/dismiss()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/draw(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/layoutSubviews()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/show(_:fromView:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/show(_:fromView:inView:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/show(_:point:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/show(_:point:inView:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/showAsDialog(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/showAsDialog(_:inView:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopover"}],"title":"GTPopover","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTPopover","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTPopover"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"seeAlsoSections":[{"title":"基础组件","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonTheme","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBadgeView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSlider","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitch","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitchV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPaginationViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3"],"generated":true}],"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/blackOverlay":{"role":"symbol","title":"blackOverlay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blackOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/blackOverlay","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/blackoverlay"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/draw(_:)":{"role":"symbol","title":"draw(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/draw(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawRect:"}],"url":"\/documentation\/gtuikit\/gtpopover\/draw(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBox":{"role":"symbol","title":"GTCheckBox","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBox"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBox"}],"url":"\/documentation\/gtuikit\/gtcheckbox"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/showBlackOverlay":{"role":"symbol","title":"showBlackOverlay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showBlackOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/showBlackOverlay","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/showblackoverlay"},"doc://org.cocoapods.GTUIKit/9PinLayout10LayoutableP":{"type":"unresolvable","title":"PinLayout.Layoutable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP"},"doc://org.cocoapods.GTUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/popoverColor":{"role":"symbol","title":"popoverColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"popoverColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/popoverColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/popovercolor"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewCellV3":{"role":"symbol","title":"GTTableViewCellV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTableViewCellV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTableViewCellV3"}],"url":"\/documentation\/gtuikit\/gttableviewcellv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarViewV3":{"role":"symbol","title":"GTAvatarViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAvatarViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAvatarViewV3"}],"url":"\/documentation\/gtuikit\/gtavatarviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/init(showHandler:dismissHandler:)":{"role":"symbol","title":"init(showHandler:dismissHandler:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"showHandler"},{"kind":"text","text":": (() -> ())?, "},{"kind":"externalParam","text":"dismissHandler"},{"kind":"text","text":": (() -> ())?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/init(showHandler:dismissHandler:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/init(showhandler:dismisshandler:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/gtuikit\/gtpopover\/layoutsubviews()"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTLoading":{"role":"symbol","title":"GTLoading","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTLoading"}],"abstract":[{"type":"text","text":"Loding动画"},{"type":"text","text":" "},{"type":"text","text":"显示: "},{"type":"codeVoice","code":"view.loading.show()"},{"type":"text","text":" "},{"type":"text","text":"隐藏:"},{"type":"codeVoice","code":" view.loading.hidden()"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTLoading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTLoading"}],"url":"\/documentation\/gtuikit\/gtloading"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/borderColor":{"role":"symbol","title":"borderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/borderColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/bordercolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/highlightFromView":{"role":"symbol","title":"highlightFromView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightFromView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/highlightFromView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/highlightfromview"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/arrowSize":{"role":"symbol","title":"arrowSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"arrowSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/arrowSize","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/arrowsize"},"doc://org.cocoapods.GTUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/animationIn":{"role":"symbol","title":"animationIn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/animationIn","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/animationin"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarViewV3":{"role":"symbol","title":"GTSearchBarViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSearchBarViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSearchBarViewV3"}],"url":"\/documentation\/gtuikit\/gtsearchbarviewv3"},"doc://org.cocoapods.GTUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/sideEdge":{"role":"symbol","title":"sideEdge","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sideEdge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/sideEdge","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/sideedge"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyV3":{"role":"symbol","title":"GTEmptyV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyV3"}],"url":"\/documentation\/gtuikit\/gtemptyv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTButtonTheme":{"role":"symbol","title":"GTButtonTheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTButtonTheme"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTButtonTheme"}],"url":"\/documentation\/gtuikit\/gtbuttontheme"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/show(_:point:inView:)":{"role":"symbol","title":"show(_:point:inView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/show(_:point:inView:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/show(_:point:inview:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/springDamping":{"role":"symbol","title":"springDamping","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"springDamping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/springDamping","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/springdamping"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPaginationViewV3":{"role":"symbol","title":"GTPaginationViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPaginationViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPaginationViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPaginationViewV3"}],"url":"\/documentation\/gtuikit\/gtpaginationviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSwitch":{"role":"symbol","title":"GTSwitch","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSwitch"}],"abstract":[{"type":"text","text":"自定义Switch 通过枚举设置size，不需要外部再设置大小，"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSwitch"}],"url":"\/documentation\/gtuikit\/gtswitch"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/showAsDialog(_:inView:)":{"role":"symbol","title":"showAsDialog(_:inView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAsDialog"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/showAsDialog(_:inView:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/showasdialog(_:inview:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/highlightCornerRadius":{"role":"symbol","title":"highlightCornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightCornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/highlightCornerRadius","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/highlightcornerradius"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTButtonV3":{"role":"symbol","title":"GTButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTButtonV3"}],"url":"\/documentation\/gtuikit\/gtbuttonv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/gtuikit\/gtpopover\/init(coder:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/gtuikit\/gtpopover\/init()"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.GTUIKit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/dismissOnBlackOverlayTap":{"role":"symbol","title":"dismissOnBlackOverlayTap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissOnBlackOverlayTap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/dismissOnBlackOverlayTap","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/dismissonblackoverlaytap"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/cornerRadius":{"role":"symbol","title":"cornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/cornerRadius","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/cornerradius"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.GTUIKit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.GTUIKit/9PinLayout18AutoSizeCalculableP":{"type":"unresolvable","title":"PinLayout.AutoSizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxV3":{"role":"symbol","title":"GTCheckBoxV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBoxV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBoxV3"}],"url":"\/documentation\/gtuikit\/gtcheckboxv3"},"doc://org.cocoapods.GTUIKit/9PinLayout14SizeCalculableP":{"type":"unresolvable","title":"PinLayout.SizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyType":{"role":"symbol","title":"GTEmptyType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyType"}],"url":"\/documentation\/gtuikit\/gtemptytype"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/didShowHandler":{"role":"symbol","title":"didShowHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didShowHandler"},{"kind":"text","text":": (() -> ())?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/didShowHandler","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/didshowhandler"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/didDismissHandler":{"role":"symbol","title":"didDismissHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismissHandler"},{"kind":"text","text":": (() -> ())?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/didDismissHandler","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/diddismisshandler"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmpty":{"role":"symbol","title":"GTEmpty","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmpty"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmpty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmpty"}],"url":"\/documentation\/gtuikit\/gtempty"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBadgeView":{"role":"symbol","title":"GTBadgeView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBadgeView"}],"abstract":[{"type":"text","text":"徽标提供及时、重要的信息提示。"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBadgeView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTBadgeView"}],"url":"\/documentation\/gtuikit\/gtbadgeview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/sideOffset":{"role":"symbol","title":"sideOffset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sideOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/sideOffset","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/sideoffset"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSlider":{"role":"symbol","title":"GTSlider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSlider"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSlider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSlider"}],"url":"\/documentation\/gtuikit\/gtslider"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/showAsDialog(_:)":{"role":"symbol","title":"showAsDialog(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAsDialog"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/showAsDialog(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/showasdialog(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/show(_:fromView:inView:)":{"role":"symbol","title":"show(_:fromView:inView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/show(_:fromView:inView:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/show(_:fromview:inview:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSwitchV3":{"role":"symbol","title":"GTSwitchV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSwitchV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitchV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSwitchV3"}],"url":"\/documentation\/gtuikit\/gtswitchv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/willShowHandler":{"role":"symbol","title":"willShowHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"willShowHandler"},{"kind":"text","text":": (() -> ())?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/willShowHandler","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/willshowhandler"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/show(_:fromView:)":{"role":"symbol","title":"show(_:fromView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/show(_:fromView:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/show(_:fromview:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/accessibilityPerformEscape()":{"role":"symbol","title":"accessibilityPerformEscape()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityPerformEscape"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/accessibilityPerformEscape()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessibilityPerformEscape"}],"url":"\/documentation\/gtuikit\/gtpopover\/accessibilityperformescape()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/overlayBlur":{"role":"symbol","title":"overlayBlur","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayBlur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/overlayBlur","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/overlayblur"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/show(_:point:)":{"role":"symbol","title":"show(_:point:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/show(_:point:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/show(_:point:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopView":{"role":"symbol","title":"GTPopView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopView"}],"url":"\/documentation\/gtuikit\/gtpopview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldV3":{"role":"symbol","title":"GTTextFieldV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextFieldV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextFieldV3"}],"url":"\/documentation\/gtuikit\/gttextfieldv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/willDismissHandler":{"role":"symbol","title":"willDismissHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismissHandler"},{"kind":"text","text":": (() -> ())?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/willDismissHandler","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/willdismisshandler"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/blackOverlayColor":{"role":"symbol","title":"blackOverlayColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blackOverlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/blackOverlayColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/blackoverlaycolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/animationOut":{"role":"symbol","title":"animationOut","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationOut"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/animationOut","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/animationout"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/init(options:showHandler:dismissHandler:)":{"role":"symbol","title":"init(options:showHandler:dismissHandler:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTPopoverOption","preciseIdentifier":"s:7GTUIKit15GTPopoverOptionO"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"showHandler"},{"kind":"text","text":": (() -> ())?, "},{"kind":"externalParam","text":"dismissHandler"},{"kind":"text","text":": (() -> ())?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/init(options:showHandler:dismissHandler:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/init(options:showhandler:dismisshandler:)"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/dismiss()":{"role":"symbol","title":"dismiss()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/dismiss()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismiss"}],"url":"\/documentation\/gtuikit\/gtpopover\/dismiss()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepViewV3":{"role":"symbol","title":"GTStepViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepViewV3"}],"url":"\/documentation\/gtuikit\/gtstepviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover":{"role":"symbol","title":"GTPopover","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopover"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopover"}],"url":"\/documentation\/gtuikit\/gtpopover"},"doc://org.cocoapods.GTUIKit/12SkeletonView0aB8ExtendedP":{"type":"unresolvable","title":"SkeletonView.SkeletonViewExtended","identifier":"doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/initialSpringVelocity":{"role":"symbol","title":"initialSpringVelocity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialSpringVelocity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/initialSpringVelocity","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/initialspringvelocity"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopover/popoverType":{"role":"symbol","title":"popoverType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"popoverType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopoverPosition","preciseIdentifier":"s:7GTUIKit17GTPopoverPositionO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/popoverType","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopover\/popovertype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTPopover"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTPopover"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTPopover"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/accessibilityPerformEscape()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/dismiss()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/draw(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/init()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopover\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"基础组件","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBadgeView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSlider","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitch","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSwitchV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPaginationViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopover"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1draw(_:)\/title","value":"drawRect:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1draw(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBox\/title","value":"GTCheckBox"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBox\/fragments","value":[{"kind":"identifier","text":"GTCheckBox"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/title","value":"GTTableViewCellV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/fragments","value":[{"kind":"identifier","text":"GTTableViewCellV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarViewV3\/title","value":"GTAvatarViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarViewV3\/fragments","value":[{"kind":"identifier","text":"GTAvatarViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarViewV3\/title","value":"GTSearchBarViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarViewV3\/fragments","value":[{"kind":"identifier","text":"GTSearchBarViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPaginationViewV3\/title","value":"GTPaginationViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPaginationViewV3\/fragments","value":[{"kind":"identifier","text":"GTPaginationViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitch\/title","value":"GTSwitch"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitch\/fragments","value":[{"kind":"identifier","text":"GTSwitch"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTButtonV3\/title","value":"GTButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTButtonV3\/fragments","value":[{"kind":"identifier","text":"GTButtonV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/title","value":"GTCheckBoxV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/fragments","value":[{"kind":"identifier","text":"GTCheckBoxV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBadgeView\/title","value":"GTBadgeView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBadgeView\/fragments","value":[{"kind":"identifier","text":"GTBadgeView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSlider\/title","value":"GTSlider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSlider\/fragments","value":[{"kind":"identifier","text":"GTSlider"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitchV3\/title","value":"GTSwitchV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSwitchV3\/fragments","value":[{"kind":"identifier","text":"GTSwitchV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1accessibilityPerformEscape()\/title","value":"accessibilityPerformEscape"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1accessibilityPerformEscape()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityPerformEscape"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopView\/title","value":"GTPopView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopView\/fragments","value":[{"kind":"identifier","text":"GTPopView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldV3\/title","value":"GTTextFieldV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldV3\/fragments","value":[{"kind":"identifier","text":"GTTextFieldV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1dismiss()\/title","value":"dismiss"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover~1dismiss()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismiss"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepViewV3\/title","value":"GTStepViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepViewV3\/fragments","value":[{"kind":"identifier","text":"GTStepViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover\/title","value":"GTPopover"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopover\/fragments","value":[{"kind":"identifier","text":"GTPopover"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}