{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSkeletionMiniUnitType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtskeletionminiunittype"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionItemV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCustomButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTKeyboardItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIIconfontButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINormalSegmentItemView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/SWNavigationButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ZFSliderButton"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSkeletionMiniUnitType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSkeletionMiniUnitType"}],"title":"GTSkeletionMiniUnitType","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit23GTSkeletionMiniUnitTypeP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTSkeletionMiniUnitType"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBox":{"role":"symbol","title":"GTCheckBox","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBox"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBox"}],"url":"\/documentation\/gtuikit\/gtcheckbox"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNavigationItem":{"role":"symbol","title":"GTNavigationItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNavigationItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNavigationItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNavigationItem"}],"url":"\/documentation\/gtuikit\/gtnavigationitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTThirdlySegmentItemViewV3":{"role":"symbol","title":"GTThirdlySegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTThirdlySegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTThirdlySegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtthirdlysegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCustomButton":{"role":"symbol","title":"GTCustomButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCustomButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCustomButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCustomButton"}],"url":"\/documentation\/gtuikit\/gtcustombutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxV3":{"role":"symbol","title":"GTCheckBoxV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBoxV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBoxV3"}],"url":"\/documentation\/gtuikit\/gtcheckboxv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCardSegmentItemViewV3":{"role":"symbol","title":"GTCardSegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCardSegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCardSegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtcardsegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPrimarySegmentItemViewV3":{"role":"symbol","title":"GTPrimarySegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPrimarySegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPrimarySegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtprimarysegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTButtonV3":{"role":"symbol","title":"GTButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTButtonV3"}],"url":"\/documentation\/gtuikit\/gtbuttonv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/SWNavigationButton":{"role":"symbol","title":"SWNavigationButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SWNavigationButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/SWNavigationButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SWNavigationButton"}],"url":"\/documentation\/gtuikit\/swnavigationbutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ZFSliderButton":{"role":"symbol","title":"ZFSliderButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZFSliderButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ZFSliderButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZFSliderButton"}],"url":"\/documentation\/gtuikit\/zfsliderbutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionItem":{"role":"symbol","title":"GTActionItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTActionItem"}],"abstract":[{"type":"text","text":"GTActionSheetView 按钮"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTActionItem"}],"url":"\/documentation\/gtuikit\/gtactionitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTKeyboardItem":{"role":"symbol","title":"GTKeyboardItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTKeyboardItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTKeyboardItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTKeyboardItem"}],"url":"\/documentation\/gtuikit\/gtkeyboarditem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionItemV3":{"role":"symbol","title":"GTActionItemV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTActionItemV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionItemV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTActionItemV3"}],"url":"\/documentation\/gtuikit\/gtactionitemv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUINormalSegmentItemView":{"role":"symbol","title":"GTUINormalSegmentItemView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUINormalSegmentItemView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINormalSegmentItemView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUINormalSegmentItemView"}],"url":"\/documentation\/gtuikit\/gtuinormalsegmentitemview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3":{"role":"symbol","title":"GTUIButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIButtonV3"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView":{"role":"symbol","title":"TagView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagView"}],"url":"\/documentation\/gtuikit\/tagview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSkeletionMiniUnitType":{"role":"symbol","title":"GTSkeletionMiniUnitType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSkeletionMiniUnitType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSkeletionMiniUnitType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSkeletionMiniUnitType"}],"url":"\/documentation\/gtuikit\/gtskeletionminiunittype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSecondarySegmentItemViewV3":{"role":"symbol","title":"GTSecondarySegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSecondarySegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSecondarySegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtsecondarysegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIIconfontButton":{"role":"symbol","title":"GTUIIconfontButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIIconfontButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIIconfontButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIIconfontButton"}],"url":"\/documentation\/gtuikit\/gtuiiconfontbutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButton":{"role":"symbol","title":"GTUIButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIButton"}],"url":"\/documentation\/gtuikit\/gtuibutton"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBox\/title","value":"GTCheckBox"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBox\/fragments","value":[{"kind":"identifier","text":"GTCheckBox"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNavigationItem\/title","value":"GTNavigationItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNavigationItem\/fragments","value":[{"kind":"identifier","text":"GTNavigationItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTThirdlySegmentItemViewV3\/title","value":"GTThirdlySegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTThirdlySegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTThirdlySegmentItemViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCustomButton\/title","value":"GTCustomButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCustomButton\/fragments","value":[{"kind":"identifier","text":"GTCustomButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/title","value":"GTCheckBoxV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/fragments","value":[{"kind":"identifier","text":"GTCheckBoxV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCardSegmentItemViewV3\/title","value":"GTCardSegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCardSegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTCardSegmentItemViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPrimarySegmentItemViewV3\/title","value":"GTPrimarySegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPrimarySegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTPrimarySegmentItemViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTButtonV3\/title","value":"GTButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTButtonV3\/fragments","value":[{"kind":"identifier","text":"GTButtonV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1SWNavigationButton\/title","value":"SWNavigationButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1SWNavigationButton\/fragments","value":[{"kind":"identifier","text":"SWNavigationButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionItem\/title","value":"GTActionItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionItem\/fragments","value":[{"kind":"identifier","text":"GTActionItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTKeyboardItem\/title","value":"GTKeyboardItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTKeyboardItem\/fragments","value":[{"kind":"identifier","text":"GTKeyboardItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionItemV3\/title","value":"GTActionItemV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionItemV3\/fragments","value":[{"kind":"identifier","text":"GTActionItemV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINormalSegmentItemView\/title","value":"GTUINormalSegmentItemView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINormalSegmentItemView\/fragments","value":[{"kind":"identifier","text":"GTUINormalSegmentItemView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/title","value":"GTUIButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/fragments","value":[{"kind":"identifier","text":"GTUIButtonV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView\/title","value":"TagView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView\/fragments","value":[{"kind":"identifier","text":"TagView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSecondarySegmentItemViewV3\/title","value":"GTSecondarySegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSecondarySegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTSecondarySegmentItemViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIIconfontButton\/title","value":"GTUIIconfontButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIIconfontButton\/fragments","value":[{"kind":"identifier","text":"GTUIIconfontButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButton\/title","value":"GTUIButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButton\/fragments","value":[{"kind":"identifier","text":"GTUIButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}