{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentTransitionContext"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmenttransitioncontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuisegmenttransitioncontext"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIViewControllerContextTransitioning"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/init(fromViewController:toViewController:containerViewController:containerView:fromIndex:toIndex:delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/delegate","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/fromIndex","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/toIndex","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/transitionPercent"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/start(_:)-4fzh4","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/start(_:)-mnk6"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/UIViewControllerContextTransitioning-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentTransitionContext"}],"title":"GTUISegmentTransitionContext","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTUISegmentTransitionContext","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/start(_:)-mnk6":{"role":"symbol","title":"start(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTUISegmentSlideAnimationController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentSlideAnimationController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/start(_:)-mnk6","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/start(_:)-mnk6"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/toIndex":{"role":"symbol","title":"toIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"toIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/toIndex","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/toindex"},"doc://org.cocoapods.GTUIKit/objc(pl)UIViewControllerContextTransitioning":{"type":"unresolvable","title":"UIViewControllerContextTransitioning","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIViewControllerContextTransitioning"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/UIViewControllerContextTransitioning-Implementations":{"role":"collectionGroup","title":"UIViewControllerContextTransitioning Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/UIViewControllerContextTransitioning-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/uiviewcontrollercontexttransitioning-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext":{"role":"symbol","title":"GTUISegmentTransitionContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentTransitionContext"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}],"url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/start(_:)-4fzh4":{"role":"symbol","title":"start(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTUISegmentInteractiveTransition","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentInteractiveTransition"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/start(_:)-4fzh4","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/start(_:)-4fzh4"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/fromIndex":{"role":"symbol","title":"fromIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/fromIndex","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/fromindex"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/transitionPercent":{"role":"symbol","title":"transitionPercent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionPercent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/transitionPercent","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/transitionpercent"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/init(fromViewController:toViewController:containerViewController:containerView:fromIndex:toIndex:delegate:)":{"role":"symbol","title":"init(fromViewController:toViewController:containerViewController:containerView:fromIndex:toIndex:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"toViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"containerViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"containerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"fromIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"toIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentTransitionContextDelegate","preciseIdentifier":"s:7GTUIKit36GTUISegmentTransitionContextDelegateP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/init(fromViewController:toViewController:containerViewController:containerView:fromIndex:toIndex:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/init(fromviewcontroller:toviewcontroller:containerviewcontroller:containerview:fromindex:toindex:delegate:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentTransitionContext/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentTransitionContextDelegate","preciseIdentifier":"s:7GTUIKit36GTUISegmentTransitionContextDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmenttransitioncontext\/delegate"},"doc://org.cocoapods.GTUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTUISegmentTransitionContext"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentTransitionContext\/UIViewControllerContextTransitioning-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIViewControllerContextTransitioning"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentTransitionContext"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionContext\/title","value":"GTUISegmentTransitionContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentTransitionContext\/fragments","value":[{"kind":"identifier","text":"GTUISegmentTransitionContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}