{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionItem"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/background","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/compositor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/footer","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/header","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/headerZIndex","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/sectionFooterDimension","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/sectionHeaderDimension","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/sectionMargin","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/sectionPadding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/stick"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"title":"GTUIFallLayoutSectionBaseItem","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutSectionBaseItem","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem":{"role":"symbol","title":"GTUICollectionViewSectionItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewSectionItem"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/init()"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/sectionMargin":{"role":"symbol","title":"sectionMargin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sectionMargin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/sectionMargin","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/sectionmargin"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem":{"role":"symbol","title":"GTUIFallLayoutSectionBaseItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/sectionPadding":{"role":"symbol","title":"sectionPadding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sectionPadding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/sectionPadding","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/sectionpadding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/headerZIndex":{"role":"symbol","title":"headerZIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerZIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutZIndex","preciseIdentifier":"s:7GTUIKit20GTUIFallLayoutZIndexO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/headerZIndex","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/headerzindex"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/compositor":{"role":"symbol","title":"compositor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"compositor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutCompositor","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutCompositor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/compositor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/compositor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/sectionFooterDimension":{"role":"symbol","title":"sectionFooterDimension","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sectionFooterDimension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/sectionFooterDimension","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/sectionfooterdimension"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/background":{"role":"symbol","title":"background","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutBackground","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutBackground"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/background","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/background"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/sectionHeaderDimension":{"role":"symbol","title":"sectionHeaderDimension","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sectionHeaderDimension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/sectionHeaderDimension","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/sectionheaderdimension"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/footer":{"role":"symbol","title":"footer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutFooter","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutFooter"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/footer","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/footer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol":{"role":"symbol","title":"GTUICollectionViewSectionItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItemProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewSectionItemProtocol"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionItem":{"role":"symbol","title":"GTUIFallLayoutSectionItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutSectionItem"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutsectionitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/stick":{"role":"symbol","title":"stick","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/stick","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/stick"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem/header":{"role":"symbol","title":"header","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"header"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutHeader","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutHeader"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/header","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem\/header"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTUIFallLayoutSectionBaseItem"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionItem"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUICollectionViewSectionItem","text":"GTUICollectionViewSectionItem"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewSectionItem\/title","value":"GTUICollectionViewSectionItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewSectionItem\/fragments","value":[{"kind":"identifier","text":"GTUICollectionViewSectionItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/title","value":"GTUIFallLayoutSectionBaseItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionItem\/title","value":"GTUIFallLayoutSectionItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionItem\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}