{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuirefreshheaderconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuirefreshheaderconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/animationJSON","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/backgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/height","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/hiddenTextLabel","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/idleAttributedString","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/imageWithTitleSpace","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/layout","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/noMoreDataAttributedString","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/pullingAttributedString","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/refreshingAttributedString","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/willRefreshAttributedString"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}],"title":"GTUIRefreshHeaderConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTUIRefreshHeaderConfig","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/animationJSON":{"role":"symbol","title":"animationJSON","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationJSON"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"keyword","text":"Any"},{"kind":"text","text":">?"}],"abstract":[{"type":"text","text":"lottie-ios动画JSON"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/animationJSON","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/animationjson"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/hiddenTextLabel":{"role":"symbol","title":"hiddenTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"隐藏text内容"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/hiddenTextLabel","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/hiddentextlabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig":{"role":"symbol","title":"GTUIRefreshHeaderConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}],"url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/init()"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/pullingAttributedString":{"role":"symbol","title":"pullingAttributedString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pullingAttributedString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"下拉"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/pullingAttributedString","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/pullingattributedstring"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/backgroundColor":{"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"背景颜色"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/backgroundColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/backgroundcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/imageWithTitleSpace":{"role":"symbol","title":"imageWithTitleSpace","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageWithTitleSpace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"动画与文本间距"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/imageWithTitleSpace","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/imagewithtitlespace"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/layout":{"role":"symbol","title":"layout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIRefreshLayout","preciseIdentifier":"s:7GTUIKit17GTUIRefreshLayoutO"}],"abstract":[{"type":"text","text":"默认文本在下"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/layout","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/layout"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/height":{"role":"symbol","title":"height","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"视图图高度"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/height","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/height"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/willRefreshAttributedString":{"role":"symbol","title":"willRefreshAttributedString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"willRefreshAttributedString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"将要刷新"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/willRefreshAttributedString","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/willrefreshattributedstring"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/idleAttributedString":{"role":"symbol","title":"idleAttributedString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idleAttributedString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"闲置"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/idleAttributedString","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/idleattributedstring"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/refreshingAttributedString":{"role":"symbol","title":"refreshingAttributedString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshingAttributedString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"刷新中"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/refreshingAttributedString","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/refreshingattributedstring"},"doc://org.cocoapods.GTUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig/noMoreDataAttributedString":{"role":"symbol","title":"noMoreDataAttributedString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noMoreDataAttributedString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"没有更多数据"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/noMoreDataAttributedString","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig\/nomoredataattributedstring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTUIRefreshHeaderConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRefreshHeaderConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRefreshHeaderConfig\/title","value":"GTUIRefreshHeaderConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRefreshHeaderConfig\/fragments","value":[{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRefreshHeaderConfig~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRefreshHeaderConfig~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}