{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuitableviewcellitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuitableviewcellitem"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCellItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceTableViewCellItem"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItemProtocol","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/accessibilityIdentifier","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/cellClass","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/cellHeight","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/cellNib","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/cellTarget","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/identifier","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/target"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItem"}],"title":"GTUITableViewCellItem","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTUITableViewCellItem","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUITableViewCellItem"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem/accessibilityIdentifier":{"role":"symbol","title":"accessibilityIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"辨识符"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/accessibilityIdentifier","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewcellitem\/accessibilityidentifier"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/gtuikit\/gtuitableviewcellitem\/init"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem/cellClass":{"role":"symbol","title":"cellClass","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Cell类"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/cellClass","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewcellitem\/cellclass"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem/target":{"role":"symbol","title":"target","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"响应者"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/target","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewcellitem\/target"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem/cellNib":{"role":"symbol","title":"cellNib","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellNib"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"返回xib创建的nib"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/cellNib","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewcellitem\/cellnib"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewItemBaseProtocol":{"role":"symbol","title":"GTUITableViewItemBaseProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewItemBaseProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewItemBaseProtocol"}],"url":"\/documentation\/gtuikit\/gtuitableviewitembaseprotocol"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItemProtocol":{"role":"symbol","title":"GTUITableViewCellItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItemProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewCellItemProtocol"}],"url":"\/documentation\/gtuikit\/gtuitableviewcellitemprotocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem/identifier":{"role":"symbol","title":"identifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"重用标识符"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/identifier","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewcellitem\/identifier"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRoundRectCellItem":{"role":"symbol","title":"GTUIRoundRectCellItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRoundRectCellItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCellItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIRoundRectCellItem"}],"url":"\/documentation\/gtuikit\/gtuiroundrectcellitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem/cellTarget":{"role":"symbol","title":"cellTarget","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellTarget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUITableViewCellDelegate","preciseIdentifier":"s:7GTUIKit25GTUITableViewCellDelegateP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"响应者"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/cellTarget","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewcellitem\/celltarget"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISpaceTableViewCellItem":{"role":"symbol","title":"GTUISpaceTableViewCellItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISpaceTableViewCellItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceTableViewCellItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISpaceTableViewCellItem"}],"url":"\/documentation\/gtuikit\/gtuispacetableviewcellitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem":{"role":"symbol","title":"GTUITableViewCellItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewCellItem"}],"url":"\/documentation\/gtuikit\/gtuitableviewcellitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem/cellHeight":{"role":"symbol","title":"cellHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"高度"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/cellHeight","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewcellitem\/cellheight"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTUITableViewCellItem"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTUITableViewCellItem"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTUITableViewCellItem"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCellItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceTableViewCellItem"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItem"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectCellItem\/title","value":"GTUIRoundRectCellItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectCellItem\/fragments","value":[{"kind":"identifier","text":"GTUIRoundRectCellItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceTableViewCellItem\/title","value":"GTUISpaceTableViewCellItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceTableViewCellItem\/fragments","value":[{"kind":"identifier","text":"GTUISpaceTableViewCellItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCellItem\/title","value":"GTUITableViewCellItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCellItem\/fragments","value":[{"kind":"identifier","text":"GTUITableViewCellItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}