{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutHeader"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutheader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuifalllayoutheader"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/init(dimension:stick:zIndex:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/dimension","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/stick","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/zIndex"]},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/header(dimension:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutHeader"}],"title":"GTUIFallLayoutHeader","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutHeader","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutHeader"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutHeader/dimension":{"role":"symbol","title":"dimension","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dimension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/dimension","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutheader\/dimension"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutHeader/header(dimension:)":{"role":"symbol","title":"header(dimension:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"header"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dimension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GTUIFallLayoutHeader","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutHeader"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/header(dimension:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutheader\/header(dimension:)"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutHeader/init(dimension:stick:zIndex:)":{"role":"symbol","title":"init(dimension:stick:zIndex:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dimension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"zIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutZIndex","preciseIdentifier":"s:7GTUIKit20GTUIFallLayoutZIndexO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/init(dimension:stick:zIndex:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutheader\/init(dimension:stick:zindex:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutHeader/stick":{"role":"symbol","title":"stick","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutStick","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutStick"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"固定"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/stick","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutheader\/stick"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutHeader":{"role":"symbol","title":"GTUIFallLayoutHeader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutHeader"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutHeader"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutheader"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutHeader/zIndex":{"role":"symbol","title":"zIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIFallLayoutZIndex","preciseIdentifier":"s:7GTUIKit20GTUIFallLayoutZIndexO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutHeader\/zIndex","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutheader\/zindex"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTUIFallLayoutHeader"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutHeader"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTUIFallLayoutHeader"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutHeader"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutHeader\/title","value":"GTUIFallLayoutHeader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutHeader\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutHeader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}