{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentIndicatorType"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmentindicatortype"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentIndicator","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentIndicator","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentIndicator","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentIndicator","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINormalIndicator"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentIndicatorType","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentIndicatorType\/view"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentIndicatorType"}],"title":"GTUISegmentIndicatorType","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit24GTUISegmentIndicatorTypeP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUISegmentIndicatorType"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCardSegmentIndicator":{"role":"symbol","title":"GTCardSegmentIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCardSegmentIndicator"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCardSegmentIndicator"}],"url":"\/documentation\/gtuikit\/gtcardsegmentindicator"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentIndicatorType/view":{"role":"symbol","title":"view","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentIndicatorViewType","preciseIdentifier":"s:7GTUIKit28GTUISegmentIndicatorViewTypeP"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentIndicatorType\/view","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentindicatortype\/view"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentIndicatorType":{"role":"symbol","title":"GTUISegmentIndicatorType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentIndicatorType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentIndicatorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentIndicatorType"}],"url":"\/documentation\/gtuikit\/gtuisegmentindicatortype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPrimarySegmentIndicator":{"role":"symbol","title":"GTPrimarySegmentIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPrimarySegmentIndicator"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPrimarySegmentIndicator"}],"url":"\/documentation\/gtuikit\/gtprimarysegmentindicator"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUINormalIndicator":{"role":"symbol","title":"GTUINormalIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUINormalIndicator"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINormalIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUINormalIndicator"}],"url":"\/documentation\/gtuikit\/gtuinormalindicator"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSecondarySegmentIndicator":{"role":"symbol","title":"GTSecondarySegmentIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSecondarySegmentIndicator"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSecondarySegmentIndicator"}],"url":"\/documentation\/gtuikit\/gtsecondarysegmentindicator"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTThirdlySegmentIndicator":{"role":"symbol","title":"GTThirdlySegmentIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTThirdlySegmentIndicator"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTThirdlySegmentIndicator"}],"url":"\/documentation\/gtuikit\/gtthirdlysegmentindicator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCardSegmentIndicator\/title","value":"GTCardSegmentIndicator"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCardSegmentIndicator\/fragments","value":[{"kind":"identifier","text":"GTCardSegmentIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPrimarySegmentIndicator\/title","value":"GTPrimarySegmentIndicator"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPrimarySegmentIndicator\/fragments","value":[{"kind":"identifier","text":"GTPrimarySegmentIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINormalIndicator\/title","value":"GTUINormalIndicator"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINormalIndicator\/fragments","value":[{"kind":"identifier","text":"GTUINormalIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSecondarySegmentIndicator\/title","value":"GTSecondarySegmentIndicator"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSecondarySegmentIndicator\/fragments","value":[{"kind":"identifier","text":"GTSecondarySegmentIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTThirdlySegmentIndicator\/title","value":"GTThirdlySegmentIndicator"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTThirdlySegmentIndicator\/fragments","value":[{"kind":"identifier","text":"GTThirdlySegmentIndicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}