{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuifalllayoutlinkageobject"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuifalllayoutlinkageobject"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutLinkageObject","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutLinkageObject\/init(linkageViewPortSize:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutLinkageObject\/linkageViewPortSize"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}],"title":"GTUIFallLayoutLinkageObject","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTUIFallLayoutLinkageObject","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutLinkageObject/linkageViewPortSize":{"role":"symbol","title":"linkageViewPortSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkageViewPortSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutLinkageObject\/linkageViewPortSize","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutlinkageobject\/linkageviewportsize"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutLinkageObject/init(linkageViewPortSize:)":{"role":"symbol","title":"init(linkageViewPortSize:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"linkageViewPortSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutLinkageObject\/init(linkageViewPortSize:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuifalllayoutlinkageobject\/init(linkageviewportsize:)"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutLinkageObject":{"role":"symbol","title":"GTUIFallLayoutLinkageObject","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutLinkageObject","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutlinkageobject"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTUIFallLayoutLinkageObject"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutLinkageObject\/title","value":"GTUIFallLayoutLinkageObject"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutLinkageObject\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutLinkageObject"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}