{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentItemViewType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmentitemviewtype"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIButton"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINormalSegmentItemView"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemViewType","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemViewType\/select(isSelected:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemViewType\/update(progress:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentItemViewType"}],"title":"GTUISegmentItemViewType","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit23GTUISegmentItemViewTypeP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUISegmentItemViewType"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTThirdlySegmentItemViewV3":{"role":"symbol","title":"GTThirdlySegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTThirdlySegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTThirdlySegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtthirdlysegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/objc(cs)UIButton":{"type":"unresolvable","title":"UIKit.UIButton","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIButton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSecondarySegmentItemViewV3":{"role":"symbol","title":"GTSecondarySegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSecondarySegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSecondarySegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtsecondarysegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUINormalSegmentItemView":{"role":"symbol","title":"GTUINormalSegmentItemView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUINormalSegmentItemView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINormalSegmentItemView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUINormalSegmentItemView"}],"url":"\/documentation\/gtuikit\/gtuinormalsegmentitemview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPrimarySegmentItemViewV3":{"role":"symbol","title":"GTPrimarySegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPrimarySegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPrimarySegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtprimarysegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCardSegmentItemViewV3":{"role":"symbol","title":"GTCardSegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCardSegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCardSegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtcardsegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentItemViewType/update(progress:)":{"role":"symbol","title":"update(progress:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"更新进度"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemViewType\/update(progress:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentitemviewtype\/update(progress:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentItemViewType/select(isSelected:)":{"role":"symbol","title":"select(isSelected:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"select"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"判断是否选中"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemViewType\/select(isSelected:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentitemviewtype\/select(isselected:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentItemViewType":{"role":"symbol","title":"GTUISegmentItemViewType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentItemViewType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemViewType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentItemViewType"}],"url":"\/documentation\/gtuikit\/gtuisegmentitemviewtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTThirdlySegmentItemViewV3\/title","value":"GTThirdlySegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTThirdlySegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTThirdlySegmentItemViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSecondarySegmentItemViewV3\/title","value":"GTSecondarySegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSecondarySegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTSecondarySegmentItemViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINormalSegmentItemView\/title","value":"GTUINormalSegmentItemView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINormalSegmentItemView\/fragments","value":[{"kind":"identifier","text":"GTUINormalSegmentItemView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPrimarySegmentItemViewV3\/title","value":"GTPrimarySegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPrimarySegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTPrimarySegmentItemViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCardSegmentItemViewV3\/title","value":"GTCardSegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCardSegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTCardSegmentItemViewV3"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}