{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentItemType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmentitemtype"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentItemV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentItemV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentItemV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentItemV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINormalSegmentItem"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemType","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemType\/size","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemType\/view"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentItemType"}],"title":"GTUISegmentItemType","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit19GTUISegmentItemTypeP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUISegmentItemType"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUINormalSegmentItem":{"role":"symbol","title":"GTUINormalSegmentItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUINormalSegmentItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINormalSegmentItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUINormalSegmentItem"}],"url":"\/documentation\/gtuikit\/gtuinormalsegmentitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPrimarySegmentItemV3":{"role":"symbol","title":"GTPrimarySegmentItemV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPrimarySegmentItemV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentItemV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPrimarySegmentItemV3"}],"url":"\/documentation\/gtuikit\/gtprimarysegmentitemv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentItemType/view":{"role":"symbol","title":"view","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentItemViewType","preciseIdentifier":"s:7GTUIKit23GTUISegmentItemViewTypeP"}],"abstract":[{"type":"text","text":"返回一个ItemView"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemType\/view","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentitemtype\/view"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSecondarySegmentItemV3":{"role":"symbol","title":"GTSecondarySegmentItemV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSecondarySegmentItemV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentItemV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSecondarySegmentItemV3"}],"url":"\/documentation\/gtuikit\/gtsecondarysegmentitemv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCardSegmentItemV3":{"role":"symbol","title":"GTCardSegmentItemV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCardSegmentItemV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentItemV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCardSegmentItemV3"}],"url":"\/documentation\/gtuikit\/gtcardsegmentitemv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentItemType":{"role":"symbol","title":"GTUISegmentItemType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentItemType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentItemType"}],"url":"\/documentation\/gtuikit\/gtuisegmentitemtype"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTThirdlySegmentItemV3":{"role":"symbol","title":"GTThirdlySegmentItemV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTThirdlySegmentItemV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentItemV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTThirdlySegmentItemV3"}],"url":"\/documentation\/gtuikit\/gtthirdlysegmentitemv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentItemType/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"设置当前的Item大小高度最高以segmentControl为准"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentItemType\/size","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentitemtype\/size"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINormalSegmentItem\/title","value":"GTUINormalSegmentItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINormalSegmentItem\/fragments","value":[{"kind":"identifier","text":"GTUINormalSegmentItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPrimarySegmentItemV3\/title","value":"GTPrimarySegmentItemV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPrimarySegmentItemV3\/fragments","value":[{"kind":"identifier","text":"GTPrimarySegmentItemV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSecondarySegmentItemV3\/title","value":"GTSecondarySegmentItemV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSecondarySegmentItemV3\/fragments","value":[{"kind":"identifier","text":"GTSecondarySegmentItemV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCardSegmentItemV3\/title","value":"GTCardSegmentItemV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCardSegmentItemV3\/fragments","value":[{"kind":"identifier","text":"GTCardSegmentItemV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTThirdlySegmentItemV3\/title","value":"GTThirdlySegmentItemV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTThirdlySegmentItemV3\/fragments","value":[{"kind":"identifier","text":"GTThirdlySegmentItemV3"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}