{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITabBarController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuitabbarcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuitabbarcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/NavigationBarHiddenable","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITabBarDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController\/tabBar(_:doubleClick:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITabBarController"}],"title":"GTUITabBarController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTUITabBarController","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUITabBarController"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"seeAlsoSections":[{"title":"基类","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIImageView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabbar","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIScrollView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIControl","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextField","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINavigationController"],"generated":true}],"references":{"doc://org.cocoapods.GTUIKit/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIViewController":{"role":"symbol","title":"GTUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIViewController"}],"url":"\/documentation\/gtuikit\/gtuiviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITabBarController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/gtuikit\/gtuitabbarcontroller\/initwithnibname:bundle:"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITabBarController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/gtuikit\/gtuitabbarcontroller\/initwithcoder:"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIView":{"role":"symbol","title":"GTUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIView"}],"url":"\/documentation\/gtuikit\/gtuiview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITextView":{"role":"symbol","title":"GTUITextView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITextView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITextView"}],"url":"\/documentation\/gtuikit\/gtuitextview"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSExtensionRequestHandling"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITabBarController":{"role":"symbol","title":"GTUITabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITabBarController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITabBarController"}],"url":"\/documentation\/gtuikit\/gtuitabbarcontroller"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarController":{"role":"symbol","title":"ESTabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarController"}],"url":"\/documentation\/gtuikit\/estabbarcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITextField":{"role":"symbol","title":"GTUITextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITextField"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITextField"}],"url":"\/documentation\/gtuikit\/gtuitextfield"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIImageView":{"role":"symbol","title":"GTUIImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIImageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIImageView"}],"url":"\/documentation\/gtuikit\/gtuiimageview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUINavigationController":{"role":"symbol","title":"GTUINavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUINavigationController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUINavigationController"}],"url":"\/documentation\/gtuikit\/gtuinavigationcontroller"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITabBarController/tabBar(_:doubleClick:)":{"role":"symbol","title":"tabBar(_:doubleClick:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBar","preciseIdentifier":"c:objc(cs)UITabBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"doubleClick"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITabBarItem","preciseIdentifier":"c:objc(cs)UITabBarItem"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController\/tabBar(_:doubleClick:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuitabbarcontroller\/tabbar(_:doubleclick:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITabbar":{"role":"symbol","title":"GTUITabbar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITabbar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabbar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITabbar"}],"url":"\/documentation\/gtuikit\/gtuitabbar"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIContentContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIScrollView":{"role":"symbol","title":"GTUIScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIScrollView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIScrollView"}],"url":"\/documentation\/gtuikit\/gtuiscrollview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITabBarController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Customize set tabBar use KVC."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/gtuikit\/gtuitabbarcontroller\/viewdidload()"},"doc://org.cocoapods.GTUIKit/objc(pl)UITabBarDelegate":{"type":"unresolvable","title":"UIKit.UITabBarDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITabBarDelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIControl":{"role":"symbol","title":"GTUIControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIControl"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIControl"}],"url":"\/documentation\/gtuikit\/gtuicontrol"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILabel":{"role":"symbol","title":"GTUILabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILabel"}],"url":"\/documentation\/gtuikit\/gtuilabel"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3":{"role":"symbol","title":"GTUIButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIButtonV3"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableView":{"role":"symbol","title":"GTUITableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableView"}],"url":"\/documentation\/gtuikit\/gtuitableview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButton":{"role":"symbol","title":"GTUIButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIButton"}],"url":"\/documentation\/gtuikit\/gtuibutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/NavigationBarHiddenable":{"role":"symbol","title":"NavigationBarHiddenable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationBarHiddenable"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/NavigationBarHiddenable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationBarHiddenable"}],"url":"\/documentation\/gtuikit\/navigationbarhiddenable"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTUITabBarController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTUITabBarController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTUITabBarController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController\/initWithCoder:","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController\/initWithNibName:bundle:","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"基类","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIImageView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabbar","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIScrollView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIControl","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextField","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINavigationController"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITabBarController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarController","text":"ESTabBarController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIViewController\/title","value":"GTUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIViewController\/fragments","value":[{"kind":"identifier","text":"GTUIViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIView\/title","value":"GTUIView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIView\/fragments","value":[{"kind":"identifier","text":"GTUIView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView\/title","value":"GTUITextView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView\/fragments","value":[{"kind":"identifier","text":"GTUITextView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabBarController\/title","value":"GTUITabBarController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabBarController\/fragments","value":[{"kind":"identifier","text":"GTUITabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarController\/title","value":"ESTabBarController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarController\/fragments","value":[{"kind":"identifier","text":"ESTabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextField\/title","value":"GTUITextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextField\/fragments","value":[{"kind":"identifier","text":"GTUITextField"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIImageView\/title","value":"GTUIImageView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIImageView\/fragments","value":[{"kind":"identifier","text":"GTUIImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINavigationController\/title","value":"GTUINavigationController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINavigationController\/fragments","value":[{"kind":"identifier","text":"GTUINavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabbar\/title","value":"GTUITabbar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabbar\/fragments","value":[{"kind":"identifier","text":"GTUITabbar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIScrollView\/title","value":"GTUIScrollView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIScrollView\/fragments","value":[{"kind":"identifier","text":"GTUIScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabBarController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabBarController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIControl\/title","value":"GTUIControl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIControl\/fragments","value":[{"kind":"identifier","text":"GTUIControl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILabel\/title","value":"GTUILabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILabel\/fragments","value":[{"kind":"identifier","text":"GTUILabel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/title","value":"GTUIButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/fragments","value":[{"kind":"identifier","text":"GTUIButtonV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableView\/title","value":"GTUITableView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableView\/fragments","value":[{"kind":"identifier","text":"GTUITableView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButton\/title","value":"GTUIButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButton\/fragments","value":[{"kind":"identifier","text":"GTUIButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}