{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTWeb3TextIconFontNode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtweb3texticonfontnode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtweb3texticonfontnode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/init(isIconLeft:leftSpace:middleSpace:rightSpace:verticalSpace:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/iconAligment","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/iconFont","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/iconTextColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/iconfontNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/iconfontText","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/selectedClosure","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/title","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/titleAligment","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/titleColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/titleFont","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/titleNode"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/didLoad()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/layout()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/layoutSpecThatFits(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTWeb3TextIconFontNode"}],"title":"GTWeb3TextIconFontNode","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTWeb3TextIconFontNode","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTWeb3TextIconFontNode"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/objc(pl)ASInterfaceStateDelegate":{"type":"unresolvable","title":"AsyncDisplayKit.ASInterfaceStateDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLocking":{"type":"unresolvable","title":"AsyncDisplayKit.ASLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/layout()":{"role":"symbol","title":"layout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/layout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layout"}],"url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/layout()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/titleAligment":{"role":"symbol","title":"titleAligment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleAligment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/titleAligment","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/titlealigment"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/iconTextColor":{"role":"symbol","title":"iconTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/iconTextColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/icontextcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/title","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/title"},"doc://org.cocoapods.GTUIKit/objc(pl)NSLocking":{"type":"unresolvable","title":"Foundation.NSLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking"},"doc://org.cocoapods.GTUIKit/objc(cs)ASDisplayNode":{"type":"unresolvable","title":"ASDisplayNode","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/init(isIconLeft:leftSpace:middleSpace:rightSpace:verticalSpace:)":{"role":"symbol","title":"init(isIconLeft:leftSpace:middleSpace:rightSpace:verticalSpace:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isIconLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"leftSpace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"middleSpace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rightSpace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"verticalSpace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/init(isIconLeft:leftSpace:middleSpace:rightSpace:verticalSpace:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/init(isiconleft:leftspace:middlespace:rightspace:verticalspace:)"},"doc://org.cocoapods.GTUIKit/objc(pl)ASDebugNameProvider":{"type":"unresolvable","title":"AsyncDisplayKit.ASDebugNameProvider","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/titleColor":{"role":"symbol","title":"titleColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/titleColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/titlecolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/iconfontText":{"role":"symbol","title":"iconfontText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconfontText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/iconfontText","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/iconfonttext"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode":{"role":"symbol","title":"GTWeb3TextIconFontNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTWeb3TextIconFontNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTWeb3TextIconFontNode"}],"url":"\/documentation\/gtuikit\/gtweb3texticonfontnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/iconAligment":{"role":"symbol","title":"iconAligment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconAligment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/iconAligment","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/iconaligment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/layoutSpecThatFits(_:)":{"role":"symbol","title":"layoutSpecThatFits(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSpecThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASSizeRange","preciseIdentifier":"c:@SA@ASSizeRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASLayoutSpec","preciseIdentifier":"c:objc(cs)ASLayoutSpec"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/layoutSpecThatFits(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSpecThatFits:"}],"url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/layoutspecthatfits(_:)"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElement":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElement","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/titleNode":{"role":"symbol","title":"titleNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASTextNode","preciseIdentifier":"c:objc(cs)ASTextNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/titleNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/titlenode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/selectedClosure":{"role":"symbol","title":"selectedClosure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedClosure"},{"kind":"text","text":": (() -> ())?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/selectedClosure","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/selectedclosure"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/didLoad()":{"role":"symbol","title":"didLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/didLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didLoad"}],"url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/didload()"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/iconFont":{"role":"symbol","title":"iconFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/iconFont","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/iconfont"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementAsciiArtProtocol":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementAsciiArtProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementStylability":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementStylability","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/titleFont":{"role":"symbol","title":"titleFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/titleFont","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/titlefont"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTraitEnvironment":{"type":"unresolvable","title":"AsyncDisplayKit.ASTraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTWeb3TextIconFontNode/iconfontNode":{"role":"symbol","title":"iconfontNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconfontNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASTextNode","preciseIdentifier":"c:objc(cs)ASTextNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/iconfontNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtweb3texticonfontnode\/iconfontnode"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementExtensibility":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementExtensibility","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTWeb3TextIconFontNode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTWeb3TextIconFontNode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTWeb3TextIconFontNode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/didLoad()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/layout()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTWeb3TextIconFontNode\/layoutSpecThatFits(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTWeb3TextIconFontNode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ASDisplayNode","preciseIdentifier":"c:objc(cs)ASDisplayNode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTWeb3TextIconFontNode~1layout()\/title","value":"layout"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTWeb3TextIconFontNode~1layout()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layout"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTWeb3TextIconFontNode\/title","value":"GTWeb3TextIconFontNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTWeb3TextIconFontNode\/fragments","value":[{"kind":"identifier","text":"GTWeb3TextIconFontNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTWeb3TextIconFontNode~1layoutSpecThatFits(_:)\/title","value":"layoutSpecThatFits:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTWeb3TextIconFontNode~1layoutSpecThatFits(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSpecThatFits:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTWeb3TextIconFontNode~1didLoad()\/title","value":"didLoad"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTWeb3TextIconFontNode~1didLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}