{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationBarHiddenable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/navigationbarhiddenable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/DMLPhotoBrowser","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINavigationController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptorController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISubLinkageViewController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/PGDatePickManager","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/PagingViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/NavigationBarHiddenable","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/NavigationBarHiddenable\/gt_interactivePopDisabled","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/NavigationBarHiddenable\/gt_navigationBarHidden"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationBarHiddenable"}],"title":"NavigationBarHiddenable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit23NavigationBarHiddenableP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"NavigationBarHiddenable"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILinkageViewController":{"role":"symbol","title":"GTUILinkageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILinkageViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILinkageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILinkageViewController"}],"url":"\/documentation\/gtuikit\/gtuilinkageviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewController":{"role":"symbol","title":"GTUITableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewController"}],"url":"\/documentation\/gtuikit\/gtuitableviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/NavigationBarHiddenable":{"role":"symbol","title":"NavigationBarHiddenable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationBarHiddenable"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/NavigationBarHiddenable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationBarHiddenable"}],"url":"\/documentation\/gtuikit\/navigationbarhiddenable"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/NavigationBarHiddenable/gt_navigationBarHidden":{"role":"symbol","title":"gt_navigationBarHidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_navigationBarHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/NavigationBarHiddenable\/gt_navigationBarHidden","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/navigationbarhiddenable\/gt_navigationbarhidden"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarController":{"role":"symbol","title":"ESTabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarController"}],"url":"\/documentation\/gtuikit\/estabbarcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/DMLPhotoBrowser":{"role":"symbol","title":"DMLPhotoBrowser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DMLPhotoBrowser"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/DMLPhotoBrowser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DMLPhotoBrowser"}],"url":"\/documentation\/gtuikit\/dmlphotobrowser"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISubLinkageViewController":{"role":"symbol","title":"GTUISubLinkageViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISubLinkageViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISubLinkageViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISubLinkageViewController"}],"url":"\/documentation\/gtuikit\/gtuisublinkageviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIViewController":{"role":"symbol","title":"GTUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIViewController"}],"url":"\/documentation\/gtuikit\/gtuiviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/PagingViewController":{"role":"symbol","title":"PagingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PagingViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/PagingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PagingViewController"}],"url":"\/documentation\/gtuikit\/pagingviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentAdaptorController":{"role":"symbol","title":"GTUISegmentAdaptorController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentAdaptorController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentAdaptorController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentAdaptorController"}],"url":"\/documentation\/gtuikit\/gtuisegmentadaptorcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITabBarController":{"role":"symbol","title":"GTUITabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITabBarController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITabBarController"}],"url":"\/documentation\/gtuikit\/gtuitabbarcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/NavigationBarHiddenable/gt_interactivePopDisabled":{"role":"symbol","title":"gt_interactivePopDisabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_interactivePopDisabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/NavigationBarHiddenable\/gt_interactivePopDisabled","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/navigationbarhiddenable\/gt_interactivepopdisabled"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/PGDatePickManager":{"role":"symbol","title":"PGDatePickManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDatePickManager"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/PGDatePickManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGDatePickManager"}],"url":"\/documentation\/gtuikit\/pgdatepickmanager"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUINavigationController":{"role":"symbol","title":"GTUINavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUINavigationController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUINavigationController"}],"url":"\/documentation\/gtuikit\/gtuinavigationcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/title","value":"GTUILinkageViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILinkageViewController\/fragments","value":[{"kind":"identifier","text":"GTUILinkageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewController\/title","value":"GTUITableViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewController\/fragments","value":[{"kind":"identifier","text":"GTUITableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarController\/title","value":"ESTabBarController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarController\/fragments","value":[{"kind":"identifier","text":"ESTabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISubLinkageViewController\/title","value":"GTUISubLinkageViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISubLinkageViewController\/fragments","value":[{"kind":"identifier","text":"GTUISubLinkageViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIViewController\/title","value":"GTUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIViewController\/fragments","value":[{"kind":"identifier","text":"GTUIViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptorController\/title","value":"GTUISegmentAdaptorController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentAdaptorController\/fragments","value":[{"kind":"identifier","text":"GTUISegmentAdaptorController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabBarController\/title","value":"GTUITabBarController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabBarController\/fragments","value":[{"kind":"identifier","text":"GTUITabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINavigationController\/title","value":"GTUINavigationController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINavigationController\/fragments","value":[{"kind":"identifier","text":"GTUINavigationController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}