{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReusableView"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/reusableview"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/DMLPhotoCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/FSCalendarBlankCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/FSCalendarCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/FSCalendarHeaderCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/FSCalendarSeparatorDecorationView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/FSCalendarStickyHeader","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTComponentCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewHeaderFooterView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleAvatarCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleAvatarSubtitleCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleDescriptionCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSubtitleCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSubtitleDescriptionCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSubtitleSwitchCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSwitchCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceCollectionViewCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceTableViewCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCell","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/PGDatePickerView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/PGPickerColumnCell"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ReusableView","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ReusableView\/reuseIdentifier"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReusableView"}],"title":"ReusableView","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit12ReusableViewP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ReusableView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/DMLPhotoCell":{"role":"symbol","title":"DMLPhotoCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DMLPhotoCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/DMLPhotoCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DMLPhotoCell"}],"url":"\/documentation\/gtuikit\/dmlphotocell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ReusableView":{"role":"symbol","title":"ReusableView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReusableView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ReusableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReusableView"}],"url":"\/documentation\/gtuikit\/reusableview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/PGDatePickerView":{"role":"symbol","title":"PGDatePickerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDatePickerView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/PGDatePickerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGDatePickerView"}],"url":"\/documentation\/gtuikit\/pgdatepickerview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/FSCalendarStickyHeader":{"role":"symbol","title":"FSCalendarStickyHeader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FSCalendarStickyHeader"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/FSCalendarStickyHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FSCalendarStickyHeader"}],"url":"\/documentation\/gtuikit\/fscalendarstickyheader"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISpaceCollectionViewCell":{"role":"symbol","title":"GTUISpaceCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISpaceCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISpaceCollectionViewCell"}],"url":"\/documentation\/gtuikit\/gtuispacecollectionviewcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRoundRectCell":{"role":"symbol","title":"GTUIRoundRectCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRoundRectCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIRoundRectCell"}],"url":"\/documentation\/gtuikit\/gtuiroundrectcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleAvatarCell":{"role":"symbol","title":"GTTitleAvatarCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTitleAvatarCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleAvatarCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTitleAvatarCell"}],"url":"\/documentation\/gtuikit\/gttitleavatarcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/FSCalendarCell":{"role":"symbol","title":"FSCalendarCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FSCalendarCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/FSCalendarCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FSCalendarCell"}],"url":"\/documentation\/gtuikit\/fscalendarcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleSubtitleDescriptionCell":{"role":"symbol","title":"GTTitleSubtitleDescriptionCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTitleSubtitleDescriptionCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSubtitleDescriptionCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTitleSubtitleDescriptionCell"}],"url":"\/documentation\/gtuikit\/gttitlesubtitledescriptioncell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleSubtitleSwitchCell":{"role":"symbol","title":"GTTitleSubtitleSwitchCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTitleSubtitleSwitchCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSubtitleSwitchCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTitleSubtitleSwitchCell"}],"url":"\/documentation\/gtuikit\/gttitlesubtitleswitchcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ReusableView/reuseIdentifier":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"reuseIdentifier","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"反回当前类名的字符串"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ReusableView\/reuseIdentifier","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/reusableview\/reuseidentifier"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/PGPickerColumnCell":{"role":"symbol","title":"PGPickerColumnCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPickerColumnCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/PGPickerColumnCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPickerColumnCell"}],"url":"\/documentation\/gtuikit\/pgpickercolumncell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/FSCalendarHeaderCell":{"role":"symbol","title":"FSCalendarHeaderCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FSCalendarHeaderCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/FSCalendarHeaderCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FSCalendarHeaderCell"}],"url":"\/documentation\/gtuikit\/fscalendarheadercell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewCellV3":{"role":"symbol","title":"GTTableViewCellV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTableViewCellV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewCellV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTableViewCellV3"}],"url":"\/documentation\/gtuikit\/gttableviewcellv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleCell":{"role":"symbol","title":"GTTitleCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTitleCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTitleCell"}],"url":"\/documentation\/gtuikit\/gttitlecell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCell":{"role":"symbol","title":"GTUITableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCell"}],"abstract":[{"type":"text","text":"TableViewCell基类"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewCell"}],"url":"\/documentation\/gtuikit\/gtuitableviewcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/FSCalendarSeparatorDecorationView":{"role":"symbol","title":"FSCalendarSeparatorDecorationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FSCalendarSeparatorDecorationView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/FSCalendarSeparatorDecorationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FSCalendarSeparatorDecorationView"}],"url":"\/documentation\/gtuikit\/fscalendarseparatordecorationview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleDescriptionCell":{"role":"symbol","title":"GTTitleDescriptionCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTitleDescriptionCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleDescriptionCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTitleDescriptionCell"}],"url":"\/documentation\/gtuikit\/gttitledescriptioncell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISpaceTableViewCell":{"role":"symbol","title":"GTUISpaceTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISpaceTableViewCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISpaceTableViewCell"}],"url":"\/documentation\/gtuikit\/gtuispacetableviewcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleSwitchCell":{"role":"symbol","title":"GTTitleSwitchCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTitleSwitchCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSwitchCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTitleSwitchCell"}],"url":"\/documentation\/gtuikit\/gttitleswitchcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewCell":{"role":"symbol","title":"GTUICollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewCell"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleSubtitleCell":{"role":"symbol","title":"GTTitleSubtitleCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTitleSubtitleCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleSubtitleCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTitleSubtitleCell"}],"url":"\/documentation\/gtuikit\/gttitlesubtitlecell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTitleAvatarSubtitleCell":{"role":"symbol","title":"GTTitleAvatarSubtitleCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTitleAvatarSubtitleCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTitleAvatarSubtitleCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTitleAvatarSubtitleCell"}],"url":"\/documentation\/gtuikit\/gttitleavatarsubtitlecell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTableViewHeaderFooterView":{"role":"symbol","title":"GTTableViewHeaderFooterView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTableViewHeaderFooterView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTableViewHeaderFooterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTableViewHeaderFooterView"}],"url":"\/documentation\/gtuikit\/gttableviewheaderfooterview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTComponentCell":{"role":"symbol","title":"GTComponentCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTComponentCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTComponentCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTComponentCell"}],"url":"\/documentation\/gtuikit\/gtcomponentcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/FSCalendarBlankCell":{"role":"symbol","title":"FSCalendarBlankCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FSCalendarBlankCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/FSCalendarBlankCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FSCalendarBlankCell"}],"url":"\/documentation\/gtuikit\/fscalendarblankcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceCollectionViewCell\/title","value":"GTUISpaceCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"GTUISpaceCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectCell\/title","value":"GTUIRoundRectCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectCell\/fragments","value":[{"kind":"identifier","text":"GTUIRoundRectCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleAvatarCell\/title","value":"GTTitleAvatarCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleAvatarCell\/fragments","value":[{"kind":"identifier","text":"GTTitleAvatarCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleSubtitleDescriptionCell\/title","value":"GTTitleSubtitleDescriptionCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleSubtitleDescriptionCell\/fragments","value":[{"kind":"identifier","text":"GTTitleSubtitleDescriptionCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleSubtitleSwitchCell\/title","value":"GTTitleSubtitleSwitchCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleSubtitleSwitchCell\/fragments","value":[{"kind":"identifier","text":"GTTitleSubtitleSwitchCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/title","value":"GTTableViewCellV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewCellV3\/fragments","value":[{"kind":"identifier","text":"GTTableViewCellV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleCell\/title","value":"GTTitleCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleCell\/fragments","value":[{"kind":"identifier","text":"GTTitleCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCell\/title","value":"GTUITableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCell\/fragments","value":[{"kind":"identifier","text":"GTUITableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleDescriptionCell\/title","value":"GTTitleDescriptionCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleDescriptionCell\/fragments","value":[{"kind":"identifier","text":"GTTitleDescriptionCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceTableViewCell\/title","value":"GTUISpaceTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceTableViewCell\/fragments","value":[{"kind":"identifier","text":"GTUISpaceTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleSwitchCell\/title","value":"GTTitleSwitchCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleSwitchCell\/fragments","value":[{"kind":"identifier","text":"GTTitleSwitchCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewCell\/title","value":"GTUICollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewCell\/fragments","value":[{"kind":"identifier","text":"GTUICollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleSubtitleCell\/title","value":"GTTitleSubtitleCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleSubtitleCell\/fragments","value":[{"kind":"identifier","text":"GTTitleSubtitleCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleAvatarSubtitleCell\/title","value":"GTTitleAvatarSubtitleCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTitleAvatarSubtitleCell\/fragments","value":[{"kind":"identifier","text":"GTTitleAvatarSubtitleCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewHeaderFooterView\/title","value":"GTTableViewHeaderFooterView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTableViewHeaderFooterView\/fragments","value":[{"kind":"identifier","text":"GTTableViewHeaderFooterView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTComponentCell\/title","value":"GTComponentCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTComponentCell\/fragments","value":[{"kind":"identifier","text":"GTComponentCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}