{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBDesignable"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/tagview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/tagview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIButton"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonLoadingType","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSkeletionMiniUnitType","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/init(title:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/borderColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/borderWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/cornerRadius","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/enableRemoveButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/highlightedBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/intrinsicContentSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/isHighlighted","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/isSelected","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/onLongPress","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/onTap","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/paddingX","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/paddingY","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/removeButtonIconSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/removeIconLineColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/removeIconLineWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/selectedBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/selectedBorderColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/selectedTextColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/tagBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/textColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/textFont","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/titleLineBreakMode"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/layoutSubviews()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagView"}],"title":"TagView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)TagView","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"TagView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/isHighlighted":{"role":"symbol","title":"isHighlighted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHighlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/isHighlighted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlighted"}],"url":"\/documentation\/gtuikit\/tagview\/ishighlighted"},"doc://org.cocoapods.GTUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/intrinsicContentSize":{"role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/intrinsicContentSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/gtuikit\/tagview\/intrinsiccontentsize"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/highlightedBackgroundColor":{"role":"symbol","title":"highlightedBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/highlightedBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlightedBackgroundColor"}],"url":"\/documentation\/gtuikit\/tagview\/highlightedbackgroundcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView":{"role":"symbol","title":"TagView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagView"}],"url":"\/documentation\/gtuikit\/tagview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/tagBackgroundColor":{"role":"symbol","title":"tagBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/tagBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tagBackgroundColor"}],"url":"\/documentation\/gtuikit\/tagview\/tagbackgroundcolor"},"doc://org.cocoapods.GTUIKit/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"type":"unresolvable","title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/borderWidth":{"role":"symbol","title":"borderWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/borderWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"borderWidth"}],"url":"\/documentation\/gtuikit\/tagview\/borderwidth"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/enableRemoveButton":{"role":"symbol","title":"enableRemoveButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableRemoveButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/enableRemoveButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableRemoveButton"}],"url":"\/documentation\/gtuikit\/tagview\/enableremovebutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/gtuikit\/tagview\/layoutsubviews()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/selectedBorderColor":{"role":"symbol","title":"selectedBorderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedBorderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/selectedBorderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedBorderColor"}],"url":"\/documentation\/gtuikit\/tagview\/selectedbordercolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/textColor":{"role":"symbol","title":"textColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/textColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textColor"}],"url":"\/documentation\/gtuikit\/tagview\/textcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSkeletionMiniUnitType":{"role":"symbol","title":"GTSkeletionMiniUnitType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSkeletionMiniUnitType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSkeletionMiniUnitType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSkeletionMiniUnitType"}],"url":"\/documentation\/gtuikit\/gtskeletionminiunittype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/isSelected":{"role":"symbol","title":"isSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/isSelected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selected"}],"url":"\/documentation\/gtuikit\/tagview\/isselected"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/paddingX":{"role":"symbol","title":"paddingX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paddingX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/paddingX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paddingX"}],"url":"\/documentation\/gtuikit\/tagview\/paddingx"},"doc://org.cocoapods.GTUIKit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.GTUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyType":{"role":"symbol","title":"GTEmptyType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyType"}],"url":"\/documentation\/gtuikit\/gtemptytype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/paddingY":{"role":"symbol","title":"paddingY","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paddingY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/paddingY","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paddingY"}],"url":"\/documentation\/gtuikit\/tagview\/paddingy"},"doc://org.cocoapods.GTUIKit/9PinLayout14SizeCalculableP":{"type":"unresolvable","title":"PinLayout.SizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/removeButtonIconSize":{"role":"symbol","title":"removeButtonIconSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeButtonIconSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/removeButtonIconSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeButtonIconSize"}],"url":"\/documentation\/gtuikit\/tagview\/removebuttoniconsize"},"doc://org.cocoapods.GTUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/selectedTextColor":{"role":"symbol","title":"selectedTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/selectedTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedTextColor"}],"url":"\/documentation\/gtuikit\/tagview\/selectedtextcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/onLongPress":{"role":"symbol","title":"onLongPress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLongPress"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/onLongPress","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/tagview\/onlongpress"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTButtonLoadingType":{"role":"symbol","title":"GTButtonLoadingType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTButtonLoadingType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonLoadingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTButtonLoadingType"}],"url":"\/documentation\/gtuikit\/gtbuttonloadingtype"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/textFont":{"role":"symbol","title":"textFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/textFont","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFont"}],"url":"\/documentation\/gtuikit\/tagview\/textfont"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/borderColor":{"role":"symbol","title":"borderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/borderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"borderColor"}],"url":"\/documentation\/gtuikit\/tagview\/bordercolor"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.GTUIKit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/titleLineBreakMode":{"role":"symbol","title":"titleLineBreakMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLineBreakMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLineBreakMode","preciseIdentifier":"c:@E@NSLineBreakMode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/titleLineBreakMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLineBreakMode"}],"url":"\/documentation\/gtuikit\/tagview\/titlelinebreakmode"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/12SkeletonView0aB8ExtendedP":{"type":"unresolvable","title":"SkeletonView.SkeletonViewExtended","identifier":"doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/9PinLayout18AutoSizeCalculableP":{"type":"unresolvable","title":"PinLayout.AutoSizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP"},"doc://org.cocoapods.GTUIKit/9PinLayout10LayoutableP":{"type":"unresolvable","title":"PinLayout.Layoutable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","title":"UIKit.UIContextMenuInteractionDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIContextMenuInteractionDelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/gtuikit\/tagview\/init(coder:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/removeIconLineWidth":{"role":"symbol","title":"removeIconLineWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeIconLineWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/removeIconLineWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeIconLineWidth"}],"url":"\/documentation\/gtuikit\/tagview\/removeiconlinewidth"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/selectedBackgroundColor":{"role":"symbol","title":"selectedBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/selectedBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedBackgroundColor"}],"url":"\/documentation\/gtuikit\/tagview\/selectedbackgroundcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/cornerRadius":{"role":"symbol","title":"cornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/cornerRadius","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cornerRadius"}],"url":"\/documentation\/gtuikit\/tagview\/cornerradius"},"doc://org.cocoapods.GTUIKit/objc(cs)UIButton":{"type":"unresolvable","title":"UIButton","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIButton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/removeIconLineColor":{"role":"symbol","title":"removeIconLineColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeIconLineColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/removeIconLineColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeIconLineColor"}],"url":"\/documentation\/gtuikit\/tagview\/removeiconlinecolor"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/onTap":{"role":"symbol","title":"onTap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTap"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Handles Tap (TouchUpInside)"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/onTap","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/tagview\/ontap"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView/init(title:)":{"role":"symbol","title":"init(title:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/init(title:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/tagview\/init(title:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TagView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TagView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TagView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/borderColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/borderWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/cornerRadius","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/enableRemoveButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/highlightedBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/intrinsicContentSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/isHighlighted","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/isSelected","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/paddingX","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/paddingY","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/removeButtonIconSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/removeIconLineColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/removeIconLineWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/selectedBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/selectedBorderColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/selectedTextColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/tagBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/textColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/textFont","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/titleLineBreakMode"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIButton"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1isHighlighted\/title","value":"highlighted"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1isHighlighted\/fragments","value":[{"kind":"identifier","text":"highlighted"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1highlightedBackgroundColor\/title","value":"highlightedBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1highlightedBackgroundColor\/fragments","value":[{"kind":"identifier","text":"highlightedBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView\/title","value":"TagView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView\/fragments","value":[{"kind":"identifier","text":"TagView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1tagBackgroundColor\/title","value":"tagBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1tagBackgroundColor\/fragments","value":[{"kind":"identifier","text":"tagBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1borderWidth\/title","value":"borderWidth"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1borderWidth\/fragments","value":[{"kind":"identifier","text":"borderWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1enableRemoveButton\/title","value":"enableRemoveButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1enableRemoveButton\/fragments","value":[{"kind":"identifier","text":"enableRemoveButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1selectedBorderColor\/title","value":"selectedBorderColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1selectedBorderColor\/fragments","value":[{"kind":"identifier","text":"selectedBorderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1textColor\/title","value":"textColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1textColor\/fragments","value":[{"kind":"identifier","text":"textColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1isSelected\/title","value":"selected"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1isSelected\/fragments","value":[{"kind":"identifier","text":"selected"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1paddingX\/title","value":"paddingX"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1paddingX\/fragments","value":[{"kind":"identifier","text":"paddingX"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1paddingY\/title","value":"paddingY"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1paddingY\/fragments","value":[{"kind":"identifier","text":"paddingY"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1removeButtonIconSize\/title","value":"removeButtonIconSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1removeButtonIconSize\/fragments","value":[{"kind":"identifier","text":"removeButtonIconSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1selectedTextColor\/title","value":"selectedTextColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1selectedTextColor\/fragments","value":[{"kind":"identifier","text":"selectedTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1textFont\/title","value":"textFont"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1textFont\/fragments","value":[{"kind":"identifier","text":"textFont"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1borderColor\/title","value":"borderColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1borderColor\/fragments","value":[{"kind":"identifier","text":"borderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1titleLineBreakMode\/title","value":"titleLineBreakMode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1titleLineBreakMode\/fragments","value":[{"kind":"identifier","text":"titleLineBreakMode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1removeIconLineWidth\/title","value":"removeIconLineWidth"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1removeIconLineWidth\/fragments","value":[{"kind":"identifier","text":"removeIconLineWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1selectedBackgroundColor\/title","value":"selectedBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1selectedBackgroundColor\/fragments","value":[{"kind":"identifier","text":"selectedBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1cornerRadius\/title","value":"cornerRadius"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1cornerRadius\/fragments","value":[{"kind":"identifier","text":"cornerRadius"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1removeIconLineColor\/title","value":"removeIconLineColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView~1removeIconLineColor\/fragments","value":[{"kind":"identifier","text":"removeIconLineColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}