{"variants":[{"paths":["\/documentation\/gtuikit\/gtalertrowitemnode\/astabledelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtalertrowitemnode\/astabledelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/ASTableDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:didSelectRowAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"ASTableDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/tableNode(_:didSelectRowAt:)":{"role":"symbol","title":"tableNode(_:didSelectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableNode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASTableNode","preciseIdentifier":"c:objc(cs)ASTableNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:didSelectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableNode:didSelectRowAtIndexPath:"}],"url":"\/documentation\/gtuikit\/gtalertrowitemnode\/tablenode(_:didselectrowat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode":{"role":"symbol","title":"GTAlertRowItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertRowItemNode"}],"abstract":[{"type":"text","text":"Cancel Item Alert"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertRowItemNode"}],"url":"\/documentation\/gtuikit\/gtalertrowitemnode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:didSelectRowAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode~1tableNode(_:didSelectRowAt:)\/title","value":"tableNode:didSelectRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode~1tableNode(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableNode:didSelectRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/title","value":"GTAlertRowItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertRowItemNode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}