{"variants":[{"paths":["\/documentation\/gtuikit\/gtalertrowitemnode\/astabledatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtalertrowitemnode\/astabledatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/ASTableDataSource-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:nodeBlockForRowAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:numberOfRowsInSection:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"ASTableDataSource Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode":{"role":"symbol","title":"GTAlertRowItemNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAlertRowItemNode"}],"abstract":[{"type":"text","text":"Cancel Item Alert"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAlertRowItemNode"}],"url":"\/documentation\/gtuikit\/gtalertrowitemnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/tableNode(_:nodeBlockForRowAt:)":{"role":"symbol","title":"tableNode(_:nodeBlockForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableNode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASTableNode","preciseIdentifier":"c:objc(cs)ASTableNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nodeBlockForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASCellNodeBlock","preciseIdentifier":"c:ASBlockTypes.h@T@ASCellNodeBlock"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:nodeBlockForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableNode:nodeBlockForRowAtIndexPath:"}],"url":"\/documentation\/gtuikit\/gtalertrowitemnode\/tablenode(_:nodeblockforrowat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAlertRowItemNode/tableNode(_:numberOfRowsInSection:)":{"role":"symbol","title":"tableNode(_:numberOfRowsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableNode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASTableNode","preciseIdentifier":"c:objc(cs)ASTableNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:numberOfRowsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableNode:numberOfRowsInSection:"}],"url":"\/documentation\/gtuikit\/gtalertrowitemnode\/tablenode(_:numberofrowsinsection:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:nodeBlockForRowAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAlertRowItemNode\/tableNode(_:numberOfRowsInSection:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/title","value":"GTAlertRowItemNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode\/fragments","value":[{"kind":"identifier","text":"GTAlertRowItemNode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode~1tableNode(_:nodeBlockForRowAt:)\/title","value":"tableNode:nodeBlockForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode~1tableNode(_:nodeBlockForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableNode:nodeBlockForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode~1tableNode(_:numberOfRowsInSection:)\/title","value":"tableNode:numberOfRowsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAlertRowItemNode~1tableNode(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableNode:numberOfRowsInSection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}