{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkBoxButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTCheckBox","text":"GTCheckBox"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtcheckalertview\/checkboxbutton"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckAlertView\/checkBoxButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkBoxButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTCheckBox","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTCheckBox"}],"title":"checkBoxButton","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit16GTCheckAlertViewC14checkBoxButtonAA0bF0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckAlertView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckAlertView/checkBoxButton":{"role":"symbol","title":"checkBoxButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkBoxButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTCheckBox","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTCheckBox"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckAlertView\/checkBoxButton","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtcheckalertview\/checkboxbutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckAlertView":{"role":"symbol","title":"GTCheckAlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckAlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckAlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckAlertView"}],"url":"\/documentation\/gtuikit\/gtcheckalertview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBox":{"role":"symbol","title":"GTCheckBox","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBox"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBox","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBox"}],"url":"\/documentation\/gtuikit\/gtcheckbox"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckAlertView\/title","value":"GTCheckAlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckAlertView\/fragments","value":[{"kind":"identifier","text":"GTCheckAlertView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBox\/title","value":"GTCheckBox"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBox\/fragments","value":[{"kind":"identifier","text":"GTCheckBox"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}