{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtbasealertview\/scrollviewdidscroll(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtbasealertview\/scrollviewdidscroll(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView\/scrollViewDidScroll(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"修改verticalIndicator 颜色"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}],"role":"symbol","title":"scrollViewDidScroll(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTBaseAlertView(im)scrollViewDidScroll:","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView\/UIScrollViewDelegate-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBaseAlertView/UIScrollViewDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView\/UIScrollViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtbasealertview\/uiscrollviewdelegate-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBaseAlertView":{"role":"symbol","title":"GTBaseAlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBaseAlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTBaseAlertView"}],"url":"\/documentation\/gtuikit\/gtbasealertview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBaseAlertView/scrollViewDidScroll(_:)":{"role":"symbol","title":"scrollViewDidScroll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"修改verticalIndicator 颜色"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView\/scrollViewDidScroll(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}],"url":"\/documentation\/gtuikit\/gtbasealertview\/scrollviewdidscroll(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scrollViewDidScroll:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scrollViewDidScroll:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBaseAlertView\/title","value":"GTBaseAlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBaseAlertView\/fragments","value":[{"kind":"identifier","text":"GTBaseAlertView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBaseAlertView~1scrollViewDidScroll(_:)\/title","value":"scrollViewDidScroll:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBaseAlertView~1scrollViewDidScroll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}