{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentSlideAnimationController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentSlideAnimationController","text":"GTUISegmentSlideAnimationController"},{"kind":"text","text":"! { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmentinteractivetransition\/animationcontroller"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition\/animationController","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentSlideAnimationController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentSlideAnimationController"},{"kind":"text","text":"!"}],"title":"animationController","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit32GTUISegmentInteractiveTransitionC19animationControllerAA0b14SlideAnimationF0CSgvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentInteractiveTransition/animationController":{"role":"symbol","title":"animationController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUISegmentSlideAnimationController","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUISegmentSlideAnimationController"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition\/animationController","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentinteractivetransition\/animationcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentSlideAnimationController":{"role":"symbol","title":"GTUISegmentSlideAnimationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentSlideAnimationController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentSlideAnimationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentSlideAnimationController"}],"url":"\/documentation\/gtuikit\/gtuisegmentslideanimationcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentInteractiveTransition":{"role":"symbol","title":"GTUISegmentInteractiveTransition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}],"url":"\/documentation\/gtuikit\/gtuisegmentinteractivetransition"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentSlideAnimationController\/title","value":"GTUISegmentSlideAnimationController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentSlideAnimationController\/fragments","value":[{"kind":"identifier","text":"GTUISegmentSlideAnimationController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition\/title","value":"GTUISegmentInteractiveTransition"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition\/fragments","value":[{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}