{"variants":[{"paths":["\/documentation\/gtuikit\/gtpagecontrolview\/fspagerviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtpagecontrolview\/fspagerviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/FSPagerViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerView(_:didSelectItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerViewDidEndScrollAnimation(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerViewDidScroll(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerViewWillEndDragging(_:targetIndex:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"FSPagerViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControlView":{"role":"symbol","title":"GTPageControlView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPageControlView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPageControlView"}],"url":"\/documentation\/gtuikit\/gtpagecontrolview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControlView/pagerViewDidScroll(_:)":{"role":"symbol","title":"pagerViewDidScroll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerViewDidScroll(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pagerViewDidScroll:"}],"url":"\/documentation\/gtuikit\/gtpagecontrolview\/pagerviewdidscroll(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControlView/pagerViewWillEndDragging(_:targetIndex:)":{"role":"symbol","title":"pagerViewWillEndDragging(_:targetIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerViewWillEndDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerViewWillEndDragging(_:targetIndex:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pagerViewWillEndDragging:targetIndex:"}],"url":"\/documentation\/gtuikit\/gtpagecontrolview\/pagerviewwillenddragging(_:targetindex:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControlView/pagerView(_:didSelectItemAt:)":{"role":"symbol","title":"pagerView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerView(_:didSelectItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pagerView:didSelectItemAtIndex:"}],"url":"\/documentation\/gtuikit\/gtpagecontrolview\/pagerview(_:didselectitemat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControlView/pagerViewDidEndScrollAnimation(_:)":{"role":"symbol","title":"pagerViewDidEndScrollAnimation(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerViewDidEndScrollAnimation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerViewDidEndScrollAnimation(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pagerViewDidEndScrollAnimation:"}],"url":"\/documentation\/gtuikit\/gtpagecontrolview\/pagerviewdidendscrollanimation(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerView(_:didSelectItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerViewDidEndScrollAnimation(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerViewDidScroll(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pagerViewWillEndDragging(_:targetIndex:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView\/title","value":"GTPageControlView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView\/fragments","value":[{"kind":"identifier","text":"GTPageControlView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView~1pagerViewDidScroll(_:)\/title","value":"pagerViewDidScroll:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView~1pagerViewDidScroll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pagerViewDidScroll:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView~1pagerViewWillEndDragging(_:targetIndex:)\/title","value":"pagerViewWillEndDragging:targetIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView~1pagerViewWillEndDragging(_:targetIndex:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pagerViewWillEndDragging:targetIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView~1pagerView(_:didSelectItemAt:)\/title","value":"pagerView:didSelectItemAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView~1pagerView(_:didSelectItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pagerView:didSelectItemAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView~1pagerViewDidEndScrollAnimation(_:)\/title","value":"pagerViewDidEndScrollAnimation:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView~1pagerViewDidEndScrollAnimation(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pagerViewDidEndScrollAnimation:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}