{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControl","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPageControl","text":"GTPageControl"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtpagecontrolview\/pagecontrol"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pageControl","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPageControl","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPageControl"}],"title":"pageControl","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit17GTPageControlViewC04pageC0AA0bC0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControl":{"role":"symbol","title":"GTPageControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPageControl"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPageControl"}],"url":"\/documentation\/gtuikit\/gtpagecontrol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControlView":{"role":"symbol","title":"GTPageControlView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPageControlView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPageControlView"}],"url":"\/documentation\/gtuikit\/gtpagecontrolview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPageControlView/pageControl":{"role":"symbol","title":"pageControl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPageControl","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPageControl"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPageControlView\/pageControl","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpagecontrolview\/pagecontrol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControl\/title","value":"GTPageControl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControl\/fragments","value":[{"kind":"identifier","text":"GTPageControl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView\/title","value":"GTPageControlView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPageControlView\/fragments","value":[{"kind":"identifier","text":"GTPageControlView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}