{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setAttributedPrefixIconFont"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThemeAttributedStringPicker","preciseIdentifier":"s:7GTUIKit29GTThemeAttributedStringPickera","text":"GTThemeAttributedStringPicker"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuibuttonv3\/gt_setattributedprefixiconfont(_:forstate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuibuttonv3\/gt_setattributedprefixiconfont(_:forstate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedPrefixIconFont(_:forState:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setAttributedPrefixIconFont"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeAttributedStringPicker","preciseIdentifier":"s:7GTUIKit29GTThemeAttributedStringPickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"title":"gt_setAttributedPrefixIconFont(_:forState:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTUIButtonV3(im)gt_setAttributedPrefixIconFont:forState:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"gt_setAttributedPrefixIconFont:forState:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTThemeAttributedStringPicker":{"role":"symbol","title":"GTThemeAttributedStringPicker","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTThemeAttributedStringPicker"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThemeAttributedStringPicker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTThemeAttributedStringPicker"}],"url":"\/documentation\/gtuikit\/gtthemeattributedstringpicker"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setAttributedPrefixIconFont(_:forState:)":{"role":"symbol","title":"gt_setAttributedPrefixIconFont(_:forState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setAttributedPrefixIconFont"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeAttributedStringPicker","preciseIdentifier":"s:7GTUIKit29GTThemeAttributedStringPickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedPrefixIconFont(_:forState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setAttributedPrefixIconFont:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_setattributedprefixiconfont(_:forstate:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3":{"role":"symbol","title":"GTUIButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIButtonV3"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"gt_setAttributedPrefixIconFont:forState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setAttributedPrefixIconFont:forState:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"gt_setAttributedPrefixIconFont:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ThemeAttributedStringPicker","preciseIdentifier":"c:objc(cs)ThemeAttributedStringPicker"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":" "},{"kind":"identifier","text":"forState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIControlState","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setAttributedPrefixIconFont(_:forState:)\/title","value":"gt_setAttributedPrefixIconFont:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setAttributedPrefixIconFont(_:forState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setAttributedPrefixIconFont:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/title","value":"GTUIButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/fragments","value":[{"kind":"identifier","text":"GTUIButtonV3"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}