{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIRefreshHeaderConfig","text":"GTUIRefreshHeaderConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuirefreshheader\/config"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeader\/config","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIRefreshHeaderConfig","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIRefreshHeaderConfig"}],"title":"config","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit17GTUIRefreshHeaderC6configAA0bC6ConfigCvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeader"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeader":{"role":"symbol","title":"GTUIRefreshHeader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRefreshHeader"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIRefreshHeader"}],"url":"\/documentation\/gtuikit\/gtuirefreshheader"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeaderConfig":{"role":"symbol","title":"GTUIRefreshHeaderConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeaderConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}],"url":"\/documentation\/gtuikit\/gtuirefreshheaderconfig"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRefreshHeader/config":{"role":"symbol","title":"config","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIRefreshHeaderConfig","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIRefreshHeaderConfig"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRefreshHeader\/config","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuirefreshheader\/config"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRefreshHeader\/title","value":"GTUIRefreshHeader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRefreshHeader\/fragments","value":[{"kind":"identifier","text":"GTUIRefreshHeader"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRefreshHeaderConfig\/title","value":"GTUIRefreshHeaderConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRefreshHeaderConfig\/fragments","value":[{"kind":"identifier","text":"GTUIRefreshHeaderConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}