{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarView","text":"GTAvatarView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtavatarviewv3\/avatar"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3\/avatar","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAvatarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarView"}],"title":"avatar","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit14GTAvatarViewV3C6avatarAA0bC0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarViewV3/avatar":{"role":"symbol","title":"avatar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTAvatarView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTAvatarView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3\/avatar","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtavatarviewv3\/avatar"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarViewV3":{"role":"symbol","title":"GTAvatarViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAvatarViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAvatarViewV3"}],"url":"\/documentation\/gtuikit\/gtavatarviewv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTAvatarView":{"role":"symbol","title":"GTAvatarView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTAvatarView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTAvatarView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTAvatarView"}],"url":"\/documentation\/gtuikit\/gtavatarview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarViewV3\/title","value":"GTAvatarViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarViewV3\/fragments","value":[{"kind":"identifier","text":"GTAvatarViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarView\/title","value":"GTAvatarView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTAvatarView\/fragments","value":[{"kind":"identifier","text":"GTAvatarView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}