{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundRectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIRoundRectView","text":"GTUIRoundRectView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuiroundrectcell\/roundrectview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCell\/roundRectView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundRectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIRoundRectView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIRoundRectView"}],"title":"roundRectView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit17GTUIRoundRectCellC05roundC4ViewAA0bcF0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCell"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRoundRectCell/roundRectView":{"role":"symbol","title":"roundRectView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundRectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIRoundRectView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIRoundRectView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCell\/roundRectView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuiroundrectcell\/roundrectview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRoundRectCell":{"role":"symbol","title":"GTUIRoundRectCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRoundRectCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIRoundRectCell"}],"url":"\/documentation\/gtuikit\/gtuiroundrectcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRoundRectView":{"role":"symbol","title":"GTUIRoundRectView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRoundRectView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIRoundRectView"}],"url":"\/documentation\/gtuikit\/gtuiroundrectview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectCell\/title","value":"GTUIRoundRectCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectCell\/fragments","value":[{"kind":"identifier","text":"GTUIRoundRectCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectView\/title","value":"GTUIRoundRectView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectView\/fragments","value":[{"kind":"identifier","text":"GTUIRoundRectView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}