{"variants":[{"paths":["\/documentation\/gtuikit\/gtnoticebar\/fspagerviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtnoticebar\/fspagerviewdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/FSPagerViewDataSource-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/numberOfItems(in:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/pagerView(_:cellForItemAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"FSPagerViewDataSource Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar/pagerView(_:cellForItemAt:)":{"role":"symbol","title":"pagerView(_:cellForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pagerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FSPagerViewCell","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerViewCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/pagerView(_:cellForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pagerView:cellForItemAtIndex:"}],"url":"\/documentation\/gtuikit\/gtnoticebar\/pagerview(_:cellforitemat:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar":{"role":"symbol","title":"GTNoticeBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTNoticeBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTNoticeBar"}],"url":"\/documentation\/gtuikit\/gtnoticebar"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTNoticeBar/numberOfItems(in:)":{"role":"symbol","title":"numberOfItems(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FSPagerView","preciseIdentifier":"c:@M@FSPagerView@objc(cs)FSPagerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/numberOfItems(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfItemsInPagerView:"}],"url":"\/documentation\/gtuikit\/gtnoticebar\/numberofitems(in:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/numberOfItems(in:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTNoticeBar\/pagerView(_:cellForItemAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar~1pagerView(_:cellForItemAt:)\/title","value":"pagerView:cellForItemAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar~1pagerView(_:cellForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pagerView:cellForItemAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar\/title","value":"GTNoticeBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar\/fragments","value":[{"kind":"identifier","text":"GTNoticeBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar~1numberOfItems(in:)\/title","value":"numberOfItemsInPagerView:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTNoticeBar~1numberOfItems(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfItemsInPagerView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}