{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":" "},{"kind":"internalParam","text":"range"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":" "},{"kind":"internalParam","text":"string"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtsearchbarview\/textfield(_:shouldchangecharactersin:replacementstring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtsearchbarview\/textfield(_:shouldchangecharactersin:replacementstring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textField(_:shouldChangeCharactersIn:replacementString:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITextFieldDelegate.textField(_:shouldChangeCharactersIn:replacementString:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}],"role":"symbol","title":"textField(_:shouldChangeCharactersIn:replacementString:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTSearchBarView(im)textField:shouldChangeCharactersInRange:replacementString:","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/UITextFieldDelegate-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView/UITextFieldDelegate-Implementations":{"role":"collectionGroup","title":"UITextFieldDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/UITextFieldDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtsearchbarview\/uitextfielddelegate-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView/textField(_:shouldChangeCharactersIn:replacementString:)":{"role":"symbol","title":"textField(_:shouldChangeCharactersIn:replacementString:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView\/textField(_:shouldChangeCharactersIn:replacementString:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}],"url":"\/documentation\/gtuikit\/gtsearchbarview\/textfield(_:shouldchangecharactersin:replacementstring:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSearchBarView":{"role":"symbol","title":"GTSearchBarView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSearchBarView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSearchBarView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSearchBarView"}],"url":"\/documentation\/gtuikit\/gtsearchbarview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"textField:shouldChangeCharactersInRange:replacementString:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"textField:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldChangeCharactersInRange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@S@_NSRange"},{"kind":"text","text":") "},{"kind":"internalParam","text":"range"},{"kind":"text","text":" "},{"kind":"identifier","text":"replacementString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"string"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textField(_:shouldChangeCharactersIn:replacementString:)\/title","value":"textField:shouldChangeCharactersInRange:replacementString:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView~1textField(_:shouldChangeCharactersIn:replacementString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView\/title","value":"GTSearchBarView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSearchBarView\/fragments","value":[{"kind":"identifier","text":"GTSearchBarView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}