{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customLayoutAtTarget"},{"kind":"text","text":"("},{"kind":"externalParam","text":"popView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPopView","text":"GTPopView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtpopviewprotocol\/customlayoutattarget(popview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtpopviewprotocol\/customlayoutattarget(popview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopViewProtocol\/customLayoutAtTarget(popView:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"customLayoutAtTargetWithPopView:"}],"role":"symbol","title":"customLayoutAtTarget(popView:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customLayoutAtTarget"},{"kind":"text","text":"("},{"kind":"externalParam","text":"popView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPopView"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@GTUIKit@objc(pl)GTPopViewProtocol(im)customLayoutAtTargetWithPopView:","required":true,"modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopViewProtocol"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopViewProtocol":{"role":"symbol","title":"GTPopViewProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopViewProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopViewProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopViewProtocol"}],"url":"\/documentation\/gtuikit\/gtpopviewprotocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopViewProtocol/customLayoutAtTarget(popView:)":{"navigatorTitle":[{"kind":"identifier","text":"customLayoutAtTargetWithPopView:"}],"role":"symbol","title":"customLayoutAtTarget(popView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customLayoutAtTarget"},{"kind":"text","text":"("},{"kind":"externalParam","text":"popView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPopView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopViewProtocol\/customLayoutAtTarget(popView:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtpopviewprotocol\/customlayoutattarget(popview:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopView":{"role":"symbol","title":"GTPopView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopView"}],"url":"\/documentation\/gtuikit\/gtpopview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"customLayoutAtTargetWithPopView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customLayoutAtTargetWithPopView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"customLayoutAtTargetWithPopView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTPopView","text":"GTPopView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"popView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopViewProtocol\/title","value":"GTPopViewProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopViewProtocol\/fragments","value":[{"kind":"identifier","text":"GTPopViewProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopViewProtocol~1customLayoutAtTarget(popView:)\/title","value":"customLayoutAtTargetWithPopView:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopViewProtocol~1customLayoutAtTarget(popView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customLayoutAtTargetWithPopView:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopView\/title","value":"GTPopView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopView\/fragments","value":[{"kind":"identifier","text":"GTPopView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}