{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startInteractiveTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"transitionContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmentinteractivetransition\/startinteractivetransition(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuisegmentinteractivetransition\/startinteractivetransition(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition\/startInteractiveTransition(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIViewControllerInteractiveTransitioning.startInteractiveTransition(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startInteractiveTransition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"title":"startInteractiveTransition(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTUISegmentInteractiveTransition(im)startInteractiveTransition:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"startInteractiveTransition:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition\/UIViewControllerInteractiveTransitioning-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentInteractiveTransition/startInteractiveTransition(_:)":{"role":"symbol","title":"startInteractiveTransition(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startInteractiveTransition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition\/startInteractiveTransition(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startInteractiveTransition:"}],"url":"\/documentation\/gtuikit\/gtuisegmentinteractivetransition\/startinteractivetransition(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentInteractiveTransition/UIViewControllerInteractiveTransitioning-Implementations":{"role":"collectionGroup","title":"UIViewControllerInteractiveTransitioning Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition\/UIViewControllerInteractiveTransitioning-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtuisegmentinteractivetransition\/uiviewcontrollerinteractivetransitioning-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentInteractiveTransition":{"role":"symbol","title":"GTUISegmentInteractiveTransition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}],"url":"\/documentation\/gtuikit\/gtuisegmentinteractivetransition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startInteractiveTransition:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startInteractiveTransition:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startInteractiveTransition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UIViewControllerContextTransitioning>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"transitionContext"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition~1startInteractiveTransition(_:)\/title","value":"startInteractiveTransition:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition~1startInteractiveTransition(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startInteractiveTransition:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition\/title","value":"GTUISegmentInteractiveTransition"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition\/fragments","value":[{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}