{"variants":[{"paths":["\/documentation\/gtuikit\/gtuisegmentinteractivetransition\/uiviewcontrollerinteractivetransitioning-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuisegmentinteractivetransition\/uiviewcontrollerinteractivetransitioning-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition\/UIViewControllerInteractiveTransitioning-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition\/startInteractiveTransition(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"UIViewControllerInteractiveTransitioning Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentInteractiveTransition":{"role":"symbol","title":"GTUISegmentInteractiveTransition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}],"url":"\/documentation\/gtuikit\/gtuisegmentinteractivetransition"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISegmentInteractiveTransition/startInteractiveTransition(_:)":{"role":"symbol","title":"startInteractiveTransition(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startInteractiveTransition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition\/startInteractiveTransition(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startInteractiveTransition:"}],"url":"\/documentation\/gtuikit\/gtuisegmentinteractivetransition\/startinteractivetransition(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISegmentInteractiveTransition\/startInteractiveTransition(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition\/title","value":"GTUISegmentInteractiveTransition"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition\/fragments","value":[{"kind":"identifier","text":"GTUISegmentInteractiveTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition~1startInteractiveTransition(_:)\/title","value":"startInteractiveTransition:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISegmentInteractiveTransition~1startInteractiveTransition(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startInteractiveTransition:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}