{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTActionItem","text":"GTActionItem"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtactionsheetview\/init(message:items:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetView\/init(message:items:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTActionItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTActionItem"},{"kind":"text","text":"])"}],"title":"init(message:items:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:7GTUIKit17GTActionSheetViewC7message5itemsACSSSg_SayAA0B4ItemCGtcfc","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionItem":{"role":"symbol","title":"GTActionItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTActionItem"}],"abstract":[{"type":"text","text":"GTActionSheetView 按钮"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTActionItem"}],"url":"\/documentation\/gtuikit\/gtactionitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionSheetView":{"role":"symbol","title":"GTActionSheetView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTActionSheetView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTActionSheetView"}],"url":"\/documentation\/gtuikit\/gtactionsheetview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTActionSheetView/init(message:items:)":{"role":"symbol","title":"init(message:items:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTActionItem","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTActionItem"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTActionSheetView\/init(message:items:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtactionsheetview\/init(message:items:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionItem\/title","value":"GTActionItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionItem\/fragments","value":[{"kind":"identifier","text":"GTActionItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionSheetView\/title","value":"GTActionSheetView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTActionSheetView\/fragments","value":[{"kind":"identifier","text":"GTActionSheetView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}