{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagRemoveButtonPressed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView","text":"TagView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagListView","text":"TagListView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/taglistviewdelegate\/tagremovebuttonpressed(_:tagview:sender:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/taglistviewdelegate\/tagremovebuttonpressed(_:tagview:sender:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate\/tagRemoveButtonPressed(_:tagView:sender:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"tagRemoveButtonPressed:tagView:sender:"}],"role":"symbol","title":"tagRemoveButtonPressed(_:tagView:sender:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagRemoveButtonPressed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagListView"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@GTUIKit@objc(pl)TagListViewDelegate(im)tagRemoveButtonPressed:tagView:sender:","required":true,"modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView":{"role":"symbol","title":"TagListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListView"}],"url":"\/documentation\/gtuikit\/taglistview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagView":{"role":"symbol","title":"TagView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagView"}],"url":"\/documentation\/gtuikit\/tagview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListViewDelegate":{"role":"symbol","title":"TagListViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListViewDelegate"}],"url":"\/documentation\/gtuikit\/taglistviewdelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListViewDelegate/tagRemoveButtonPressed(_:tagView:sender:)":{"navigatorTitle":[{"kind":"identifier","text":"tagRemoveButtonPressed:tagView:sender:"}],"role":"symbol","title":"tagRemoveButtonPressed(_:tagView:sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagRemoveButtonPressed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagListView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate\/tagRemoveButtonPressed(_:tagView:sender:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/taglistviewdelegate\/tagremovebuttonpressed(_:tagview:sender:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tagRemoveButtonPressed:tagView:sender:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tagRemoveButtonPressed:tagView:sender:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"tagRemoveButtonPressed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"title"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView","text":"TagView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tagView"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagListView","text":"TagListView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView\/title","value":"TagListView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView\/fragments","value":[{"kind":"identifier","text":"TagListView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView\/title","value":"TagView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagView\/fragments","value":[{"kind":"identifier","text":"TagView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListViewDelegate\/title","value":"TagListViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListViewDelegate\/fragments","value":[{"kind":"identifier","text":"TagListViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListViewDelegate~1tagRemoveButtonPressed(_:tagView:sender:)\/title","value":"tagRemoveButtonPressed:tagView:sender:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListViewDelegate~1tagRemoveButtonPressed(_:tagView:sender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tagRemoveButtonPressed:tagView:sender:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}