{"variants":[{"paths":["\/documentation\/gtuikit\/gtsliderview\/asvaluetrackingsliderdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtsliderview\/asvaluetrackingsliderdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView\/ASValueTrackingSliderDataSource-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView\/slider(_:stringForValue:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"ASValueTrackingSliderDataSource Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSliderView/slider(_:stringForValue:)":{"role":"symbol","title":"slider(_:stringForValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASValueTrackingSlider","preciseIdentifier":"c:objc(cs)ASValueTrackingSlider"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"stringForValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView\/slider(_:stringForValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"slider:stringForValue:"}],"url":"\/documentation\/gtuikit\/gtsliderview\/slider(_:stringforvalue:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSliderView":{"role":"symbol","title":"GTSliderView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSliderView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSliderView"}],"url":"\/documentation\/gtuikit\/gtsliderview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView\/slider(_:stringForValue:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSliderView~1slider(_:stringForValue:)\/title","value":"slider:stringForValue:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSliderView~1slider(_:stringForValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"slider:stringForValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSliderView\/title","value":"GTSliderView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSliderView\/fragments","value":[{"kind":"identifier","text":"GTSliderView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}