{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"slider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASValueTrackingSlider","preciseIdentifier":"c:objc(cs)ASValueTrackingSlider"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"stringForValue"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtsliderview\/slider(_:stringforvalue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtsliderview\/slider(_:stringforvalue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView\/slider(_:stringForValue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ASValueTrackingSliderDataSource.slider(_:stringForValue:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"slider:stringForValue:"}],"role":"symbol","title":"slider(_:stringForValue:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASValueTrackingSlider","preciseIdentifier":"c:objc(cs)ASValueTrackingSlider"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"stringForValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTSliderView(im)slider:stringForValue:","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView\/ASValueTrackingSliderDataSource-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSliderView/ASValueTrackingSliderDataSource-Implementations":{"role":"collectionGroup","title":"ASValueTrackingSliderDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView\/ASValueTrackingSliderDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtsliderview\/asvaluetrackingsliderdatasource-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSliderView":{"role":"symbol","title":"GTSliderView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSliderView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSliderView"}],"url":"\/documentation\/gtuikit\/gtsliderview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSliderView/slider(_:stringForValue:)":{"role":"symbol","title":"slider(_:stringForValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASValueTrackingSlider","preciseIdentifier":"c:objc(cs)ASValueTrackingSlider"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"stringForValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSliderView\/slider(_:stringForValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"slider:stringForValue:"}],"url":"\/documentation\/gtuikit\/gtsliderview\/slider(_:stringforvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"slider:stringForValue:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"slider:stringForValue:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"slider:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASValueTrackingSlider","preciseIdentifier":"c:objc(cs)ASValueTrackingSlider"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"slider"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringForValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSliderView\/title","value":"GTSliderView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSliderView\/fragments","value":[{"kind":"identifier","text":"GTSliderView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSliderView~1slider(_:stringForValue:)\/title","value":"slider:stringForValue:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSliderView~1slider(_:stringForValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"slider:stringForValue:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}