{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView","text":"GTStepsItemView"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtstepsview\/init(message:items:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView\/init(message:items:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView"},{"kind":"text","text":"])"}],"title":"init(message:items:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:7GTUIKit11GTStepsViewC7message5itemsACSSSg_SayAA0b4ItemC0CGtcfc","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsView":{"role":"symbol","title":"GTStepsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepsView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepsView"}],"url":"\/documentation\/gtuikit\/gtstepsview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsView/init(message:items:)":{"role":"symbol","title":"init(message:items:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView\/init(message:items:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtstepsview\/init(message:items:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsItemView":{"role":"symbol","title":"GTStepsItemView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepsItemView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepsItemView"}],"url":"\/documentation\/gtuikit\/gtstepsitemview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsView\/title","value":"GTStepsView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsView\/fragments","value":[{"kind":"identifier","text":"GTStepsView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsItemView\/title","value":"GTStepsItemView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsItemView\/fragments","value":[{"kind":"identifier","text":"GTStepsItemView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}