{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsViewDelegate","preciseIdentifier":"s:7GTUIKit19GTStepsViewDelegateP","text":"GTStepsViewDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView","text":"GTStepsItemView"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"event"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsView","text":"GTStepsView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsView","text":"GTStepsView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtstepsview\/show(title:message:delegate:items:event:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView\/show(title:message:delegate:items:event:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"show(title:message:delegate:items:event:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTStepsViewDelegate","preciseIdentifier":"s:7GTUIKit19GTStepsViewDelegateP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"event"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"GTStepsView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"GTStepsView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsView"}],"symbolKind":"method","externalID":"s:7GTUIKit11GTStepsViewC4show5title7message8delegate5items5eventACSSSg_AjA0bC8Delegate_pSayAA0b4ItemC0CGyACcSgtFZ","extendedModule":"GTUIKit","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsView":{"role":"symbol","title":"GTStepsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepsView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepsView"}],"url":"\/documentation\/gtuikit\/gtstepsview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsViewDelegate":{"role":"symbol","title":"GTStepsViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepsViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepsViewDelegate"}],"url":"\/documentation\/gtuikit\/gtstepsviewdelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsView/show(title:message:delegate:items:event:)":{"role":"symbol","title":"show(title:message:delegate:items:event:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTStepsViewDelegate","preciseIdentifier":"s:7GTUIKit19GTStepsViewDelegateP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTStepsItemView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsItemView"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"event"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"GTStepsView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"GTStepsView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTStepsView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsView\/show(title:message:delegate:items:event:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtstepsview\/show(title:message:delegate:items:event:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTStepsItemView":{"role":"symbol","title":"GTStepsItemView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTStepsItemView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTStepsItemView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTStepsItemView"}],"url":"\/documentation\/gtuikit\/gtstepsitemview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsView\/title","value":"GTStepsView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsView\/fragments","value":[{"kind":"identifier","text":"GTStepsView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsItemView\/title","value":"GTStepsItemView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTStepsItemView\/fragments","value":[{"kind":"identifier","text":"GTStepsItemView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}