{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemBadgeView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemBadgeView","text":"ESTabBarItemBadgeView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/estabbaritemcontentview\/badgeview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ESTabBarItemBadgeView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemBadgeView"}],"title":"badgeView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit23ESTabBarItemContentViewC05badgeF0AA0bcd5BadgeF0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView":{"role":"symbol","title":"ESTabBarItemContentView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItemContentView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarItemContentView"}],"url":"\/documentation\/gtuikit\/estabbaritemcontentview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/badgeView":{"role":"symbol","title":"badgeView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ESTabBarItemBadgeView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemBadgeView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/badgeview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemBadgeView":{"role":"symbol","title":"ESTabBarItemBadgeView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItemBadgeView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemBadgeView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarItemBadgeView"}],"url":"\/documentation\/gtuikit\/estabbaritembadgeview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView\/title","value":"ESTabBarItemContentView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView\/fragments","value":[{"kind":"identifier","text":"ESTabBarItemContentView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemBadgeView\/title","value":"ESTabBarItemBadgeView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemBadgeView\/fragments","value":[{"kind":"identifier","text":"ESTabBarItemBadgeView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}