{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource","preciseIdentifier":"c:@M@GTUIKit@objc(pl)LYpageViewDataSource","text":"LYpageViewDataSource"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/lypageview\/datasource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/lypageview\/datasource"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageView\/dataSource","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LYpageViewDataSource","preciseIdentifier":"c:@M@GTUIKit@objc(pl)LYpageViewDataSource"},{"kind":"text","text":"?"}],"title":"dataSource","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@GTUIKit@objc(cs)LYPageView(py)dataSource","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"dataSource"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYPageView":{"role":"symbol","title":"LYPageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYPageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LYPageView"}],"url":"\/documentation\/gtuikit\/lypageview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYPageView/dataSource":{"role":"symbol","title":"dataSource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LYpageViewDataSource","preciseIdentifier":"c:@M@GTUIKit@objc(pl)LYpageViewDataSource"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYPageView\/dataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataSource"}],"url":"\/documentation\/gtuikit\/lypageview\/datasource"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYpageViewDataSource":{"role":"symbol","title":"LYpageViewDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYpageViewDataSource"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LYpageViewDataSource"}],"url":"\/documentation\/gtuikit\/lypageviewdatasource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dataSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dataSource"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<LYpageViewDataSource>","preciseIdentifier":"c:Qo@M@GTUIKit@objc(pl)LYpageViewDataSource"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dataSource"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageView\/title","value":"LYPageView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageView\/fragments","value":[{"kind":"identifier","text":"LYPageView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageView~1dataSource\/title","value":"dataSource"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYPageView~1dataSource\/fragments","value":[{"kind":"identifier","text":"dataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource\/title","value":"LYpageViewDataSource"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource\/fragments","value":[{"kind":"identifier","text":"LYpageViewDataSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}