{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDidStop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"anim"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CAAnimation","preciseIdentifier":"c:objc(cs)CAAnimation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtdotloadinganimationview\/animationdidstop(_:finished:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtdotloadinganimationview\/animationdidstop(_:finished:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView\/animationDidStop(_:finished:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CAAnimationDelegate.animationDidStop(_:finished:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDidStop"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CAAnimation","preciseIdentifier":"c:objc(cs)CAAnimation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"animationDidStop(_:finished:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@GTUIKit@objc(cs)GTDotLoadingAnimationView(im)animationDidStop:finished:","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"animationDidStop:finished:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView\/CAAnimationDelegate-Implementations"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDotLoadingAnimationView/CAAnimationDelegate-Implementations":{"role":"collectionGroup","title":"CAAnimationDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView\/CAAnimationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtuikit\/gtdotloadinganimationview\/caanimationdelegate-implementations"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDotLoadingAnimationView/animationDidStop(_:finished:)":{"role":"symbol","title":"animationDidStop(_:finished:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDidStop"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CAAnimation","preciseIdentifier":"c:objc(cs)CAAnimation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView\/animationDidStop(_:finished:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationDidStop:finished:"}],"url":"\/documentation\/gtuikit\/gtdotloadinganimationview\/animationdidstop(_:finished:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDotLoadingAnimationView":{"role":"symbol","title":"GTDotLoadingAnimationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDotLoadingAnimationView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTDotLoadingAnimationView"}],"url":"\/documentation\/gtuikit\/gtdotloadinganimationview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"animationDidStop:finished:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationDidStop:finished:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"animationDidStop:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CAAnimation","preciseIdentifier":"c:objc(cs)CAAnimation"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"anim"},{"kind":"text","text":" "},{"kind":"identifier","text":"finished:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"flag"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDotLoadingAnimationView~1animationDidStop(_:finished:)\/title","value":"animationDidStop:finished:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDotLoadingAnimationView~1animationDidStop(_:finished:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationDidStop:finished:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDotLoadingAnimationView\/title","value":"GTDotLoadingAnimationView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDotLoadingAnimationView\/fragments","value":[{"kind":"identifier","text":"GTDotLoadingAnimationView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}