{"variants":[{"paths":["\/documentation\/gtuikit\/gtdotloadinganimationview\/caanimationdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtdotloadinganimationview\/caanimationdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView\/CAAnimationDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView\/animationDidStop(_:finished:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTUIKit"}],"role":"collectionGroup","title":"CAAnimationDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDotLoadingAnimationView/animationDidStop(_:finished:)":{"role":"symbol","title":"animationDidStop(_:finished:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDidStop"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CAAnimation","preciseIdentifier":"c:objc(cs)CAAnimation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView\/animationDidStop(_:finished:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationDidStop:finished:"}],"url":"\/documentation\/gtuikit\/gtdotloadinganimationview\/animationdidstop(_:finished:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTDotLoadingAnimationView":{"role":"symbol","title":"GTDotLoadingAnimationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTDotLoadingAnimationView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTDotLoadingAnimationView"}],"url":"\/documentation\/gtuikit\/gtdotloadinganimationview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTDotLoadingAnimationView\/animationDidStop(_:finished:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDotLoadingAnimationView~1animationDidStop(_:finished:)\/title","value":"animationDidStop:finished:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDotLoadingAnimationView~1animationDidStop(_:finished:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationDidStop:finished:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDotLoadingAnimationView\/title","value":"GTDotLoadingAnimationView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTDotLoadingAnimationView\/fragments","value":[{"kind":"identifier","text":"GTDotLoadingAnimationView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}