{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_keyboardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThemeKeyboardAppearancePicker","preciseIdentifier":"s:7GTUIKit31GTThemeKeyboardAppearancePickera","text":"GTThemeKeyboardAppearancePicker"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuitextview\/gt_keyboardappearance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuitextview\/gt_keyboardappearance"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView\/gt_keyboardAppearance","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_keyboardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTThemeKeyboardAppearancePicker","preciseIdentifier":"s:7GTUIKit31GTThemeKeyboardAppearancePickera"},{"kind":"text","text":"?"}],"title":"gt_keyboardAppearance","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@CM@GTUIKit@objc(cs)GTUITextView(py)gt_keyboardAppearance","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"gt_keyboardAppearance"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITextView/gt_keyboardAppearance":{"role":"symbol","title":"gt_keyboardAppearance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_keyboardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTThemeKeyboardAppearancePicker","preciseIdentifier":"s:7GTUIKit31GTThemeKeyboardAppearancePickera"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView\/gt_keyboardAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_keyboardAppearance"}],"url":"\/documentation\/gtuikit\/gtuitextview\/gt_keyboardappearance"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITextView":{"role":"symbol","title":"GTUITextView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITextView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITextView"}],"url":"\/documentation\/gtuikit\/gtuitextview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTThemeKeyboardAppearancePicker":{"role":"symbol","title":"GTThemeKeyboardAppearancePicker","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTThemeKeyboardAppearancePicker"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThemeKeyboardAppearancePicker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTThemeKeyboardAppearancePicker"}],"url":"\/documentation\/gtuikit\/gtthemekeyboardappearancepicker"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"gt_keyboardAppearance"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"gt_keyboardAppearance"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ThemeKeyboardAppearancePicker","preciseIdentifier":"c:objc(cs)ThemeKeyboardAppearancePicker"},{"kind":"text","text":" * "},{"kind":"identifier","text":"gt_keyboardAppearance"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView~1gt_keyboardAppearance\/title","value":"gt_keyboardAppearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView~1gt_keyboardAppearance\/fragments","value":[{"kind":"identifier","text":"gt_keyboardAppearance"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView\/title","value":"GTUITextView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView\/fragments","value":[{"kind":"identifier","text":"GTUITextView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}