{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButton","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIButton","text":"GTUIButton"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtbasealertview\/closebutton"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView\/closeButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIButton","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIButton"}],"title":"closeButton","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit15GTBaseAlertViewC11closeButtonAA10GTUIButtonCvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButton":{"role":"symbol","title":"GTUIButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIButton"}],"url":"\/documentation\/gtuikit\/gtuibutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBaseAlertView":{"role":"symbol","title":"GTBaseAlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTBaseAlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTBaseAlertView"}],"url":"\/documentation\/gtuikit\/gtbasealertview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTBaseAlertView/closeButton":{"role":"symbol","title":"closeButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUIButton","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUIButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTBaseAlertView\/closeButton","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtbasealertview\/closebutton"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButton\/title","value":"GTUIButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButton\/fragments","value":[{"kind":"identifier","text":"GTUIButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBaseAlertView\/title","value":"GTBaseAlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTBaseAlertView\/fragments","value":[{"kind":"identifier","text":"GTBaseAlertView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}