{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItemContentView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/estabbaritemcontentview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/estabbaritemcontentview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemMoreContentView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTabBarItemBaseContentView"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/backdropColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeOffset","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeValue","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlightBackdropColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlightEnabled","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlightIconColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlightTextColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlighted","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/iconColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/image","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/imageView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/insets","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/itemContentMode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/renderingMode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/selected","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/selectedImage","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/textColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/title","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeChangedAnimation(animated:completion:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/dehighlightAnimation(animated:completion:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/deselectAnimation(animated:completion:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlightAnimation(animated:completion:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/reselectAnimation(animated:completion:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/selectAnimation(animated:completion:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/updateDisplay()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/updateLayout()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItemContentView"}],"title":"ESTabBarItemContentView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)ESTabBarItemContentView","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ESTabBarItemContentView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/highlightAnimation(animated:completion:)":{"role":"symbol","title":"highlightAnimation(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlightAnimation(animated:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/highlightanimation(animated:completion:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/title","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/title"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/highlightEnabled":{"role":"symbol","title":"highlightEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"是否支持高亮"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlightEnabled","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/highlightenabled"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/backdropColor":{"role":"symbol","title":"backdropColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backdropColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"背景颜色"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/backdropColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/backdropcolor"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/highlightIconColor":{"role":"symbol","title":"highlightIconColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightIconColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"高亮时icon颜色"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlightIconColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/highlighticoncolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/insets":{"role":"symbol","title":"insets","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"insets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[{"type":"text","text":"设置contentView的偏移"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/insets","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/insets"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/highlighted":{"role":"symbol","title":"highlighted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"是否处于高亮状态"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlighted","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/highlighted"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/highlightBackdropColor":{"role":"symbol","title":"highlightBackdropColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightBackdropColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"高亮时背景颜色"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlightBackdropColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/highlightbackdropcolor"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/updateDisplay()":{"role":"symbol","title":"updateDisplay()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDisplay"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/updateDisplay()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/updatedisplay()"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/gtuikit\/estabbaritemcontentview\/init(coder:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/renderingMode":{"role":"symbol","title":"renderingMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"RenderingMode","preciseIdentifier":"c:@E@UIImageRenderingMode"}],"abstract":[{"type":"text","text":"Icon imageView renderingMode, default is .alwaysTemplate like UITabBarItem"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/renderingMode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/renderingmode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/imageView":{"role":"symbol","title":"imageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/imageView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/imageview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/selectAnimation(animated:completion:)":{"role":"symbol","title":"selectAnimation(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/selectAnimation(animated:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/selectanimation(animated:completion:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/deselectAnimation(animated:completion:)":{"role":"symbol","title":"deselectAnimation(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deselectAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/deselectAnimation(animated:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/deselectanimation(animated:completion:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/selectedImage":{"role":"symbol","title":"selectedImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/selectedImage","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/selectedimage"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView":{"role":"symbol","title":"ESTabBarItemContentView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItemContentView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarItemContentView"}],"url":"\/documentation\/gtuikit\/estabbaritemcontentview"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/selected":{"role":"symbol","title":"selected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"是否被选中"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/selected","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/selected"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemMoreContentView":{"role":"symbol","title":"ESTabBarItemMoreContentView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItemMoreContentView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemMoreContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ESTabBarItemMoreContentView"}],"url":"\/documentation\/gtuikit\/estabbaritemmorecontentview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTabBarItemBaseContentView":{"role":"symbol","title":"GTTabBarItemBaseContentView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTabBarItemBaseContentView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTabBarItemBaseContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTabBarItemBaseContentView"}],"url":"\/documentation\/gtuikit\/gttabbaritembasecontentview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/badgeColor":{"role":"symbol","title":"badgeColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/badgecolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/image":{"role":"symbol","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Icon imageView’s image"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/image","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/image"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/badgeOffset":{"role":"symbol","title":"badgeOffset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOffset","preciseIdentifier":"c:@S@UIOffset"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeOffset","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/badgeoffset"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/badgeView":{"role":"symbol","title":"badgeView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ESTabBarItemBadgeView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)ESTabBarItemBadgeView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/badgeview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/dehighlightAnimation(animated:completion:)":{"role":"symbol","title":"dehighlightAnimation(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dehighlightAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/dehighlightAnimation(animated:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/dehighlightanimation(animated:completion:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/reselectAnimation(animated:completion:)":{"role":"symbol","title":"reselectAnimation(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reselectAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/reselectAnimation(animated:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/reselectanimation(animated:completion:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyType":{"role":"symbol","title":"GTEmptyType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyType"}],"url":"\/documentation\/gtuikit\/gtemptytype"},"doc://org.cocoapods.GTUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/highlightTextColor":{"role":"symbol","title":"highlightTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"高亮时文字颜色"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/highlightTextColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/highlighttextcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/updateLayout()":{"role":"symbol","title":"updateLayout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateLayout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/updateLayout()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/updatelayout()"},"doc://org.cocoapods.GTUIKit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.GTUIKit/9PinLayout10LayoutableP":{"type":"unresolvable","title":"PinLayout.Layoutable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/titleLabel","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/titlelabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/gtuikit\/estabbaritemcontentview\/init(frame:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/badgeChangedAnimation(animated:completion:)":{"role":"symbol","title":"badgeChangedAnimation(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeChangedAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeChangedAnimation(animated:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/badgechangedanimation(animated:completion:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/textColor":{"role":"symbol","title":"textColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"文字颜色"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/textColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/textcolor"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/12SkeletonView0aB8ExtendedP":{"type":"unresolvable","title":"SkeletonView.SkeletonViewExtended","identifier":"doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/iconColor":{"role":"symbol","title":"iconColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"icon颜色"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/iconColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/iconcolor"},"doc://org.cocoapods.GTUIKit/9PinLayout18AutoSizeCalculableP":{"type":"unresolvable","title":"PinLayout.AutoSizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/badgeValue":{"role":"symbol","title":"badgeValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Badge value"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/badgeValue","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/badgevalue"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/ESTabBarItemContentView/itemContentMode":{"role":"symbol","title":"itemContentMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemContentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ESTabBarItemContentMode","preciseIdentifier":"s:7GTUIKit23ESTabBarItemContentModeO"}],"abstract":[{"type":"text","text":"Item content mode, default is .alwaysTemplate like UITabBarItem"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/itemContentMode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/estabbaritemcontentview\/itemcontentmode"},"doc://org.cocoapods.GTUIKit/9PinLayout14SizeCalculableP":{"type":"unresolvable","title":"PinLayout.SizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ESTabBarItemContentView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ESTabBarItemContentView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ESTabBarItemContentView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemContentView\/init(frame:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/ESTabBarItemMoreContentView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTabBarItemBaseContentView"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ESTabBarItemContentView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView\/title","value":"ESTabBarItemContentView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView\/fragments","value":[{"kind":"identifier","text":"ESTabBarItemContentView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemMoreContentView\/title","value":"ESTabBarItemMoreContentView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemMoreContentView\/fragments","value":[{"kind":"identifier","text":"ESTabBarItemMoreContentView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTabBarItemBaseContentView\/title","value":"GTTabBarItemBaseContentView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTabBarItemBaseContentView\/fragments","value":[{"kind":"identifier","text":"GTTabBarItemBaseContentView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1ESTabBarItemContentView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}