{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBoxGroup"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtcheckboxgroup"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtcheckboxgroup"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/init(mode:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/mode-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/add(_:)-20966","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/add(_:)-2m8sn","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/delete(_:)-7q31a","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/delete(_:)-vgzh"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/Mode-swift.enum"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBoxGroup"}],"title":"GTCheckBoxGroup","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTCheckBoxGroup","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTCheckBoxGroup"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxGroup/mode-swift.property":{"role":"symbol","title":"mode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:7GTUIKit15GTCheckBoxGroupC4ModeO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/mode-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtcheckboxgroup\/mode-swift.property"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxGroup/delete(_:)-7q31a":{"role":"symbol","title":"delete(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"GTCheckBoxGroup","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTCheckBoxGroup"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/delete(_:)-7q31a","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtcheckboxgroup\/delete(_:)-7q31a"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxGroup/add(_:)-2m8sn":{"role":"symbol","title":"add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GTCheckBoxGroup","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTCheckBoxGroup"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/add(_:)-2m8sn","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtcheckboxgroup\/add(_:)-2m8sn"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxGroup/add(_:)-20966":{"role":"symbol","title":"add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"GTCheckBoxGroup","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTCheckBoxGroup"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/add(_:)-20966","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtcheckboxgroup\/add(_:)-20966"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxGroup/init(mode:)":{"role":"symbol","title":"init(mode:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:7GTUIKit15GTCheckBoxGroupC4ModeO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/init(mode:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtcheckboxgroup\/init(mode:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxGroup/delete(_:)-vgzh":{"role":"symbol","title":"delete(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GTCheckBoxGroup","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTCheckBoxGroup"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/delete(_:)-vgzh","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtcheckboxgroup\/delete(_:)-vgzh"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxGroup":{"role":"symbol","title":"GTCheckBoxGroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBoxGroup"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBoxGroup"}],"url":"\/documentation\/gtuikit\/gtcheckboxgroup"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxGroup/Mode-swift.enum":{"role":"symbol","title":"GTCheckBoxGroup.Mode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxGroup\/Mode-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"url":"\/documentation\/gtuikit\/gtcheckboxgroup\/mode-swift.enum"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTCheckBoxGroup"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTCheckBoxGroup"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTCheckBoxGroup"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBoxGroup"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxGroup\/title","value":"GTCheckBoxGroup"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxGroup\/fragments","value":[{"kind":"identifier","text":"GTCheckBoxGroup"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}