{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTIconLeftRightTextNode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gticonleftrighttextnode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gticonleftrighttextnode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/init(horizontalSpace:middleSpace:verticalSpace:iconPosition:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/iconfontClosure","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/iconfontColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/iconfontNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/iconfontSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/iconfontText","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftAligment","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftFont","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftMaxNumber","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftText","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftTextClosure","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftTextColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightAligment","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightFont","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightMaxNumber","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightNode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightText","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightTextClosure","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightTextColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/layoutSpecThatFits(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTIconLeftRightTextNode"}],"title":"GTIconLeftRightTextNode","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTIconLeftRightTextNode","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTIconLeftRightTextNode"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/leftFont":{"role":"symbol","title":"leftFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftFont","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/leftfont"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/iconfontSize":{"role":"symbol","title":"iconfontSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconfontSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/iconfontSize","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/iconfontsize"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/layoutSpecThatFits(_:)":{"role":"symbol","title":"layoutSpecThatFits(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSpecThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASSizeRange","preciseIdentifier":"c:@SA@ASSizeRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASLayoutSpec","preciseIdentifier":"c:objc(cs)ASLayoutSpec"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/layoutSpecThatFits(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSpecThatFits:"}],"url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/layoutspecthatfits(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/iconfontColor":{"role":"symbol","title":"iconfontColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconfontColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/iconfontColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/iconfontcolor"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/objc(pl)ASTraitEnvironment":{"type":"unresolvable","title":"AsyncDisplayKit.ASTraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASTraitEnvironment"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/rightFont":{"role":"symbol","title":"rightFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightFont","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/rightfont"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/iconfontText":{"role":"symbol","title":"iconfontText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconfontText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/iconfontText","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/iconfonttext"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/rightAligment":{"role":"symbol","title":"rightAligment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightAligment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightAligment","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/rightaligment"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElement":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElement","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElement"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementExtensibility":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementExtensibility","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementExtensibility"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/rightTextColor":{"role":"symbol","title":"rightTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightTextColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/righttextcolor"},"doc://org.cocoapods.GTUIKit/objc(cs)ASDisplayNode":{"type":"unresolvable","title":"ASDisplayNode","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/leftText":{"role":"symbol","title":"leftText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftText","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/lefttext"},"doc://org.cocoapods.GTUIKit/objc(pl)ASDebugNameProvider":{"type":"unresolvable","title":"AsyncDisplayKit.ASDebugNameProvider","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASDebugNameProvider"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/iconfontNode":{"role":"symbol","title":"iconfontNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconfontNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASTextNode","preciseIdentifier":"c:objc(cs)ASTextNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/iconfontNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/iconfontnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/rightText":{"role":"symbol","title":"rightText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightText","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/righttext"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/rightTextClosure":{"role":"symbol","title":"rightTextClosure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTextClosure"},{"kind":"text","text":": (() -> ())?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightTextClosure","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/righttextclosure"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/leftTextColor":{"role":"symbol","title":"leftTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftTextColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/lefttextcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/init(horizontalSpace:middleSpace:verticalSpace:iconPosition:)":{"role":"symbol","title":"init(horizontalSpace:middleSpace:verticalSpace:iconPosition:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"horizontalSpace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"middleSpace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"verticalSpace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"iconPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTIconTextPosition","preciseIdentifier":"s:7GTUIKit18GTIconTextPositionO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/init(horizontalSpace:middleSpace:verticalSpace:iconPosition:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/init(horizontalspace:middlespace:verticalspace:iconposition:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/leftMaxNumber":{"role":"symbol","title":"leftMaxNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftMaxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftMaxNumber","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/leftmaxnumber"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/leftTextClosure":{"role":"symbol","title":"leftTextClosure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftTextClosure"},{"kind":"text","text":": (() -> ())?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftTextClosure","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/lefttextclosure"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLocking":{"type":"unresolvable","title":"AsyncDisplayKit.ASLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLocking"},"doc://org.cocoapods.GTUIKit/objc(pl)ASInterfaceStateDelegate":{"type":"unresolvable","title":"AsyncDisplayKit.ASInterfaceStateDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASInterfaceStateDelegate"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode":{"role":"symbol","title":"GTIconLeftRightTextNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTIconLeftRightTextNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTIconLeftRightTextNode"}],"url":"\/documentation\/gtuikit\/gticonleftrighttextnode"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementAsciiArtProtocol":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementAsciiArtProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementAsciiArtProtocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/rightMaxNumber":{"role":"symbol","title":"rightMaxNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightMaxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightMaxNumber","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/rightmaxnumber"},"doc://org.cocoapods.GTUIKit/objc(pl)NSLocking":{"type":"unresolvable","title":"Foundation.NSLocking","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSLocking"},"doc://org.cocoapods.GTUIKit/objc(pl)ASLayoutElementStylability":{"type":"unresolvable","title":"AsyncDisplayKit.ASLayoutElementStylability","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASLayoutElementStylability"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/leftAligment":{"role":"symbol","title":"leftAligment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftAligment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftAligment","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/leftaligment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/rightNode":{"role":"symbol","title":"rightNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASTextNode","preciseIdentifier":"c:objc(cs)ASTextNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/rightNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/rightnode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/iconfontClosure":{"role":"symbol","title":"iconfontClosure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconfontClosure"},{"kind":"text","text":": (() -> ())?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/iconfontClosure","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/iconfontclosure"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTIconLeftRightTextNode/leftNode":{"role":"symbol","title":"leftNode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftNode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASTextNode","preciseIdentifier":"c:objc(cs)ASTextNode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/leftNode","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gticonleftrighttextnode\/leftnode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTIconLeftRightTextNode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTIconLeftRightTextNode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTIconLeftRightTextNode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTIconLeftRightTextNode\/layoutSpecThatFits(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)ASDisplayNode"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTIconLeftRightTextNode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ASDisplayNode","preciseIdentifier":"c:objc(cs)ASDisplayNode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTIconLeftRightTextNode~1layoutSpecThatFits(_:)\/title","value":"layoutSpecThatFits:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTIconLeftRightTextNode~1layoutSpecThatFits(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSpecThatFits:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTIconLeftRightTextNode\/title","value":"GTIconLeftRightTextNode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTIconLeftRightTextNode\/fragments","value":[{"kind":"identifier","text":"GTIconLeftRightTextNode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}