{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverMenuView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtpopovermenuview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtpopovermenuview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICollectionViewDataSource","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICollectionViewDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView","interfaceLanguage":"swift"},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/MenuItem"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/init(mode:position:menuItems:popoverMaxWidth:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/arrowSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/dismissOnBackgroundTap","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/menuItems","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/mode-swift.property","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/onDismissBlock","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/onSelectedBlock","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/popoverColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/popoverMaxWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/popoverMinWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/position","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/sideEdge"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/collectionView(_:didSelectItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/collectionView(_:numberOfItemsInSection:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/dismiss()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/show(point:)"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/Mode-swift.enum"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverMenuView"}],"title":"GTPopoverMenuView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTPopoverMenuView","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTPopoverMenuView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIScrollViewDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/collectionView(_:cellForItemAt:)":{"role":"symbol","title":"collectionView(_:cellForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/collectionView(_:cellForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"url":"\/documentation\/gtuikit\/gtpopovermenuview\/collectionview(_:cellforitemat:)"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/sideEdge":{"role":"symbol","title":"sideEdge","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sideEdge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/sideEdge","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/sideedge"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverProtocol":{"role":"symbol","title":"GTPopoverProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopoverProtocol"}],"url":"\/documentation\/gtuikit\/gtpopoverprotocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/onSelectedBlock":{"role":"symbol","title":"onSelectedBlock","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSelectedBlock"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/onSelectedBlock","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/onselectedblock"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyType":{"role":"symbol","title":"GTEmptyType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyType"}],"url":"\/documentation\/gtuikit\/gtemptytype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/collectionView(_:didSelectItemAt:)":{"role":"symbol","title":"collectionView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/collectionView(_:didSelectItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"url":"\/documentation\/gtuikit\/gtpopovermenuview\/collectionview(_:didselectitemat:)"},"doc://org.cocoapods.GTUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.GTUIKit/9PinLayout10LayoutableP":{"type":"unresolvable","title":"PinLayout.Layoutable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.GTUIKit/9PinLayout14SizeCalculableP":{"type":"unresolvable","title":"PinLayout.SizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/show(point:)":{"role":"symbol","title":"show(point:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/show(point:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/show(point:)"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/dismissOnBackgroundTap":{"role":"symbol","title":"dismissOnBackgroundTap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissOnBackgroundTap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/dismissOnBackgroundTap","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/dismissonbackgroundtap"},"doc://org.cocoapods.GTUIKit/12SkeletonView0aB8ExtendedP":{"type":"unresolvable","title":"SkeletonView.SkeletonViewExtended","identifier":"doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/menuItems":{"role":"symbol","title":"menuItems","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"menuItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MenuItem","preciseIdentifier":"s:7GTUIKit17GTPopoverMenuViewC0C4ItemV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/menuItems","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/menuitems"},"doc://org.cocoapods.GTUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/Mode-swift.enum":{"role":"symbol","title":"GTPopoverMenuView.Mode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/Mode-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"url":"\/documentation\/gtuikit\/gtpopovermenuview\/mode-swift.enum"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"},"doc://org.cocoapods.GTUIKit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/arrowSize":{"role":"symbol","title":"arrowSize","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"arrowSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/arrowSize","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/arrowsize"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/position":{"role":"symbol","title":"position","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopoverPosition","preciseIdentifier":"s:7GTUIKit17GTPopoverPositionO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/position","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/position"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/MenuItem":{"role":"symbol","title":"GTPopoverMenuView.MenuItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/MenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenuItem"}],"url":"\/documentation\/gtuikit\/gtpopovermenuview\/menuitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/dismiss()":{"role":"symbol","title":"dismiss()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/dismiss()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/dismiss()"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView":{"role":"symbol","title":"GTPopoverMenuView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverMenuView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPopoverMenuView"}],"url":"\/documentation\/gtuikit\/gtpopovermenuview"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/onDismissBlock":{"role":"symbol","title":"onDismissBlock","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"os_block_t","preciseIdentifier":"c:@T@os_block_t"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/onDismissBlock","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/ondismissblock"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.GTUIKit/9PinLayout18AutoSizeCalculableP":{"type":"unresolvable","title":"PinLayout.AutoSizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/popoverMaxWidth":{"role":"symbol","title":"popoverMaxWidth","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"popoverMaxWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/popoverMaxWidth","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/popovermaxwidth"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/popoverColor":{"role":"symbol","title":"popoverColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"popoverColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/popoverColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/popovercolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/init(mode:position:menuItems:popoverMaxWidth:)":{"role":"symbol","title":"init(mode:position:menuItems:popoverMaxWidth:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:7GTUIKit17GTPopoverMenuViewC4ModeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTPopoverPosition","preciseIdentifier":"s:7GTUIKit17GTPopoverPositionO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"menuItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MenuItem","preciseIdentifier":"s:7GTUIKit17GTPopoverMenuViewC0C4ItemV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"popoverMaxWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/init(mode:position:menuItems:popoverMaxWidth:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/init(mode:position:menuitems:popovermaxwidth:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/collectionView(_:numberOfItemsInSection:)":{"role":"symbol","title":"collectionView(_:numberOfItemsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/collectionView(_:numberOfItemsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"url":"\/documentation\/gtuikit\/gtpopovermenuview\/collectionview(_:numberofitemsinsection:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/popoverMinWidth":{"role":"symbol","title":"popoverMinWidth","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"popoverMinWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/popoverMinWidth","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/popoverminwidth"},"doc://org.cocoapods.GTUIKit/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UICollectionViewDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICollectionViewDelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPopoverMenuView/mode-swift.property":{"role":"symbol","title":"mode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:7GTUIKit17GTPopoverMenuViewC4ModeO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/mode-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtpopovermenuview\/mode-swift.property"},"doc://org.cocoapods.GTUIKit/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","title":"UICollectionViewDataSource","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICollectionViewDataSource"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTPopoverMenuView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTPopoverMenuView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTPopoverMenuView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/collectionView(_:didSelectItemAt:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPopoverMenuView\/collectionView(_:numberOfItemsInSection:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICollectionViewDataSource","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICollectionViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPopoverMenuView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverMenuView~1collectionView(_:cellForItemAt:)\/title","value":"collectionView:cellForItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverMenuView~1collectionView(_:cellForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverMenuView~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverMenuView~1collectionView(_:didSelectItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverMenuView\/title","value":"GTPopoverMenuView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverMenuView\/fragments","value":[{"kind":"identifier","text":"GTPopoverMenuView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverMenuView~1collectionView(_:numberOfItemsInSection:)\/title","value":"collectionView:numberOfItemsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPopoverMenuView~1collectionView(_:numberOfItemsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}