{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewItemBaseProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuitableviewitembaseprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItemProtocol"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCellItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceTableViewCellItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/accessibilityIdentifier","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/cellClass","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/cellHeight","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/cellNib","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/cellTarget","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/identifier","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/target"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewItemBaseProtocol"}],"title":"GTUITableViewItemBaseProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit29GTUITableViewItemBaseProtocolP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUITableViewItemBaseProtocol"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewItemBaseProtocol/target":{"role":"symbol","title":"target","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"响应者"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/target","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewitembaseprotocol\/target"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewItemBaseProtocol/cellTarget":{"role":"symbol","title":"cellTarget","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellTarget"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUITableViewCellDelegate","preciseIdentifier":"s:7GTUIKit25GTUITableViewCellDelegateP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"响应者"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/cellTarget","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewitembaseprotocol\/celltarget"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewItemBaseProtocol/accessibilityIdentifier":{"role":"symbol","title":"accessibilityIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"辨识符"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/accessibilityIdentifier","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewitembaseprotocol\/accessibilityidentifier"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewItemBaseProtocol/cellClass":{"role":"symbol","title":"cellClass","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Cell类"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/cellClass","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewitembaseprotocol\/cellclass"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISpaceTableViewCellItem":{"role":"symbol","title":"GTUISpaceTableViewCellItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISpaceTableViewCellItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceTableViewCellItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISpaceTableViewCellItem"}],"url":"\/documentation\/gtuikit\/gtuispacetableviewcellitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewItemBaseProtocol":{"role":"symbol","title":"GTUITableViewItemBaseProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewItemBaseProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewItemBaseProtocol"}],"url":"\/documentation\/gtuikit\/gtuitableviewitembaseprotocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewItemBaseProtocol/cellNib":{"role":"symbol","title":"cellNib","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellNib"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"返回xib创建的nib"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/cellNib","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewitembaseprotocol\/cellnib"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem":{"role":"symbol","title":"GTUITableViewCellItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewCellItem"}],"url":"\/documentation\/gtuikit\/gtuitableviewcellitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRoundRectCellItem":{"role":"symbol","title":"GTUIRoundRectCellItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRoundRectCellItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCellItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIRoundRectCellItem"}],"url":"\/documentation\/gtuikit\/gtuiroundrectcellitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewItemBaseProtocol/identifier":{"role":"symbol","title":"identifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"重用标识符"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/identifier","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewitembaseprotocol\/identifier"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewItemBaseProtocol/cellHeight":{"role":"symbol","title":"cellHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"高度"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol\/cellHeight","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuitableviewitembaseprotocol\/cellheight"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItemProtocol":{"role":"symbol","title":"GTUITableViewCellItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItemProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewCellItemProtocol"}],"url":"\/documentation\/gtuikit\/gtuitableviewcellitemprotocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceTableViewCellItem\/title","value":"GTUISpaceTableViewCellItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceTableViewCellItem\/fragments","value":[{"kind":"identifier","text":"GTUISpaceTableViewCellItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCellItem\/title","value":"GTUITableViewCellItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCellItem\/fragments","value":[{"kind":"identifier","text":"GTUITableViewCellItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectCellItem\/title","value":"GTUIRoundRectCellItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectCellItem\/fragments","value":[{"kind":"identifier","text":"GTUIRoundRectCellItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}