{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItemProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol","preciseIdentifier":"s:7GTUIKit29GTUITableViewItemBaseProtocolP","text":"GTUITableViewItemBaseProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuitableviewcellitemprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCellItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceTableViewCellItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItemProtocol","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItemProtocol"}],"title":"GTUITableViewCellItemProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit29GTUITableViewCellItemProtocolP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUITableViewCellItemProtocol"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISpaceTableViewCellItem":{"role":"symbol","title":"GTUISpaceTableViewCellItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISpaceTableViewCellItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceTableViewCellItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISpaceTableViewCellItem"}],"url":"\/documentation\/gtuikit\/gtuispacetableviewcellitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItem":{"role":"symbol","title":"GTUITableViewCellItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewCellItem"}],"url":"\/documentation\/gtuikit\/gtuitableviewcellitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCellItemProtocol":{"role":"symbol","title":"GTUITableViewCellItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCellItemProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCellItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewCellItemProtocol"}],"url":"\/documentation\/gtuikit\/gtuitableviewcellitemprotocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIRoundRectCellItem":{"role":"symbol","title":"GTUIRoundRectCellItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIRoundRectCellItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIRoundRectCellItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIRoundRectCellItem"}],"url":"\/documentation\/gtuikit\/gtuiroundrectcellitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewItemBaseProtocol":{"role":"symbol","title":"GTUITableViewItemBaseProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewItemBaseProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewItemBaseProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewItemBaseProtocol"}],"url":"\/documentation\/gtuikit\/gtuitableviewitembaseprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceTableViewCellItem\/title","value":"GTUISpaceTableViewCellItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceTableViewCellItem\/fragments","value":[{"kind":"identifier","text":"GTUISpaceTableViewCellItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCellItem\/title","value":"GTUITableViewCellItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCellItem\/fragments","value":[{"kind":"identifier","text":"GTUITableViewCellItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectCellItem\/title","value":"GTUIRoundRectCellItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIRoundRectCellItem\/fragments","value":[{"kind":"identifier","text":"GTUIRoundRectCellItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}