{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuicollectionviewsectionitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuicollectionviewsectionitem"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/backgroundItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/footerItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/headerItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/insetForSection","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/minimumInteritemSpacing","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/minimumLineSpacing","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/sectionIdentifier","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/sectionItems"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItem"}],"title":"GTUICollectionViewSectionItem","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTUICollectionViewSectionItem","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewSectionItem"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem/sectionItems":{"role":"symbol","title":"sectionItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sectionItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GTUICollectionReusableViewItemProtocol","preciseIdentifier":"s:7GTUIKit38GTUICollectionReusableViewItemProtocolP"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/sectionItems","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem\/sectionitems"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem/headerItem":{"role":"symbol","title":"headerItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUICollectionReusableViewItemProtocol","preciseIdentifier":"s:7GTUIKit38GTUICollectionReusableViewItemProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/headerItem","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem\/headeritem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItemProtocol":{"role":"symbol","title":"GTUICollectionViewSectionItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItemProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewSectionItemProtocol"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitemprotocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem/footerItem":{"role":"symbol","title":"footerItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUICollectionReusableViewItemProtocol","preciseIdentifier":"s:7GTUIKit38GTUICollectionReusableViewItemProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/footerItem","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem\/footeritem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem/sectionIdentifier":{"role":"symbol","title":"sectionIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sectionIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/sectionIdentifier","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem\/sectionidentifier"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem/minimumInteritemSpacing":{"role":"symbol","title":"minimumInteritemSpacing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumInteritemSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/minimumInteritemSpacing","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem\/minimuminteritemspacing"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem/minimumLineSpacing":{"role":"symbol","title":"minimumLineSpacing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumLineSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/minimumLineSpacing","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem\/minimumlinespacing"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem/insetForSection":{"role":"symbol","title":"insetForSection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"insetForSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/insetForSection","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem\/insetforsection"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem\/init()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIFallLayoutSectionBaseItem":{"role":"symbol","title":"GTUIFallLayoutSectionBaseItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}],"url":"\/documentation\/gtuikit\/gtuifalllayoutsectionbaseitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem":{"role":"symbol","title":"GTUICollectionViewSectionItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionViewSectionItem"}],"url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionViewSectionItem/backgroundItem":{"role":"symbol","title":"backgroundItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUICollectionReusableViewItemProtocol","preciseIdentifier":"s:7GTUIKit38GTUICollectionReusableViewItemProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/backgroundItem","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionviewsectionitem\/backgrounditem"},"doc://org.cocoapods.GTUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTUICollectionViewSectionItem"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTUICollectionViewSectionItem"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTUICollectionViewSectionItem"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionViewSectionItem\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIFallLayoutSectionBaseItem"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionViewSectionItem"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewSectionItem~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewSectionItem~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/title","value":"GTUIFallLayoutSectionBaseItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIFallLayoutSectionBaseItem\/fragments","value":[{"kind":"identifier","text":"GTUIFallLayoutSectionBaseItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewSectionItem\/title","value":"GTUICollectionViewSectionItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionViewSectionItem\/fragments","value":[{"kind":"identifier","text":"GTUICollectionViewSectionItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}