{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButtonV3"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuibuttonv3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuibuttonv3"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIButton"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentItemViewV3"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonLoadingType","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSkeletionMiniUnitType","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/init(frame:axis:spacing:contentInsets:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/axis","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/backgroundImageView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/contentInsets","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_loadingColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/intrinsicContentSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/isEnabled","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/isHighlighted","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/isSelected","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/prefixIconView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/prefixImageView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/spacing","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/suffixIconView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/suffixImageView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedPrefixIconFont(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedSuffixIconFont(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedTitle(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setBackgroundColor(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setBackgroundImage(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setImage(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setPrefixIconColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setSuffixIconColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setTitleColor(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/layoutSubviews()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/prepareLoadingHidden()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/prepareLoadingShow()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setAttributedTitle(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setBackgroundColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setBackgroundImage(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setBorderColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixAttributedIcon(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixIcon(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixIconColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixIconState(iconState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixImage(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixAttributedIcon(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixIcon(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixIconColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixIconState(iconState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixImage(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setTitle(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setTitleColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/sizeThatFits(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/updateSubviewConstraints()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButtonV3"}],"title":"GTUIButtonV3","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)GTUIButtonV3","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUIButtonV3"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"seeAlsoSections":[{"title":"基类","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIImageView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabbar","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIScrollView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIControl","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextField","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINavigationController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController"],"generated":true}],"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setSuffixIconState(iconState:)":{"role":"symbol","title":"setSuffixIconState(iconState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSuffixIconState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"iconState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTIconState","preciseIdentifier":"s:7GTUIKit11GTIconStateO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixIconState(iconState:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/setsuffixiconstate(iconstate:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setSuffixImage(_:for:)":{"role":"symbol","title":"setSuffixImage(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSuffixImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixImage(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSuffixImage:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setsuffiximage(_:for:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"type":"unresolvable","title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/isEnabled":{"role":"symbol","title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/isEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enabled"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/isenabled"},"doc://org.cocoapods.GTUIKit/objc(cs)UIButton":{"type":"unresolvable","title":"UIButton","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIButton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUILabel":{"role":"symbol","title":"GTUILabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUILabel"}],"url":"\/documentation\/gtuikit\/gtuilabel"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_loadingColor":{"role":"symbol","title":"gt_loadingColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_loadingColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTThemeColorPicker","preciseIdentifier":"s:7GTUIKit18GTThemeColorPickera"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_loadingColor","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_loadingcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setTitle(_:for:)":{"role":"symbol","title":"setTitle(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setTitle(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setTitle:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/settitle(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setBackgroundImage(_:for:)":{"role":"symbol","title":"setBackgroundImage(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setBackgroundImage(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setBackgroundImage:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setbackgroundimage(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/isSelected":{"role":"symbol","title":"isSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/isSelected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selected"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/isselected"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/layoutsubviews()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCheckBoxV3":{"role":"symbol","title":"GTCheckBoxV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCheckBoxV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCheckBoxV3"}],"url":"\/documentation\/gtuikit\/gtcheckboxv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTThirdlySegmentItemViewV3":{"role":"symbol","title":"GTThirdlySegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTThirdlySegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTThirdlySegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtthirdlysegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setPrefixIconState(iconState:)":{"role":"symbol","title":"setPrefixIconState(iconState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPrefixIconState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"iconState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTIconState","preciseIdentifier":"s:7GTUIKit11GTIconStateO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixIconState(iconState:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/setprefixiconstate(iconstate:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setPrefixImage(_:for:)":{"role":"symbol","title":"setPrefixImage(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPrefixImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixImage(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPrefixImage:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setprefiximage(_:for:)"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setPrefixAttributedIcon(_:for:)":{"role":"symbol","title":"setPrefixAttributedIcon(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPrefixAttributedIcon"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixAttributedIcon(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPrefixAttributedIcon:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setprefixattributedicon(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITextField":{"role":"symbol","title":"GTUITextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITextField"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITextField"}],"url":"\/documentation\/gtuikit\/gtuitextfield"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIView":{"role":"symbol","title":"GTUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIView"}],"url":"\/documentation\/gtuikit\/gtuiview"},"doc://org.cocoapods.GTUIKit/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setSuffixAttributedIcon(_:for:)":{"role":"symbol","title":"setSuffixAttributedIcon(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSuffixAttributedIcon"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixAttributedIcon(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSuffixAttributedIcon:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setsuffixattributedicon(_:for:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setAttributedTitle(_:forState:)":{"role":"symbol","title":"gt_setAttributedTitle(_:forState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setAttributedTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeAttributedStringPicker","preciseIdentifier":"s:7GTUIKit29GTThemeAttributedStringPickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedTitle(_:forState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setAttributedTitle:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_setattributedtitle(_:forstate:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/9PinLayout10LayoutableP":{"type":"unresolvable","title":"PinLayout.Layoutable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITabBarController":{"role":"symbol","title":"GTUITabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITabBarController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITabBarController"}],"url":"\/documentation\/gtuikit\/gtuitabbarcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUINavigationController":{"role":"symbol","title":"GTUINavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUINavigationController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUINavigationController"}],"url":"\/documentation\/gtuikit\/gtuinavigationcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/axis":{"role":"symbol","title":"axis","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"axis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Axis","preciseIdentifier":"c:@E@UILayoutConstraintAxis"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/axis","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/axis"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyType":{"role":"symbol","title":"GTEmptyType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyType"}],"url":"\/documentation\/gtuikit\/gtemptytype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTButtonLoadingType":{"role":"symbol","title":"GTButtonLoadingType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTButtonLoadingType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonLoadingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTButtonLoadingType"}],"url":"\/documentation\/gtuikit\/gtbuttonloadingtype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3":{"role":"symbol","title":"GTUIButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIButtonV3"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setPrefixIcon(_:for:)":{"role":"symbol","title":"setPrefixIcon(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPrefixIcon"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixIcon(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPrefixIcon:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setprefixicon(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/titleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/titlelabel"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTButtonV3":{"role":"symbol","title":"GTButtonV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTButtonV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTButtonV3"}],"url":"\/documentation\/gtuikit\/gtbuttonv3"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setSuffixIconColor(_:for:)":{"role":"symbol","title":"setSuffixIconColor(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSuffixIconColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixIconColor(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSuffixIconColor:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setsuffixiconcolor(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableView":{"role":"symbol","title":"GTUITableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableView"}],"url":"\/documentation\/gtuikit\/gtuitableview"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setBackgroundColor(_:for:)":{"role":"symbol","title":"setBackgroundColor(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setBackgroundColor(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setBackgroundColor:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setbackgroundcolor(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSkeletionMiniUnitType":{"role":"symbol","title":"GTSkeletionMiniUnitType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSkeletionMiniUnitType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSkeletionMiniUnitType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSkeletionMiniUnitType"}],"url":"\/documentation\/gtuikit\/gtskeletionminiunittype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/prefixIconView":{"role":"symbol","title":"prefixIconView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefixIconView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/prefixIconView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/prefixiconview"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButton":{"role":"symbol","title":"GTUIButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIButton"}],"url":"\/documentation\/gtuikit\/gtuibutton"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setAttributedSuffixIconFont(_:forState:)":{"role":"symbol","title":"gt_setAttributedSuffixIconFont(_:forState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setAttributedSuffixIconFont"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeAttributedStringPicker","preciseIdentifier":"s:7GTUIKit29GTThemeAttributedStringPickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedSuffixIconFont(_:forState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setAttributedSuffixIconFont:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_setattributedsuffixiconfont(_:forstate:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/prepareLoadingHidden()":{"role":"symbol","title":"prepareLoadingHidden()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareLoadingHidden"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/prepareLoadingHidden()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareLoadingHidden"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/prepareloadinghidden()"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","title":"UIKit.UIContextMenuInteractionDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIContextMenuInteractionDelegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIScrollView":{"role":"symbol","title":"GTUIScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIScrollView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIScrollView"}],"url":"\/documentation\/gtuikit\/gtuiscrollview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setBackgroundImage(_:forState:)":{"role":"symbol","title":"gt_setBackgroundImage(_:forState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setBackgroundImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeImagePicker","preciseIdentifier":"s:7GTUIKit18GTThemeImagePickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setBackgroundImage(_:forState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setBackgroundImage:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_setbackgroundimage(_:forstate:)"},"doc://org.cocoapods.GTUIKit/9PinLayout18AutoSizeCalculableP":{"type":"unresolvable","title":"PinLayout.AutoSizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/intrinsicContentSize":{"role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/intrinsicContentSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/intrinsiccontentsize"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/contentInsets":{"role":"symbol","title":"contentInsets","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/contentInsets","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/contentinsets"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/init(frame:axis:spacing:contentInsets:)":{"role":"symbol","title":"init(frame:axis:spacing:contentInsets:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"axis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Axis","preciseIdentifier":"c:@E@UILayoutConstraintAxis"},{"kind":"text","text":", "},{"kind":"externalParam","text":"spacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/init(frame:axis:spacing:contentInsets:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/init(frame:axis:spacing:contentinsets:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setPrefixIconColor(_:for:)":{"role":"symbol","title":"setPrefixIconColor(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPrefixIconColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixIconColor(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPrefixIconColor:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setprefixiconcolor(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITextView":{"role":"symbol","title":"GTUITextView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITextView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITextView"}],"url":"\/documentation\/gtuikit\/gtuitextview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/backgroundImageView":{"role":"symbol","title":"backgroundImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/backgroundImageView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/backgroundimageview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setAttributedPrefixIconFont(_:forState:)":{"role":"symbol","title":"gt_setAttributedPrefixIconFont(_:forState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setAttributedPrefixIconFont"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeAttributedStringPicker","preciseIdentifier":"s:7GTUIKit29GTThemeAttributedStringPickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedPrefixIconFont(_:forState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setAttributedPrefixIconFont:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_setattributedprefixiconfont(_:forstate:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setSuffixIconColor(_:for:)":{"role":"symbol","title":"gt_setSuffixIconColor(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setSuffixIconColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeColorPicker","preciseIdentifier":"s:7GTUIKit18GTThemeColorPickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setSuffixIconColor(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setSuffixIconColor:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_setsuffixiconcolor(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTCardSegmentItemViewV3":{"role":"symbol","title":"GTCardSegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTCardSegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTCardSegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtcardsegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/isHighlighted":{"role":"symbol","title":"isHighlighted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHighlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/isHighlighted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlighted"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/ishighlighted"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTPrimarySegmentItemViewV3":{"role":"symbol","title":"GTPrimarySegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTPrimarySegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTPrimarySegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtprimarysegmentitemviewv3"},"doc://org.cocoapods.GTUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setAttributedTitle(_:for:)":{"role":"symbol","title":"setAttributedTitle(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAttributedTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setAttributedTitle(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAttributedTitle:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setattributedtitle(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/spacing":{"role":"symbol","title":"spacing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"spacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/spacing","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/spacing"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/suffixIconView":{"role":"symbol","title":"suffixIconView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suffixIconView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTUILabel","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTUILabel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/suffixIconView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/suffixiconview"},"doc://org.cocoapods.GTUIKit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.GTUIKit/9PinLayout14SizeCalculableP":{"type":"unresolvable","title":"PinLayout.SizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/suffixImageView":{"role":"symbol","title":"suffixImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suffixImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/suffixImageView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/suffiximageview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setImage(_:forState:)":{"role":"symbol","title":"gt_setImage(_:forState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeImagePicker","preciseIdentifier":"s:7GTUIKit18GTThemeImagePickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setImage(_:forState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setImage:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_setimage(_:forstate:)"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/prefixImageView":{"role":"symbol","title":"prefixImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefixImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/prefixImageView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/prefiximageview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/init(coder:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIControl":{"role":"symbol","title":"GTUIControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIControl"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIControl"}],"url":"\/documentation\/gtuikit\/gtuicontrol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setPrefixIconColor(_:for:)":{"role":"symbol","title":"gt_setPrefixIconColor(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setPrefixIconColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeColorPicker","preciseIdentifier":"s:7GTUIKit18GTThemeColorPickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setPrefixIconColor(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setPrefixIconColor:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_setprefixiconcolor(_:for:)"},"doc://org.cocoapods.GTUIKit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setBorderColor(_:for:)":{"role":"symbol","title":"setBorderColor(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBorderColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGColor","preciseIdentifier":"c:@T@CGColorRef"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setBorderColor(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setBorderColor:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setbordercolor(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIImageView":{"role":"symbol","title":"GTUIImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIImageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIImageView"}],"url":"\/documentation\/gtuikit\/gtuiimageview"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setTitleColor(_:forState:)":{"role":"symbol","title":"gt_setTitleColor(_:forState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setTitleColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeColorPicker","preciseIdentifier":"s:7GTUIKit18GTThemeColorPickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setTitleColor(_:forState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setTitleColor:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_settitlecolor(_:forstate:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITabbar":{"role":"symbol","title":"GTUITabbar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITabbar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabbar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITabbar"}],"url":"\/documentation\/gtuikit\/gtuitabbar"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/updateSubviewConstraints()":{"role":"symbol","title":"updateSubviewConstraints()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateSubviewConstraints"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/updateSubviewConstraints()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gtuibuttonv3\/updatesubviewconstraints()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setTitleColor(_:for:)":{"role":"symbol","title":"setTitleColor(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitleColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setTitleColor(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setTitleColor:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/settitlecolor(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/prepareLoadingShow()":{"role":"symbol","title":"prepareLoadingShow()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareLoadingShow"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/prepareLoadingShow()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareLoadingShow"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/prepareloadingshow()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/sizeThatFits(_:)":{"role":"symbol","title":"sizeThatFits(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/sizeThatFits(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sizeThatFits:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/sizethatfits(_:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/12SkeletonView0aB8ExtendedP":{"type":"unresolvable","title":"SkeletonView.SkeletonViewExtended","identifier":"doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/setSuffixIcon(_:for:)":{"role":"symbol","title":"setSuffixIcon(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSuffixIcon"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixIcon(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSuffixIcon:for:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/setsuffixicon(_:for:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIButtonV3/gt_setBackgroundColor(_:forState:)":{"role":"symbol","title":"gt_setBackgroundColor(_:forState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gt_setBackgroundColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GTThemeColorPicker","preciseIdentifier":"s:7GTUIKit18GTThemeColorPickera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setBackgroundColor(_:forState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gt_setBackgroundColor:forState:"}],"url":"\/documentation\/gtuikit\/gtuibuttonv3\/gt_setbackgroundcolor(_:forstate:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUIViewController":{"role":"symbol","title":"GTUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUIViewController"}],"url":"\/documentation\/gtuikit\/gtuiviewcontroller"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTSecondarySegmentItemViewV3":{"role":"symbol","title":"GTSecondarySegmentItemViewV3","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTSecondarySegmentItemViewV3"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentItemViewV3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTSecondarySegmentItemViewV3"}],"url":"\/documentation\/gtuikit\/gtsecondarysegmentitemviewv3"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTUIButtonV3"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTUIButtonV3"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTUIButtonV3"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/intrinsicContentSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/isEnabled","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/isHighlighted","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/isSelected","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedPrefixIconFont(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedSuffixIconFont(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setAttributedTitle(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setBackgroundColor(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setBackgroundImage(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setImage(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setPrefixIconColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setSuffixIconColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/gt_setTitleColor(_:forState:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/init(coder:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/layoutSubviews()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/prepareLoadingHidden()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/prepareLoadingShow()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setAttributedTitle(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setBackgroundColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setBackgroundImage(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setBorderColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixAttributedIcon(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixIcon(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixIconColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setPrefixImage(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixAttributedIcon(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixIcon(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixIconColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setSuffixImage(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setTitle(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/setTitleColor(_:for:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButtonV3\/sizeThatFits(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIButton"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTButtonV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCardSegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTCheckBoxV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTPrimarySegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTSecondarySegmentItemViewV3","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTThirdlySegmentItemViewV3"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"基类","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUILabel","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIImageView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabbar","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIScrollView","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIControl","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITextField","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUIViewController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUINavigationController","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITabBarController"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUIButtonV3"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setSuffixImage(_:for:)\/title","value":"setSuffixImage:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setSuffixImage(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSuffixImage:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1isEnabled\/title","value":"enabled"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1isEnabled\/fragments","value":[{"kind":"identifier","text":"enabled"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILabel\/title","value":"GTUILabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUILabel\/fragments","value":[{"kind":"identifier","text":"GTUILabel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setTitle(_:for:)\/title","value":"setTitle:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setTitle(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitle:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setBackgroundImage(_:for:)\/title","value":"setBackgroundImage:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setBackgroundImage(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBackgroundImage:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1isSelected\/title","value":"selected"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1isSelected\/fragments","value":[{"kind":"identifier","text":"selected"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/title","value":"GTCheckBoxV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCheckBoxV3\/fragments","value":[{"kind":"identifier","text":"GTCheckBoxV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTThirdlySegmentItemViewV3\/title","value":"GTThirdlySegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTThirdlySegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTThirdlySegmentItemViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setPrefixImage(_:for:)\/title","value":"setPrefixImage:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setPrefixImage(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPrefixImage:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setPrefixAttributedIcon(_:for:)\/title","value":"setPrefixAttributedIcon:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setPrefixAttributedIcon(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPrefixAttributedIcon:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextField\/title","value":"GTUITextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextField\/fragments","value":[{"kind":"identifier","text":"GTUITextField"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIView\/title","value":"GTUIView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIView\/fragments","value":[{"kind":"identifier","text":"GTUIView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setSuffixAttributedIcon(_:for:)\/title","value":"setSuffixAttributedIcon:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setSuffixAttributedIcon(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSuffixAttributedIcon:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setAttributedTitle(_:forState:)\/title","value":"gt_setAttributedTitle:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setAttributedTitle(_:forState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setAttributedTitle:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabBarController\/title","value":"GTUITabBarController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabBarController\/fragments","value":[{"kind":"identifier","text":"GTUITabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINavigationController\/title","value":"GTUINavigationController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUINavigationController\/fragments","value":[{"kind":"identifier","text":"GTUINavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/title","value":"GTUIButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3\/fragments","value":[{"kind":"identifier","text":"GTUIButtonV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setPrefixIcon(_:for:)\/title","value":"setPrefixIcon:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setPrefixIcon(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPrefixIcon:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTButtonV3\/title","value":"GTButtonV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTButtonV3\/fragments","value":[{"kind":"identifier","text":"GTButtonV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setSuffixIconColor(_:for:)\/title","value":"setSuffixIconColor:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setSuffixIconColor(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSuffixIconColor:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableView\/title","value":"GTUITableView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableView\/fragments","value":[{"kind":"identifier","text":"GTUITableView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setBackgroundColor(_:for:)\/title","value":"setBackgroundColor:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setBackgroundColor(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBackgroundColor:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButton\/title","value":"GTUIButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButton\/fragments","value":[{"kind":"identifier","text":"GTUIButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setAttributedSuffixIconFont(_:forState:)\/title","value":"gt_setAttributedSuffixIconFont:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setAttributedSuffixIconFont(_:forState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setAttributedSuffixIconFont:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1prepareLoadingHidden()\/title","value":"prepareLoadingHidden"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1prepareLoadingHidden()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareLoadingHidden"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIScrollView\/title","value":"GTUIScrollView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIScrollView\/fragments","value":[{"kind":"identifier","text":"GTUIScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setBackgroundImage(_:forState:)\/title","value":"gt_setBackgroundImage:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setBackgroundImage(_:forState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setBackgroundImage:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setPrefixIconColor(_:for:)\/title","value":"setPrefixIconColor:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setPrefixIconColor(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPrefixIconColor:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView\/title","value":"GTUITextView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITextView\/fragments","value":[{"kind":"identifier","text":"GTUITextView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setAttributedPrefixIconFont(_:forState:)\/title","value":"gt_setAttributedPrefixIconFont:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setAttributedPrefixIconFont(_:forState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setAttributedPrefixIconFont:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setSuffixIconColor(_:for:)\/title","value":"gt_setSuffixIconColor:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setSuffixIconColor(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setSuffixIconColor:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCardSegmentItemViewV3\/title","value":"GTCardSegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTCardSegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTCardSegmentItemViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1isHighlighted\/title","value":"highlighted"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1isHighlighted\/fragments","value":[{"kind":"identifier","text":"highlighted"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPrimarySegmentItemViewV3\/title","value":"GTPrimarySegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTPrimarySegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTPrimarySegmentItemViewV3"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setAttributedTitle(_:for:)\/title","value":"setAttributedTitle:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setAttributedTitle(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAttributedTitle:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setImage(_:forState:)\/title","value":"gt_setImage:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setImage(_:forState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setImage:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIControl\/title","value":"GTUIControl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIControl\/fragments","value":[{"kind":"identifier","text":"GTUIControl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setPrefixIconColor(_:for:)\/title","value":"gt_setPrefixIconColor:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setPrefixIconColor(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setPrefixIconColor:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setBorderColor(_:for:)\/title","value":"setBorderColor:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setBorderColor(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBorderColor:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIImageView\/title","value":"GTUIImageView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIImageView\/fragments","value":[{"kind":"identifier","text":"GTUIImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setTitleColor(_:forState:)\/title","value":"gt_setTitleColor:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setTitleColor(_:forState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setTitleColor:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabbar\/title","value":"GTUITabbar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITabbar\/fragments","value":[{"kind":"identifier","text":"GTUITabbar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setTitleColor(_:for:)\/title","value":"setTitleColor:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setTitleColor(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleColor:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1prepareLoadingShow()\/title","value":"prepareLoadingShow"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1prepareLoadingShow()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareLoadingShow"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1sizeThatFits(_:)\/title","value":"sizeThatFits:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1sizeThatFits(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeThatFits:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setSuffixIcon(_:for:)\/title","value":"setSuffixIcon:for:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1setSuffixIcon(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSuffixIcon:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setBackgroundColor(_:forState:)\/title","value":"gt_setBackgroundColor:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIButtonV3~1gt_setBackgroundColor(_:forState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gt_setBackgroundColor:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIViewController\/title","value":"GTUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUIViewController\/fragments","value":[{"kind":"identifier","text":"GTUIViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSecondarySegmentItemViewV3\/title","value":"GTSecondarySegmentItemViewV3"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTSecondarySegmentItemViewV3\/fragments","value":[{"kind":"identifier","text":"GTSecondarySegmentItemViewV3"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}