{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionReusableViewItemProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuicollectionreusableviewitemprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItem","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceCollectionViewCellItem"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol\/cellSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol\/cls","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol\/nib","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol\/reuseIdentifier","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol\/target"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionReusableViewItemProtocol"}],"title":"GTUICollectionReusableViewItemProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:7GTUIKit38GTUICollectionReusableViewItemProtocolP","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GTUICollectionReusableViewItemProtocol"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionReusableViewItemProtocol":{"role":"symbol","title":"GTUICollectionReusableViewItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionReusableViewItemProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionReusableViewItemProtocol"}],"url":"\/documentation\/gtuikit\/gtuicollectionreusableviewitemprotocol"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionReusableViewItemProtocol/target":{"role":"symbol","title":"target","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol\/target","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionreusableviewitemprotocol\/target"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUISpaceCollectionViewCellItem":{"role":"symbol","title":"GTUISpaceCollectionViewCellItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUISpaceCollectionViewCellItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUISpaceCollectionViewCellItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUISpaceCollectionViewCellItem"}],"url":"\/documentation\/gtuikit\/gtuispacecollectionviewcellitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionReusableViewItemProtocol/reuseIdentifier":{"role":"symbol","title":"reuseIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol\/reuseIdentifier","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionreusableviewitemprotocol\/reuseidentifier"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionReusableViewItemProtocol/nib":{"role":"symbol","title":"nib","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nib"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol\/nib","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionreusableviewitemprotocol\/nib"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionReusableViewItemProtocol/cls":{"role":"symbol","title":"cls","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cls"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol\/cls","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionreusableviewitemprotocol\/cls"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionReusableViewItem":{"role":"symbol","title":"GTUICollectionReusableViewItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUICollectionReusableViewItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUICollectionReusableViewItem"}],"url":"\/documentation\/gtuikit\/gtuicollectionreusableviewitem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUICollectionReusableViewItemProtocol/cellSize":{"role":"symbol","title":"cellSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUICollectionReusableViewItemProtocol\/cellSize","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/gtuicollectionreusableviewitemprotocol\/cellsize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceCollectionViewCellItem\/title","value":"GTUISpaceCollectionViewCellItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUISpaceCollectionViewCellItem\/fragments","value":[{"kind":"identifier","text":"GTUISpaceCollectionViewCellItem"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionReusableViewItem\/title","value":"GTUICollectionReusableViewItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUICollectionReusableViewItem\/fragments","value":[{"kind":"identifier","text":"GTUICollectionReusableViewItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}