{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYpageViewDataSource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/lypageviewdatasource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/lypageviewdatasource"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/itemView(forTab:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/numberOfTab(view:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/pageOfTab(at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/titleForTab(at:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYpageViewDataSource"}],"title":"LYpageViewDataSource","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@GTUIKit@objc(pl)LYpageViewDataSource","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"LYpageViewDataSource"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYpageViewDataSource/numberOfTab(view:)":{"navigatorTitle":[{"kind":"identifier","text":"numberOfTabWithView:"}],"role":"symbol","title":"numberOfTab(view:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTab"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LYPageView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)LYPageView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"顶部tab页签个数"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/numberOfTab(view:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/lypageviewdatasource\/numberoftab(view:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYpageViewDataSource":{"role":"symbol","title":"LYpageViewDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYpageViewDataSource"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LYpageViewDataSource"}],"url":"\/documentation\/gtuikit\/lypageviewdatasource"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYpageViewDataSource/itemView(forTab:)":{"role":"symbol","title":"itemView(forTab:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTab"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"自定义item"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/itemView(forTab:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"itemViewForTab:"}],"url":"\/documentation\/gtuikit\/lypageviewdatasource\/itemview(fortab:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYpageViewDataSource/pageOfTab(at:)":{"navigatorTitle":[{"kind":"identifier","text":"pageOfTabAt:"}],"role":"symbol","title":"pageOfTab(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageOfTab"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"每个tab所属vc"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/pageOfTab(at:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/lypageviewdatasource\/pageoftab(at:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/LYpageViewDataSource/titleForTab(at:)":{"role":"symbol","title":"titleForTab(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleForTab"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"页签对应标题"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/titleForTab(at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleForTabAt:"}],"url":"\/documentation\/gtuikit\/lypageviewdatasource\/titlefortab(at:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"LYpageViewDataSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LYpageViewDataSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LYpageViewDataSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/itemView(forTab:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/numberOfTab(view:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/pageOfTab(at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/LYpageViewDataSource\/titleForTab(at:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LYpageViewDataSource"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource~1numberOfTab(view:)\/title","value":"numberOfTabWithView:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource~1numberOfTab(view:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfTabWithView:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource\/title","value":"LYpageViewDataSource"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource\/fragments","value":[{"kind":"identifier","text":"LYpageViewDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource~1itemView(forTab:)\/title","value":"itemViewForTab:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource~1itemView(forTab:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"itemViewForTab:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource~1pageOfTab(at:)\/title","value":"pageOfTabAt:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource~1pageOfTab(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageOfTabAt:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource~1titleForTab(at:)\/title","value":"titleForTabAt:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1LYpageViewDataSource~1titleForTab(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleForTabAt:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}