{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBDesignable"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/taglistview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/taglistview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP","doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.GTUIKit\/SQ","doc:\/\/org.cocoapods.GTUIKit\/SH","doc:\/\/org.cocoapods.GTUIKit\/s8SendableP","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/alignment-swift.property","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/borderColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/borderWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/cornerRadius","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/delegate","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/enableRemoveButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/intrinsicContentSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/marginX","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/marginY","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/paddingX","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/paddingY","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeButtonIconSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeIconLineColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeIconLineWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/selectedBorderColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/selectedTextColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowOffset","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowOpacity","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowRadius","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagHighlightedBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagLineBreakMode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagSelectedBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagViews","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/textColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/textFont"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/addTag(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/addTagView(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/addTagViews(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/addTags(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/insertTag(_:at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/insertTagView(_:at:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/layoutSubviews()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/prepareForInterfaceBuilder()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeAllTags()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeTag(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeTagView(_:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/selectedTags()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/setTitle(_:at:)"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/Alignment-swift.enum"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListView"}],"title":"TagListView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTUIKit@objc(cs)TagListView","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"TagListView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/borderColor":{"role":"symbol","title":"borderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/borderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"borderColor"}],"url":"\/documentation\/gtuikit\/taglistview\/bordercolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/Alignment-swift.enum":{"role":"symbol","title":"TagListView.Alignment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Alignment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/Alignment-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Alignment"}],"url":"\/documentation\/gtuikit\/taglistview\/alignment-swift.enum"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.GTUIKit/9PinLayout14SizeCalculableP":{"type":"unresolvable","title":"PinLayout.SizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout14SizeCalculableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/enableRemoveButton":{"role":"symbol","title":"enableRemoveButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableRemoveButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/enableRemoveButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableRemoveButton"}],"url":"\/documentation\/gtuikit\/taglistview\/enableremovebutton"},"doc://org.cocoapods.GTUIKit/objc(pl)ASAsyncTransactionContainer":{"type":"unresolvable","title":"AsyncDisplayKit.ASAsyncTransactionContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)ASAsyncTransactionContainer"},"doc://org.cocoapods.GTUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SH"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/textColor":{"role":"symbol","title":"textColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/textColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textColor"}],"url":"\/documentation\/gtuikit\/taglistview\/textcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/paddingX":{"role":"symbol","title":"paddingX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paddingX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/paddingX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paddingX"}],"url":"\/documentation\/gtuikit\/taglistview\/paddingx"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/cornerRadius":{"role":"symbol","title":"cornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/cornerRadius","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cornerRadius"}],"url":"\/documentation\/gtuikit\/taglistview\/cornerradius"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/tagViews":{"role":"symbol","title":"tagViews","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagViews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagViews","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/tagviews"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListViewDelegate","preciseIdentifier":"c:@M@GTUIKit@objc(pl)TagListViewDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/gtuikit\/taglistview\/delegate"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/shadowOffset":{"role":"symbol","title":"shadowOffset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowOffset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shadowOffset"}],"url":"\/documentation\/gtuikit\/taglistview\/shadowoffset"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/shadowRadius":{"role":"symbol","title":"shadowRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowRadius","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shadowRadius"}],"url":"\/documentation\/gtuikit\/taglistview\/shadowradius"},"doc://org.cocoapods.GTUIKit/9PinLayout18AutoSizeCalculableP":{"type":"unresolvable","title":"PinLayout.AutoSizeCalculable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout18AutoSizeCalculableP"},"doc://org.cocoapods.GTUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/insertTagView(_:at:)":{"role":"symbol","title":"insertTagView(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertTagView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/insertTagView(_:at:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/inserttagview(_:at:)"},"doc://org.cocoapods.GTUIKit/12SkeletonView0aB8ExtendedP":{"type":"unresolvable","title":"SkeletonView.SkeletonViewExtended","identifier":"doc:\/\/org.cocoapods.GTUIKit\/12SkeletonView0aB8ExtendedP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/marginY":{"role":"symbol","title":"marginY","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"marginY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/marginY","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"marginY"}],"url":"\/documentation\/gtuikit\/taglistview\/marginy"},"doc://org.cocoapods.GTUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/removeTagView(_:)":{"role":"symbol","title":"removeTagView(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTagView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeTagView(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/removetagview(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/shadowColor":{"role":"symbol","title":"shadowColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shadowColor"}],"url":"\/documentation\/gtuikit\/taglistview\/shadowcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/removeIconLineColor":{"role":"symbol","title":"removeIconLineColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeIconLineColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeIconLineColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeIconLineColor"}],"url":"\/documentation\/gtuikit\/taglistview\/removeiconlinecolor"},"doc://org.cocoapods.GTUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/selectedTags()":{"role":"symbol","title":"selectedTags()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedTags"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/selectedTags()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/selectedtags()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/marginX":{"role":"symbol","title":"marginX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"marginX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/marginX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"marginX"}],"url":"\/documentation\/gtuikit\/taglistview\/marginx"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/addTagView(_:)":{"role":"symbol","title":"addTagView(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTagView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/addTagView(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/addtagview(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/tagSelectedBackgroundColor":{"role":"symbol","title":"tagSelectedBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagSelectedBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagSelectedBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tagSelectedBackgroundColor"}],"url":"\/documentation\/gtuikit\/taglistview\/tagselectedbackgroundcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/insertTag(_:at:)":{"role":"symbol","title":"insertTag(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertTag"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/insertTag(_:at:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/inserttag(_:at:)"},"doc://org.cocoapods.GTUIKit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/alignment-swift.property":{"role":"symbol","title":"alignment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Alignment","preciseIdentifier":"s:7GTUIKit11TagListViewC9AlignmentO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/alignment-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"alignment"}],"url":"\/documentation\/gtuikit\/taglistview\/alignment-swift.property"},"doc://org.cocoapods.GTUIKit/9PinLayout10LayoutableP":{"type":"unresolvable","title":"PinLayout.Layoutable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/9PinLayout10LayoutableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/addTagViews(_:)":{"role":"symbol","title":"addTagViews(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTagViews"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":"]) -> ["},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/addTagViews(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/addtagviews(_:)"},"doc://org.cocoapods.GTUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/shadowOpacity":{"role":"symbol","title":"shadowOpacity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowOpacity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowOpacity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shadowOpacity"}],"url":"\/documentation\/gtuikit\/taglistview\/shadowopacity"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/gtuikit\/taglistview\/initwithcoder:"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTEmptyType":{"role":"symbol","title":"GTEmptyType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTEmptyType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTEmptyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTEmptyType"}],"url":"\/documentation\/gtuikit\/gtemptytype"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView":{"role":"symbol","title":"TagListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListView"}],"url":"\/documentation\/gtuikit\/taglistview"},"doc://org.cocoapods.GTUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s7CVarArgP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/addTag(_:)":{"role":"symbol","title":"addTag(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTag"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/addTag(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/addtag(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/prepareForInterfaceBuilder()":{"role":"symbol","title":"prepareForInterfaceBuilder()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForInterfaceBuilder"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/prepareForInterfaceBuilder()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareForInterfaceBuilder"}],"url":"\/documentation\/gtuikit\/taglistview\/prepareforinterfacebuilder()"},"doc://org.cocoapods.GTUIKit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.GTUIKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/selectedTextColor":{"role":"symbol","title":"selectedTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/selectedTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedTextColor"}],"url":"\/documentation\/gtuikit\/taglistview\/selectedtextcolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/gtuikit\/taglistview\/initwithframe:"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.GTUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/addTags(_:)":{"role":"symbol","title":"addTags(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTags"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> ["},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/addTags(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/addtags(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/tagLineBreakMode":{"role":"symbol","title":"tagLineBreakMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagLineBreakMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLineBreakMode","preciseIdentifier":"c:@E@NSLineBreakMode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagLineBreakMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tagLineBreakMode"}],"url":"\/documentation\/gtuikit\/taglistview\/taglinebreakmode"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/removeIconLineWidth":{"role":"symbol","title":"removeIconLineWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeIconLineWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeIconLineWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeIconLineWidth"}],"url":"\/documentation\/gtuikit\/taglistview\/removeiconlinewidth"},"doc://org.cocoapods.GTUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.GTUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/tagHighlightedBackgroundColor":{"role":"symbol","title":"tagHighlightedBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagHighlightedBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagHighlightedBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tagHighlightedBackgroundColor"}],"url":"\/documentation\/gtuikit\/taglistview\/taghighlightedbackgroundcolor"},"doc://org.cocoapods.GTUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.GTUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/textFont":{"role":"symbol","title":"textFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/textFont","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFont"}],"url":"\/documentation\/gtuikit\/taglistview\/textfont"},"doc://org.cocoapods.GTUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/removeAllTags()":{"role":"symbol","title":"removeAllTags()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllTags"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeAllTags()","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/removealltags()"},"doc://org.cocoapods.GTUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/intrinsicContentSize":{"role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/intrinsicContentSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/gtuikit\/taglistview\/intrinsiccontentsize"},"doc://org.cocoapods.GTUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/borderWidth":{"role":"symbol","title":"borderWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/borderWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"borderWidth"}],"url":"\/documentation\/gtuikit\/taglistview\/borderwidth"},"doc://org.cocoapods.GTUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/s8SendableP"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/paddingY":{"role":"symbol","title":"paddingY","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paddingY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/paddingY","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paddingY"}],"url":"\/documentation\/gtuikit\/taglistview\/paddingy"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/selectedBorderColor":{"role":"symbol","title":"selectedBorderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedBorderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/selectedBorderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedBorderColor"}],"url":"\/documentation\/gtuikit\/taglistview\/selectedbordercolor"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/removeButtonIconSize":{"role":"symbol","title":"removeButtonIconSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeButtonIconSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeButtonIconSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeButtonIconSize"}],"url":"\/documentation\/gtuikit\/taglistview\/removebuttoniconsize"},"doc://org.cocoapods.GTUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.GTUIKit\/SQ"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/gtuikit\/taglistview\/layoutsubviews()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/removeTag(_:)":{"role":"symbol","title":"removeTag(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTag"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeTag(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/removetag(_:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/setTitle(_:at:)":{"role":"symbol","title":"setTitle(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/setTitle(_:at:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/taglistview\/settitle(_:at:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListView/tagBackgroundColor":{"role":"symbol","title":"tagBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tagBackgroundColor"}],"url":"\/documentation\/gtuikit\/taglistview\/tagbackgroundcolor"},"doc://org.cocoapods.GTUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.GTUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.GTUIKit\/objc(pl)UIUserActivityRestoring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TagListView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TagListView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TagListView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/alignment-swift.property","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/borderColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/borderWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/cornerRadius","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/delegate","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/enableRemoveButton","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/intrinsicContentSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/marginX","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/marginY","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/paddingX","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/paddingY","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeButtonIconSize","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeIconLineColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/removeIconLineWidth","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/selectedBorderColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/selectedTextColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowOffset","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowOpacity","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/shadowRadius","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagHighlightedBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagLineBreakMode","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/tagSelectedBackgroundColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/textColor","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/textFont"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/initWithCoder:","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/initWithFrame:","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/layoutSubviews()","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListView\/prepareForInterfaceBuilder()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GTUIKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1borderColor\/title","value":"borderColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1borderColor\/fragments","value":[{"kind":"identifier","text":"borderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1enableRemoveButton\/title","value":"enableRemoveButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1enableRemoveButton\/fragments","value":[{"kind":"identifier","text":"enableRemoveButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1textColor\/title","value":"textColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1textColor\/fragments","value":[{"kind":"identifier","text":"textColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1paddingX\/title","value":"paddingX"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1paddingX\/fragments","value":[{"kind":"identifier","text":"paddingX"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1cornerRadius\/title","value":"cornerRadius"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1cornerRadius\/fragments","value":[{"kind":"identifier","text":"cornerRadius"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1shadowOffset\/title","value":"shadowOffset"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1shadowOffset\/fragments","value":[{"kind":"identifier","text":"shadowOffset"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1shadowRadius\/title","value":"shadowRadius"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1shadowRadius\/fragments","value":[{"kind":"identifier","text":"shadowRadius"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1marginY\/title","value":"marginY"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1marginY\/fragments","value":[{"kind":"identifier","text":"marginY"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1shadowColor\/title","value":"shadowColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1shadowColor\/fragments","value":[{"kind":"identifier","text":"shadowColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1removeIconLineColor\/title","value":"removeIconLineColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1removeIconLineColor\/fragments","value":[{"kind":"identifier","text":"removeIconLineColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1marginX\/title","value":"marginX"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1marginX\/fragments","value":[{"kind":"identifier","text":"marginX"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1tagSelectedBackgroundColor\/title","value":"tagSelectedBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1tagSelectedBackgroundColor\/fragments","value":[{"kind":"identifier","text":"tagSelectedBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1alignment-swift.property\/title","value":"alignment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1alignment-swift.property\/fragments","value":[{"kind":"identifier","text":"alignment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1shadowOpacity\/title","value":"shadowOpacity"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1shadowOpacity\/fragments","value":[{"kind":"identifier","text":"shadowOpacity"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView\/title","value":"TagListView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView\/fragments","value":[{"kind":"identifier","text":"TagListView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1prepareForInterfaceBuilder()\/title","value":"prepareForInterfaceBuilder"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1prepareForInterfaceBuilder()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForInterfaceBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1selectedTextColor\/title","value":"selectedTextColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1selectedTextColor\/fragments","value":[{"kind":"identifier","text":"selectedTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1tagLineBreakMode\/title","value":"tagLineBreakMode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1tagLineBreakMode\/fragments","value":[{"kind":"identifier","text":"tagLineBreakMode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1removeIconLineWidth\/title","value":"removeIconLineWidth"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1removeIconLineWidth\/fragments","value":[{"kind":"identifier","text":"removeIconLineWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1tagHighlightedBackgroundColor\/title","value":"tagHighlightedBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1tagHighlightedBackgroundColor\/fragments","value":[{"kind":"identifier","text":"tagHighlightedBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1textFont\/title","value":"textFont"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1textFont\/fragments","value":[{"kind":"identifier","text":"textFont"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1borderWidth\/title","value":"borderWidth"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1borderWidth\/fragments","value":[{"kind":"identifier","text":"borderWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1paddingY\/title","value":"paddingY"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1paddingY\/fragments","value":[{"kind":"identifier","text":"paddingY"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1selectedBorderColor\/title","value":"selectedBorderColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1selectedBorderColor\/fragments","value":[{"kind":"identifier","text":"selectedBorderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1removeButtonIconSize\/title","value":"removeButtonIconSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1removeButtonIconSize\/fragments","value":[{"kind":"identifier","text":"removeButtonIconSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1tagBackgroundColor\/title","value":"tagBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListView~1tagBackgroundColor\/fragments","value":[{"kind":"identifier","text":"tagBackgroundColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}