{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/taglistviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/taglistviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate\/tagPressed(_:tagView:sender:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate\/tagRemoveButtonPressed(_:tagView:sender:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewDelegate"}],"title":"TagListViewDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@GTUIKit@objc(pl)TagListViewDelegate","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"TagListViewDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListViewDelegate/tagPressed(_:tagView:sender:)":{"navigatorTitle":[{"kind":"identifier","text":"tagPressed:tagView:sender:"}],"role":"symbol","title":"tagPressed(_:tagView:sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagPressed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagListView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate\/tagPressed(_:tagView:sender:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/taglistviewdelegate\/tagpressed(_:tagview:sender:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListViewDelegate/tagRemoveButtonPressed(_:tagView:sender:)":{"navigatorTitle":[{"kind":"identifier","text":"tagRemoveButtonPressed:tagView:sender:"}],"role":"symbol","title":"tagRemoveButtonPressed(_:tagView:sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagRemoveButtonPressed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagListView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)TagListView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate\/tagRemoveButtonPressed(_:tagView:sender:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtuikit\/taglistviewdelegate\/tagremovebuttonpressed(_:tagview:sender:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/TagListViewDelegate":{"role":"symbol","title":"TagListViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagListViewDelegate"}],"url":"\/documentation\/gtuikit\/taglistviewdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"TagListViewDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TagListViewDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TagListViewDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate\/tagPressed(_:tagView:sender:)","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/TagListViewDelegate\/tagRemoveButtonPressed(_:tagView:sender:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagListViewDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListViewDelegate~1tagPressed(_:tagView:sender:)\/title","value":"tagPressed:tagView:sender:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListViewDelegate~1tagPressed(_:tagView:sender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tagPressed:tagView:sender:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListViewDelegate~1tagRemoveButtonPressed(_:tagView:sender:)\/title","value":"tagRemoveButtonPressed:tagView:sender:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListViewDelegate~1tagRemoveButtonPressed(_:tagView:sender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tagRemoveButtonPressed:tagView:sender:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListViewDelegate\/title","value":"TagListViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1TagListViewDelegate\/fragments","value":[{"kind":"identifier","text":"TagListViewDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}