{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"affectsPerformanceOperation"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gtuitableviewcell\/affectsperformanceoperation()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtuikit\/gtuitableviewcell\/affectsperformanceoperation()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCell\/affectsPerformanceOperation()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"影响性能的操作"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"affectsPerformanceOperation"},{"kind":"text","text":"()"}],"title":"affectsPerformanceOperation()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTUIKit@objc(cs)GTUITableViewCell(im)affectsPerformanceOperation","modules":[{"name":"GTUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"affectsPerformanceOperation"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCell"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCell":{"role":"symbol","title":"GTUITableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTUITableViewCell"}],"abstract":[{"type":"text","text":"TableViewCell基类"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTUITableViewCell"}],"url":"\/documentation\/gtuikit\/gtuitableviewcell"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTUITableViewCell/affectsPerformanceOperation()":{"role":"symbol","title":"affectsPerformanceOperation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"affectsPerformanceOperation"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"影响性能的操作"}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTUITableViewCell\/affectsPerformanceOperation()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"affectsPerformanceOperation"}],"url":"\/documentation\/gtuikit\/gtuitableviewcell\/affectsperformanceoperation()"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"affectsPerformanceOperation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"affectsPerformanceOperation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"affectsPerformanceOperation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCell\/title","value":"GTUITableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCell\/fragments","value":[{"kind":"identifier","text":"GTUITableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCell~1affectsPerformanceOperation()\/title","value":"affectsPerformanceOperation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTUITableViewCell~1affectsPerformanceOperation()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"affectsPerformanceOperation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}