{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldHelperView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextFieldHelperView","text":"GTTextFieldHelperView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttextfieldalertview\/textfieldview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldAlertView\/textFieldView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextFieldHelperView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextFieldHelperView"}],"title":"textFieldView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:7GTUIKit20GTTextFieldAlertViewC04textcE0AA0bc6HelperE0Cvp","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldAlertView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldAlertView/textFieldView":{"role":"symbol","title":"textFieldView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextFieldHelperView","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextFieldHelperView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldAlertView\/textFieldView","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gttextfieldalertview\/textfieldview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldHelperView":{"role":"symbol","title":"GTTextFieldHelperView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextFieldHelperView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldHelperView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextFieldHelperView"}],"url":"\/documentation\/gtuikit\/gttextfieldhelperview"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldAlertView":{"role":"symbol","title":"GTTextFieldAlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextFieldAlertView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldAlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextFieldAlertView"}],"url":"\/documentation\/gtuikit\/gttextfieldalertview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldHelperView\/title","value":"GTTextFieldHelperView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldHelperView\/fragments","value":[{"kind":"identifier","text":"GTTextFieldHelperView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldAlertView\/title","value":"GTTextFieldAlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldAlertView\/fragments","value":[{"kind":"identifier","text":"GTTextFieldAlertView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}