{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextField","text":"GTTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField\/Mode-swift.enum","preciseIdentifier":"s:7GTUIKit11GTTextFieldC4ModeO","text":"Mode"},{"kind":"text","text":" = .medium, "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextField","text":"GTTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField\/Style-swift.enum","preciseIdentifier":"s:7GTUIKit11GTTextFieldC5StyleO","text":"Style"},{"kind":"text","text":" = .white, "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"helper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtuikit\/gttextfieldhelperview\/init(mode:style:title:helper:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldHelperView\/init(mode:style:title:helper:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextField","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:7GTUIKit11GTTextFieldC4ModeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextField","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:7GTUIKit11GTTextFieldC5StyleO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"helper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(mode:style:title:helper:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:7GTUIKit21GTTextFieldHelperViewC4mode5style5title6helperAcA0bC0C4ModeO_AI5StyleOSSSgANtcfc","modules":[{"name":"GTUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldHelperView"]]},"references":{"doc://org.cocoapods.GTUIKit/documentation/GTUIKit":{"role":"collection","title":"GTUIKit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextField/Mode-swift.enum":{"role":"symbol","title":"GTTextField.Mode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField\/Mode-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"url":"\/documentation\/gtuikit\/gttextfield\/mode-swift.enum"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldHelperView/init(mode:style:title:helper:)":{"role":"symbol","title":"init(mode:style:title:helper:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextField","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:7GTUIKit11GTTextFieldC4ModeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTTextField","preciseIdentifier":"c:@M@GTUIKit@objc(cs)GTTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:7GTUIKit11GTTextFieldC5StyleO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"helper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldHelperView\/init(mode:style:title:helper:)","kind":"symbol","type":"topic","url":"\/documentation\/gtuikit\/gttextfieldhelperview\/init(mode:style:title:helper:)"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextField":{"role":"symbol","title":"GTTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextField"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextField"}],"url":"\/documentation\/gtuikit\/gttextfield"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextField/Style-swift.enum":{"role":"symbol","title":"GTTextField.Style","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextField\/Style-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/gtuikit\/gttextfield\/style-swift.enum"},"doc://org.cocoapods.GTUIKit/documentation/GTUIKit/GTTextFieldHelperView":{"role":"symbol","title":"GTTextFieldHelperView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTTextFieldHelperView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.GTUIKit\/documentation\/GTUIKit\/GTTextFieldHelperView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTTextFieldHelperView"}],"url":"\/documentation\/gtuikit\/gttextfieldhelperview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextField\/title","value":"GTTextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextField\/fragments","value":[{"kind":"identifier","text":"GTTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldHelperView\/title","value":"GTTextFieldHelperView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.GTUIKit~1documentation~1GTUIKit~1GTTextFieldHelperView\/fragments","value":[{"kind":"identifier","text":"GTTextFieldHelperView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}